- modules/user_manual/pages/files/access_webdav.adoc
> [10.3] [PR 1840] Remove sudo usage with curl

- bin/cli
> [10.3] [PR 1595] Update cli script

- bin/cli
> [10.0] [PR 1595] Update cli script

- bin/cli
> [10.1] [PR 1595] Update cli script

- bin/cli
> [10.2] [PR 1595] Update cli script

- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
> [10.3] [PR 1870] Minor grammatical and formatting revisions

- modules/developer_manual/examples/core/scripts/curl/create-share.sh
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.3] [PR 1874] Document the attributes field of the create-share API

- bin/cli
> [10.0] [PR 1883] Fixed a bug in the cli script when generating PDF files

- bin/cli
> [10.1] [PR 1883] Fixed a bug in the cli script when generating PDF files

- bin/cli
> [10.2] [PR 1883] Fixed a bug in the cli script when generating PDF files

- bin/cli
> [10.3] [PR 1883] Fixed a bug in the cli script when generating PDF files

- modules/developer_manual/examples/core/apis/ocs/roles/responses/success.json
- modules/developer_manual/examples/core/apis/ocs/roles/responses/success.xml
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/apis/roles-api.adoc
> [10.3] [PR 1873] Documentation of the Roles API

- modules/admin_manual/pages/configuration/files/external_storage/amazons3.adoc
- site.yml
> [10.3] [PR 1793] Document oC 10.3 upgrade requirements for Amazon S3

- modules/admin_manual/pages/release_notes.adoc
> [10.3] [PR 1881] Server 10.3 Release Notes

- modules/admin_manual/pages/release_notes.adoc
> [10.0] [PR 1881] Server 10.3 Release Notes

- modules/admin_manual/pages/release_notes.adoc
> [10.1] [PR 1881] Server 10.3 Release Notes

- modules/admin_manual/pages/release_notes.adoc
> [10.2] [PR 1881] Server 10.3 Release Notes

- modules/developer_manual/examples/core/scripts/curl/dav/public_files/view_public_link.sh
- modules/developer_manual/examples/core/scripts/php/dav/public_files/view_public_link.php
- modules/developer_manual/examples/core/webdav_api/public_files/response/listing-members-is-disabled.xml
- modules/developer_manual/examples/core/webdav_api/public_files/response/no-read-privileges-on-public-link.xml
- modules/developer_manual/examples/core/webdav_api/public_files/response/public-link-is-available.xml
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/webdav_api/public_files.adoc
> [10.3] [PR 1879] Document the public-files WebDAV API endpoint

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
> [10.3] [PR 1877] [1869] Document how to configure federation behind a proxy

- package.json
- yarn.lock
This version was released last week. Time to upgrade.
> Upgrade Antora to version 2.1.2

- .drone.yml
> [10.2] [PR 1951] Remove the build-artifacts build step

- modules/admin_manual/pages/release_notes.adoc
> [10.3] [PR 1947] release notes - occ app:disable can disable one app a time

- modules/admin_manual/pages/configuration/server/activity_configuration.adoc
> [10.2] [PR 1957] Update activity_configuration.adoc

- modules/admin_manual/pages/configuration/server/activity_configuration.adoc
> [10.1] [PR 1957] Update activity_configuration.adoc

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Add information from release notes regarding Redis Session Locking
> Redis Session Locking

- .drone.yml
> [10.3] [PR 1951] Remove the build-artifacts build step

- modules/admin_manual/pages/configuration/server/activity_configuration.adoc
> [10.3] [PR 1957] Update activity_configuration.adoc

- bin/cli
> [10.3] [PR 1891] Fix (potential) asciidoctor shell script bug

- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/code-standard.adoc
> [10.3] [PR 1963] Document php-cs-fixer in the developer documentation

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
> Backport systemcron docs to master

- modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
> [10.2] [PR 1978] Fix little typo in conditions option

- modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
> [10.3] [PR 1978] Fix little typo in conditions option

- modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
> [10.1] [PR 1978] Fix little typo in conditions option

- modules/admin_manual/pages/enterprise/installation/install.adoc
- modules/admin_manual/pages/maintenance/upgrade.adoc
After a request from @pako81 I have update the docs to fix https://github.com/owncloud/docs/issues/1984
> updated the docs

- modules/admin_manual/pages/enterprise/installation/install.adoc
- modules/admin_manual/pages/maintenance/upgrade.adoc
> [10.3] [PR 1987] updated the docs

- modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
- modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
- modules/developer_manual/pages/webdav_api/search/search_files.adoc
> [10.2] [PR 1990] Reference filtering and other search options in endpoint docs

- modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
- modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
- modules/developer_manual/pages/webdav_api/search/search_files.adoc
> [10.1] [PR 1990] Reference filtering and other search options in endpoint docs

- modules/admin_manual/pages/appliance/installation/installation.adoc
> [10.3] [PR 1988] Appliance setup rework

- modules/admin_manual/pages/appliance/installation/installation.adoc
> [10.2] [PR 1988] Appliance setup rework

- modules/admin_manual/pages/appliance/installation/installation.adoc
> [10.1] [PR 1988] Appliance setup rework

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.1] [PR 1995] Add missing cron job

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.2] [PR 1995] Add missing cron job

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
> [10.3] [PR 1983] Document the --progress/-p options for system:cron

- modules/admin_manual/pages/installation/linux_installation.adoc
corrected the link to the server packages.
> removed the index.html

- modules/user_manual/pages/files/access_webdav.adoc
replaced code brackeds from .... to ----
> fixed formatting issue

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
> Refine wording in API documentation

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
> [10.3] [PR 2011] Refine wording in API documentation

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
> [10.2] [PR 2011] Refine wording in API documentation

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
> [10.1] [PR 2011] Refine wording in API documentation

- modules/admin_manual/pages/installation/system_requirements.adoc
- site.yml
This fixes #2007.
**Only backport to 10.3.**
> Update the supported PHP versions to include PHP 7.3

- modules/admin_manual/pages/installation/system_requirements.adoc
- site.yml
> [10.3] [PR 2008] Update the supported PHP versions to include PHP 7.3

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
- modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
- modules/developer_manual/pages/app/advanced/storage-backend.adoc
> [10.3] [PR 2017] Remove note about mtime

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
- modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
- modules/developer_manual/pages/app/advanced/storage-backend.adoc
> [10.2] [PR 2017] Remove note about mtime

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
- modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
- modules/developer_manual/pages/app/advanced/storage-backend.adoc
> [10.1] [PR 2017] Remove note about mtime

- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/fundamentals/controllers.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/development_environment.adoc
> [10.3] [PR 2021] Correct developer documentation mistakes

- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/fundamentals/controllers.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/development_environment.adoc
> [10.2] [PR 2021] Correct developer documentation mistakes

- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/fundamentals/controllers.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/development_environment.adoc
> [10.1] [PR 2021] Correct developer documentation mistakes

- modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
- modules/admin_manual/pages/configuration/user/reset_user_password.adoc
- modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/user_manual/pages/personal_settings/general.adoc
> Document that password changes log out all user sessions

- modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
- modules/admin_manual/pages/configuration/user/reset_user_password.adoc
- modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/user_manual/pages/personal_settings/general.adoc
> [10.3] [PR 2019] Document that password changes log out all user sessions

- modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
- modules/admin_manual/pages/configuration/user/reset_user_password.adoc
- modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/user_manual/pages/personal_settings/general.adoc
> [10.2] [PR 2019] Document that password changes log out all user sessions

- modules/admin_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/reset_admin_password.adoc
- modules/admin_manual/pages/configuration/user/reset_user_password.adoc
- modules/user_manual/pages/_partials/configuration/user/update-password-note.adoc
- modules/user_manual/pages/personal_settings/general.adoc
> [10.1] [PR 2019] Document that password changes log out all user sessions

- modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.3] [PR 2032] Update documentation of the occ config:list command

- modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.2] [PR 2032] Update documentation of the occ config:list command

- modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.1] [PR 2032] Update documentation of the occ config:list command

- modules/developer_manual/pages/core/code-standard.adoc
> [10.1] [PR 1971] Update code-standard.adoc

- modules/developer_manual/pages/core/code-standard.adoc
> [10.2] [PR 1971] Update code-standard.adoc

- modules/developer_manual/pages/core/code-standard.adoc
> [10.3] [PR 1971] Update code-standard.adoc

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.3] Fix docs pdf errors

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.2] Fix docs pdf errors

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.1] Fix docs pdf errors

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.3] [PR 2056] Update virus-scanner-support.adoc

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.2] [PR 2056] Update virus-scanner-support.adoc

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.1] [PR 2056] Update virus-scanner-support.adoc

- modules/admin_manual/pages/release_notes.adoc
> [10.2] 10.3.1 release notes #2067

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Reverts owncloud/docs#2047. Doing this so that the relevant PRs can be backported individually.
> Revert "[10.2] Fix docs pdf errors"

- modules/admin_manual/pages/configuration/user/reset_user_password.adoc
- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
Some of these were breaking the build. Others were updated for consistency within the respective file.
> Fix example blocks so that they are surrounded consistently

- docs/the-branching-workflow.md
> [10.3] Updated the branching workflow

- modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
> [10.3] [PR 2077] Update wnd_setup.adoc

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
after changing it in our knowledge sharing session this document got 2 upgrade sections.
This PR fixes it and brings it to the same state as the latest document in the master branch
> fixed the 10.1 manual upgrade document

- modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
The version number was wrong - as you can see under the "prerequisites", oC 10.3 is needed.
> Updated requiered oC version from 10.2 to 10.3

- modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
> [10.3] [PR 2085] Updated requiered oC version from 10.2 to 10.3

- modules/developer_manual/examples/app/advanced/notifications/intro-notification.php
- modules/developer_manual/examples/app/advanced/notifications/notification-with-object.php
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/app/advanced/notifications.adoc
> [PR 324] Document how to send notifications from apps

- modules/developer_manual/examples/app/advanced/notifications/intro-notification.php
- modules/developer_manual/examples/app/advanced/notifications/notification-with-object.php
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/app/advanced/notifications.adoc
> [10.3] [PR 2093] [PR 324] Document how to send notifications from apps

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
This fixes #553, and relates to https://github.com/owncloud/core/issues/34222, and https://github.com/owncloud/core/issues/34343.
> [553] Document known federated sharing bugs

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
> [10.3] [PR 2094] [553] Document known federated sharing bugs

- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.3] [PR 2099] Delete double present command files_external:create

- modules/developer_manual/pages/app/fundamentals/database.adoc
- modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
> [10.3] [PR 2088] [321] Add note about migrations in database tutorial docs

- modules/developer_manual/pages/app/fundamentals/logging.adoc
> [10.3] [PR 2003] [292] Document extra logging fields and string interpolation in logging

- modules/admin_manual/pages/installation/manual_installation.adoc
- modules/admin_manual/pages/installation/nginx_configuration.adoc
> [10.3] [PR 2115] Create nginx_configuration.adoc

- modules/admin_manual/pages/configuration/files/files_locking_transactional.adoc
Put the important part with the link to memcache on the top with a note that this will do why they came here to begin with - to solve the warning on their admin page.
> Restructure file_locking document

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
> [10.3] [PR 2125] Fix error in database example

- modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
> [10.3] [PR 2126] fix: Fix admonition in enable encryption guide

- modules/admin_manual/pages/configuration/search/index.adoc
This change updates the known limitations list for the full text search app by:
- Removing fixed limitations
- Removing ambiguity in the wording of the remaining known limitations
> Update the full text search app's known limitations

- modules/admin_manual/pages/configuration/search/index.adoc
> [10.3] [PR 2138] Update index.adoc

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> Replace PHP 7.2 with 7.3 in the Ubuntu Setup doc

- modules/admin_manual/pages/configuration/search/index.adoc
> [10.3] [PR 2134] Update the full text search app's known limitations

- modules/developer_manual/pages/webdav_api/comments.adoc
- modules/developer_manual/pages/webdav_api/tags.adoc
> [10.3] [PR 2146] Update standard PROPFIND request attributes

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.3] [PR 2092] Document ability to disable WND Notify functionality

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
> Move providing logs and config files back to the troubleshooting section

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
> [10.3] [PR 2153] Move providing logs and config files back to the troubleshooting section

- modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
> Update the list of PROPFIND properties and their descriptions

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
for the enterprise customers to the tar balls on customer.owncloud.com site.
> add description how to get the link

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
> [10.3] [PR 2171] Specificate exact version

- modules/admin_manual/pages/appliance/configuration/app_settings.adoc
to finish the guide about the app settings, I added screenshots
> add images

- modules/developer_manual/pages/app/advanced/notifications.adoc
> [10.3] [PR 2164] Update notifications.adoc

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
> [10.3] [PR 2177] Update the background jobs configuration documentation

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
This PR backports a few, small, layout and text changes from #2180 to master branch, so that they are not lost.
> Backport 2180 to master

- modules/user_manual/pages/files/webgui/custom_groups.adoc
> [10.3] [PR 2175] Document the ability to disable admins from administering custom groups

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
This is an update of config.sample files according the changes made for 10.4
It contains fixes and new config parameters.
Pls note, that I have updated config-to-docs (see merged PR: https://github.com/owncloud/config-to-docs/pull/7 and 8) to work with the short array style
> [10.4] update config sample

- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.4] Document the occ maintenance:install database-connection-string option

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/user_manual/pages/apps/market.adoc
> [10.4] [PR 2200] Fix asciidoctor build warnings

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/user_manual/pages/apps/market.adoc
> [10.3] [PR 2200] Fix asciidoctor build warnings

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Backport of PR #2170. Need to check if a similar change needs to be applied in 10.4.
> [10.3] [PR 2170] [2169] Update major release note to reflect latest releases

- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.4] Document the occ encryption:hsmdaemon command

- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.3] Document the occ encryption:hsmdaemon command 

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
> [10.4] [PR 2207] [10.3] [PR 2170] [2169] Update major release note to reflect latest releases

- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
This PR superseeds https://github.com/owncloud/docs/pull/1292 which can be closed now.
I took all suggested changes and transported it in a proper way.
Additionally I did some improvements like headlines, propers console base, text ect.
Backporting to at least 10.3 should be done
> Update: Migrating User Key-based Encryption to Master Key Encryption

- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
> [10.4] Update: Migrating User Key-based Encryption to Master Key Encryption

- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
> [10.3] Update: Migrating User Key-based Encryption to Master Key Encryption

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
> Updating the version

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.4] [PR 2202] Remove apt install software-properties-common

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.3] [PR 2202] Remove apt install software-properties-common

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/ldap/index.adoc
> [10.4] [PR 2220] remove unnecessary LDAP documentation structure

- modules/admin_manual/pages/installation/docker/index.adoc
Link pointed to github repo, but there is no docker-compose.yml
> Update link to docker-compose.yml

- modules/user_manual/pages/whats_new.adoc
client 2.0 no longer works. 2.3.3 is bare minimum.
It seems this section is falling behind. There should be newer entries in what's new, or the section should be dropped, if unmaintained.
> update whats new

- .drone.yml
- bin/cli
> [10.3] [PR 2233] Update build tools to be format-aware

- .drone.yml
- bin/cli
> [10.4] [PR 2233] Update build tools to be format-aware

- modules/admin_manual/pages/_partials/maintenance/upgrading/upgrade_steps.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
> [10.4] [PR 2172] Update upgrade steps documentation 

- modules/user_manual/pages/pim/index.adoc
> [10.3] [PR 2242] Update index.adoc

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
>  [10.3] [PR 2252] update backgroundjob configuration #2255 

- modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
> [10.4] [PR 2248] Remove dav.enable.tech_preview from example

- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
> Add page redirect for old ransomware protection documentation

- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
> [10.3] [PR 2261] Add page redirect for old ransomware protection documentation

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
> [10.4] [PR 2252] update backgroundjob configuration

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
In order to setup a OfficeOnline Server, there were requirements missing. I added them
> add requirements

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.4] [PR 2264] add requirements

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.3] [PR 2264] add requirements

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/developer_manual/examples/core/apis/ocs/user-sync/successful-response.xml
- modules/developer_manual/examples/core/scripts/curl/ocs/user-sync.sh
- modules/developer_manual/examples/core/scripts/php/ocs/user-sync.php
- modules/developer_manual/examples/core/scripts/php/user-sync.php
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/apis/ocs/user-sync-api.adoc
> [10.4] [PR 2234] Document single user-sync endpoint

- modules/user_manual/pages/pim/index.adoc
> [10.4] [PR 2242] Update index.adoc

- modules/admin_manual/examples/installation/appinfo.xml
- modules/admin_manual/pages/installation/apps_management_installation.adoc
- site.yml
> [10.4] [PR 2154] Update the formatting of the installation instructions

- modules/admin_manual/examples/installation/appinfo.xml
- modules/admin_manual/pages/installation/apps_management_installation.adoc
- site.yml
>  [10.3] [PR 2154] Update the formatting of the installation instructions

- modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
> [10.3] [PR 2271] Correct level offset values for included pages

- modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
> [10.4] [PR 2271] Correct level offset values for included pages

- modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
> Square Parenthesis needed

- modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
> [10.3] [PR 2280] Square Parenthesis needed

- modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
> [10.4] [PR 2280] Square Parenthesis needed

- modules/user_manual/pages/session_management.adoc
> fix simple typo

- modules/user_manual/pages/session_management.adoc
> [10.4] [PR 2287] fix simple typo

- modules/user_manual/pages/session_management.adoc
> [10.3] [PR 2287] fix simple typo

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.4] [PR 2290] Update of config.sample files with latest changes from core

- modules/admin_manual/pages/installation/manual_installation.adoc
> [10.3] [PR 2263] Remove unused Apache environment variables

- modules/admin_manual/pages/release_notes.adoc
> [10.4] [PR 2307] Add PHP 7.1 deprecation note to 10.4 release notes

- modules/admin_manual/pages/installation/manual_installation.adoc
> [10.4] [PR 2263] Remove unused Apache environment variables

- modules/admin_manual/pages/release_notes.adoc
> [10.3] [PR 2307] Add PHP 7.1 deprecation note to 10.4 release notes

- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.3] [PR 2310] Add missing occ commands

- modules/admin_manual/nav.adoc
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/index.adoc
- modules/user_manual/nav.adoc
> [10.4] [PR 2284] Update the navigation files to fix the navigation bug in the PDF files

- modules/admin_manual/nav.adoc
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/index.adoc
- modules/user_manual/nav.adoc
> [10.3] [PR 2284] Update the navigation files to fix the navigation bug in the PDF files

- modules/admin_manual/pages/installation/system_requirements.adoc
> [10.4] [PR 2320] Update system_requirements.adoc

- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.3] [PR 2321] Changed recommendations to meet real life scenarios. And streamlined

- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.4] [PR 2321] Changed recommendations to meet real life scenarios. And streamlined

- modules/admin_manual/pages/installation/system_requirements.adoc
> [10.3] [PR 2320] Update system_requirements.adoc

- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
> Correct grammar mistake in the file firewall docs

- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
> [10.4] [PR 2329] Correct grammar mistake in the file firewall docs

- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
> [10.3] [PR 2329] Correct grammar mistake in the file firewall docs

- modules/admin_manual/pages/installation/system_requirements.adoc
> Add Mobile OS back in and remove redundant desktop OS section

- modules/admin_manual/pages/installation/system_requirements.adoc
This PR syncs the changes in 10.3 with 10.4.
> Backport changes in system requirements from 10.3 to 10.4

- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
as a table to provide the common mimetypes.
completes https://github.com/owncloud/docs/issues/2293
needs to be backported to all available branches.
> add common mimetypes

- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
> [10.4] [PR 2319] add common mimetypes

- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
> [10.3] [PR 2319] add common mimetypes

- modules/admin_manual/pages/installation/system_requirements.adoc
Backport of #2344 to 10.4 docs branch
> PostgreSQL 10 is supported by ownCloud core 10.4 onwards

- modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
> Backport to 10.3 Rewrite manually-moving-data-folders

- modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
> Backport to 10.4 Rewrite manually-moving-data-folders

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
To explain to our customer what the lock icon is for.
> add locking to the doc of wopi app

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
> [10.4] [PR 2347] Rework the Linux Database Configuration documentation

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
> [10.3] [PR 2347] Rework the Linux Database Configuration documentation

- modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
the rich documents app version 2.2.0
fixes https://github.com/owncloud/docs/issues/2357
> add crucial part of secure view prerequisites

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.4] [PR 2350] restructure of the memory caching document

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.3] [PR 2350] restructure of the memory caching document

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Backport #2372 to 10.4 docs branch
> [10.3] Add scenario tags to acceptance test docs

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Backport #2372 to 10.4 docs branch
> [10.4] Add scenario tags to acceptance test docs

- modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
> [10.3] Fix privateLinks typo

- modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
> [10.4] Fix privateLinks typo

- modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.4] [PR 2334] [2326] Update deployment recommendations example for finding the PHP session.save_path value

- modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.3] [PR 2334] [2326] Update deployment recommendations example for finding the PHP session.save_path value

- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/MultipartStreamTest.php
> [10.3] [PR 2379] Fix Content-Type typo

- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/MultipartStreamTest.php
> [10.4] [PR 2379] Fix Content-Type typo

- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/CHANGELOG.md
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/UPGRADING.md
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/promises/src/functions.php
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/LimitStreamTest.php
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/PumpStreamTest.php
- modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/CHANGELOG.md
- modules/developer_manual/pages/app/advanced/l10n.adoc
- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/tutorial/testing.adoc
- modules/developer_manual/pages/general/backporting.adoc
- modules/developer_manual/pages/general/devenv.adoc
- modules/developer_manual/pages/mobile_development/android_library/examples.adoc
- modules/developer_manual/pages/mobile_development/ios_library/examples.adoc
- modules/developer_manual/pages/testing/test-pilots.adoc
> [10.3] Fix typos in developer docs

- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/CHANGELOG.md
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/UPGRADING.md
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/promises/src/functions.php
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/LimitStreamTest.php
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/PumpStreamTest.php
- modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/CHANGELOG.md
- modules/developer_manual/pages/app/advanced/l10n.adoc
- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/tutorial/testing.adoc
- modules/developer_manual/pages/general/backporting.adoc
- modules/developer_manual/pages/general/devenv.adoc
- modules/developer_manual/pages/mobile_development/android_library/examples.adoc
- modules/developer_manual/pages/mobile_development/ios_library/examples.adoc
- modules/developer_manual/pages/testing/test-pilots.adoc
> [10.4] Fix typos in developer docs

- modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
> Deprecate the ldap:update-group from occ commands

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.3] [PR 2361] add locking to the doc of wopi app

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.4] [PR 2361] add locking to the doc of wopi app

- modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
>  [10.4] [PR 2316] Redirect the external storage configuration to the relevant occ commands

- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
Fixes https://github.com/owncloud/docs/issues/2396
> Ransomware protection list updated

- modules/admin_manual/pages/installation/docker/index.adoc
> mention quick eval option

- modules/admin_manual/pages/installation/docker/index.adoc
> [master] [PR 2401] mention quick eval option

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.3] [PR 2401] mention quick eval option

- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
> [10.3] [PR 2397] Ransomware protection list updated

- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
> [10.4] [PR 2397] Ransomware protection list updated

- modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
This PR improves `excluded_and_blacklisted_doc`
Backport to 10.3 and 10.4 necessary
@pmaier1 fyi :smile:
> Improve excluded_and_blacklisted_doc

- modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
> [10.3] [PR 2348] Improve excluded_and_blacklisted_doc

- modules/admin_manual/pages/configuration/server/excluded_blacklisted_files.adoc
> [10.4] [PR 2348] Improve excluded_and_blacklisted_doc

- modules/developer_manual/pages/general/backporting.adoc
> [10.4] [PR 2400] Backporting page update

- modules/developer_manual/pages/general/backporting.adoc
> [10.3] [PR 2400] Backporting page update

- modules/admin_manual/pages/configuration/server/app_commands/activity_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/user_manual/pages/apps/activity.adoc
> [10.4] [PR 2393] Document the changes to the Activity app in ver 2.5.3

- modules/admin_manual/pages/configuration/server/app_commands/activity_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/user_manual/pages/apps/activity.adoc
> [10.3] [PR 2393] Document the changes to the Activity app in ver 2.5.3

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
- modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
> [10.4] [PR 2367] [2354] Replace lingering references to cron.php with system:cron

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
- modules/admin_manual/pages/configuration/files/index.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
>  [10.3] [PR 2316] Redirect the external storage configuration to the relevant occ commands

- modules/admin_manual/examples/installation/post-installation-steps.sh
This is a small improvement for the post install script.
Tested by doing, runs fine.
Backporting to 10.4 and 10.3 needed
> Small improvement for the post install script

- modules/admin_manual/examples/installation/post-installation-steps.sh
> [10.3] [PR 2430] Small improvement for the post install script

- modules/admin_manual/examples/installation/post-installation-steps.sh
> [10.4] [PR 2430] Small improvement for the post install script

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.4] [PR 2432] Improvement of Redis setup

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.3] [PR 2432] Improvement of Redis setup

- modules/admin_manual/pages/installation/system_requirements.adoc
- site.yml
Started an update of that page. It got old. I suppose more should be updated here...
It is referenced in installation instructions and README files of customer facing documentation.
> drop old linux platforms, add new.

- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
> [10.4] Remove some PHP 7.0 references

- modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
I added this small section while working through #2449. Seemed right to add it in.
> Document how to retrieve PHP details from the command-line

- site.yml
This PR renames the site-wide attribute to reflect how it's used in the docs, fixing a render bug.
> [10.4] Rename site attribute

- site.yml
This PR renames the site-wide attribute to reflect how it's used in the docs, fixing a render bug.
> Rename site attribute to fix render bug

- modules/admin_manual/pages/installation/docker/index.adoc
>  [10.4] [PR 2427] compose down with everything?

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.3] [PR 2427] compose down with everything? 

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Maybe writing a more simple sentence will avoid confusion?
I am intending to describe/document more clearly/simply what the required/intended behaviour is. Then of course if the software does not actually do it, then there is a bug to be investigated and fixed.
Will need backport to 10.4 and 10.3
> Clarify the description of Office Online unlocking

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.4] Clarify the description of Office Online unlocking

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.3] Clarify the description of Office Online unlocking

- modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
- modules/user_manual/pages/files/media_viewer_app.adoc
> [10.3] [PR 2464] [2448] Document that QuickTime is not supported in Chrome

- modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
- modules/user_manual/pages/files/media_viewer_app.adoc
> [10.4] [PR 2464] [2448] Document that QuickTime is not supported in Chrome

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
> [10.3] [PR 2460] Improve server_prep_ubuntu_18.04

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
> [10.4] [PR 2460] Improve server_prep_ubuntu_18.04

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
> [10.3] [PR 2369] Document the options for the occ files:checksums:verify command

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
> [10.4] [PR 2369] Document the options for the occ files:checksums:verify command

- modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
> [10.4] [PR 2423] Update background jobs selector documentation

- modules/admin_manual/pages/configuration/server/occ_command/background_jobs_selector.adoc
> [10.3] [PR 2423] Update background jobs selector documentation

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/index.adoc
- modules/admin_manual/pages/release_notes.adoc
- modules/admin_manual/pages/whats_new_admin.adoc
> Deprecate the What's New page in the admin manual

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
These changes and one link fix have whyever slipped thru the last update 🤦‍♂ , fixing it now.
Backport to 10.3 and 10.4 needed
Info: successor of #2470 because drone was stuck
> minor fixes to Ubuntu install doc

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
> [10.4] minor fixes to Ubuntu install doc

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
> [10.3] minor fixes to Ubuntu install doc

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
> [10.4] [PR 2485] Slight update to the files:transfer-ownership documentation

- modules/admin_manual/pages/release_notes.adoc
> [10.4] Add known issue with password policy to release notes

- modules/admin_manual/pages/faq/index.adoc
> Fix broken link to sync-exclude.list on GitHub

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
> [10.4] [PR 2497] adding occ command files:check-cache

- modules/admin_manual/pages/faq/index.adoc
> [10.3] [PR 2499] Fix broken link to sync-exclude.list on GitHub

- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.3] [PR 2503] Update all external links to follow the style guide

- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.4] [PR 2503] Update all external links to follow the style guide

- modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
- modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-multiple-versions.xml
- modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-one-version.xml
- modules/developer_manual/pages/webdav_api/files_versions.adoc
- modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
> [10.4] [PR 2166] [269] Update Files Versions API documentation

- modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-files.xml
- modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-multiple-versions.xml
- modules/developer_manual/examples/core/webdav_api/files_versions/successful-response-which-contains-one-version.xml
- modules/developer_manual/pages/webdav_api/files_versions.adoc
- modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
> [10.3] [PR 2166] [269] Update Files Versions API documentation

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
> [10.4] [PR 2510] Adding php-ssh2 recommended for oidc

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
> [10.3] [PR 2510] Adding php-ssh2 recommended for oidc

- modules/admin_manual/pages/release_notes.adoc
> [10.3] [PR 683] Release notes foreign keys

- modules/admin_manual/pages/release_notes.adoc
> [10.4] [PR 683] Release notes foreign keys

- modules/developer_manual/assets/attachments/core/Makefile.example
- modules/developer_manual/pages/testing/unit-testing.adoc
This fixes #320 by working to enhance the clarity of the unit testing documentation in the developer docs.
> Update Unit Testing Documentation

- modules/developer_manual/assets/attachments/core/Makefile.example
- modules/developer_manual/pages/testing/unit-testing.adoc
> [10.4] Update unit test documentation

- modules/developer_manual/pages/testing/unit-testing.adoc
Forward port of commit from 10.3 branch
See discussion in PR #2518
> [10.4] Fix xref to admin_manual:installation/apps_supported.adoc

- modules/developer_manual/pages/testing/unit-testing.adoc
Forward port of commit from 10.3 branch
See discussion in PR #2518
> Fix xref to admin_manual:installation/apps_supported.adoc

- modules/developer_manual/pages/testing/unit-testing.adoc
> [10.4] Remove old ownCloud9 phpunit docs

- modules/developer_manual/pages/testing/unit-testing.adoc
> [10.3] Remove old ownCloud9 phpunit docs

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
> Remove lingering user:sync Shibboleth example

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
> [10.3] [PR 2530] Remove lingering user:sync Shibboleth example

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
> [10.4] [PR 2530] Remove lingering user:sync Shibboleth example

- modules/developer_manual/examples/core/webdav_api/meta/meta-files-filter.xml
- modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
- modules/developer_manual/examples/core/webdav_api/meta/response-failure.xml
- modules/developer_manual/examples/core/webdav_api/meta/response-success.xml
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
- site.yml
> [10.3] [PR 2159] [2157] Document WebDAV Meta endpoint

- modules/developer_manual/examples/core/webdav_api/meta/meta-files-filter.xml
- modules/developer_manual/examples/core/webdav_api/meta/report-propfind.xml
- modules/developer_manual/examples/core/webdav_api/meta/response-failure.xml
- modules/developer_manual/examples/core/webdav_api/meta/response-success.xml
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
- site.yml
> [10.4] [PR 2159] [2157] Document WebDAV Meta endpoint

- modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/routes_and_controllers.adoc
- modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
- modules/developer_manual/pages/core/apis/ocs/user-sync-api.adoc
- modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
- modules/user_manual/pages/apps/enterprise/admin_audit.adoc
> [10.4] Fix up build errors in the core documentation

- modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/routes_and_controllers.adoc
- modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
- modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
- modules/user_manual/pages/apps/enterprise/admin_audit.adoc
> [10.3] Fix up build errors in the core documentation

- modules/developer_manual/examples/scripts/backport.sh
> [10.4] [PR 2539] Backporting script: update git key names

- modules/developer_manual/examples/scripts/backport.sh
> [10.3] [PR 2539] Backporting script: update git key names

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.4] [PR 2533] [2529] Update federated cloud shares documentation

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.3] [PR 2533] [2529] Update federated cloud shares documentation

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
hetzner cloud 18.04 apache is installed without ssl-cert
> Add ssl-cert

- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
> [10.4] [PR 2549] Document OAuth2 app requirements

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
> [10.4] [PR 2523] Document that files:transfer-ownership changes in 10.4.1

- modules/developer_manual/examples/app/fundamentals/database/author-access-attributes.php
- modules/developer_manual/examples/app/fundamentals/database/author.php
- modules/developer_manual/examples/app/fundamentals/database/authormapper.php
- modules/developer_manual/examples/app/fundamentals/database/create-migration-step.php
- modules/developer_manual/examples/app/fundamentals/database/custom-attribute-to-database-column-mapping.php
- modules/developer_manual/examples/app/fundamentals/database/database-access.php
- modules/developer_manual/examples/app/fundamentals/database/migrations.php
- modules/developer_manual/examples/app/fundamentals/database/schema-migration-step.php
- modules/developer_manual/examples/app/fundamentals/database/schema-update.xml
- modules/developer_manual/examples/app/fundamentals/database/slug.php
- modules/developer_manual/examples/app/fundamentals/database/sql-migration-step.php
- modules/developer_manual/pages/app/fundamentals/database.adoc
> [10.4] [PR 2563] Update developer manual database fundamentals documentation

- modules/admin_manual/pages/release_notes.adoc
As usual!
@micbar @phil-davis @settermjd
> Add Server 10.4.1 release notes

- modules/developer_manual/examples/app/fundamentals/database/author-access-attributes.php
- modules/developer_manual/examples/app/fundamentals/database/author.php
- modules/developer_manual/examples/app/fundamentals/database/authormapper.php
- modules/developer_manual/examples/app/fundamentals/database/create-migration-step.php
- modules/developer_manual/examples/app/fundamentals/database/custom-attribute-to-database-column-mapping.php
- modules/developer_manual/examples/app/fundamentals/database/database-access.php
- modules/developer_manual/examples/app/fundamentals/database/migrations.php
- modules/developer_manual/examples/app/fundamentals/database/schema-migration-step.php
- modules/developer_manual/examples/app/fundamentals/database/schema-update.xml
- modules/developer_manual/examples/app/fundamentals/database/slug.php
- modules/developer_manual/examples/app/fundamentals/database/sql-migration-step.php
- modules/developer_manual/pages/app/fundamentals/database.adoc
> [10.3] [PR 2563] Update developer manual database fundamentals documentation

- modules/admin_manual/pages/release_notes.adoc
> [10.4] Add Server 10.4.1 release notes

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
This relates to #2554. It also makes some of the changes seen in #2554.
> Update finalise-install to render correctly

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.4] [PR 2557] Update finalise-install to render correctly

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
While the script should work properly without these changes, for completeness
and consistency's sake, it's worth making these changes.
> Update finalise install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.3] [PR 2557] Update finalise-install to render correctly

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.2] [PR 2557] Update finalise-install to render correctly

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.1] [PR 2557] Update finalise-install to render correctly

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.4] [PR 2570] Update finalise install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.3] [PR 2570] Update finalise install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.2] [PR 2570] Update finalise install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.1] [PR 2570] Update finalise install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.1] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.2] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.3] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.4] [PR 2584] Fix .htaccess permissions and file owner in finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
The intent here is to simplify some of the script, so that it's more repeatable, make the permission settings more consistent, make the script that much more verbose and reliable. This PR is attempting to cover all of the following feedback:
- https://github.com/owncloud/docs/issues/2566#issuecomment-615398150
- https://github.com/owncloud/docs/issues/2566#issuecomment-615501286
Fwiw, I don't know how it would break networking, as mentioned in https://github.com/owncloud/docs/issues/2566#issuecomment-615501286.
> Update finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.4] [PR 2589] Update finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.3] [PR 2589] Update finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.2] [PR 2589] Update finalise-install script

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
> [10.1] [PR 2589] Update finalise-install script

- .drone.yml
> [10.3] [PR 2601] Add Drone environment variable to set the latest version

- .drone.yml
> [10.4] [PR 2601] Add Drone environment variable to set the latest version

- modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
> [10.4] [PR 2596] Update create-vhost-config.sh

- .drone.yml
> [10.2] [PR 2601] Add Drone environment variable to set the latest version

- modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
> [10.3] [PR 2596] Update create-vhost-config.sh

- .drone.yml
> [10.1] [PR 2601] Add Drone environment variable to set the latest version

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.3] Update user_auth_ldap.adoc

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.4] Update user_auth_ldap.adoc

- modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
> [10.4] user_external link fix

- modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
> [10.3] user_external link fix

- modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
> [10.1] user_external link fix

- modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
> [10.2] user_external link fix

- modules/admin_manual/pages/release_notes.adoc
@phil-davis can you do backporting magic as far as necessary? THX!
> Add known issue when sharing with numeric UIDs

- modules/admin_manual/pages/release_notes.adoc
> [10.4] Add known issue when sharing with numeric UIDs

- modules/admin_manual/pages/release_notes.adoc
> [10.3] Add known issue when sharing with numeric UIDs

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.4] [PR 2645] Incorporate changes from core for config.sample.php

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.3] [PR 2645] Incorporate changes from core for config.sample.php

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Refrences core merge: https://github.com/owncloud/core/pull/37436 (Allow the get demo key link to be configurable)
Fixes: doc https://github.com/owncloud/docs/issues/2650
Needs backporting to 10.5
> config.sample update based on core change

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.5] [PR 2664] config.sample update based on core change

- modules/developer_manual/pages/testing/acceptance-tests.adoc
> [10.5] Document how to replace usernames in acceptance tests

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
Replaced violent language with an appropriate terminology.
> Replaced Master-Slave with primary-secondary

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.5] Replaced Master-Slave with primary-replica

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.4] Replaced Master-Slave with primary-replica

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.3] Replaced Master-Slave with primary-replica

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.2] Replaced Master-Slave with primary-replica

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
> [10.1] Replaced Master-Slave with primary-replica

- modules/developer_manual/pages/core/theming.adoc
Fix typo in #body-login regarding comments syntax
> Fix typo in body-login regarding comments syntax

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
> [10.5] Update index.adoc

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
> [10.4] Update index.adoc

- modules/developer_manual/pages/core/theming.adoc
> [10.5] Fix typo in body-login regarding comments syntax

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
because now the latest one is 10.4.1
> update the latest server version

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Backport #2699 
This is all that needs backporting to here.
> [10.4] update the latest server version

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
> [10.5] update the latest server version

- modules/admin_manual/pages/installation/system_requirements.adoc
> [10.4] Update system_requirements.adoc

- modules/admin_manual/pages/installation/system_requirements.adoc
> [10.5] Update system_requirements.adoc

- modules/developer_manual/pages/general/devenv.adoc
should probably be merged into master...
> [10.4] doc updates while trying

- modules/developer_manual/pages/general/devenv.adoc
> [10.5] Update devenv.adoc

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
> [10.5] Fixup doc of Provisioning API Add User

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
> [10.4] Fixup doc of Provisioning API Add User

- modules/user_manual/pages/files/access_webdav.adoc
> [10.5] Uploading to public link

- modules/user_manual/pages/files/access_webdav.adoc
> [10.4] Add an example to upload files to a public link using curl

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Backport #2685 
@voroyam please double-check that these fixes are correct for 10.4.1
> [10.4] fixed ldap cron job in Installation manual

- modules/admin_manual/pages/release_notes.adoc
This is a draft for 10.5 release notes. Feedback pls!
> 10.5 Release Notes

- modules/admin_manual/pages/release_notes.adoc
> [10.5] Release Notes

- site.yml
> [10.5] Update site.yml to have PHP 7.2 to 7.4

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
A proper parametrisation for rendering the document changed was missing, setting toclevels to 1 for better readability.
Backport to 10.5 only !
> some rendering fixes

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
> [10.5] some rendering fixes

- modules/developer_manual/pages/testing/test-pilots.adoc
> [10.5] [PR 2750] Migrate from mailing-list to testing-newsletter

- modules/developer_manual/pages/testing/test-pilots.adoc
> [10.4] [PR 2750] Migrate from mailing-list to testing-newsletter

- modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
- modules/developer_manual/examples/core/scripts/curl/create-share.sh
- modules/developer_manual/examples/core/scripts/curl/dav/public_files/view_public_link.sh
- modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/delete-file-from-trashbin.sh
- modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/list-files-in-trashbin.sh
- modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/restore-file-to-trashbin.sh
- modules/developer_manual/examples/core/scripts/curl/delete-share.sh
- modules/developer_manual/examples/core/scripts/curl/get-share-info.sh
- modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-server-capabilities.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-user-notifications.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/user-sync.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
- modules/developer_manual/examples/core/scripts/curl/provisioning_api/add-user.curl
- modules/developer_manual/examples/core/scripts/curl/update-share.sh
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
- modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
- modules/developer_manual/pages/webdav_api/trashbin.adoc
Some more fixes for antora compile warnings.
The warning list is a lot less now :smile:
Backport to 10.4 and 10.5
The older branches 10.3 - 10.1 may get a backport too if someone takes the task.
But this is a lof of work to see if/which changes have been made from 10.1 to 10.4
> fix more anotra compile warnings

- modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
- modules/developer_manual/examples/core/scripts/curl/create-share.sh
- modules/developer_manual/examples/core/scripts/curl/dav/public_files/view_public_link.sh
- modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/delete-file-from-trashbin.sh
- modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/list-files-in-trashbin.sh
- modules/developer_manual/examples/core/scripts/curl/dav/trashbin_api/restore-file-to-trashbin.sh
- modules/developer_manual/examples/core/scripts/curl/delete-share.sh
- modules/developer_manual/examples/core/scripts/curl/get-share-info.sh
- modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-server-capabilities.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/notifications/get-user-notifications.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/notify-public-link-by-email.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/user-sync.sh
- modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
- modules/developer_manual/examples/core/scripts/curl/provisioning_api/add-user.curl
- modules/developer_manual/examples/core/scripts/curl/update-share.sh
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
- modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
- modules/developer_manual/pages/webdav_api/trashbin.adoc
> [10.5] [PR 2754] fix more anotra compile warnings

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
- site.yml
> [10.4] Update hardcoded version with latest-download-version variable

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.5] Update hardcoded ownCloud10 patch version

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.5] Update caching_configuration.adoc

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.4] Update caching_configuration.adoc

- modules/admin_manual/pages/release_notes.adoc
> [10.5] Add tip about ownCloud Server 10.5 and PHP 7.4 upgrade order

- modules/user_manual/pages/files/webgui/sharing.adoc
> [10.5] Update description of sharing expiration date

- modules/user_manual/pages/files/webgui/sharing.adoc
Backport #2797 to 10.4
Expiration date for user and group shares is in 10.4
> [10.4] Update description of sharing expiration date

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
> [10.5] Update admin file_sharing_configuration with current information

- modules/developer_manual/pages/index.adoc
Fixed broken link to the Contributor Agreement
Backport #2807 to 10.5
> [10.5] Fix link to CLA

- modules/developer_manual/pages/index.adoc
Fixed broken link to the Contributor Agreement
Backport #2807 to 10.4
> [10.4] Fix link to CLA

- modules/admin_manual/pages/installation/apps_supported.adoc
Forward-port of #2781 to master
> Review supported list of enterprise apps

- modules/user_manual/pages/whats_new.adoc
Forward port of #2812 to master.
Otherwise this will already be out-of-date for a future 10.6 docs branch.
> client min version 2.6

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Closes https://github.com/owncloud/docs/issues/2711
> add doc for strict login checking required for disabling login with LDAP email address

- modules/admin_manual/pages/installation/system_requirements.adoc
IMO it is worth backporting this to 10.5, since many users will be reading 10.5 docs these days.
> [10.5] Migrate desktop & mobile system requirements

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
owncloud.org was merged with owncloud.com. some links need to be re-adjusted
> update links to owncloud.org/support

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
> [10.5] Document OpenID Connect

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
Some structure and styling needed.
Review for correctness needed.
Some open questions.
> Document OpenID Connect

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
and add blank lines before lists and tips so that they render correctly.
backported fix is PR #2838
> Fix xref in OIDC docs

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
> [10.5] update links to owncloud.org/support

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Backport #2779 and #2835 to 10.5
> [10.5] add occ background:cron to set the background job to cron

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Backport #2779 and #2835 to 10.4
> [10.4] add occ background:cron to set the background job to cron

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Backport #2779 and #2835 to 10.3
> [10.3] add occ background:cron to set the background job to cron

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
> [10.4] update links to owncloud.org/support

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
> [10.3] update links to owncloud.org/support

- modules/admin_manual/pages/installation/docker/index.adoc
Addresses https://github.com/owncloud/docs/issues/2775
> Fix reference to docker-compose.yml

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.5] Fix reference to docker-compose.yml

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
```
git clone https://github.com/owncloud/docs.git
cd docs
git checkout oidc/basic-migration
yarn install
yarn antora
yarn serve
```
Test http://localhost:8080/server/admin_manual/configuration/user/oidc/index.html
@pmaier1 could you fix lower-/upper-case, punctuation etc?
> Trigger client migration basic > OIDC

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
> [10.5] Oidc basic migration

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.5] Add missing part from service config

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.4] Add missing part from service config

- modules/admin_manual/pages/appliance/configuration/office.adoc
> Backport von https://github.com/owncloud/docs/pull/2875

- modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
Change service reference as the original does not exist
Add the install section
> Update wnd_setup for appliance

- modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
> [10.5] Update wnd_setup.adoc

- modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
> [10.4] [PR 2878] Some text fixes for the external mount point documentation

- modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
> [10.5] [PR 2878] Some text fixes for the external mount point documentation

- modules/admin_manual/pages/appliance/configuration/office.adoc
backporting https://github.com/owncloud/docs/pull/2875
> [backport 10.4]-Update office.adoc

- modules/admin_manual/pages/appliance/configuration/office.adoc
[https://github.com/owncloud/docs/issues/2849]
> add troubleshooting to the "Working on Documents" doc

- modules/admin_manual/pages/appliance/configuration/office.adoc
https://github.com/owncloud/docs/issues/2849
> [backport 10.5] add troubleshooting to the "Working on Documents" doc

- modules/admin_manual/pages/appliance/configuration/office.adoc
https://github.com/owncloud/docs/issues/2849
> [backport 10.4] add troubleshooting to the "Working on Documents" doc

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/files/index.adoc
- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
because https://github.com/owncloud/docs/issues/2696
> document manual file locking

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/files/index.adoc
- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
because https://github.com/owncloud/docs/issues/2696
https://github.com/owncloud/docs/pull/2903
> [Backport 10.4] document manual file locking

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/files/index.adoc
- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
because https://github.com/owncloud/docs/issues/2696
https://github.com/owncloud/docs/pull/2903
> [Backport 10.5] document manual file locking

- modules/admin_manual/pages/installation/linux_installation.adoc
they only document nextcloud there.
> remove link to mageia wiki

- modules/admin_manual/pages/installation/docker/index.adoc
Obsoletes one part of the unmergeable https://github.com/owncloud/docs/pull/2854
Backports needed: 10.5, 10-6 .. maybe more?
> Disentagle some language to make it easier to read.

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.5] Disentagle some language to make it easier to read.

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
closes https://github.com/owncloud/docs/issues/2794
> document files:troubleshoot-transfer-ownership

- .drone.star
- site.yml
Includes todays latest commits from @voroyam and @mschreml, thanks!
Needed for 10.6.0RC2
> branch 10.6 with updated .drone.star and site.yml

- modules/developer_manual/pages/core/theming.adoc
> Theming example - wrong comments

- modules/developer_manual/pages/core/theming.adoc
> [10.6] Wrong comments

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Added example to user:sync in user_commands.adoc
https://github.com/owncloud/docs/issues/2885
> [Backport 10.5) Added example to user:sync in user_commands.adoc

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Backport of PR #2928 to 10.6
Issue #2885
> [10.6] Added example to user:sync in user_commands.adoc

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Backport of PR #2928 to 10.4
Issue #2885
> [10.4] Added example to user:sync in user_commands.adoc

- README.md
This improves README.md with regards to PR creation and backporting.
No backporting necessary as it is a repro documentation only.
> PR and Backport Documentation Improvements in README.md

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.4] Clarifying WND null Permission manager

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.5] Clarifying WND null Permission manager

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.6] Clarifying WND null Permission manager

- modules/admin_manual/pages/release_notes.adoc
Please check @micbar @phil-davis @dirkstascheit
> 10.6 Release Notes

- modules/admin_manual/pages/release_notes.adoc
> [10.6] Release Notes

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.6] [PR 2945] Missing config sample changes from core 10.6

- modules/developer_manual/pages/general/backporting.adoc
> [10.6] [PR 2954] Update backporting.adoc

- modules/developer_manual/pages/general/backporting.adoc
> [10.5] [PR 2954] Update backporting.adoc

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
> [10.6] [PR 2851] Update ubuntu_18_04.adoc

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
> [10.5] [PR 2851] Update ubuntu_18_04.adoc

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.4] [PR 2851] Update ubuntu_18_04.adoc

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
> [10.6] [PR 2828] Update ubuntu_18_04.adoc

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
> [10.5] [PR 2828] Update ubuntu_18_04.adoc

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.6] [PR 2856] Add note about username and password

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.5] [PR 2856] Add note about username and password

- modules/admin_manual/pages/installation/index.adoc
> [10.6] [PR 2826] Update index.adoc

- modules/admin_manual/pages/installation/index.adoc
> [10.5] [PR 2826] Update index.adoc

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.6] [PR 2978] force https for some links

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.5] [PR 2978] force https for some links

- modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
> [10.6] [PR 2846] remove useless use of sudo

- modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh
> [10.5] [PR 2846] remove useless use of sudo

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> Quick Guide for Ubuntu 20.04

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.5] Quick Guide for Ubuntu 20.04

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.6] Quick Guide for Ubuntu 20.04

- modules/admin_manual/pages/installation/apps_management_installation.adoc
> [10.6] Update apps_management_installation.adoc

- modules/admin_manual/pages/installation/apps_management_installation.adoc
> [10.5] Update apps_management_installation.adoc

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.6] Various edits to ubuntu installation

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.5] Various edits to ubuntu installation

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
> [10.5] Update server_prep_18.04 when using multiple PHP installs

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
> [10.6] Update server_prep_18.04 when using multiple PHP installs

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
...and document how to solve the error message.
fixes https://github.com/owncloud/docs/issues/2994
backport to 10 6 and 10 5
> add missing file to integrity check warning

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
...and document how to solve the error message.
fixes https://github.com/owncloud/docs/issues/2994
> [10.6] add missing file to integrity check warning

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
...and document how to solve the error message.
fixes https://github.com/owncloud/docs/issues/2994
> [10.5] add missing file to integrity check warning

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/developer_manual/pages/app/advanced/code_signing.adoc
> [10.6] Fix another FILE_MISSING and some FAQ headings

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/developer_manual/pages/app/advanced/code_signing.adoc
> [10.5] Fix another FILE_MISSING and some FAQ headings

- modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
This is an update of the `smb.adoc` file.
Contains improvements and fixes. Deleted old and outdated content.
Backport needed to 10.6 and 10.5
> Fixes and Updates to smb.adoc

- modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
> [10.5] [PR 3007] Fixes and Updates to smb.adoc

- modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
> [10.6] [PR 3007] Fixes and Updates to smb.adoc

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
> [10.6] Fix out-of-date minor version in table

- generator/generate-site.js
- package.json
- yarn.lock
Fixes https://github.com/owncloud/docs/issues/3014.
> bump html-entities to v2.0.2

- .drone.star
- docs/build-the-docs.md
- generator/xref-validator.js
See https://gitlab.com/antora/antora/-/issues/374 and https://docs.antora.org/antora/2.0/whats-new/
> replace deprecated antora --pull flag with --fetch

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
> [10.6] [PR 3020] Use antora variable from site.yml in maintenance for the latest download version

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
> [10.6] Reduce list of 10.x.y versions in example upgrade table

- modules/admin_manual/pages/release_notes.adoc
> [10.6] Add known issue to 10.6 release notes

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- modules/developer_manual/pages/core/configfile.adoc
Backport #3040 and #3041 to 10.6
> [10.6] apps_paths note

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- modules/developer_manual/pages/core/configfile.adoc
Backport #3040 and #3041 to 10.5
> [10.5] apps_paths note

- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
> [10.6] [PR 3046] add background jobs to security warnings

- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
> [10.5] [PR 3046] add background jobs to security warnings

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
recover page alias on modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
> Recover page alias modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc 

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
> [10.6] [PR3052] Recover page alias modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
> [10.5] [PR3052] Recover page alias modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Closes: #3027 
Screenshot taken from a preview in VS Code.
> Fixes formatting of "Finalize the Installation" section

- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
- webUI includes web server env in phpinfo
- cli doesn't have access to that
=> generate through webUI if possible
> Adding note about configreport

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
> [10.6] [PR 3063] Fixes formatting of "Finalize the Installation" section

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
> [10.5] [PR 3063] Fixes formatting of "Finalize the Installation" section

- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
Backport #3068 
- webUI includes web server env in phpinfo
- cli doesn't have access to that
=> generate through webUI if possible
> [10.6] Adding note about configreport

- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
Backport #3068 
- webUI includes web server env in phpinfo
- cli doesn't have access to that
=> generate through webUI if possible
> [10.5] Adding note about configreport

- modules/admin_manual/pages/installation/docker/index.adoc
This PR will guide how to run occ commands proper in a docker environment
> Add Running occ command section to admin_manual/pages/installation/docker/index.adoc

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.6] add Running occ command section

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.5] add Running occ command section

- modules/user_manual/pages/personal_settings/security.adoc
Hint for users, to setup valid CORS records
> Add Important Note for valid CORS entries

- modules/user_manual/pages/personal_settings/security.adoc
> [10.6] [PR 3075] Add Important Note for valid CORS entries

- modules/admin_manual/examples/installation/manual_installation/instance.sh
> [10.5] [PR 3076] Update instance.sh

- modules/admin_manual/examples/installation/manual_installation/instance.sh
> [10.6] [PR 3076] Update instance.sh

- modules/developer_manual/examples/scripts/backport.sh
> [10.5] Small update of the Backport Script reflecting recent changes on GH

- modules/developer_manual/examples/scripts/backport.sh
> [10.6] Small update of the Backport Script reflecting recent changes on GH

- modules/admin_manual/pages/configuration/user/guests_app.adoc
* Removed the enterprise only title
* Changed 'enterprise bundle to enterprise'
> Changed modules/admin_manual/pages/configuration/user/guests_app.adoc

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/apis/provisioning-api.adoc
The Provisioning API will be located under developer_manual/core/apis
The navigation item 'User Provisioning API' at admin_manual/configuration/user/ will link to this page to section #instruction-set-for-users
A important note that the given user must be an admin or sub-admin will be displayed
> Adjust Provisioning API

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/apis/provisioning-api.adoc
> [10.5] Adjust Provisioning API

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/apis/provisioning-api.adoc
> [10.6] Adjust Provisioning API

- modules/admin_manual/pages/release_notes.adoc
Changed web references from html to adoc where possible.
Some text improvements for better readability.
Backporting to 10.6 only!
> small update and fixes

- modules/admin_manual/pages/release_notes.adoc
> [10.6] small update

- site.yml
Master + last 2 are staying in the online docs.
> remove old doc branches

- docs/best-practices.md
This updates the Best Practices Guide with new content.
No backport necessary
> Update Best Practices Guide

- modules/admin_manual/pages/configuration/user/guests_app.adoc
> [10.6] Removed the enterprise stuff

- modules/admin_manual/pages/configuration/user/guests_app.adoc
> [10.5] Removed the enterprise stuff

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
to better distinguish it from the Appliance doc and the upcoming quick guide doc.
> Name Change of the Server Documentation for WND

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.6] LDAPS documentation

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.5] LDAPS documentation

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.6] [PR 3103] Name Change of the Server Documentation for WND

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.5] [PR 3103] Name Change of the Server Documentation for WND

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.6] [PR 3110] add note to User-Auth with LDAP doc

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.5] [PR 3110] add note to User-Auth with LDAP doc

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
Improvements to `user_auth_ldap.adoc`
Backport to 10.5 and 10.6 necessary
> Update of user_auth_ldap.adoc

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.5] [PR 3125] Update of user_auth_ldap.adoc

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.6] [PR 3125] Update of user_auth_ldap.adoc

- modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
> [10.5] Change section name of WND to distinguish it from the server one

- modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
> [10.6] Change section name of WND to distinguish it from the server one

- modules/admin_manual/pages/installation/docker/index.adoc
Layout and text improvement for the docker installation guide.
Backport to 10.5 and 10.6 necessary
> Installing Docker Improvements

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.5] [PR 3136] Installing Docker Improvements

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.6] [PR 3136] Installing Docker Improvements

- modules/admin_manual/pages/installation/apps_management_installation.adoc
add recommendation regarding multiple servers and apps / config directory.
inspiration: https://central.owncloud.org/t/owncloud-scaling-with-multiple-servers-can-var-www-owncloud-be-shared-via-nfs/24932/2?u=dmitry
BP of https://github.com/owncloud/docs/pull/3143
> [ 10.6 ] Update apps_management_installation.adoc

- modules/admin_manual/pages/installation/apps_management_installation.adoc
add recommendation regarding multiple servers and apps / config directory.
inspiration: https://central.owncloud.org/t/owncloud-scaling-with-multiple-servers-can-var-www-owncloud-be-shared-via-nfs/24932/2?u=dmitry
Backport of #3143
> [ 10.5 ] Update apps_management_installation.adoc

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Fixing issue #3026
Backport #3148
> [10.6] Update manual_upgrade.adoc

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Fixing issue #3026
Backport #3148
> [10.5] Update manual_upgrade.adoc

- modules/ROOT/pages/index.adoc
Fixes PDF links for older server versions and adds missing versions.
> fix pdf links for old server version

- modules/ROOT/pages/index.adoc
> [10.5] [PR 3153] fix pdf links for old server version

- modules/ROOT/pages/index.adoc
> [10.6] [PR 3153] fix pdf links for old server version

- modules/admin_manual/pages/release_notes.adoc
> Add 10.6 known issue to release notes

- modules/admin_manual/pages/release_notes.adoc
> [10.6] Add 10.6 known issue to release notes

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
clean new PR from https://github.com/owncloud/docs/pull/3156
> page rework

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
backport of https://github.com/owncloud/docs/pull/3162
> [10.5] page rework

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
backport of https://github.com/owncloud/docs/pull/3162
> [10.6] page rework

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
clean version of https://github.com/owncloud/docs/pull/3045
fixes https://github.com/owncloud/docs/issues/2872
> wnd quick guide

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
BP of https://github.com/owncloud/docs/pull/3166
> [10.6] wnd quick guide

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
bp of https://github.com/owncloud/docs/pull/3167
> [ 10.5] fixed the break line

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
bp of https://github.com/owncloud/docs/pull/3167
> [ 10.6] fixed the break line

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
BP of https://github.com/owncloud/docs/pull/3166
> [10.5] wnd quick guide

- modules/ROOT/pages/index.adoc
added top visited pages on the landing page of the docs
> added useful pages to the landing page

- modules/ROOT/pages/index.adoc
bp of https://github.com/owncloud/docs/pull/3173
> [10.5] added useful pages to the landing page

- modules/ROOT/pages/index.adoc
bp of https://github.com/owncloud/docs/pull/3173
> [10.6] added useful pages to the landing page

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Some small AV improvements.
Backport to 10.5 and 10.6 necessary
> AV Improvements

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.6] config-to-docs run

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.5] config-to-docs run

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.5] [PR 3186] AV Improvements

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.6] [PR 3186] AV Improvements

- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
another case documented for 0 storages, this time wrong credential method
> troubleshooting addition

- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
See https://github.com/owncloud/docs/pull/3098
> Changed RestartSec to avoid DefaultStartLimitBurst

- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
> [10.6] [PR 3202] Changed RestartSec to avoid DefaultStartLimitBurst

- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
> [10.5] [PR 3202] Changed RestartSec to avoid DefaultStartLimitBurst

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.6] Clarify log/delete choice actions in files_antivirus

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
> [10.5] Clarify log/delete choice actions in files_antivirus

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/metrics/metrics.adoc
I've cleaned up my old branch (hopefully!), here's a new one.
This obsoletes PR #3200.
> Added new metrics documentation.

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/metrics/metrics.adoc
> [10.6] [PR 3217] Added new metrics documentation.

- modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
This PR fixes one bad anchor and is especially made, that the last backports merged will get published.
(The publishing process is currently triggered only, when a PR made for master is merged...)
This PR needs backporting to 10.5 and 10.6
> Fix one bad anchor reference

- modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
> [10.6] [PR 3221] Fix one bad anchor reference

- modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
> [10.5] [PR 3221] Fix one bad anchor reference

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/metrics/metrics.adoc
Backport of PR #3217
There will be follow up backports for #3218 and #3225
> [10.5] [PR 3217] Added new metrics documentation.

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
owncloud/windows_network_drive#321
> Remove insecure wnd password example

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
> [10.6] [PR 3235] Fix trailing slashes when using examplesdir

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
> [10.5] [PR 3235] Fix trailing slashes when using examplesdir

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
fixes https://github.com/owncloud/docs/issues/345
> documented options

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
https://github.com/owncloud/docs/pull/3242
> [10.5] documented options

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
https://github.com/owncloud/docs/pull/3242
> [10.6] documented options

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Backport #3238 
owncloud/windows_network_drive#321
> [10.5] Remove insecure wnd password example

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Backport #3238 
owncloud/windows_network_drive#321
> [10.6] Remove insecure wnd password example

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
fixes: https://github.com/owncloud/docs/issues/3109
other PR https://github.com/owncloud/docs/pull/3236
> clarified the functionality of the command

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
bp of https://github.com/owncloud/docs/pull/3252
> [10.6] clarified the functionality of the command

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
bp of https://github.com/owncloud/docs/pull/3252
> [10.5] clarified the functionality of the command

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.6] add note about wnd listener limitations

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> [10.5] add note about wnd listener limitations

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/server/security/index.adoc
- modules/admin_manual/pages/configuration/server/security/jquery_warning.adoc
Add userinformation on outdated jQuery warnings
Issue: #3261
PR needed for 10.6 and 10.5
> Add infos to docs about jQuery outdated warning

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/server/security/index.adoc
- modules/admin_manual/pages/configuration/server/security/jquery_warning.adoc
> [10.5] [PR 3266] Add infos to docs about jQuery outdated warning

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/server/security/index.adoc
- modules/admin_manual/pages/configuration/server/security/jquery_warning.adoc
> [10.6] [PR 3266] Add infos to docs about jQuery outdated warning

- modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
Issue #3261
broken link fix and small textchanges
BP needed for 10.6 and 10.5
> Update jQuery Warning Info

- modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
> [10.6] [PR 3269] Update jQuery Warning Info

- modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
> [10.5] [PR 3269] Update jQuery Warning Info

- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/testing/drone.adoc
fixes https://github.com/owncloud/docs/issues/291
> drone testing

- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/testing/drone.adoc
bp of https://github.com/owncloud/docs/pull/3272
> [10.5] drone testing

- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/testing/drone.adoc
bp of https://github.com/owncloud/docs/pull/3272
> [10.6] drone testing

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
bp of https://github.com/owncloud/docs/pull/3275
> [10.6] fixed example block

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
bp of https://github.com/owncloud/docs/pull/3275
> [10.5] fixed example block

- modules/developer_manual/pages/core/index.adoc
- modules/developer_manual/pages/core/introduction.adoc
> [10.5] Develop with latest core master

- modules/developer_manual/pages/core/index.adoc
- modules/developer_manual/pages/core/introduction.adoc
> [10.6] Develop with latest core master

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
https://github.com/owncloud/docs/pull/3282
> note about the permission manager

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
bp of https://github.com/owncloud/docs/pull/3287
> [10.5] note about the permission manager

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
bp of https://github.com/owncloud/docs/pull/3287
> [10.6] note about the permission manager

- modules/admin_manual/pages/appliance/configuration/office.adoc
Issue: #2492
(re-do after problems with squashing)
> OnlyOffice documentation for license path new

- modules/admin_manual/pages/appliance/configuration/office.adoc
> [10.6] [PR 3290] OnlyOffice documentation for license path new

- modules/admin_manual/pages/appliance/configuration/office.adoc
> [10.5] [PR 3290] OnlyOffice documentation for license path new

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
fixes https://github.com/owncloud/docs/issues/2724
> added checklist for troubleshooting

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.6] [PR 3294] added checklist for troubleshooting

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
> [10.5] [PR 3294] added checklist for troubleshooting

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.6] [PR 3295] changes to unclear LDAP Quota

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
> [10.5] [PR 3295] changes to unclear LDAP Quota

- modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
- modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
Just some improvements and fixes.
Needs backporting to 10.5 and 10.6
> Some improvements and fixes

- modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
- modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
> [10.5] [PR 3301] Some improvements and fixes

- modules/admin_manual/pages/configuration/server/maintenance_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/managing_background_jobs.adoc
- modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
> [10.6] [PR 3301] Some improvements and fixes

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- changed name of the document
- made the improvements suggested by Interns
- removed unnecessary warnings and notes
- changed the LDAPS section back to the original state
> document improvements

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
BP of https://github.com/owncloud/docs/pull/3293
url variable
Co-authored-by: Martin <github@diemattels.at>
remove new url
Co-authored-by: Martin <github@diemattels.at>
removed extra spaces
> [10.6] document improvements

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
BP of https://github.com/owncloud/docs/pull/3293
url variable
Co-authored-by: Martin <github@diemattels.at>
remove new url
Co-authored-by: Martin <github@diemattels.at>
removed extra spaces
> [10.5] document improvements

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.6] [PR 3307] ubuntu 20.04 -- append to crontab 

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.5] [PR 3307] ubuntu 20.04 -- append to crontab

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
fixes https://github.com/owncloud/docs/issues/3028
> removed verbose option

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
BP of https://github.com/owncloud/docs/pull/3311
> [10.5] removed verbose option

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
BP of https://github.com/owncloud/docs/pull/3311
> [10.6] removed verbose option

- modules/user_manual/pages/files/federated_cloud_sharing.adoc
fixes https://github.com/owncloud/docs/issues/2294
fixed button syntax at the end of the document
> added note about fed sharing configuration

- modules/user_manual/pages/files/webgui/sharing.adoc
fixes https://github.com/owncloud/docs/issues/2294
added note about the guest users being able to use the sync client
> added note about sync client and guest users

- modules/user_manual/pages/files/webgui/sharing.adoc
BP of https://github.com/owncloud/docs/pull/3280
> [10.5] added note about sync client and guest users

- modules/user_manual/pages/files/webgui/sharing.adoc
BP of https://github.com/owncloud/docs/pull/3280
> [10.6] added note about sync client and guest users

- modules/admin_manual/pages/installation/docker/index.adoc
fixes https://github.com/owncloud/docs/pull/2782
> enterprise docker image deprication note

- modules/admin_manual/pages/installation/docker/index.adoc
BP of https://github.com/owncloud/docs/pull/3319
> [10.6] enterprise docker image deprication note

- modules/admin_manual/pages/installation/docker/index.adoc
BP of https://github.com/owncloud/docs/pull/3319
> [10.5] enterprise docker image deprication note

- modules/admin_manual/pages/installation/apps_supported.adoc
fixes https://github.com/owncloud/docs/pull/3038
> edited note

- modules/admin_manual/pages/installation/apps_supported.adoc
> [10.5] edited note

- modules/admin_manual/pages/installation/apps_supported.adoc
BP of https://github.com/owncloud/docs/pull/3327
> [10.6] edited note

- modules/admin_manual/pages/installation/docker/index.adoc
> [10.6] fixed code block, added header, removed registry, fixed link

- modules/admin_manual/pages/installation/docker/index.adoc
BP of https://github.com/owncloud/docs/pull/3338
> [10.5] fixed code block, added header, removed registry, fixed link

- bin/cli
- bin/yamlparse.sh
- bin/yamltest.sh
> [10.5] [PR 3337] Fix to dynamically create the attribute-to-argument list for asciidoctor-pdf

- bin/cli
- bin/yamlparse.sh
- bin/yamltest.sh
> [10.6] [PR 3337] Fix to dynamically create the attribute-to-argument list for asciidoctor-pdf

- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
> [10.6] [PR 2818] Update saml_2.0_sso.adoc

- modules/admin_manual/examples/enterprise/user_management/shibboleth/apache-2.4-configuration.conf
- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
> [10.6] Change mod_shib to mod-shib

- modules/admin_manual/examples/enterprise/user_management/shibboleth/apache-2.4-configuration.conf
- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
> [10.5] Change mod_shib to mod-shib

- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
fixes https://github.com/owncloud/docs/issues/3308
@micbar please help me with the wording.
> added limitation to the metrics app doc

- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
> [10.6][PR 3347] added limitation to the metrics app doc

- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
> [10.5][PR 3347] added limitation to the metrics app doc

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
fixes: # #3260 #3060
transports config.sample changes from core to docs
> transports config.sample changes from core to docs

- modules/admin_manual/pages/enterprise/installation/install.adoc
Issue: #3180
backport needed for 10.6 and 10.5
> added info on license key registration

- modules/admin_manual/pages/enterprise/installation/install.adoc
> [10.6][#3361] added info on license key registration

- modules/admin_manual/pages/enterprise/installation/install.adoc
> [10.5][#3361] added info on license key registration

- docs/best-practices.md
Small update of the Best Practice Guide.
No backport needed.
> Update BPG Guide

- modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
link redis server attributes from site.yml
> link redis server attributes in docs

- modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.6][#3364] link redis server attributes in docs

- modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.5][#3364] link redis server attributes in docs

- README.md
- docs/new-version-branch.md
> [10.6] [PR 3370] Improved README.md how to create a new version branch

- README.md
- docs/new-version-branch.md
> [10.7] [PR 3370] Improved README.md how to create a new version branch

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
> [10.7][#3368] add link to introduction in code_signing.html

- modules/admin_manual/pages/maintenance/migrating.adoc
> [10.7][PR 3378] Update migrating.adoc

- modules/admin_manual/pages/maintenance/migrating.adoc
> [10.6] [PR 3378] Update migrating.adoc

- docs/best-practices.md
new PR after problems in #3373
backport needed for 10.7 and 10.6
> fix best-practices guide changes

- docs/best-practices.md
> [10.7][PR 3384] fix best-practices guide changes

- docs/best-practices.md
> [10.6][PR 3384] fix best-practices guide changes

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Updates for config.apps.sample changes from core.
References: https://github.com/owncloud/core/pull/38576
Please merge only after core PR has been merged.
> config.apps.sample changes from core

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
> [10.7] [PR 3389] config.apps.sample changes from core

- modules/admin_manual/pages/release_notes.adoc
Draft for 10.7 Release Notes. Please review for correctness and language.
THX!
> 10.7 Release Notes

- modules/user_manual/pages/files/webgui/tagging.adoc
Fixed issue #3336 and smoothed the text. Needs backport to 10.7.
> Updated according to the interface changes in 10.7 with regard to tagging.

- modules/admin_manual/pages/release_notes.adoc
> [master] [PR 3388] 10.7 Release Notes

- modules/user_manual/pages/files/webgui/tagging.adoc
> [10.7] [PR 3391] Updated according to the interface changes in 10.7 with regard to tagging

- modules/admin_manual/pages/release_notes.adoc
> [10.7] [PR 3396] Add migration info to 10.7 release notes

- docs/new-version-branch.md
Documents: https://github.com/owncloud/docs/pull/3399
> Fix documenting new version branch

- modules/developer_manual/pages/core/theming.adoc
Fixed the apps directory name and added the docker directory as reported in issue #3393. Backport for 10.7 and 10.6 needed.
> Corrected the apps directory.

- modules/developer_manual/pages/core/theming.adoc
> [10.7] Corrected the apps directory.

- modules/developer_manual/pages/core/theming.adoc
> [10.6] Corrected the apps directory.

- modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
Layout fixes for issue #3405. Backport to 10.7 and 10.6 necessary.
> Fixed layout problems in occ-commands.

- modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
> [10.6] [PR 3406] Fixed layout problems in occ-commands.

- modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
> [10.7] [PR 3406] Fixed layout problems in occ-commands.

- modules/admin_manual/pages/configuration/server/app_commands/wnd_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
Add missing occ wnd commands
Backport **only** to 10.7
> Add missing occ wnd commands

- modules/admin_manual/pages/configuration/server/app_commands/wnd_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.7] [PR 3409 ] Add missing occ wnd commands

- modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
> [10.7] [PR 3402]  don't change /usr/lib/systemd/system/httpd.service

- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
> Fix typo of Metrics

- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
> [10.7] Fix typo of Metrics

- modules/admin_manual/pages/release_notes.adoc
> 10.7 known issues

- modules/admin_manual/pages/release_notes.adoc
> [10.7] [PR 3422] 10.7 known issues

- docs/style-guide.md
Creating an actual style guide. Please add things you'd like to see mentioned or protest if you don't agree with something.
> Major additions to style guide

- README.md
Added pointer to style guide and fixed some language issues.
> Adding reference to style guide.
