owncloud/docs

- modules/developer_manual/pages/core/theming.adoc
[4312 from the documentation repository](https://github.com/owncloud/documentation/pull/4312): "_Mimetypes Management addition to theming_".
> Backport https://github.com/owncloud/documentation/pull/4312

- modules/ROOT/pages/configuration/files/external_storage/ftp.adoc
- modules/ROOT/pages/configuration/files/external_storage_configuration_gui.adoc
This backports https://github.com/owncloud/documentation/pull/4290/. It contains changes to external storage FTP and the external storage configuration GUI documentation.
> Backport documentation #4290

- modules/ROOT/pages/configuration/files/encryption_configuration.adoc
A user in central has noticed that you can't move the master key keys to another location other than one inside the onwcloud data directory. This should document that limitation
> Encryption move keys

- modules/ROOT/nav.adoc
- modules/ROOT/pages/configuration/files/big_file_upload_configuration.adoc
- modules/ROOT/pages/configuration/server/occ_command.adoc
- modules/ROOT/pages/configuration/user/user_auth_ftp_smb_imap.adoc
- modules/ROOT/pages/enterprise/installation/install.adoc
- modules/ROOT/pages/installation/command_line_installation.adoc
- modules/ROOT/pages/installation/installation_wizard.adoc
- modules/ROOT/pages/installation/linux_installation.adoc
- modules/ROOT/pages/installation/manual_installation.adoc
- modules/ROOT/pages/maintenance/manual_upgrade.adoc
- modules/ROOT/pages/maintenance/migrating.adoc
- modules/ROOT/pages/maintenance/restore.adoc
- modules/ROOT/pages/maintenance/update.adoc
This change was suggested by @voroyam, as it makes the documentation that much more intuitive.
> Rename source_installation to manual_installation

- modules/user_manual/pages/files/access_webdav.adoc
Recently, we found that the setting "Allow users on this server to send shares to other servers" is required in order to access public shares over WebDAV.
If this setting is not enabled, "HTTP Access Denied" is returned (which is correct, but) what makes it difficult to find out how to enable this feature.
Hence, we should note this in the docs.
> noted required setting for accessing public shares over WebDAV

- modules/ROOT/pages/installation/manual_installation.adoc
- modules/ROOT/pages/installation/system_requirements.adoc
This updates the documentation to set PHP 7.2 as the minimum
(recommended) version of PHP.
> Backport #4429 to the Antora build

- docs/what-is-asciidoc.md
Added a set of handy AsciiDoc documentation links to the "_What is AsciiDoc_" section of the documentation. This fixes #104.
> Add a set of documentation links to the AsciiDoc guide

- modules/developer_manual/examples/scripts/read-config.php
- modules/developer_manual/examples/scripts/theme-bootstrap.sh
- modules/developer_manual/pages/core/theming.adoc
Two scripts were missing from developer_manual/core/theming.adoc. Without these, the user will be unable to follow the instructions on the page. This is a, sort-of, backport of the fix applied to the old
documentation. Thanks to @voroyam for pointing this out in the old documentation.
> Add missing developer manual theming scripts

- modules/ROOT/pages/configuration/user/user_configuration.adoc
Add text in ``configuration/user/user_configuration.adoc`` that the initial password cant be "0".
This text is already present in occ_commands.adoc but was missing here.
References: https://github.com/owncloud/docs/pull/115 (User password cannot be "0") which was closed because of a file issue.
> Add text that user password cannot be "0"

- modules/ROOT/pages/configuration/server/occ_app_command.adoc
References: https://github.com/owncloud/docs/issues/79 (Antivirus - missing occ command background true/false)
Adds the documentation how to configure ``files_antivirus`` in the ``occ_apps_command`` file.
pls note that the description text is taken from the app.
(I also changed the sort order of the rows of the tables in brute force to be inline with files_antivirus)
> Document occ app files_antivirus

- .github/issue_template.md
This PR updates the GitHub New Issue template to provide a step-by-step guide on what's required to create a new issue.  My intent is that this will:
1. Help encourage potential contributors to get involved and contribute to the documentation.
2. Make it as simple as possible to create detailed issues that can be actioned as quickly as possible.
This fixes #103.
> Update the GitHub New Issue Template

- README.md
- resources/themes/custom-theme.yml
- resources/themes/owncloud-theme.yml
This PR
1. Adds a custom theme, which overrides the relevant settings, and copies in a lot of the other settings.
2. Extends the README, documenting how to generate the PDF versions of the manuals.
💁: The custom theme is required as, [asciidoctor-pdf](https://github.com/asciidoctor/asciidoctor-pdf#themes) uses a default theme. While fine, it isn't enough for ownCloud's needs, as it looks quite different to the PDF's currently being generated.
> Add PDF Theme Support

- modules/developer_manual/pages/commun/help_and_communication.adoc
- modules/developer_manual/pages/core/introduction.adoc
Without these changes, the developer PDF manual will not build correctly, specifically the TOC (table of contents).
> Minor changes to the developer manual to help with PDF generation

- .gitignore
These aren't necessary as the TTF files need to be supplied at installation and the PDF files are generated as-needed.
> Do not track PDF and TTF files

- README.md
- resources/themes/owncloud-theme.yml
This PR updates the custom PDF theme to use two custom fonts, *Times New Roman* and *Courier*, in place of the bundled Times Roman and Courier fonts. This is because the bundled fonts don’t support a wide enough character set to render the manuals correctly.
#92 & #97.
> Use Custom Font in the Custom ownCloud PDF Theme

- modules/ROOT/pages/configuration/files/file_sharing_configuration.adoc
A user in central did not see the sharing section. after some troubleshooting we found that the adblock plugin was resprosible for this weird behavior. this should document this. Fixes #106.
> sharing section adblocker

- modules/administration_manual/pages/installation/system_requirements.adoc
A user in central has brought to my attention that nowhere in our docs we have mentioned what client version still works with the current server release.
If people are for what ever reason not upgrading to the latest version we should document what still works.
> Minimum client versions

- modules/administration_manual/pages/configuration/server/occ_command.adoc
This backport documents that occ config:system:set accepts values in JSON format, in addition to boolean, integer, float, and string. It fixes #94.
> Backport owncloud/documentation#4405 to the new docs

- Makefile
To help ensure that the quality of the documentation continues to improve, two extra Makefile targets have been added in this commit. The first one checks the prose of all AsciiDoc files. The second one checks the prose in staged AsciiDoc files only. The intent here is to allow for prose review in a variety of circumstances.
> Add prose linting support

- modules/administration_manual/pages/configuration/server/occ_command.adoc
Fixes: https://github.com/owncloud/docs/issues/163 (Port of documentation/pull/4411)
Port: https://github.com/owncloud/documentation/pull/4411 (Document the send-email and output-link options to user:resetpassword)
The texts were adopted, improved and fixed.
> Document the send-email and output-link options to user:resetpassword

- modules/administration_manual/pages/configuration/files/external_storage/dropbox.adoc
Fix for https://github.com/owncloud/docs/pull/153#issuecomment-430960610 (unterminated listing block)
modules/administration_manual/pages/configuration/files/external_storage/dropbox.adoc
This was a bug. Now the document renders properly.
> fix unterminated listing block

- modules/developer_manual/pages/core/acceptance-tests.adoc
- modules/developer_manual/pages/core/ui-testing.adoc
Issue #140 
We have introduced these 3 make file targets ``test-acceptance-api`` ``test-acceptance-cli`` and ``test-acceptance-api`` in core. They are also implemented in some apps, and we will gradually implement this "standard" through all apps that have acceptance tests.
> document make test-acceptance-api,cli,webui

- modules/developer_manual/pages/core/acceptance-tests.adoc
This commit corrects a series of small issues, including:
- Correcting spelling of product names and terms
- Reflowing text to be one sentence per line (most of the time)
- Removing non-ascii characters
> Minor corrections to acceptance tests documentation

- modules/administration_manual/pages/configuration/files/encryption_configuration.adoc
This PR fixes:
- properly call occ 
- some texts
- table layouts
- quote (air quote)
- broken link
References: https://github.com/owncloud/docs/issues/180 (Correct references to occ in configuration/files/encryption_configuration.adoc)
> Fixes encryption_configuration.adoc: occ commands and other stuff

- modules/administration_manual/pages/installation/docker/index.adoc
Remove references to port 443 and replace references to port 80 with 8080. This fixes to  owncloud/docs#185 and relates to owncloud-docker/server#94.
>  Update documented ports in the docker documentation

- docs/getting-started.md
- docs/install-antora.md
Fix for issue: https://github.com/owncloud/docs/issues/190 (Broken link to install Antora command line tools)
``install-antora.md`` is in the same directory as ``getting-started.md``
> fix link to install antora

- modules/administration_manual/pages/configuration/server/occ_app_command.adoc
- modules/administration_manual/pages/configuration/server/occ_command.adoc
This PR corrects the level for headers like Arguments and Options but also for some others in the occ (apps) command reference, so that the header levels used are now correct.
> Correct header level for argument and options in occ (apps) command reference

- docs/getting-started.md
This is a small improvement.
The current ``Learn [the AsciiDoc file format]`` references to the same file as ``Learn [Antora's basics](./what-is-antora.md)`` which makes imho no sense.
Therefore I changed that line to a more relevant content, to get the syntax right, see links/references added.
> Improve getting-started.md

- modules/administration_manual/pages/configuration/server/occ_app_command.adoc
- modules/administration_manual/pages/configuration/server/occ_command.adoc
This PR fixes a warning:
``WARNING: file_xy.adoc: line 771: section title out of sequence: expected level 2, got level 3``
This happens when you have headers where headers jump over an expected level.
No Warning
``==``
``===``
``====``
Warning
``==``
``====``
The fix eliminates the warning by adding a header with the needed level.
There is no visibility break when you don´t do it, but fixing it quiets the antora docs build process.
> Section Title out of Sequence

- modules/administration_manual/nav.adoc
- modules/administration_manual/pages/configuration/server/occ_app_command.adoc
- modules/administration_manual/pages/maintenance/export_import_instance_data.adoc
Contains a new page describing the upcoming ``data_exporter`` app with examples and an extension of the occ apps command page describing the commands in detail.
I have created ths PR here in docs as it is the correct place for it.
Complies with the new antora doc system we use.
References:
Issue: https://github.com/owncloud/data_exporter/issues/13 (Write user documentation)
PR: https://github.com/owncloud/data_exporter/pull/44 (User manual - Draft)
PR: https://github.com/owncloud/data_exporter/pull/45 (Having a common hierarchy for the occ commands)
Please comment/add all your stuff here, this is the only place your documentation contribution will reach  the users !
Merging only when data_exporter will be released to the marketplace !
> Description for data_exporter app

- site.sample.yml
[Antora](https://docs.antora.org/antora/)'s still a bit young, so it doesn't - **yet** - provide documentation in all forms necessary to answer the questions that every user could have (okay, no project does a perfectly comprehensive job, but I hope you get what I'm saying here). 
So this commit adds a sample [Playbook file](https://docs.antora.org/antora/1.0/playbook/#playbook-file-formats), one that is heavily commented, so that contributors can better understand what can be configured, what the sections do, and where to find more information.
**Note:** It is also usable when building the ownCloud docs in what Antora refers to as [Author Mode](https://docs.antora.org/antora/1.0/playbook/author-mode/).
> Add a sample playbook file

- modules/administration_manual/pages/installation/docker/index.adoc
The SSL functionality has been dropped recently.
The section referenced to an https URL and didn't indicate the correct port as defined in the ``docker-compose.yml``.
The box about the HTTPS warning is not needed anymore.
See: https://github.com/owncloud-docker/server/issues/89
> [Docker] Adapt missleading 'Logging In' Section

- docs/build-the-docs.md
- generator/xref-validator.js
This PR adds a custom Antora generator script that can find and report broken Xrefs in the documentation and updates the docs to show how to use it.
> Add broken Xref checker

- .dockerignore
- Dockerfile
- docs/build-the-docs.md
- generate-site.js
- package-lock.json
- package.json
- site.prod.yml
This PR implements site search into the documentation, powered by Lunr. There is an as yet unresolved bug generating the documentation with a Docker container, but the documentation can be generated from the command-line successfully.
> Implement site search

- docs/checking-broken-links.md
Small update to the broken link page to highlight that there are sample links which are reported as false-positives.
> adding a note about false positives

- modules/developer_manual/pages/app/advanced/code_signing.adoc
- modules/developer_manual/pages/core/ui-testing.adoc
- modules/developer_manual/pages/core/unit-testing.adoc
- modules/developer_manual/pages/general/devenv.adoc
- modules/developer_manual/pages/general/security.adoc
- modules/developer_manual/pages/testing/index.adoc
- modules/user_manual/pages/files/large_file_upload.adoc
- modules/user_manual/pages/files/webgui/custom_groups.adoc
The next PR fixing broken links.
As usual:
- fixing broken links
- changing redirected links to the new location
- using link: in front of http
- fixing links with problematic URL (needs special attention)
- fixing (broken) references to the built site by using xref instead of http
- text fixes where found
There will be more PR´s with these kind of fixes (as you already hyve seen before) because I have to run the linkckecker each time again after merging. The resulting output file has to be parsed manually and there are so many entries to check...
But we are getting closer to an end :smile:
> Fixing more broken links

- modules/administration_manual/pages/installation/docker/index.adoc
Replace "server" with "owncloud" to match the correct service name.
Added step for "occ upgrade".
Note: I could not test the instructions with "occ upgrade" because in my local env the container is stuck trying to restart:
```
CONTAINER ID        IMAGE                      COMMAND                  CREATED              STATUS                          PORTS               NAMES
64e0fbd816e0        owncloud/server:10.0.10    "/usr/bin/entrypoint…"   About a minute ago   Restarting (5) 32 seconds ago                       owncloud-docker-server_owncloud_1
1f8913bc6932        webhippie/redis:latest     "/usr/bin/entrypoint…"   About a minute ago   Up About a minute (healthy)     6379/tcp            owncloud-docker-server_redis_1
1594998c7ca7        webhippie/mariadb:latest …
```
> Update docker upgrade instructions

- .drone.yml
- docs/build-the-docs.md
- site.yml
As Playbook options can be passed on the command-line, such as the site URL, there's no point in going down the path of creating environment-specific playbooks. As such, the core Playbook's been renamed and the documentation that referred to it has been updated.
> Remove environment-specific Antora playbook

- modules/administration_manual/pages/issues/impersonate_users.adoc
This backports https://github.com/owncloud/documentation/pull/4466 from
the old documentation.
> Backport update to Impersonate Section

- Makefile
To make it as simple as possible to get users up and running, this commit adds a make target that automates installing the Antora command-line tools.
> Add a make target to install the Antora command-line tools

- Makefile
This is designed as another step for simplifying working with Antora projects. It uses a custom Antora build pipeline that makes use of a custom project generator, that can validate all Xrefs in a Playbook's
source files and output a report based on what it finds, if there are any invalid Xrefs found.
This is an initial concept. I'd like to integrate it with the ui-bundle.zip that's built, in the future, as part of the upcoming docs-ui build pipeline.
> Add a make target for running an Antora Xref validator

- modules/administration_manual/pages/maintenance/manual_upgrade.adoc
This backports https://github.com/owncloud/documentation/pull/4455.
According to @tomneedham, the advice is incorrect and may lead to
upgrade errors.
> Deprecate instruction to disable core apps before upgrading

- modules/developer_manual/pages/general/security.adoc
While there's nothing, necessarily, wrong with the link as it was, it's at risk of becoming hard to read. However, if a page attribute is used, then the link can be written as normal, with no unnecessary extra
formatting, and also makes the prose easier to read, as there's no infix URL to scan.
See https://asciidoctor.org/docs/user-manual/#complex-urls for more info on the topic.
💁 personally, I'm for using attributes, the more I look at it, as they make the prose easier to read and they're also reusable. They're like a nicer version of rST page links.
> Simplify the XSS link in the developer security documentation

- modules/developer_manual/pages/core/acceptance-tests.adoc
- modules/developer_manual/pages/core/ui-testing.adoc
This backports https://github.com/owncloud/documentation/pull/4473/files to the new documentation. Thanks @phil-davis.
> Backport remove-sudo-www-data-from-acceptance-test-instructions

- modules/administration_manual/pages/configuration/files/encryption/index.adoc
This is a small fix because of an error message when building the docs:
``only book doctypes can contain level 0 sections``
caused by a missing ``leveloffset=+1`` in configuration/files/encryption/index.adoc
> Fix: only book doctypes can contain level 0 sections

- modules/developer_manual/pages/core/acceptance-tests.adoc
Update and add to the acceptance test documentation.
This PR is aimed at:
from issue #156
> Document how we write acceptance tests

- modules/administration_manual/pages/configuration/server/occ_command.adoc
Referencing issue: https://github.com/owncloud/docs/issues/409 (occ command "upgrade" got an additional option)
Referencing core PR: https://github.com/owncloud/core/pull/32491 (Pass an additional parameter on the core update)
`occ upgrade` new option: `--major`
`Automatically update apps to new major versions during minor updates of ownCloud Server`
> occ upgrade new option

- site.yml
This PR integrates [the branded_clients](https://github.com/owncloud/branded_clients) repository's `master-antora` branch into the new Antora docs.
> Add the branded_clients antora build to the docs

- modules/administration_manual/pages/configuration/server/antivirus_configuration.adoc
- modules/administration_manual/pages/enterprise/firewall/file_firewall.adoc
This PR fixes an issue I found when looking in the drone result creating pdf´s, example:
Failed to parse formatted text: <img src="/drone/src/modules/administration_manual/assets/images/enterprise/firewall/firewall-3.png" format="png" alt="[Protecting files tagged with "Confidential" from outside access]" tmp="false">
The issue are the double quote inside the alternative text eg "Confidential".
This is not a problem when the docs are built to html because double quotes inside an alt text are rewritten to `&quot;` (see https://github.com/asciidoctor/asciidoctor/issues/2061) but in building the pdf´s seems they are.
The pdf generator seems to take the complete img src string and parses back `&quot;` to double quotes which generate this error...
Created an issue at: …
> fixing failed to parse formatted text (image alt text)

- modules/ROOT/pages/index.adoc
This updates the links to the root pages of the iOS and Android manuals. 
Waiting on merge of the following PRs:
- https://github.com/owncloud/ios/pull/1092
- https://github.com/owncloud/android/pull/2380
> Update links to root pages of ios and android manuals

- site.yml
The decision's been made to remove the prefix and change the separator to a hyphen in auto-generated anchors to help keep the content structure reasonably consistent with the old documentation.
> Customise the way that auto-generated anchors are created

- modules/administration_manual/pages/configuration/server/occ_command.adoc
References https://github.com/owncloud/docs/issues/437 (Replace email example in occ user:setting)
**Reason**
When you set an email address with occ like described at https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/occ_command.html#setting-a-setting, this address is stored in oc_preferences as user preferences whereas changing the password in the UI only changes the values in oc_accounts (source).
At every login the password is synced from the preferences to the accounts table (called here and performed there) and thus changes from the UI are lost.
> update occ user setting command

- modules/developer_manual/pages/general/security.adoc
The `:xss-link:` reference was broken.
Maybe due to auto cleanup of `link:`...
Tested with docs build, works now.
> xss link reference broken

- modules/administration_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
The `occ-files_transfer-ownership-link:` reference was broken.
Maybe due to auto cleanup of `link:`...
Tested with docs build, works now.
Plus some text fixes.
> occ-files_transfer-ownership-link broken

- generators/xref-validator.js
This PR fixes the `xref-validator.js` script to be inline with: https://gitlab.com/antora/docs.antora.org/tree/master/generator
There has been a recent change made in master related to my PR https://gitlab.com/antora/docs.antora.org/merge_requests/18
Tested with `make validate`, I do not get any error when no broken links are found.
Any release update of antora will now contain this fix.
> Fix xref-validator copied from antora master

- modules/administration_manual/pages/configuration/files/encryption/master-key-encryption.adoc
- modules/administration_manual/pages/configuration/files/external_storage/dropbox.adoc
- modules/administration_manual/pages/configuration/server/logging_configuration.adoc
- modules/administration_manual/pages/configuration/server/occ_command.adoc
- modules/administration_manual/pages/enterprise/ransomware-protection/index.adoc
- modules/administration_manual/pages/issues/general_troubleshooting.adoc
- modules/administration_manual/pages/release_notes.adoc
- modules/developer_manual/pages/app/advanced/code_signing.adoc
- modules/developer_manual/pages/core/acceptance-tests.adoc
There were a number of instances where rST-style double-backticks still persisted. These are unnecessary in AsciiDoc.
> Convert rST double backticks to adoc single backticks

- modules/administration_manual/nav.adoc
This PR is just a small change in the navigation for better identification
`Migrating` --> `Migrating to a Different Server`
> Better naming for migration to a different server

- modules/administration_manual/nav.adoc
This PR fixes the missing config apps sample parameter doc entry in the navigation section
> Missing config apps navigation entry

- site.yml
This fix ensures that docs master is always used for building the latest docs. Somehow, the [author mode](https://docs.antora.org/antora/1.1/playbook/author-mode/#activate-author-mode) configuration had slipped through which broke the "_Edit This Page_" links.
> Fix incorrect site.yml configuration

- Makefile
- docs/install-antora.md
After a discussion with @PVince81 "setup" is much more intuitive.
> Rename install make target to setup

- modules/ROOT/pages/index.adoc
- modules/administration_manual/pages/configuration/files/external_storage/ftp.adoc
- modules/administration_manual/pages/configuration/files/external_storage/local.adoc
- modules/administration_manual/pages/index.adoc
- modules/administration_manual/pages/release_notes.adoc
- modules/developer_manual/pages/app/fundamentals/database.adoc
- modules/developer_manual/pages/app/fundamentals/info.adoc
- modules/user_manual/pages/files/desktop_mobile_sync.adoc
- modules/user_manual/pages/index.adoc
This is necessary as the .org domain has been deprecated, [as @tboerger pointed out](https://github.com/owncloud/docs/pull/468/#pullrequestreview-190141473).
> Replace references to doc.owncloud.org with .com

- Makefile
- docs/build-the-docs.md
- site.local.yml
This PR provides a local playbook, that will build the three core manuals, incorporating changes made in the local (GIT) working directory. It also updates the docs so that users know that this option is available.
> Add a local playbook

- modules/administration_manual/pages/enterprise/file_management/files_tagging.adoc
This relates to owncloud/enterprise#2748, by documenting the ability to create static tags, that are only editable by admins but can be assigned and unassigned by whitelisted group members.
This change:
1. Converts the previous formatting of the tag types into a description list to provide them with greater emphasis
2. Better emphasises that the Collaborative Tag Management app needs to be installed
3. Reflows some text as one sentence per line, so that it's easier to edit and maintain.
> Document static tagging functionality

- modules/administration_manual/pages/configuration/database/linux_database_configuration.adoc
This PR fixes
- An error when building the site with make html because of list indexing starting with the same number
Now the numbering and indent is correct and no error is shown.
- Some line breakes for better source readability (no rendering impact)
- Fix link to config sample file
> Fix list item index error

- docs/getting-started.md
As @tboerger rightly pointed out, GitHub automatically generates anchors for each header in a page. The custom ones that I inserted, therefore, are unnecessary.
> Remove unnecessary custom anchors

- modules/developer_manual/pages/app/advanced/code_signing.adoc
As the statement was, it could be misleading. So this commit updates it to make a distinction between apps that are to be uploaded to the Marketplace, and those that aren't (_just used directly in ownCloud, via manual installation_).
> Better clarify statement about code signing being optional

- .github/issue_template.md
This PR primarily aims to ensure that if someone is in a hurry, they can write what they need to as quickly as possible, and not have to fill out unnecessary forms. Thanks @voroyam.
It also:
1. Reorders the existing template items, top-loading them from the most to the least important.
2. Marks some items as optional.
3. Marks some items as used only by the docs team, not for people creating issues.
💁‍♂️ I hope this balances the requirements for people who are in a hurry, and those who have more time.
> Update the issue template to make it simpler

- .drone.yml
To change the directory for the site scraper it must change to `/root` instead of `root`
> Properly change to root folder for search update

- modules/administration_manual/pages/installation/deployment_considerations.adoc
SWIFT was still listed as usable backend storage - removed it.
> Remove SWIFT from the List of usable Storages

- site.yml
As the UI bundle changes from time to time, it needs to be marked as a snapshot, so that Antora will download it and get the latest changes. Not having this option set has lead to several UI updates, including the integrated site search not being made available.
- https://docs.antora.org/antora/2.0/playbook/configure-ui/#snapshot
- #554 
- https://github.com/owncloud/enterprise/issues/2528
> Mark UI Bundle as a snapshot

- site.yml
The Piwik settings should never have been merged, so they're temporarily being disabled for the time being.
> Temporarily disable the Piwik option

- Makefile
To continue improving the DocOps functionality of the project, I'm adding this change that adds four new targets. The targets add linting support for `XML`, `YAML`, `JSON`, and `PHP` files.
> Add a series of filetype-specific Markfile validation targets

- Makefile
- books/admin.adoc
- books/developer.adoc
- books/user.adoc
[According to the documentation](https://asciidoctor.org/docs/user-manual/#revision-number-date-and-remark) the revision number and date were being set from incorrect attributes. Based on that, this PR has been created to ensure that the PDF configuration files follow the format correctly.
This relates to:
- owncloud/administration-internal#101
- owncloud/enterprise#2528
> Set the revision number and date correctly

- modules/administration_manual/pages/installation/manual_installation.adoc
The configuration is for 18.04 and not for 16.04, php 7.2 is not by default
> Version to 18.04

- modules/administration_manual/nav.adoc
This change implements https://github.com/owncloud/documentation/issues/3346. It moves the
maintenance section out of the configuration section, giving it prominence again, and reorganises the upgrading section within it to have that section make more sense, as well as be easier to navigate.
> Reorganise the maintenance section of the admin manual's navigation menu

- site.yml
This backports #588 to the 10.1 branch.
> Remove Piwik integration

- antora.yml
- modules/ROOT/pages/index.adoc
This PR:
- Updates the docs to build version 10.1 and move version 10.0 to be the previous version.
- Update the links to the three core manuals to reference the new latest version and to move the others back a version.
> Update docs for version 10.1

- modules/ROOT/pages/index.adoc
- site.local.yml
- site.yml
This will ensure that the playbook and component descriptor for version 10.0 of the docs only builds the latest docs from the 10.0 branch and no longer include master.
> Update playbook and component descriptor for version 10.0

- modules/ROOT/pages/_partials/maintenance-release-schedule-link.adoc
- modules/ROOT/pages/index.adoc
@settermjd Just an idea, should we make more clear, 9.1 is EOL? (in the past we had multiple supported versions)
BTW No [PR template](https://help.github.com/articles/about-issue-and-pull-request-templates/#pull-request-templates) here?
> Clarify ownCloud server 9.1 is EOL

- modules/developer_manual/pages/core/acceptance-tests.adoc
so that developers can know what are the tags used in acceptance test features and scenarios.
> Add section about tagging scenarios to acceptance-tests.adoc

- docs/what-is-antora.md
This change uses the recently created animated gif, showing how to navigate between different versions of a manual in Antora, rather than the previous still image.
> Use Antora version changer animated gif in what-is-antora docs

- modules/admin_manual/pages/configuration/server/occ_command.adoc
Issue #284 
This change should be released with the next core major version release.
So it should be able to be merged to `docs` `master`, but do not backport to any `10.*` branch because it will not be released in any of those versions.
> [OC11] Issue 284 document files:scan --group

- modules/developer_manual/examples/core/acceptance-tests/given-step.php
- modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php
- modules/developer_manual/examples/core/acceptance-tests/then-step.php
- modules/developer_manual/examples/core/acceptance-tests/when-step.php
- modules/developer_manual/pages/core/acceptance-tests.adoc
Part of issue #156 
This is meant to just give some clues/guidelines for the code of `Given` `When` and `Then` steps. For gory detail of how the whole Behat infrastructure fits together, I think developers need to actually read the Behat User Guide - we do have our `behat.yml`, suites and format of context PHP in the standard Behat way.
It applies equally-well to core `10.0` and `10.1` so can be backported.
> How to add new acceptance test steps

- modules/developer_manual/nav.adoc
the navigation link of "Availiable APIs" links to "Application Configuration"
> fix Available APIs navigation link

- modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
- modules/developer_manual/pages/app/fundamentals/filesystem.adoc
- modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
While building the docs recently, I've noticed that there have been a number of build errors. This change fixes quite a number of them but leaves the ones relating to "WARNING: skipping reference to missing attribute", as they'll take a bit of research to fix.
💁‍♂️ Check if backport to 10.1 & 10.1 is required.
> Fix some of the build errors

- modules/developer_manual/pages/core/unit-testing.adoc
Issue #660 
due to core PR https://github.com/owncloud/core/pull/34638
> Rename make test-php to test-php-unit

- modules/admin_manual/pages/release_notes.adoc
This fixes #649.
💁‍♂️ check if backport to 10.0 and 10.1 are required.
> Fix broken links in admin manual's release notes

- modules/developer_manual/pages/core/ocs-share-api.adoc
similar to  #664, accepting a pending remote share does not return any data, just the status
> accepting a pending remote share does not return any data

- modules/developer_manual/pages/core/ocs-share-api.adoc
> [10.1] accepting a pending remote share does not return any data

- modules/developer_manual/pages/core/ocs-share-api.adoc
> [10.0] accepting a pending remote share does not return any data

- modules/user_manual/pages/troubleshooting.adoc
Small fix because of an asciidoctor warning. (leftover double quote)
Backporting recommended
> fix leftover quote in user_manual/pages/troubleshooting.adoc

- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
Backport of #686 
* Add Location directive override warning
(cherry picked from commit 5609e7e5cc97418a27be39c9db241f17924a5816)
> 10.1 backport shib override warning3

- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
Backport of #686 
* Add Location directive override warning
(cherry picked from commit 5609e7e5cc97418a27be39c9db241f17924a5816)
> Add shibboleth override warning (#686)

- modules/admin_manual/pages/installation/manual_installation.adoc
In most other distributions ( ubuntu/debian or sles ) opcache is installed per default with the php packages. However in RedHat based distributions this is not the case.
While inspecting a couple of environments at customers sides I noticed that they are missing opcache.
Many instance I would consider this a performance issue and thus a less ideal user experience. 
Let's recommend to install these modules also per default
> Include opcache in the default installation recommendations

- modules/developer_manual/pages/general/backporting.adoc
This update improves the backporting script of the developer manual.
**New:**
- it checks if the SHA is already merged
- it finds automatically the PR of the SHA
- unified and better branch naming
- unified and better commit message naming
**Example (based on core):**
```
./backport.sh e989d22 stable10
Backporting commit 989d22 to stable10
...
Switched to a new branch ‘stable10-989d22-34654‘
...
Pushing [stable10] [PR 34654] Each generated birthday or death event gets a new UID
```
@settermjd this script is repro independent, means `./backport.sh abcdef 10.0`. We just need to set a link in our backporting description somwhere in readme.md
> Developer Manual: Improving the backport script

- modules/admin_manual/pages/release_notes.adoc
> [10.0] [PR 655] Fix broken links in admin manual's release notes

- modules/admin_manual/pages/release_notes.adoc
> [10.1] [PR 655] Fix broken links in admin manual's release notes

- modules/admin_manual/pages/configuration/server/occ_command.adoc
core PR https://github.com/owncloud/core/pull/34721 removed this.
The core changed is merged to core `stable10` by PR https://github.com/owncloud/core/pull/34722
So it will be released in the next core release, likely to be called 10.2
> Remove db:generate-change-script

- modules/developer_manual/examples/scripts/backport.sh
- modules/developer_manual/pages/general/backporting.adoc
I have found a much better way to gather the PR headline (title) and adopted the script,
plus improved the description text.
Info, to get the PR title in a proper way, you have to query via github api. There is as far as I have seen no git command to query the PR title and the attempts tried return sometimes empty or commit texts which lead to a manual copy/paste PR title handling.
> Improving backport

- site.yml
This PR explicitly specifies the local branch to use (`HEAD`) in `site.yml`. Without it specified, [the branches default to `[master, v*]`](https://docs.antora.org/antora/2.0/playbook/playbook-schema/#branches-key). Without it, running `yarn antora` results in `Error: Duplicate nav: master@server:ROOT:nav.adoc`, as `master` is listed as the `version` for a number of branches.
> Explicitly specify the local branch to use in site.yml

- modules/developer_manual/examples/scripts/backport.sh
- modules/developer_manual/pages/general/backporting.adoc
Based on experience, I added a note in the description and printed out the PR title for cases where there are merge conflicts which need manual intervention.
> Add note when the script breakes

- modules/developer_manual/examples/scripts/backport.sh
- modules/developer_manual/pages/general/backporting.adoc
> [10.1] [PR 724] Add note when the script breakes

- modules/developer_manual/examples/scripts/backport.sh
Another backporting script improvement.
Useful if you want to do consecutive backports, eg first to 10.0 and after to 10.1.
**Before** you manually had to switch back eg to the master branch and then do backporting.
**Now** you just can recall the last backport command and change the target branch.
> Remeber the base branch and switch back when finished

- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
There was no link but only a text looking like a link: (`See selinux_configuration for a...`)
Now there is a xref to the correct page.
> selinux link fix

- modules/admin_manual/pages/configuration/server/occ_command.adoc
Issue #742 
The `files:scan` command now supports both `--group` and `--groups` options. See the issue for details.
No backport required. This is for release in the next ownCloud core server, which is expected to be numbered `10.2`
> Document both files:scan --group and --groups options

- modules/developer_manual/pages/core/ocs-share-api.adoc
This PR is a followup of https://github.com/owncloud/docs/issues/757 (Missing examples in developer docs)
**Before**
Missing linked xml response files
**After**
xml response files are now linked
**Important**
I did NOT checked if the response content is valid... !
**Note**
I had to line compare the old file from the documentation repository with this one and manuall add all those missing xml response examples with their proper path. I also took the freedom, as this was not present before, to start each example with either `Failure` or `Success`  for better readability and distinction of those two.
There are more example files to be checked for their existance but missing inclusion in other documents...
> Fixes to ocs-share-api.adoc for missing xml response examples

- .drone.yml
- overlay/robots.txt
- overlay/ui.yml
- site.yml
Reverts owncloud/docs#793, it's wrong to add these secrets to the other branches, this should ONLY be done by the master branch and not on any other branch. The other branches are executing Antora only to verify that it's building correctly, it should not upload any data except the PDFs.
> Revert "Backport search secrets to 10.1"

- docs/checking-broken-links.md
This is a small improvement with regards of the command
`yarn linkcheck http://localhost:8080`
Added grep to filter broken results as the rest is not of value
`yarn linkcheck http://localhost:8080 | grep "BROKEN"`
Adopted the output accordingly and added a text line to highlight that there are real broken links.
> Improving Linkchecker

- docs/build-the-docs.md
Add `yarn run` to get a list of available  yarn commands which also can be started from that command.
> yarn run (build-the-docs.md)

- modules/admin_manual/pages/enterprise/installation/install.adoc
the links lead to e.g. `https://doc.owncloud.com/server/admin_manual/enterprise/installation/install.html#maintenance/upgrade`
would that fix it?
> fixing links

- modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc
- modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
This is a fix for
- missing references
- a small formatting cleanup
> Fix missing references in developer docs

- modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc
- modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
Reverts owncloud/docs#826
References revert https://github.com/owncloud/docs/pull/831
> Revert "[10.1] [PR 820] Fix missing references in developer docs"

- modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc
- modules/developer_manual/pages/webdav_api/groups.adoc
- modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
- modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
Small update to the developer docs fixing a typo and adding some comments for better understanding the include and varibale flow.
> Comments, typo and formatting update in dev_docs

- docs/getting-started.md
- docs/the-build-pipeline.md
This is a small text improvement how docs are built and deployed.
Before this was implizit in .drone.yml.
You needed to read the file to know what and when things happen.
Now it is explicitly written.
@PVince81 fyi
> Improve description how docs are built and deployed

- modules/developer_manual/nav.adoc
Clicking on Developer Manual, the list on the left opens, but the content on the right did not appear due to a missing refrence to index.adoc.
> Developer Manual reference to index was missing

- modules/developer_manual/nav.adoc
> [10.1] [PR 867] Developer Manual reference to index was missing

- modules/developer_manual/nav.adoc
> [10.0] [PR 867] Developer Manual reference to index was missing

- docs/build-the-docs.md
It adds a section showing how to install any prerequisite software and further clarifies how to install Antora's dependencies. It fixes #818.
> Provide extra clarity for how to build the docs locally

- modules/developer_manual/pages/general/devenv_docker.adoc
This is an emergency fix, because #739 has a failing xref (missing modulename to admin_manual)
Please approve so we can merge immedately. Other PR´s are failing because of this missing fix.
Will backport asap after merge.
> xref fix missing module name

- modules/user_manual/pages/files/webgui/sharing.adoc
As @voroyam said in #798, it's essential to document that when one user renames a share, they're the only one that will see the new name; all other users continue to see the original name. This fixes #798.
> Document the renaming shares functionality

- modules/developer_manual/pages/general/devenv_docker.adoc
Backport of PR #880
the original unmerged backports contained the whole new file and the error.
I closed these bp and replaced them with this respectively the other one.
else we would have the same issue with 10.0 and 10.1.
> [10.0] [PR 880] xref fix missing module name

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
This commit fixes #112 by documenting that:
- The Cron service needs to be re-enabled after an upgrade
- The web server user and group needs to own the downloaded archive
> Fix omissions in the manual upgrade documentation

- modules/admin_manual/pages/installation/manual_installation.adoc
- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Adresses: https://github.com/owncloud/docs/issues/602 (Ubuntu 18.04 php 7.2 ownCloud module dependency fix list)
The intention of this commit is to create a preparation page for Ubuntu 18.04 before ownCloud gets installed. There are too many steps for one page having all OS prepared and the oC installation, so lets split that and get a better overview.
As we know with this page how thinks look like, we can derive relatively easy to other OS and create own documents for them.
It currently does not cover any details to setups after installing like php or redis or mariadb ect.
A second page how to install oC on a prepared server makes a lot of sense and is OS independent.
This page is currently **NOT** linked to the index and is intended for work in progress.
When final, it can be renamed, …
> Preparation page for Ubuntu 18.04

- modules/admin_manual/examples/enterprise/user_management/shibboleth/apache-2.4-configuration.conf
- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
This change ensures the configuration can be linted, integrating it better with the build pipeline and that much simpler to maintain. The source syntax highlighting configuration was updated as well.
> Extract the Shibboleth Apache config example to an include file

- docs/best-practices.md
This is a short description for the use of `Table of Contents` in Best Practices (documentation in the repro, not adoc!)
> Including ToC in Best Practices

- modules/admin_manual/pages/installation/apps_management_installation.adoc
- modules/admin_manual/pages/installation/apps_supported.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/installation/docker/index.adoc
- modules/admin_manual/pages/installation/installation_wizard.adoc
- modules/admin_manual/pages/installation/letsencrypt/apache.adoc
- modules/admin_manual/pages/installation/letsencrypt/nginx.adoc
- modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
- modules/admin_manual/pages/installation/linux_installation.adoc
- modules/admin_manual/pages/installation/manual_installation.adoc
- modules/admin_manual/pages/installation/nginx_configuration.adoc
- modules/admin_manual/pages/installation/selinux_configuration.adoc
- modules/admin_manual/pages/installation/system_requirements.adoc
This is the first of a series of PR´s which addresses the use of auto-generated Table of Contents (ToC) for much better readability of the documentation. It also reduces the need of manually creating and maintaining xrefs to do the same.
This first shot covers all documents in administration - installation.
I will do consecutive PR´s (not commits!) because the list of addressed files is big and I want to avoid blockings or merge conflicts.
I have checked each page changed by building the documentation locally.
> TOC in admin manual - installation

- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
- Reflow paragraphs to be one sentence per/line
- Remove unrequired anchors
- Fix up AsciiDoc formatting
> Tidy up the Shibboleth documentation

- modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/installation/linux_installation.adoc
- modules/admin_manual/pages/installation/manual_installation.adoc
- modules/admin_manual/pages/installation/system_requirements.adoc
- modules/admin_manual/pages/installation/troubleshooting.adoc
- modules/admin_manual/pages/issues/general_troubleshooting.adoc
- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
This was the cause I filed that PR
Using `grep -rn "\-label"` and checking each result, also in old-docs - admin_manual only.
Update: I have checked the developer and user manual for results of the grep above - nothing found to be fixed.
> Fixing orphaned references from old docs

- modules/admin_manual/nav.adoc
This relates to https://github.com/owncloud/docs/pull/876#issuecomment-480627831. @michaelstingl, is this sufficient for an installation index page, or would you prefer to have a shot table of contents as well?
The contents of the now linked file is:
```asciidoc
= Installation
In this section, you will find all the information you need for installing ownCloud.
```
> Link the installation home page to the main installation nav item

- modules/admin_manual/pages/installation/letsencrypt/apache.adoc
- modules/admin_manual/pages/installation/letsencrypt/nginx.adoc
After we have TOC enabled, I have seen that the two documents were ready for an improvment.
Both documents are now streamlined.
> Improving Letsencrypt configuration for Apache and Nginx

- modules/admin_manual/pages/installation/system_requirements.adoc
This change removes PHP 5.x from the list of supported and recommended PHP versions.
💁‍♂️ - **Only backport to 10.2**
> Update system requirements

- modules/admin_manual/pages/installation/system_requirements.adoc
This reverts commit 0227585173b1933ba12773e31ce8da466be4cba0.
Because PHP 5.6 is still supported by `10.0.*`
Note: the ppa=>PPA text edit can be done as a separate backport if somebody cares.
> Revert "[10.0] [PR 909] Update system requirements (#928)"

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
This is small text fix because of a typo: `Introcuction` --> `Introduction`
> Fix typo in linux database configuration

- modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
With AWS SDK 3.28.5 the old way of defining path/host style via command line options has been deprecated.
ref: https://github.com/aws/aws-sdk-php/blob/8fa68de81738f851e0aa62fbc0a657f2905aa860/.changes/3.28.5
> Update files_primary_s3 config examples to use correct path style syntax

- modules/ROOT/pages/index.adoc
This is a small but important fix.
Related to merged PR #876 
All open PRs are failing because of missing this fix.
It is necessary to merge this PR and backports immediate.
Then, the failing PRs need to be rebased to be merge ready.
**Note** Drone fails because this issue occurs also in 10.0 and 10.1 (10.2 ?)
Means that at least one of the upcoming backports will fail too.
> Important fix for a wrong link

- modules/admin_manual/pages/configuration/server/occ_command.adoc
> [10.2] [PR 988] Document the incoming-shares:poll command

- modules/developer_manual/pages/core/acceptance-tests.adoc
The --database-pass parameter of acceptance-tests install example does not have a nice format.
I am not sure why it was written like this, maybe just an accident?
> Fixup --database-pass parameter of acceptance-tests install example

- modules/admin_manual/pages/maintenance/backup.adoc
Running `yarn antora` I get a warning regarding a level out of order.
This PR fixes that warning.
> Fix wrong level in maintenance/backup.adoc

- docs/best-practices.md
Small addition that the use of some macros need the `:experimental:` attribute.
> Best Practices - experimental attribute

- docs/the-branching-workflow.md
This change reflects the advice provided by @phil-davis, pertaining to why earlier documentation branches receive backports, in addition to the latest 2.
> Document why backports are made to older documentation branches

- package.json
As per https://github.com/owncloud/docs/pull/982#pullrequestreview-230123586 and the discussion in the rest of the PR, this change updates the build script to have [Antora generate static redirects](https://gitlab.com/antora/antora/merge_requests/281/diffs) if redirects are required.
> Update the antora build script to support static redirects

- modules/user_manual/pages/files/federated_cloud_sharing.adoc
This is a small fix because the list generation was wrong.
The `+` sign is necessary to get the positioning of the included image correct.
> user_manual fix list in federated_cloud_sharing.adoc

- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
Small fix because two section levels were out of order.
With this PR the site build does not caomplain anymore.
> Fix section level out of order

- modules/admin_manual/pages/installation/selinux_configuration.adoc
With 10.2 the `apps-external` folder has been made default. 
This pr now changes the selinux configuration to allow http/apache to write to the apps-external folder ( instead of the old apps folder )
> updated selinux configuration to reflect apps-external change with 10.2

- modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc
- modules/admin_manual/pages/enterprise/clients/custom_client_repos.adoc
- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
- modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
- modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc
- modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
- modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
- modules/admin_manual/pages/enterprise/installation/install.adoc
- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
- modules/admin_manual/pages/enterprise/ransomware-protection/index.adoc
- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
Some text and xref fixes included
Fixes of header levels where necessary (because of beeing wrong).
`toc_it_6` is the last branch to add TOC´s in the administration manual - all done :thumbsup:
> TOC in admin manual - Enterprise

- docs/checking-broken-links.md
This is an update of the Checking Broken Links page. It adds a new linkcheck tool. I used this tool when working on #1103 and found it extremely usefuly and the best I worked with so far.
I have written the text in a way where you only need to copy paste the command and get a nice result.
**Benefits**
- VERY FAST
- Highlights broken links to anchors very easy
- Textfile to exclude search patterns (exclude branches, client-docs, excluded by robots.txt ect.)
- Turn connection errors into warnings
@PVince81 fyi
@phil-davis mind to check my grammar :smile:
> Update Checking Broken Links page

- Makefile
This PR fixes the path for command `make clean` in makefile: `build/` --> `public/`
**Update:**
I reset the path to the original state according the comment of @tboerger below,
and updated the command description to make it more clear
> Improve makefile phony clean comment to make it clear that the pdf path is meant

- modules/developer_manual/pages/core/theming.adoc
'icon-share' renamed to 'icon-shared' to be Adblock friendly with this PR: https://github.com/owncloud/core/pull/35147 . 
Now, core will use `shared.svg` instead of `share.svg`. I only found this line which referencing old `share.svg`. Corrected it in this PR.
> update share icon path

- modules/admin_manual/pages/installation/linux_installation.adoc
Previously there was no link to the existing instructions for adding ownCloud's repository to a distribution's package manager. This change adds a link to the information so that user's don't think that the package doesn't exist. This fixes #1203.
> Link to instructions for adding the ownCloud repository

- modules/admin_manual/pages/release_notes.adoc
Draft for 10.2 release notes. Still some things missing.
@tomneedham can you check line 108, please?
@phil-davis @settermjd @PVince81 as usual :)
THX!
> 10.2 Release Notes

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/server/email_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/installation/docker/index.adoc
- modules/developer_manual/pages/app/tutorial/restful_api.adoc
- modules/developer_manual/pages/core/acceptance-tests.adoc
- modules/developer_manual/pages/core/ui-testing.adoc
- site.yml
This PR aims to continue making the docs as easy to maintain — especially across versions — as possible. The intent here is that standard ports are replaced by attributes, so that they're consistently used throughout the documentation, and trivial to change, if and when the need arises.
> Replace standard ports with global attributes

- modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
This fixes #1173 by using one of the existing images in place of the incorrectly referenced image.
> [1173] Fix broken LDAP configuration image link

- modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
This was found to be missing in 10.1, after running the antora validation script.
> Add missing softhsm2 file from master branch to 10.1

- modules/admin_manual/pages/installation/manual_installation.adoc
This fixes #1258 by adding a [page redirect](https://gitlab.com/antora/antora/merge_requests/281/diffs) from source_installation to manual_installation.
> Add a redirect from source_installation to manual_installation

- modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json
- modules/developer_manual/pages/core/ocs-capabilities.adoc
- modules/user_manual/pages/_partials/direct_file_access_tip.adoc
- modules/user_manual/pages/files/version_control.adoc
- modules/user_manual/pages/files/webgui/comments.adoc
- modules/user_manual/pages/files/webgui/sharing.adoc
This fixes #265 and relates to https://github.com/owncloud/core/pull/32152. It details the ability to open one of three file sidebars (versions, comments, and shares) by using a permalink. I wasn't quite sure where to document this feature. The three locations that it has been documented in this PR seemed the best places (at least so far).
💁‍♂ Only backport to 10.2.
> Document ability to open the file sidebar from a permalink

- modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json
- modules/developer_manual/pages/core/ocs-capabilities.adoc
- modules/user_manual/pages/_partials/direct_file_access_tip.adoc
- modules/user_manual/pages/files/version_control.adoc
- modules/user_manual/pages/files/webgui/comments.adoc
- modules/user_manual/pages/files/webgui/sharing.adoc
> [10.1] [PR 1228] Document ability to open the file sidebar from a permalink

- modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json
- modules/developer_manual/pages/core/ocs-capabilities.adoc
The `privateLinksDetailsParam` was only added in 10.2
Revert parts of the changes that were backported to `10.0` in PR #1280
> Revert private links details param 10.0

- modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json
- modules/developer_manual/pages/core/ocs-capabilities.adoc
The `privateLinksDetailsParam` was only added in 10.2
Revert parts of the changes that were backported to `10.1` in PR #1281
> Revert private links details param 10.1

- modules/developer_manual/pages/core/ocs-share-api.adoc
Remove note:
```
Also, a permission cannot be changed for a public link share.
```
Issue #1328 
The note is not true.
> Remove text about public link share permissions

- modules/developer_manual/pages/core/ocs-share-api.adoc
> [10.0] [PR 1329] Remove text about public link share permissions

- modules/developer_manual/pages/core/ocs-share-api.adoc
> [10.1] [PR 1329] Remove text about public link share permissions

- modules/developer_manual/pages/core/ocs-share-api.adoc
> [10.2] [PR 1329] Remove text about public link share permissions

- site.yml
This relates to #1356.
💁‍♂ This **cannot** be merged before https://github.com/owncloud/ios-app/pull/422 and https://github.com/owncloud/ios/pull/1110 have been merged.
> Add new iOS 11+ docs as a content source

- modules/admin_manual/examples/installation/docker/docker-compose.yml
- modules/admin_manual/pages/installation/docker/index.adoc
Since in the future the owncloud-docker repo will have less info about the compose setup, I have copied the yaml file for the docker-compose setup together with the instructions for the enterprise customers on how to get the enterprise container in the docker compose docs.
> Added YAML file and registry instructions

- modules/admin_manual/pages/installation/linux_installation.adoc
The link is pointing to an old repository which would install version 10.1.0 and is confusing as it shows '10.0' in the link.
So users assume that they could use '10.2' in there to update and install version 10.2 of owncloud-files, but that repository doesn't work.
> Update repo link for owncloud-files

- modules/admin_manual/pages/configuration/files/external_storage/webdav.adoc
This fixes #1346 by fixing the links that weren't properly migrated from the previous Sphinx-Doc implementation of the docs. It also refreshes the text to bring it in line with the new best practices and
style guide, and reflows it to help make it more efficient for the reader.
> Update WebDAV documentation

- modules/developer_manual/pages/core/apis/externalapi.adoc
- modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/webdav_api/tags.adoc
While working through the documentation to implement the changes required for #1397, I found a number of places where the documentation could be cleaned up. The changes include fixing spelling mistakes, and reflowing the text to follow the style guide.
> Clean up some of the API documentation

- modules/admin_manual/pages/configuration/files/encryption/enabling-user-key-encryption.adoc
- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
- modules/admin_manual/pages/configuration/files/encryption/master-key-encryption.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/encryption_configuration_quick_guide.adoc
- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
> [10.2] [PR 1395] [1387] Document the -y and --yes options for the occ encrypt-all command

- modules/developer_manual/pages/core/apis/externalapi.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.2] [PR 1398] Move the API code examples into tab blocks

- lib/extensions/tabs.js
- site.yml
Tab blocks are not a native part of AsciiDoc, so are not available default. However, there a tabs block extension is available which extends AsciiDoc to support tab blocks; it is available at: https://gitlab.com/antora/antora-asciidoctor-extensions/tree/master/tabs-block. This change enables the extension and is related to #1388.
> Enable the Antora Tab Blocks Extension

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
The docs were "refined" after a knowledge sharing session but something(tm) went horribly wrong.
The new content was simply copied above the old content, creating a loop upgrade like: "first back up your files, then enable maintenance mode, .... first back up your files, then enable maintenance mode, ..."
This document is huge, so it took a lot of work to fix this, because some parts of the old document were hasty copy pasted, missing the proper context. Like if you have 2 sentences, and the second one references the subject of the first one with "it" and you copy just the second sentence - it does not make any sense.
Also the work from @settermjd was applied only to the old document, not to the new one, especially the reformatting of the code blocks, so I had to pull them from the old …
> Fixed the upgrade docs

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/admin_manual/pages/installation/apps_management_installation.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- modules/admin_manual/pages/release_notes.adoc
This PR fixes a series of links that weren't correctly migrated from Sphinx-Doc to Antora, that have been overlooked or undiscovered up until this point.
> Fix a set of links corrupted during the migration from Sphinx-Doc

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
remove the incorrect script, as noticed by @enbrnz 
instead we have a simple chown.
> permissions

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
The example wasn't using the scripts parameters in a crucial step. Making it unnecessarily complicated to adopt the script with different variables, as script-users would have to adjust the webserver-user at several positions in the script even though we define a webserver-user at the beginning of the script.
> Update finalise-install.sh example

- docs/getting-started.md
The "official" plugin advertised at https://asciidoctor.org/docs/editing-asciidoc-with-live-preview/ does not load in my firefox. It is corrupt.
> link to firefox extension asciidoctor.js live

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
We tested the new version of the document and noticed errors.
This restores the previous state of some code blocks and makes it functional again.
> restore Ubuntu 18.04 example to functional state

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/configuration/user/user_configuration.adoc
- modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc
- modules/admin_manual/pages/release_notes.adoc
- modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/user_manual/pages/files/access_webdav.adoc
- modules/user_manual/pages/files/gallery_app.adoc
- modules/user_manual/pages/files/webgui/overview.adoc
- modules/user_manual/pages/files/webgui/quota.adoc
- modules/user_manual/pages/files/webgui/sharing.adoc
IMO we has decided to call these "public link shares", so make the documentation consistent.
- change any "public share link" to "public link share"
- change any "public share" to "public link share"
Preparation for/sort of related to issue #1328 
May as well get this consistent first, then touch some place(s) that need content clarified.
>  Standardize 'public link share' words

- modules/admin_manual/pages/installation/manual_installation.adoc
Since we (the ownCloud Team) decided that we want to keep the docs Apache / maria db / Ubuntu exclusive  I removed the instructions for cent OS or RHEL or SUSE Linux from the manual installation guide.
The Full Guide shall be transferred to central, where it can be maintained by the community.
This PR also fixes the code block formatting error with the docs and the minuses.
> removed non apache2 instructions

- docs/getting-started.md
- modules/admin_manual/pages/appliance/configuration/clamav.adoc
....
systemctl enable clamav-daemon.service
systemctl start clamav-daemon.service
....
----------------
Troubleshooting section
-------------
Removed the occ command at the bottom, since in the container there is no sudo installed, so this command would fail. Also it's easier to tell the user to configure the clamAV instead of making him look up the possible values of the occ command.
> Changes to the clamAV document

- modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json
- modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json
- modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json
- modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml
- modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml
- modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml
- modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh
- modules/developer_manual/nav.adoc
- modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
This PR documents the new OCS TOTP Validation API in [2-Factor Authentication](https://marketplace.owncloud.com/apps/twofactor_totp) v0.6.0. The changes show:
- What the API is
- How to use it with a CURL example
- Prerequisites
- Example responses
It fixes #674.
> Document the new OCS TOTP Validation API

- modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
changed 
TIP: See xref:configuration/server/occ_command.adoc[the occ’s file operations] for more information.
to
TIP: See xref:configuration/server/occ_command.adoc#the-filesscan-command[the occ’s file operations] for more information.
to get the user to the right section right away.
fixes:
https://github.com/owncloud/docs/issues/261
> added a tag to link

- modules/admin_manual/pages/installation/docker/index.adoc
Changes in the Docker repo broke some of the steps in the Docker install docs:
(https://github.com/owncloud-docker/server/commit/71369eadbb3521930c2eca116f8e2acd657b692a)
Directly referencing the example file that is embedded later on this page could make the script work again…
Related issue: https://github.com/owncloud/docs/issues/1585
> Fix Docker install after repo changes

- books/ownCloud_Admin_Manual.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/user_roles.adoc
This change removes the toc-title attribute from user_roles.adoc which, in a PDF context, overrides the manual's TOC title value, set in the book configuration file. This fixes #1568.
> Fix TOC title in admin PDF manual

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/server/request_tracing.adoc
This change documents the x-request-id functionality in ownCloud server, and provides a minimum of information about how it works and what administrators need to do to enable it. This fixes #817.
> Document the x-request-id functionality in ownCloud server

- modules/admin_manual/pages/configuration/user/user_roles.adoc
Guest users have no home storage. But we don't have a notion written in the docs that an error message will appear during files:scan
> add notion for guest users

- modules/admin_manual/pages/appliance/configuration/clamav.adoc
This fixes #1461 by redirecting `server/admin_manual/pages/appliance/Clamav.adoc` to `server/admin_manual/pages/appliance/configuration/clamav.adoc`.
💁‍♂ A redirect for `appliance/clamav.adoc` already existed. But, given that the filesystem is case-sensitive, an additional redirect for `appliance/Clamav.adoc` was required.
> Create redirect for deprecated server/admin_manual/appliance/Clamav.html

- modules/admin_manual/pages/faq/index.adoc
fixes https://github.com/owncloud/docs/issues/365
> added known limitation for sync

- modules/admin_manual/pages/configuration/server/occ_command.adoc
This fixes #963. It doesn't delve deep into the command, it just looks at the basics.
> Document the occ encryption:fix-encrypted-version command

- modules/developer_manual/pages/testing/ui-testing.adoc
Core issue https://github.com/owncloud/core/issues/35444
This selenium chrome issue looks like it will not be quickly resolved.
It has caused confusion and time-waste for developers who followed the documentation here, so we had better put this detail in the documentation (and then remember to remove it when the issue is resolved and the latest selenium chrome works again)
> Document selenium chrome testing version

- modules/admin_manual/pages/maintenance/package_upgrade.adoc
- modules/admin_manual/pages/maintenance/upgrade.adoc
This fixes #1551 by unifying the documentation around if it's okay or not to skip major releases when upgrading. It also updates it to reflect more recent changes in ownCloud.
> Unify the wording around skipping major releases when upgrading

- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
This change, updates the occ and provisioning API documentation to cover that when creating users, either one or both of a username and password can be supplied. If one of these options is supplied, it makes the other optional. More specifically; if an email address is supplied and a password isn't, that a password will be automatically generated and the user will be emailed a link to change their password.
This fixes #1643.
> Document new options for adding users via provisioning API and occ

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
This is a small improvement with text and rendering fixes and a better description for MariaDB 10.4.3 as there are authentication changes. The latter eases the process a lot when installing from scratch or upading an existing installation. It also contains a info how to disable transparent huge pages which is needed for databases (if not made, redis complains during startup)
Backporting required.
> Updating Server Prep Ubuntu 18.04

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
This partial was referenced but not added in the commit that referenced it. This change adds the file under version control. This fixes #1710.
> Add missing partial referenced in maintenance upgrade docs

- antora.yml
- modules/ROOT/pages/index.adoc
The component descriptor's name was mistakenly left as "master" when the branch was originally created from the master branch. This change corrects it, so that it doesn't cause problems in the future.
> Fix component descriptor name

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
After feedback from users, we decided to adjust the wording on this topic and provide a clear instruction how to change the password of a LDAP user with user key encrypted ownCloud
> Correct the LDAP Password Change with Encryption

- bin/find-orphaned-files.sh
This PR adds a small shell script that checks if any of the example files (scripts) is used anywhere throughout the documentation.
> Add script to check for orphaned example files

- .drone.yml
There have been intermittent build failures where the final error message is: `fatal: empty ident name (for <>) not allowed`. After some discussion, @micbar said that the problem is the continuing use of an outdated Drone clone plugin. That's why this change is removing it.
> Remove outdated drone clone plugin

- modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
- modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
- modules/admin_manual/pages/configuration/server/harden_server.adoc
- modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
- modules/developer_manual/pages/bugtracker/triaging.adoc
- modules/developer_manual/pages/testing/test-pilots.adoc
- modules/user_manual/pages/files/access_webdav.adoc
Backport of c89fdc6a104d214d7cdc6de2966873ef1a8a8ebf
> [10.2] Remove extra Nginx reference from docs

- resources/themes/owncloud-theme.yml
Dusan Cirkovic made a suggestion (see #680) that some content in the PDF was not formatted (aligned) correctly. The reason for the seemingly broken formatting is because the content is justified, and not left aligned. While it works well in a lot of cases, there are some where it doesn't. And, after reviewing the PDF with left aligned text, it looks far better.
> Left align PDF content

- modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
I noticed just a minor thing about the factual accuracy of the tmp folder size and I added some better explanation to the long running uploads section (sorry I didn't really provide that earlier).
> additions and corrections on big_file_upload_configuration.adoc

- modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc
This PR covers two changes to the migrating from user key to master key documentation: 
1. The text was changed in two, small, ways so that it is that much clearer in its intent. 
2. The NOTE admonition at the top of the page was changed so that it now only contains the first two sentences. This is because the remaining sentences originally contained in it read as a normal part of the prose on that page, and don't require special attention.
> Minor grammatical and formatting revisions

- bin/cli
For some reason, which is currently unknown to me, I inserted a call to the validate_manual function in the build_manuals function. I'm not sure why I did that, but it broke PDF generation for all manuals (but not for individual manuals). 
This change removes the call, adds a bit more error checking for the call to getopts, to make it more robust, and also makes use of the "strict mode", to also make the script more robust, in the
right way. For more information on the "strict mode", check out http://redsymbol.net/articles/unofficial-bash-strict-mode/.
> Fixed a bug in the cli script when generating PDF files

- modules/user_manual/pages/apps/index.adoc
The reference to the partial section_page.adoc in apps/index.adoc was
broken as partials can only be included from the current module.
Including partials from other modules is a pending feature (well, it was
when I last investigated them).
> Fix broken reference to partial in user manual

- modules/admin_manual/pages/release_notes.adoc
The links to the new apis weren't prefixed with the version that they're
specific to.
> [10.0] Fix broken links in the release notes

- modules/admin_manual/pages/release_notes.adoc
The links to the new apis weren't prefixed with the version that they're
specific to.
> [10.2] Fix broken links in the release notes

- modules/admin_manual/pages/release_notes.adoc
The links to the new apis weren't prefixed with the version that they're
specific to.
> [10.1] Fix broken links in the release notes

- modules/admin_manual/pages/release_notes.adoc
- modules/user_manual/pages/_partials/files/not-encrypted-files.adoc
These were fixed last week, but it seems that they were only fixed in
the 10.x branches, and the fix was not backported to master.
> Fix several broken xrefs

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> Remove references to SUDO in cron job setup examples

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.3] [PR 1930] Remove references to SUDO in cron job setup examples

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.2] [PR 1930] Remove references to SUDO in cron job setup examples

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.1] [PR 1930] Remove references to SUDO in cron job setup examples

- modules/developer_manual/pages/_partials/section_page.adoc
- modules/developer_manual/pages/core/apis/index.adoc
- modules/developer_manual/pages/testing/index.adoc
- modules/developer_manual/pages/webdav_api/index.adoc
Files in one module are not able to be referenced from any other. Given
that, one of the partials was not working, as the file was not available
in the same module. This change corrects that.
:tipping_hand_man: This PR does not require backporting.
> Update broken references to section_page partial

- .drone.yml
This step was regularly causing builds to fail, and to take unnecessarily long to complete. After discussion with @tboerger, it's okay to remove it, as it's really not necessary.
> Remove the build-artifacts build step

- modules/developer_manual/pages/core/code-standard.adoc
Issue #295 
`make test-php-style` actually also runs `php_codesniffer` over the acceptance test code.
`make test-php-style-fix` only runs php-cs-fixer - because php-cs-fixer can fix stuff itself, but `php_codesniffer` cannot (always).
So actually people should run `make test-php-style`  to be sure that both code style checks are passing.
- re-organize the paragraphs to recommend always running `make test-php-style` first.
- add an example of `php_codesniffer` output.
> php_codesniffer code style documentation

- modules/admin_manual/pages/configuration/server/logging/logging_configuration.adoc
There is a little typo in the conditions example. Breaks the code highlighting.
> Fix little typo in conditions option

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Referencing: https://github.com/owncloud/docs/issues/1724 (A config-to-docs run is necessary for the upcoming 10.3 release)
This is the actual config-to-docs run to update the file(s) according the changes made in core (10.3).
Note: the use of `{occ-command-example-prefix}` instead of `sudo -u www-data php occ` or `./occ` ect.
must be made in core. Content from will be used as it is...
Info: to use the script for conversion, simply see https://github.com/owncloud/config-to-docs#how-to-use
Backport to 10.3 necessary
@settermjd
@micbar fyi
> Updated config sample parameters file from core (10.3)

- modules/developer_manual/examples/core/webdav_api/search/request/search_files/filter_results.xml
- modules/developer_manual/examples/core/webdav_api/search/request/search_files/limit_number_of_results.xml
- modules/developer_manual/pages/webdav_api/search/search_files.adoc
This fixes #359. @PVince81, can you provide a complete list of `filter-rules` properties?
> Reference filtering and other search options in endpoint docs

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
For a complete setup you also need to set up `occ dav:cleanup-chunks` cron job as per documentation:
https://doc.owncloud.com/server/10.1/admin_manual/configuration/server/background_jobs_configuration.html#cleanupchunks
- I have set the cronjob to once a day after midnight
- By default the command deletes 2 day old chunks
- It is possible to configure another number of day(s) old chunks to delete as an argument to the command
> Add missing cron job

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/release_notes.adoc
- site.yml
This PR removes all relevant (lingering) references to calling occ using `php -f`, which were pointed out #1989 by @xelan.
> Remove references to php -f for occ command

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/release_notes.adoc
- site.yml
> [10.3] [PR 1998] Remove references to php -f for occ command

- modules/developer_manual/examples/core/scripts/php/dav/public_files/view_public_link.php
> [10.3] [PR 1945] Escape reference to antora-like attribute in PHP script

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
There seemed to be some "useless" words on the end of the sentence.
> Cleanup Exclude groups from sharing text

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc
- modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
- modules/developer_manual/pages/app/advanced/storage-backend.adoc
`NOTE: ownCloud does not preserve the mtime (modification time) of directories...`
This note is appearing "randomly" in the middle of sections about the various file sharing options.
Maybe it was somewhere else in old docs? Where should it go?
> Remove note about mtime

- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/fundamentals/controllers.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/development_environment.adoc
A few mistakes in the developer documentation were pointed out in #168,
which have been causing confusion for some users (understandably). This
change corrects the mistakes, hopefully catching all instances of the
problem. It fixes #168.
> Correct developer documentation mistakes

- modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
- modules/admin_manual/pages/configuration/server/occ_command.adoc
This change:
- documents the ability to filter the command's output
- shows a complete report example (with sensitive information removed); and
- shows how to include sensitive information in the generated output/report
This fixes #275.
> [275] Update documentation of the occ config:list command

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
I noticed in drone: https://drone.owncloud.com/owncloud/docs/6130/1/6
```
Generating version 'master' of the admin manual, dated: November 06, 2019
asciidoctor: ERROR: modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc: line 15: include file not found: /drone/src/modules/admin_manual/pages/_partials/configuration/server/system_command.adoc
Failed to parse formatted text: <img src="/drone/src/modules/admin_manual/assets/images/configuration/server/anti-virus-message-misconfiguration-problem.png" format="png" alt="[Configuration error message: 'Antivirus app is misconfigured or antivirus inaccessible. The antivirus executable could not be found at path '/usr/bin/clamsfcan".]" tmp="false">
Generating version 'master' of the developer manual, dated: November …
```
> Fix docs pdf errors

- docs/the-branching-workflow.md
After discussion with mstingl, felix, pmaier, dmitry, and pdavis, changes are only to be backported to a branch for the latest ownCloud version. Three releases are no longer supported. This change reflects that decision.
> Updated the branching workflow

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Brings the TOC in the manual upgrade documentation into line with version 10.1, changed in #2082.
> Change manual upgrade toc level to 2

- modules/admin_manual/pages/configuration/server/occ_command.adoc
`files_external:create` was double present in the occ description.
Whyever this slipped in, now it is removed.
One description is now present at the correct location.
Backporting to 10.3 needed
> Delete double present command files_external:create

- modules/admin_manual/pages/configuration/server/occ_command.adoc
remove ldap:update-group because it's not there in 10.1.1
> remove ldap:update-group

- modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
The admonition was not formatted correctly, such that the page didn't render as expected. This may lead to user confusion. Given that, this change fixes it.
> fix: Fix admonition in enable encryption guide

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
This change corrects an error in the database cleanup SQL example. MySQL does not support `DELETE * FROM`. See https://dev.mysql.com/doc/refman/8.0/en/delete.html for more information.
> Fix error in database example

- modules/admin_manual/pages/configuration/server/harden_server.adoc
Add new aliases for https://github.com/owncloud/core/pull/36315
/go.php?to=use-https
/go.php?to=enable-http-strict-transport-security
should redirect to
/admin_manual/configuration/server/harden_server.html
> Add go.php redirects for core#36315

- modules/developer_manual/pages/webdav_api/comments.adoc
- modules/developer_manual/pages/webdav_api/tags.adoc
This relates to [a comment by pvince](https://github.com/owncloud/docs/pull/1999#issuecomment-562605391) in #1999. It updates the standard PROPFIND request attributes. It also does a little bit of cleaning to the documentation surrounding the change made.
> Update standard PROPFIND request attributes

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Took versions listed by https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule.
Reason: Update by use 8.0.10 could have bug for next update by 8.1.12 not happening by using 8.0.16.
> Specificate exact version

- modules/developer_manual/pages/core/apis/ocs/notifications/index.adoc
That file was merged in with the other notifications documentation in modules/developer_manual/pages/app/advanced/notifications.adoc. This relates to #2165.
> Remove unrequired xref to notification workflow file

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
After a discussion with customer support, it was not deemed to be necessary.
> Removed reference to ppa:ondrej/php repository

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.4] [PR 2190] Removed reference to ppa:ondrej/php repository

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.3] [PR 2190] Removed reference to ppa:ondrej/php repository

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/user_manual/pages/apps/market.adoc
Fixing `asciidoctor: WARNING:`
`windows-network-drive_configuration.adoc: line 558: invalid style for example block: source`
`skipping reference to missing attribute: oc-marketplace-url`
Backporting to at least 10.3 should be done
> Fix asciidoctor build warnings

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Seen #2190 remove `add-apt-repository` but `apt install software-properties-common` only required by `add-apt-repository` so remove also.
> Remove apt install software-properties-common

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
This relates to #2213, #2214 & #2202.
> Remove specific reference to PHP 7.3 in the Ubuntu 18 guide

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.4] [PR 2216] Remove specific reference to PHP 7.3 in the Ubuntu 18 guide

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
> [10.3] [PR 2216] Remove specific reference to PHP 7.3 in the Ubuntu 18 guide

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/configuration/ldap/index.adoc
removed the LDAP folder and moved the ldap proxy cache server to the general configuration site
@cdamken
> remove unnecessary LDAP documentation structure

- modules/ROOT/pages/index.adoc
This change is being backported to 10.4 from d733051. The change sets the values for the latest and previous stable releases from the global site attributes. Doing so reduces the maintenance requirements for the documentation.
> Read latest stable and previous version info from attributes

- modules/admin_manual/pages/configuration/user/user_configuration.adoc
- modules/user_manual/pages/files/webgui/custom_groups.adoc
The information should have been in the admin manual originally, and not in the user manual. This change moves it to where it should be.
> Move the overriding default (custom groups) behavior to the admin manual

- modules/developer_manual/pages/core/apis/externalapi.adoc
- modules/developer_manual/pages/core/apis/ocs-notify-public-link-by-email.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
- modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
- modules/developer_manual/pages/core/apis/roles-api.adoc
- modules/developer_manual/pages/webdav_api/public_files.adoc
- modules/developer_manual/pages/webdav_api/trashbin.adoc
This change is being made as there are build errors when generating PDF versions of the documentation because of the misunderstood tab formatting.
> Use tabs only when rendering content in HTML format

- .drone.yml
I guess, now I know what is wrong here:
To make `when: event: [ push ]` in a pipeline step, the drone.yml should have a correct `branch: 10.4` setting, (instead of master)
> Built 10.4 docs should be uploaded to doc.owncloud.com

- .drone.yml
- bin/cli
PR #2231 was merged without the relevant changes to the Drone configuration and PDF manual build script. This change makes the required changes so that the manuals build correctly and include the content with/without tabs, as appropriate.
> Update build tools to be format-aware

- modules/admin_manual/pages/_partials/configuration/server/occ_command/system_command.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
This PR corrects the BGJ page.
First we have written to upgrade to occ system:cron, later we introduced writing instance/cron.php
Improved text that an existing configuration must be updated
This is now fixed.
Needs BP to 10.4 and 10.3
> update backgroundjob configuration

- modules/admin_manual/pages/_partials/configuration/server/occ_command/config-list-report.json
issue https://github.com/owncloud/enterprise/issues/3780
core PR https://github.com/owncloud/core/pull/36815 
removes the `dav.enable.tech_preview` setting
The change is planned for release in ownCloud 10.4
This PR removes the setting from an example.
The entry in `config.sample.php` will get removed when the changes to that file are synced across from core.
Notification about the change will be part of release notes for 10.4.
Do not merge this PR until the core PR has been approved and merged.
> Remove dav.enable.tech_preview from example

- bin/cli
This fixes #2246 by enabling the experimental attribute when building
the documentation. This ensures that support for experimental features
(menus, buttons, and keyboard shortcuts) is available when building the
manuals. Otherwise, that formatting doesn't render correctly in the PDF
manuals.
> Enable experimental attribute when building the PDF manuals

- modules/admin_manual/pages/enterprise/security/ransomware-protection/index.adoc
This fixes an issue spotted by @HanaGemela. Thanks for spotting it, btw.
> Add page redirect for old ransomware protection documentation

- modules/admin_manual/pages/configuration/server/occ_command/database_conversion_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command/sharing_commands.adoc
The level offsets are being lowered as they are making the section
headers be generated out of sequence. I think they were set to the
original value as that is the common value. However, it's not correct in
this case, as leveloffset values are relative to where the file is being
included, and not at some top-level. This relates to #2045.
> Correct level offset values for included pages

- modules/admin_manual/pages/release_notes.adoc
- Added PHP 7.1 deprecation note as suggested by @phil-davis (:+1:)
- Additionally changed some confusing wording below
- The link in line 43 is broken. As I'm not fully sure how to correct it, please do so @settermjd.
> Add PHP 7.1 deprecation note to 10.4 release notes

- modules/admin_manual/pages/configuration/server/occ_command.adoc
For some reason, the files external commands were not included into the occ_commands documentation when the file was split into multiple files. This PR fixes that by including the files external commands documentation.
> Add missing occ commands

- modules/admin_manual/pages/installation/system_requirements.adoc
Here is my suggestion to sort out the desktop and mobile headings in `system_requirements.adoc`
There is a "Desktop Sync Client" and there are "Mobile Apps". The "Desktop Sync Client" can run on a range of operating systems, which are listed in that section. The "Mobile Apps" are available for/on the operating systems mentioned in that section.
Maybe we also want to re-order the sections "Desktop Sync Client", "Web Browser" and "Mobile Apps"? (I did not do that in this PR because then the diff listing will be obscured by large cut-paste, and I actually I don't know which order people prefer).
Please comment, and we can sort this out then backport it into 10.4 and 10.3
> Adjust desktop sync clients and mobile apps headings in system_requirements

- modules/admin_manual/pages/installation/system_requirements.adoc
This gets `system_requirements.adoc` to be the same is in docs `master`
(after PR #2332 to `master` applied various stuff from `10.3` forward to `master` and ...)
IMO we need to merge this so that we get the branches back in sync.
Then we can discuss what happened for the `Sync Clients and Mobile Apps` heading and the deletion of the `Mobile OS` section etc. I will make a PR to `master` suggesting what I think!
> Backport system_requirements to 10.4

- modules/admin_manual/pages/installation/system_requirements.adoc
This gets `system_requirements.adoc` to be the same is in docs `master`
(after PR #2332 to `master` applied various stuff from `10.3` forward to `master` and did formatting...)
IMO we need to merge this so that we get the branches back in sync.
Then we can discuss what happened for the `Sync Clients and Mobile Apps` heading and the deletion of the `Mobile OS` section etc. I will make a PR to `master` suggesting what I think!
> Backport system_requirements to 10.3

- modules/admin_manual/pages/installation/system_requirements.adoc
Issue #2343 
Backport to 10.4 only.
Note: `linux_database_configuration.adoc` has some detailed PostgreSQL setup information. There is some mention of PostgreSQL 8.4 there - that could be update/fixed. And should we do example setup for PostgreSQL 10?
(for any of that we could raise a separate issue...)
> PostgreSQL 10 is supported from core 10.4

- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_command/command_line_installation_commands.adoc
The intent of this change is to update the Linux configuration documentation so that:
- It follows the style guide
- Removes all grammatical and spelling errors
- Update the source code block formatting
- Make the headers clearer and more logically consistent; and 
- Make the content easier to read
> Rework the Linux Database Configuration documentation

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
removed instructions of other distributions other than Ubuntu.
added a quick configuration example.
fixes https://github.com/owncloud/docs/issues/2349
> restructure of the memory caching document

- modules/developer_manual/pages/testing/acceptance-tests.adoc
There are some other tags that we use in the acceptance test scenarios. Document them.
> Add scenario tags to acceptance test docs

- modules/developer_manual/pages/core/apis/ocs-capabilities.adoc
And I noticed that we did not have an acceptance test that checks this capability, so I have done that in core PR https://github.com/owncloud/core/pull/37066 - which confirms that this capability is really `privateLinks`
> Fix privateLinks typo

- modules/admin_manual/examples/installation/deployment_recommendations/set_session_path.sh
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
This change replaces the existing examples showing how to retrieve the `session.save_path` value with a small awk/bash one-liner that works for PHP 7.3. This fixes #2326. **Please note:** b34d1cd is a cleanup commit, nothing more.
> [2326] Update deployment recommendations example for finding the PHP session.save_path value

- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/MultipartStreamTest.php
Are these `cOntenT-Type` really supposed to be like that in `MultipartStreamTest.php`?
> Fix Content-Type typo

- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/CHANGELOG.md
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/guzzle/UPGRADING.md
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/promises/src/functions.php
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/LimitStreamTest.php
- modules/developer_manual/examples/core/scripts/php/vendor/guzzlehttp/psr7/tests/PumpStreamTest.php
- modules/developer_manual/examples/core/scripts/php/vendor/psr/http-message/CHANGELOG.md
- modules/developer_manual/pages/app/advanced/l10n.adoc
- modules/developer_manual/pages/app/fundamentals/container.adoc
- modules/developer_manual/pages/app/tutorial/testing.adoc
- modules/developer_manual/pages/general/backporting.adoc
- modules/developer_manual/pages/general/devenv.adoc
- modules/developer_manual/pages/mobile_development/android_library/examples.adoc
- modules/developer_manual/pages/mobile_development/ios_library/examples.adoc
- modules/developer_manual/pages/testing/test-pilots.adoc
Should be backported to 10.4 and 10.3
> Fix typos in developer docs

- modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
> [10.4] [PR 2366] Deprecate the ldap:update-group from occ commands

- modules/admin_manual/pages/configuration/server/app_commands/ldap_integration_commands.adoc
> [10.3] [PR 2366] Deprecate the ldap:update-group from occ commands

- modules/developer_manual/pages/general/backporting.adoc
This PR updates the backporting document because macOS users may have to use an updated version of `grep`. (+ changed all links to our standard way).
Backporting to 10.3 and 10.4 needed
> Backporting page update

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
- modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc
>  [10.3] [PR 2367] [2354] Replace lingering references to cron.php with system:cron

- modules/admin_manual/pages/installation/docker/index.adoc
There are some catches to the recommended Docker setup
* Admins can easily erase their data, when they kill their docker setup. 
* docker-compose down may change the installed apps
Made the language of the second NOTE less convoluted.
> Add a NOTE about volumes and about apps management

- modules/admin_manual/pages/configuration/files/index.adoc
This bug was uncovered while debugging #2394.
> Remove lingering xref pointing to external storage configuration

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
This is an improvement of the redis part of the documentation when using UNIX sockets.
(Based on my own tests sockets have +30% performance boost compared to localhost/TCP)
Backport to 10.3 and 10.4 needed.
> Improvement of Redis setup

- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
Part of issue #2441 
These are what I thought were "obvious/easy" changes to remove some PHP 7.0 references.
Backport to 10.4 branch is PR #2443
> Remove some PHP 7.0 references

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- modules/developer_manual/pages/app/tutorial/requirements.adoc
- site.yml
This fixes #2441. @phil-davis, I did my best to find and fix lingering references to versions of PHP prior to the, currently, minimum supported version of 7.1 and to update the references in a way that is more maintainable over the longer term.
> Remove all references to PHP versions prior to the min supported (7.1)

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- modules/developer_manual/pages/app/tutorial/requirements.adoc
- site.yml
Backport #2449 - that gets us the variables in `site.yml` related to PHP min version, and gets them in use in this branch (which will make less pain for future backports).
In the 2nd commit, adjust minimum-php-version to 7.0 because that is correct for 10.3 branch.
The changes lok like they will work nicely for the 10.3 case. Please review and see if you agree.
> [10.3] Remove all references to PHP versions prior to the min supported (7.0)

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- modules/developer_manual/pages/app/tutorial/requirements.adoc
- site.yml
> [10.4] Remove all references to PHP versions prior to the min supported (7.1)

- modules/admin_manual/pages/_partials/maintenance/upgrading/upgrade_steps.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
This PR:
- Removes the section on upgrading to PHP 5.6, which is no longer necessary as ownCloud no longer supports it, nor supported, as PHP 5.6 is well past EOL; and 
- Adds documentation for upgrading to PHP versions 7.0 - 7.3. This was recommended in https://github.com/owncloud/docs/pull/2453#discussion_r393465381.
> [10.3] Merge changes to upgrade_php.adoc from 10.4

- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- site.yml
This PR:
- Adds missing text substitutions
- Encloses the `minimum-php-version` attribute value in single quotes, as the value, when
substituted, was being truncated to `7`, and should have been rendered as `7.0`; and
- Renames the attribute `minimum-php-version-shortcode` to `minimum-php-version-short-code`, as that is how it is referenced in the docs.
> [10.3] Add missing text substitutions and enclose attribute in single quotes

- modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
- modules/user_manual/pages/files/media_viewer_app.adoc
This fixes #2448, by updating the relevant sections in both the user and admin manuals.
> [2448] Document that QuickTime is not supported in Chrome

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
This is an improvement of server_prep_ubuntu_18.04.adoc
Referencing https://github.com/owncloud/docs/pull/2447/files#r393630957
Adding / rewriting / improving content and reordering.
Backport to 10.4 and 10.3 needed
> Improve server_prep_ubuntu_18.04

- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
This fixes #2469, documenting the document lock issue when using Chrome to edit Office Online documents.
> [2469] Document Document Locking Issue With Office Online and Chrome 

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
When reading through the files:transfer-ownership documentation, while
researching #2484, I found that the wording in that section could do
with a small update. This is that update, which has the intent of making
it quicker and easier to read.
> Slight update to the files:transfer-ownership documentation

- modules/admin_manual/pages/release_notes.adoc
Backport #2446 
Note: backport to 10.3 is needed because current release notes (e.g. for 10.4) are also published in the 10.3 version of the docs, so that people about to upgrade will have an extra chance to find the release notes for upgrade...
> [10.3] Add known issue with password policy to release notes

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
This PR fixes https://github.com/owncloud/docs/issues/2493 ([10.4.1] New occ command "files:check-cache" refs core/37067)
It adds `files:check-cache` to the occ command set.
Backporting ONLY to 10.4 necessary
> adding occ command files:check-cache

- modules/admin_manual/pages/faq/index.adoc
> [10.4] [PR 2499] Fix broken link to sync-exclude.list on GitHub

- modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
Adding `php-ssh2` to the php extension installations, recommended for OIDC
Backporting to 10.4 and 10.3
> Adding php-ssh2 recommended for oidc

- modules/admin_manual/pages/release_notes.adoc
@patrickjahns you have suggested mentioning the addition of foreign keys in the release notes.
See my draft. I'm not sure what else to add there, did you have anything in mind ?
Something like "if your database / setup doesn't support it, you should ... do what ?"
> Release notes foreign keys

- modules/developer_manual/assets/attachments/core/Makefile.example
- modules/developer_manual/pages/testing/unit-testing.adoc
Backport #1673 
2nd commit: core 10.3.2 has `phpunit` 6 (10.4.0 has `phpunit` 7). I updated the example output so it has the older version.
> [10.3] Update unit test documentation

- modules/developer_manual/pages/testing/unit-testing.adoc
It is a long time since ownCloud9. IMO the current docs can just be about ownCloud10. People who still want to try and run PHP unit tests on ownCloud9 need to look in the old ownCloud9 docs.
Remove ownCloud9-specific stuff.
Backport to 10.4 and 10.3 branches.
> Remove old ownCloud9 phpunit docs

- modules/admin_manual/pages/configuration/server/app_commands/password_policy_commands.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/configuration/server/occ_command/security_commands.adoc
- modules/developer_manual/pages/app/fundamentals/routes.adoc
- modules/developer_manual/pages/app/tutorial/routes_and_controllers.adoc
- modules/developer_manual/pages/core/apis/ocs/notifications/ocs-endpoint-v1.adoc
- modules/developer_manual/pages/core/apis/ocs/user-sync-api.adoc
- modules/developer_manual/pages/webdav_api/files_versions/list_files_versions.adoc
- modules/user_manual/pages/apps/enterprise/admin_audit.adoc
This PR aims to fix #2522 — specifically for master, 10.4, & 10.3 —  by correcting the build errors displayed in Drone. It's hard to fix them in one PR because of the way that the output that Antora creates. Take the following example:
```
asciidoctor: ERROR: unit-testing.adoc: line 115: include target not found: example$core/unit-testing/MyClass.php
asciidoctor: ERROR: unit-testing.adoc: line 123: include target not found: example$core/unit-testing/MyClassTest.php
asciidoctor: WARNING: file_sharing_configuration.adoc: line 305: unterminated listing block
asciidoctor: WARNING: background_jobs_configuration.adoc: line 190: unterminated literal block
asciidoctor: WARNING: reset_user_password.adoc: line 11: unterminated literal block
asciidoctor: WARNING: user_auth_ldap.adoc: line 259: …
```
> [2522] Fix up build errors in the core documentation

- modules/developer_manual/examples/scripts/backport.sh
This PR updates the backporting script.
GitHub has silently changed the name for two variables used a little bit.
`X-RateLimit-Reset` --> `X-Ratelimit-Reset`
`X-RateLimit-Remaining` --> `X-Ratelimit-Remaining`
The script will run without that fix too but will output an error:
`backport.sh: line 72: [: -le: unary operator expected`
Backporting to 10.3 and 10.4
> Backporting script: update git key names

- modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
- modules/user_manual/pages/apps/enterprise/admin_audit.adoc
Because the leveloffset attribute hadn't been set, the section levels in the included files were set too high.
> Fix build errors in master

- modules/developer_manual/pages/_partials/webdav_api/search/file_properties.adoc
- modules/user_manual/pages/apps/enterprise/admin_audit.adoc
This fixes the build errors and a majority of the warnings in the 10.4 branch. 
There are, unfortunately, several that I've not been able to resolve,, despite grepping the entire ownCloud documentation; they are listed below. 
```console
asciidoctor: WARNING: skipping reference to missing attribute: password
asciidoctor: WARNING: skipping reference to missing attribute: request_body
asciidoctor: WARNING: skipping reference to missing attribute: server_uri
asciidoctor: WARNING: skipping reference to missing attribute: session_path
asciidoctor: WARNING: skipping reference to missing attribute: username
```
I've asked in [the Antora users forum](https://gitter.im/antora/users) and am waiting to get feedback so that I can resolve the remaining ones.
> Fix build errors in 10.4

- modules/user_manual/pages/apps/enterprise/admin_audit.adoc
This fixes the build errors and a majority of the warnings in the 10.3 branch. It has the same issue with build warnings as #2543.
> Fix leveloffset errors

- modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
This PR fixes #2529 by making the tone of the wording around the allowHttpFallback configuration more forthright and forceful.
> [2529] Update federated cloud shares documentation

- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
This PR formats the OAuth2 overview quote as a proper quotation, instead of as a source code block. When formatted as a source code block, the text flows off of the page, requiring the user to unnecessarily scroll to read the information. By formatting it as a quotation, this is no longer necessary.
> Correctly format the OAuth2 overview quote

- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
This fixes #2491 by documenting the three requirements for using the app. It also reorganises some of the sections in the documentation so that there is a better and more intuitive flow to the content.
> Document OAuth2 app requirements

- modules/admin_manual/pages/configuration/server/occ_command/file_commands.adoc
This change documents that, from 10.4.1, files:transfer-ownership can be
used for users who have never logged in before. This change is being
made after reading about the change in the 10.4.1 release notes (#2516).
> Document that files:transfer-ownership changes in 10.4.1

- modules/developer_manual/examples/app/fundamentals/database/author-access-attributes.php
- modules/developer_manual/examples/app/fundamentals/database/author.php
- modules/developer_manual/examples/app/fundamentals/database/authormapper.php
- modules/developer_manual/examples/app/fundamentals/database/create-migration-step.php
- modules/developer_manual/examples/app/fundamentals/database/custom-attribute-to-database-column-mapping.php
- modules/developer_manual/examples/app/fundamentals/database/database-access.php
- modules/developer_manual/examples/app/fundamentals/database/migrations.php
- modules/developer_manual/examples/app/fundamentals/database/schema-migration-step.php
- modules/developer_manual/examples/app/fundamentals/database/schema-update.xml
- modules/developer_manual/examples/app/fundamentals/database/slug.php
- modules/developer_manual/examples/app/fundamentals/database/sql-migration-step.php
- modules/developer_manual/pages/app/fundamentals/database.adoc
This change extracts all the examples to external files, reformats the
sentences to each be on one line, and fixes up some examples so that they use
global attributes.
> Update developer manual database fundamentals documentation

- modules/admin_manual/pages/release_notes.adoc
Backport #2516
Note: we backport the release notes to the previous doc version (10.3) so that people on 10.3 can see the release notes of the upcoming version.
> [10.3] Add Server 10.4.1 release notes

- modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh
This fixes #2582. In the finalise install script, the root user was previously set as the owner of the htaccess file. Based on the file permissions set for the file, post-install the web user wasn't able to write to the file. This PR corrects that situation.
> Fix .htaccess permissions and file owner in finalise-install script

- site.yml
This change sets a site-wide variable that integrates with the change in https://github.com/owncloud/docs-ui/pull/155. This is required for the docs UI to respond appropriately if the version of the documentation being viewed is out of date.
> Add site-wide variable for managing the outdated docs status

- .drone.yml
This environment variable is required to ensure that the outdated documentation notification in the docs will display if the version of the docs being viewed is not the latest version. For more information, please see https://github.com/owncloud/docs-ui/pull/155.
> Add Drone environment variable to set the latest version

- modules/ROOT/pages/index.adoc
- modules/admin_manual/pages/release_notes.adoc
One reference an HTML file, which would never validate, and the other referenced a specific branch, which isn't necessary. The reason why this is set to high is that it's preventing the most recent three PRs from building successfully.
> Fix invalid xrefs

- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- package.json
- site.yml
- yarn.lock
Backport of #2550 
Note: I needed to manually cherry pick to make the backport work.
Because documents have more changes in 10.1 - 10.3, I refused to do a backport for them.
I created PR #2643 to keep the deployment things inline for 10.3. This is not necessary for 10.1 and 10.2 (as they are absolutely aged)
> [10.4] [2550] Render the OAuth2 flow Ascii art diagram as an image

- package.json
- site.yml
- yarn.lock
This is a cherry pick for updated packages for 10.3 only.
It references the changes made in PR #2550 and makes `yarn.lock`, `package.json` and `site.yml` inline with master and 10.4. (see the full 10.4 backport in #2642).
This will help upcoming PR´s when they use the kroki package (render asci images to pictures).
Due to the age of older branches, I would not make a backport to them.
I have tested the changes by running a doc build in 10.3 successfully.
> 10.3 cherry pick 321900c 2550

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Incorporate the latest changes from core for `config.sample.php`
Triggered by https://github.com/owncloud/core/pull/35969
Note, I was not aware of the removal of `knowledgebaseenabled` key in core. Therefore it is in this PR as it reflects all the changes made from last config-to-docs run.
Needs backporting to 10.4 (maybe 10.3, pls advise)
> Incorporate changes from core for config.sample.php

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Document the typical user names that we use in acceptance tests.
This was implemented in core PR https://github.com/owncloud/core/pull/37397
> Use realistic user names in acceptance tests

- .drone.star
- README.md
- site.yml
See https://github.com/owncloud/docs/compare/10.5...add-10.5?expand=1 for changes compared to 10.5 branch.
I think this is correct now and tried to adjust the documentation accordingly.
If you have ideas to make it easier, let me know. The problem is that part of the changes are shared between master and 10.x and 10.x needs one individual change, that makes the instructions look a bit confusing ... (compare the link above)
edit:
So the expected outcome is roughly:
commit shared in 10.x and master branches:
- updating versions in `site.yml` and `.drone.star`
only master: 
- adding 10.x branch to `content.sources`
only in 10.x: 
- setting version in `antora.yml`
> Add 10.5 to master

- .drone.star
My latest changes removed pdf upload from branches, which apparently was not a good idea.
The html documentation can be built centrally from master - pdfs need to be built in and uploaded from their respective branches. This is okay, because they don't cross reference each other between different versions AFAICT and so we don't have constant backporting there.
> Upload pdfs from base_branch

- modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
Added note that such a LDAP proxy setup is not part of our subscription services.
Backport https://github.com/owncloud/docs/commit/d28999f866a0e9c3fb6f3a387b3e46fa85aa5f1e from `master` to `10.5` branch so that the note is published in the 10.5 docs also.
Part of issue #2669
> Added subscription note

- modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
Added note that such a LDAP proxy setup is not part of our subscription services.
Backport https://github.com/owncloud/docs/commit/d28999f866a0e9c3fb6f3a387b3e46fa85aa5f1e from `master` to `10.4` branch so that the note is published in the 10.5 docs also.
Part of issue #2669
> [10.4] Added subscription note

- modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
Added note that such a LDAP proxy setup is not part of our subscription services.
Backport https://github.com/owncloud/docs/commit/d28999f866a0e9c3fb6f3a387b3e46fa85aa5f1e from `master` to `10.3` branch so that the note is published in the 10.5 docs also.
Part of issue #2669
> [10.3] Added subscription note

- modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
Fixes issue #2674
core code changes were merged in PR https://github.com/owncloud/core/pull/37513 for 10.5.0
Backport to 10.5 only.
> files_external:list --importable-format documentation

- modules/admin_manual/pages/configuration/server/occ_command/files_external_commands.adoc
> [10.5] files_external:list --importable-format documentation

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Documents the implementation of issue https://github.com/owncloud/core/issues/33596
Backport to 10.5 (the possibility is only there from core 10.5 onwards)
> Document how to replace usernames in acceptance tests

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/installation/deployment_considerations.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
Backport #2689 
This backports easily enough all the way back to 10.0 docs, so IMO we may as well do it.
> [10.0] Replaced Master-Slave with primary-replica

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
there was a wrong cron job for user:sync. 
I also added a log file for the output of user:sync
changed header levels for better overview
removed php reference in Cron Jobs. You don't need php for system cron and user sync.
> fixed ldap cron job in Installation manual

- docs/best-practices.md
This is small addon to describe how to add images to tables in best practices documentation  of docs.
No backport needed as it is part of the repro documentation. The text is taken from quotes of the developer of Antora (mojavelinux)
> Describe: how to add images to tables in best practices docs documentation

- modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
Fixes issue #2723 
Backport to maintained branches 10.5 and 10.4
Somehow this was "just wrong". I tested with various `curl` commands there is no way to add an email in the "Add User" POST request.
> Fixup doc of Provisioning API Add User

- docs/best-practices.md
- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Backport #2719 Describe: how to add images to tables in best practices docs documentation (might as well do this so that I don't see it again in diffs between docs `master` and `10.5` branches)
Backport #2685 fixed ldap cron job in Installation manual
This was all that I can see that has missed backport to 10.5
> [10.5] Backports for 10.5

- site.yml
because that is the range of supported versions now in 10.5.0
Needs backport to 10.5 branch.
> Update site.yml to have PHP 7.2 to 7.4

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
Fixing a compile warning because of a missing reference.
Creating the proper reference in site.yml
Attn: Backport to 10.5 ONLY !
We can do a BP to 10.4 too, but...
...then we have to do a pick of `manual_upgrade.adoc` and fix `site.yml` in 10.4 (add `latest-download-version: 10.5.0`). The other content in site.yml in 10.4 stays the same !
@phil-davis your help is appreciated :smile:
> Fix Antora compile warning missing reference to latest-download-version

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- site.yml
Referencing https://github.com/owncloud/docs/pull/2749
**THIS IS FOR 10.4 ONLY**  (base target branch has been set to 10.4)
> Fix Antora compile warning missing reference to latest-download-version for 10.4 only

- modules/developer_manual/pages/testing/acceptance-tests.adoc
PR https://github.com/owncloud/core/pull/37837 added the ability to skip acceptance test scenarios when CI is running with a federated server with an old ownCloud version. This allows developers to write new acceptance test scenarios that will pass with a "modern" combination of local and federated server, but are not expected to pass with some old combination.
Document the tags that can be used.
> Document skipOnFedOcV10 test tags

- .drone.star
This is a regression fix. Drone used to have 'push' as event type for cron jobs and the cron type did not exist.
> Upload docs from cron jobs.

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
PR #2749 provided a site variable for this. Use it in another place.
Note: this effectively implements PRs #2552 and #2553 - I will look and sort out the appropriate backports to 10.5 10.4 and 10.3 branches. (Possibly 10.3 can have just a hardcoded fix_
> Update hardcoded ownCloud10 patch version

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
Backport #2763 to 10.3 branch.
The site variable `latest-download-version` exists in `site.yml` of this branch, so use it.
> [10.3] Update hardcoded ownCloud10 patch version

- modules/admin_manual/pages/release_notes.adoc
Related to core issue https://github.com/owncloud/core/issues/37898
You can get in a little bit of an issue if you first upgrade to PHP 7.4 ("throwing away" PHP 7.2 and/or 7.3). e.g. this happens if you upgrade Ubuntu to 20.04. At that point your old ownCloud 10.* system does not work at all.
It will be smother for you if you upgrade to ownCloud Server 10.5 while still on a system running PHP 7.2 or 7.3. Then upgrade to PHP 7.4 (or upgrade the whole of Ubuntu to 20.04, or...)
Add a tip to the release notes.
> Add tip about ownCloud Server 10.5 and PHP 7.4 upgrade order

- modules/developer_manual/pages/testing/acceptance-tests.adoc
that were added in PR https://github.com/owncloud/core/pull/37897
No backport needed - this is applicable to current development in any repo that uses the core master test code.
> Document acceptance test debug env variables

- modules/developer_manual/pages/testing/acceptance-tests.adoc
`skipOnOcis` tag is not used any more. The tag is now called `notToImplementOnOCIS`
(There is another tag `toImplementOnOCIS` but that is being phased-out and not to be "permanently" documented)
> Document notToImplementOnOCIS test tag

- modules/developer_manual/pages/testing/acceptance-tests.adoc
That was introduced in core PR https://github.com/owncloud/core/pull/37915
No backport required - this is a developer test extension that was added to core today.
> Document step-through for acceptance tests

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
The description of `expireDate` is too restrictive. In 10.5 it applies to public link, user and group shares.
Backport to 10.5
I will also look at backporting to 10.4 - need to check when `expireDate` existed for user and group shares.
> Expire date does not just apply to public link shares

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.5] Expire date does not just apply to public link shares

- modules/user_manual/pages/files/webgui/sharing.adoc
The section "Changing The Share Expiration Date" is out-of-date. In 10.5 the user can specify an expiration date for user, group and public link shares.
Backport to 10.5
I will look at backport to 10.4 also - IMO that had expiration for those 3 share types.
> Update description of sharing expiration date

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
Backport #2796 to 10.4
Expiration date for user and group shares is in 10.4
> [10.4] Expire date does not just apply to public link shares

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
The section on all the file sharing settings is missing various parts. I read through the document while looking at `index.php/settings/admin?sectionid=sharing` and made the documentation match what is currently in core 10.5 release.
I noticed this when looking at issue #2759 - I can't really do the doc for that until the existing doc is up-to-date.
Needs backport to 10.5
I will think about backport to 10.4 - need to check which things were or were not in 10.4.
> Update admin file_sharing_configuration with current information

- modules/admin_manual/pages/installation/apps_supported.adoc
Remove enterprise_key app from the list. It no longer exists with 10.5.
Please review the rest....
Suggest to say that "standard" enterprise apps are now included with the normal server.
Suggest to say that docker image owncloud/enterprise:10.5 does not exist. it is obsoleted by owncloud/server:10.5
> [10.5] Review supported list of enterprise apps

- modules/admin_manual/pages/installation/system_requirements.adoc
As discussed in https://github.com/owncloud/docs/pull/2684 , it's impossible to maintain the desktop & mobile system requirements in the server docs. Better remove the redundant information, and link to the the original source…
> Migrate desktop & mobile system requirements

- modules/admin_manual/pages/configuration/user/oidc/index.adoc
and add blank lines before lists and tips so that they render correctly.
Backport of #2837 to 10.5
> [10.5] Fix xref in OIDC docs

- modules/admin_manual/pages/installation/ubuntu_18_04.adoc
1) Add the settings:
`[source,console,subs="attributes+"]`
to the top of the command section.
This was accidentally left out of PR #2789 
Note: the actual `occ background:cron` should be fine, because the document has instructions up the top about how to get yourself an `occ` command that "just works" - see section "Create the occ Helper Script"
2) Fix an include `examplesdir` reference.
> Adjust command format in ubuntu_18_04.adoc

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
The configuration example was previously not copy-pastable because the following section was missing:
```
[Install]
WantedBy=multi-user.target
```
This results in the following error when trying `systemctl enable ...`: `The unit files have no installlation config`
> Add missing part from service config

- modules/admin_manual/pages/installation/docker/index.adoc
Backport of #2859 
OWNCLOUD_DOMAIN can have a port number, and should have one, if non-standard.
OWNCLOUD_DOMAIN must not have a protocol, though.
Not sure if OWNCLOUD_PORT should be implicitly applied to OWNCLOUD_DOMAIN too, aparently it is not.
That would decide, if this an issue with docu or with code.
Backports needed: 10.5, 10.6 ... maybe more?
> [10.5] Possible fix for owncloud/core#38074

- modules/admin_manual/pages/installation/docker/index.adoc
OWNCLOUD_DOMAIN can have a port number, and should have one, if non-standard.
OWNCLOUD_DOMAIN must not have a protocol, though.
Not sure if OWNCLOUD_PORT should be implicitly applied to OWNCLOUD_DOMAIN too, aparently it is not.
That would decide, if this an issue with docu or with code.
Obsoletes another part of the unmergeable #2854
Backports needed: 10.5, 10.6 ... maybe more?
> Possible fix for owncloud/core#38074

- modules/admin_manual/nav.adoc
because I forgot to do it when removing the document itself
backports to 10.5, 10.4
> removed ldap cache proxy from index

- modules/admin_manual/nav.adoc
because I forgot to do it when removing the document itself
backports to 10.5, 10.4
> [Backport 10.5] removed ldap cache proxy from index 

- modules/admin_manual/nav.adoc
because I forgot to do it when removing the document itself
backport to 10.4 of #2864
> [backport 10.4] removed ldap cache proxy from index

- modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
Some text fixes and added the missing read only option.
Backporting to 10.5 necessary
> Some text fixes for the external mount point documentation

- modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
CentOS 8 is installing PHP-FPM by default, users have to switch to mod_php
Not sure if my writing style is good enough, feel free to change it.
> Known Limitation addition: PHP-FPM is incompatible

- modules/admin_manual/pages/installation/linux_installation.adoc
they only document nextcloud there.
https://github.com/owncloud/docs/pull/2909
> 10.5 Backport - remove link to mageia wiki

- modules/admin_manual/pages/installation/linux_installation.adoc
they only document nextcloud there.
https://github.com/owncloud/docs/pull/2909
> 10.4 Backport - remove link to mageia wiki

- modules/user_manual/pages/files/access_webdav.adoc
added keyword to user manual in [access webDAV](https://doc.owncloud.com/server/user_manual/files/access_webdav.html#uploading-files-to-a-public-link-using-curl)
Issue: https://github.com/owncloud/docs/issues/2907
> [Backport 27fb479 10.5] added keyword to user manual: access webDAV

- modules/user_manual/pages/files/access_webdav.adoc
added keyword to user manual in [access webDAV](https://doc.owncloud.com/server/user_manual/files/access_webdav.html#uploading-files-to-a-public-link-using-curl)
Issue: https://github.com/owncloud/docs/issues/2907
> [Backport 10.4] added keyword to user manual: access webDAV

- .drone.star
We need to run pipelines to build pdfs. Steps are properly guarded already.
> Do not exclude version branches from running pipelines.

- modules/admin_manual/pages/configuration/server/occ_command/user_commands.adoc
Added example of the missing user options to the occ command of user:sync
https://github.com/owncloud/docs/issues/2885
> Added example to user:sync in user_commands.adoc

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Clarifying that no value is necessary to enable the nullPermissionManager for better understanding in the documentation and that people will not be confused, why the nullPermissionManager is in use even when the field is empty.
https://github.com/owncloud/docs/issues/2683
Backports needed for:
10.6
10.5
10.4
> Clarifying WND null Permission manager

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
These are config.sample changes in core for 10.6 but not yet have been transported to docs. This is the result of the config-to-docs run based on branch core/release-10.6.0
Needs backporting to 10.6 only !
> Missing config sample changes from core 10.6

- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
The current version of Shibboleth installed on Ubuntu 20.04 uses "path" instead of "file". I don't know when it changed.
Backport of #2944
> [10.6] Update SAML 2.0 instructions

- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
The current version of Shibboleth installed on Ubuntu 20.04 uses "path" instead of "file". I don't know when it changed.
Backport of #2944
> [10.5] Update SAML 2.0 instructions

- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
The current version of Shibboleth installed on Ubuntu 20.04 uses "path" instead of "file". I don't know when it changed.
Backport of #2944
> [10.4] Update SAML 2.0 instructions

- docs/best-practices.md
Had been forgotten to be fixed. `{examplesdir}` will be substituted by a build run with the proper path.
No backport needed as it is a repo doc readme file
> Update best-practices.md (fix examplesdir macro)

- docs/checking-broken-links.md
- docs/getting-started.md
Small improvements for broken link checker.
No backport needed, repo docs only.
> Update Broken Link Checker

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
As the title says. This avoids a browser redirect and accesses the data directly. 
Backporting to 10.6 and 10.5
> force https for some links

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
1) various edits to tidy up a few words in both the 18.04 and 20.4 "quick install" docs.
--------
2) I wondered what the dot was in `chown -R www-data. owncloud` - it is an old form of the `chown` command with dot as separator between user and group name. Nowadays colon is the documented way. So `www-data:` is the same as the old `www-data.` And the means to also use the group of `www-data`. In this case you correctly end up with user `www-data` and group `www-data`
- I will put this in a separte PR
--------
> Edits to ubuntu installation

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
This updates the server 18.04 prep document for the situation, when having multiple php versions installed. This happens when using the ondrej ppa and is essential for the successful installation of smbclient via pecl with the chosen php version.
Backporting to 10.6 and 10.5 necessary.
> Update server_prep_18.04 when using multiple PHP installs

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
- modules/developer_manual/pages/app/advanced/code_signing.adoc
PR #2999 corrected `MISSING_FILE` to `FILE_MISSING` in 1 place. This PR corrects it in another place.
I also updated an FAQ heading to the current standard way of specifying that. (My IDE told me about that)
Needs backport to 10.6 and 10.5
> Fix another FILE_MISSING and some FAQ headings

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
So that it mentions the correct latest release version.
Backport to 10.6 branch only.
I am fixing this directly for now. For the future a different approach could be taken in a next PR. Maybe:
For the column heading:
1) Change column heading to "Can Upgrade to current 10.x.x?" or
2) Put a reference to `site.yml` `latest-download-version` so that it automagically stays up-to-date.
For the column rows, do we really need all the examples of every 10.x minor version? That is annoying to remember to keep updating. The text above the table already says "Here are some examples:" but actually the table has a lot more entries than just a few examples.
> Fix out-of-date minor version in table

- .drone.star
- generator/generate-site.js
This PR adds on env variable option to build the search index without uploading (default=true). This option is required to use as much as possible 3rd party dependencies also on PR's to test version upgrades. 
I've also added some basic console logging to make skipped/included parts more transparent.
Fixes partially https://github.com/owncloud/docs/issues/3014
> add env option to build search index without upload

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
This PR replaces the hardcoded latest download version which is when built used in https://doc.owncloud.com/server/admin_manual/maintenance/upgrade.html
References: https://github.com/owncloud/docs/pull/3017 + discussion
Backport to 10.6 only
@phil-davis the variable in site.yml was already present, I just needed to use it.
> Use antora variable from site.yml in maintenance for the latest download version

- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
Thus avoids anyone feeling that they need to add a row to this table every minor version release.
> Reduce list of 10.x.y versions in example upgrade table

- modules/developer_manual/pages/core/configfile.adoc
Following on from PR #3040 , there is another place that setting up `apps_paths` is described. This is in the developer docs section, so one would hope that a developer will actually look and create the directory. But we may as well put the note here also.
> Add note about apps_paths to developer docs also

- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
issue #2351
Added new text for cron in security_setup_warnings.adoc.
Cron was missing in the text.
Backport needed for
10.6
10.5
10.4
> add background jobs to security warnings

- modules/developer_manual/examples/scripts/backport.sh
This is an update of the backport script that reflects recent changes on GH.
Returns again correct RateLimit values.
Backporting to 10.6 and 10.5
> Small update of the Backport Script reflecting recent changes on GH

- site.yml
Client: embed `2.7` into single quote marks --> `'2.7'`
No backport needed as it is environment specific
> Update site.yml : client, a branch needs to be in single quote marks

- modules/developer_manual/pages/testing/acceptance-tests.adoc
This documents the `replaceUsernames` setting that can by used by developers or QA to run acceptance tests with different user names and user attributes.
Part of issue https://github.com/owncloud/core/issues/33596
PR https://github.com/owncloud/core/pull/38364 adds this CI functionality. This docs PR can be merged when that core PR is merged.
No backport - this is new CI functionality in core master.
> Document the replaceUsernames setting in .drone.star

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
> Just using Restart and RestartSec is not enough: systemd services have start rate limiting enabled by default. If service is started more than StartLimitBurst times in StartLimitIntervalSec seconds is it not permitted to start any more. This parameters are inherited from DefaultStartLimitIntervalSec(default 10s) and DefaultStartLimitBurst(default 5) in systemd-system.conf
https://selivan.github.io/2017/12/30/systemd-serice-always-restart.html
This would lead to the case that the defined listener fails and is being restarted within a second. But if the listener fails to start straight away again for more than 5 consecutive times (which would be within 5 seconds [<10 sec = DefaultStartLimitIntervalSec ] ), perhaps because the share is unavailable for short amount of time. Then the …
> Changed RestartSec to avoid DefaultStartLimitBurst

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Backport #3098 to 10.5
> Just using Restart and RestartSec is not enough: systemd services have start rate limiting enabled by default. If service is started more than StartLimitBurst times in StartLimitIntervalSec seconds is it not permitted to start any more. This parameters are inherited from DefaultStartLimitIntervalSec(default 10s) and DefaultStartLimitBurst(default 5) in systemd-system.conf
https://selivan.github.io/2017/12/30/systemd-serice-always-restart.html
This would lead to the case that the defined listener fails and is being restarted within a second. But if the listener fails to start straight away again for more than 5 consecutive times (which would be within 5 seconds [<10 sec = DefaultStartLimitIntervalSec ] ), perhaps because the share is unavailable for short amount of …
> [10.5] Changed RestartSec to avoid DefaultStartLimitBurst

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Backport #3098 to 10.6
> Just using Restart and RestartSec is not enough: systemd services have start rate limiting enabled by default. If service is started more than StartLimitBurst times in StartLimitIntervalSec seconds is it not permitted to start any more. This parameters are inherited from DefaultStartLimitIntervalSec(default 10s) and DefaultStartLimitBurst(default 5) in systemd-system.conf
https://selivan.github.io/2017/12/30/systemd-serice-always-restart.html
This would lead to the case that the defined listener fails and is being restarted within a second. But if the listener fails to start straight away again for more than 5 consecutive times (which would be within 5 seconds [<10 sec = DefaultStartLimitIntervalSec ] ), perhaps because the share is unavailable for short amount of …
> [10.6] Changed RestartSec to avoid DefaultStartLimitBurst

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
I added a working(!) LDAPS documentation for Ubuntu and Windows Server to the exiting LDAP Docs.
Smaller fixes:
- fixed the headers on some pages to adjust to the "installation - configuration - troubleshooting" scheme
- fixed the troubleshooting for LDAPS
- added port example for LDAPS with explanation
BP to 10.6 and 10.5 needed.
> LDAPS documentation

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
As the name tells, there have been changes and additions in config.sample from core which need to be transported to docs.
References:
https://github.com/owncloud/core/pull/38337
https://github.com/owncloud/core/pull/38379
**NO backport, master only**
> Recent changes and additions in config.sample from core

- modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
since 10.6.0 we have the ex-enterprise bundle available as `owncloud-complete-files` -- I suggest to have this as 'recommended' install. We should probably also add a section about ugrading from owncloud-files to owncloud-complete-files
Backport #3127
> [10.6] Update linux_packetmanager_install.adoc

- modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
since 10.6.0 we have the ex-enterprise bundle available as `owncloud-complete-files` -- I suggest to have this as 'recommended' install. We should probably also add a section about ugrading from owncloud-files to owncloud-complete-files
Backport #3127
> [10.5] Update linux_packetmanager_install.adoc

- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
added explanation why the webUI features of the manual file locking are disabled by default and need to be enabled by the admin.
Backport #3137
> [10.5] Update manual_file_locking.adoc

- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
added explanation why the webUI features of the manual file locking are disabled by default and need to be enabled by the admin.
Backport #3137
> [10.6] Update manual_file_locking.adoc

- modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
remove useless reference to docker-compose
Backport #3177
> [10.6] Update full_text_search_commands.adoc

- modules/admin_manual/pages/configuration/server/occ_command/full_text_search_commands.adoc
remove useless reference to docker-compose
Backport #3177
> [10.5] Update full_text_search_commands.adoc

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Based on changes in core https://github.com/owncloud/core/pull/38431
Obsoletes: https://github.com/owncloud/docs/pull/3182
Backport to 10.5 and 10.6 necessary
> config-to-docs run

- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
another case documented for 0 storages, this time wrong credential method
bp of https://github.com/owncloud/docs/pull/3192
> [10.5] troubleshooting addition

- modules/admin_manual/pages/enterprise/external_storage/wnd_quick_guide.adoc
another case documented for 0 storages, this time wrong credential method
bp of https://github.com/owncloud/docs/pull/3192
> [10.6] troubleshooting addition

- modules/admin_manual/pages/installation/docker/index.adoc
The Owncloud Docker Version 10.5 and 10.6 won't work due to an permission error caused by an old version of libseccomp.
See https://github.com/owncloud-docker/server/issues/219
According to https://docs.linuxserver.io/faq one could also install the package source:
```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2
```
I'm not sure if it is better or not and one should mention this second approach instead of just installing the newest package manually.
Original Issue seems to be discussed here: https://github.com/moby/moby/issues/40734
> [10.6] Add information on libseccomp version (Raspbian Buster - Docker)

- modules/admin_manual/pages/installation/docker/index.adoc
The Version 10.5 and 10.6 won't work due to an permission error caused by an old version of libseccomp.
See https://github.com/owncloud-docker/server/issues/219
Backport of #3203 (from master) #3196 (from 10.6)
> [10.5] Add information on libseccomp version (Raspbian Buster)

- modules/admin_manual/pages/installation/docker/index.adoc
The Version 10.5 and 10.6 won't work due to an permission error caused by an old version of libseccomp.
See https://github.com/owncloud-docker/server/issues/219
This is a forward-port of #3196
> Add information on libseccomp version (Raspbian Buster)

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Fixes owncloud/files_antivirus#397
> Clarify log/delete choice actions in files_antivirus

- docs/build-the-docs.md
- package.json
This eases the process to build the docs with default URL = `localhost:8080` and not `docs.owncloud.com`
Just run `antora-local` instead `antora`
Benifical when you want to check for broken links.
No backport necessary.
@EParzefall  FYI
> Adding a antora-local command to predefine localhost to build the docs on.

- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/developer_manual/pages/webdav_api/meta.adoc
This PR fixes trailing slashes `{examplesdir}/` --> `{examplesdir}` as they can make troubles by being double defined
The definition of those macros is defined in `bin/cli`.
Backporting to 10.5 and 10.6 necessary
> Fix trailing slashes when using examplesdir

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/unit-testing.adoc
fixes https://github.com/owncloud/docs/issues/3214
Now there are no warnings at all during the PDF building process: 
```
latest: Pulling from owncloudci/asciidoctor
--
2 | Digest: sha256:64d1ea6a52225e48963f7cc829bb460f01af5aac4b53d2ca3a623846a2d311ac
3 | Status: Downloaded newer image for owncloudci/asciidoctor:latest
4 | + bin/cli -m
5 | Generating version 'master' of the admin manual, dated: March 08, 2021
6 | Generating version 'master' of the developer manual, dated: March 08, 2021
7 | Generating version 'master' of the user manual, dated: March 08, 2021
```
> fixed example block

- modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php
- modules/developer_manual/examples/core/acceptance-tests/then-step.php
Later releases of PHPunit Assert library have a different namespace. Update the examples of it use in acceptance tests.
I noticed this while looking at the remaining ToDos for issue #156 
No need to backport - these developer docs are really intended to be used along with the current core master.
> Update examples of Assert in acceptance tests

- modules/developer_manual/pages/core/index.adoc
- modules/developer_manual/pages/core/introduction.adoc
Add some words to the developer docs intro pages so that readers will understand that the developer docs are intended for use with current core master. (There might be all sorts of different stuff if someone checks out an old release branch and tries to develop or run tests from those)
> Develop with latest core master

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Append ldap user:sync to crontab, rather than overwriting it.
A few lines above, we added system:cron, we should not lose that.
> ubuntu 20.04 -- append to crontab

- bin/cli
changed print NF-1 to print NF-2
because the pdf build on 10.6 was throwing the same errors like on master.
```
latest: Pulling from owncloudci/asciidoctor
--
2 | Digest: sha256:64d1ea6a52225e48963f7cc829bb460f01af5aac4b53d2ca3a623846a2d311ac
3 | Status: Downloaded newer image for owncloudci/asciidoctor:latest
4 | + bin/cli -m
5 | Generating version '10.6' of the admin manual, dated: March 11, 2021
6 | asciidoctor: WARNING: modules/admin_manual/pages/index.adoc: line 1: section title out of sequence: expected levels 0 or 1, got level 2
7 | asciidoctor: WARNING: modules/admin_manual/pages/release_notes.adoc: line 1: section title out of sequence: expected levels 0 or 1, got level 2
8 | asciidoctor: WARNING: modules/admin_manual/pages/faq/index.adoc: line 1: section title out of sequence: …
```
> [10.6] Update cli

- bin/cli
- bin/yamlparse.sh
- bin/yamltest.sh
The following fix makes rendering of attributes in pdf documents working!
**This issue has not been identified since we started creating the PDF docs with Antora**
**Background**
We use _site wide attributes_ defined in site.yml, which are intensively used in all modules. These attributes harmonize the look and feel and ease maintenance a lot. Example: definition: `minimum-php-version: 7.2` usage: `{minimum-php-version}` rendering: `7.2` Means that any change we do in the definition will immediately affect all pages using the attribute `{minimum-php-version}`. This works great when building the docs for html.
But when creating the pdf´s, a different script is used which does not and cannot use site.yml. Nobody has taken care about these attributes and when rendered, you do not get `7.2` …
> Fix to dynamically create the attribute-to-argument list for asciidoctor-pdf

- modules/admin_manual/pages/installation/docker/index.adoc
The code block had an extra space, I removed it.
there was no header on the new text, I added it.
The entry about the registry was back when we had an enterprise registry, now we don't, so I removed that entry.
Links should be done via variable, I changed it.
> fixed code block, added header, removed registry, fixed link

- modules/admin_manual/examples/enterprise/user_management/shibboleth/apache-2.4-configuration.conf
- modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc
https://github.com/owncloud/docs/pull/2818#issuecomment-797641234
"(double-checked with google. "mod-shib2" is correct! "mod_shib2" is wrong.)"
Change other `mod_shib` to `mod-shib`
I need to check thus "for real" on my system to see exactly which usages are correct or not...
> [WIP] Change mod_shib to mod-shib

- .drone.star
- site.yml
This PR changes the workflow for branches to include 10.7 and drop 10.5.
This means, that 10.5 is frozen but still accessible if you enter the link on the web manually.
Any new backports, if necessary, will now go to 10.6 and 10.7
There is already a 10.7 branch made based on origin/master containing the proper setup for 10.7 only, which I pushed just right before.
When this PR is merged, the situation is set.
Post merging, we need to unprotect 10.5 (see the repo settings) and rename it to `x_archived_10.5`
Fixes: https://github.com/owncloud/docs/issues/3278
FYI: @micbar @pmaier1 @EParzefall @mschreml @voroyam
> Necessary Branch Changes for 10.7

- README.md
- docs/new-version-branch.md
This is a summary based on the last nights experience of how to properly create a new version branch.
Backport to 10.6 and 10.7 necessary
> Improved README.md how to create a new version branch

- modules/admin_manual/pages/configuration/general_topics/code_signing.adoc
Issue: #3057
(added a link to errors into introduction, instead of putting the errors on top)
backports needed for 10.7 and 10.6
> add link to introduction in code_signing.html

- .drone.star
NO backport, must stay inside 10.7 only!
> Fix 10.7 for pdf publishing

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
This fixes the file naming to that what the page is about, keeping the original link and redirecting to the new page. The document is about Collabora Secure View and not about Collabora Integration like the Microsoft Office Integration document. This is now corrected.
Backport to 10.6 and 10.7 necessary
> Fix Collabora Secure View file naming

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Fixing typo and rendering issue (visible only in when converted to docs).
No content change.
> Typo and rendering fix in config.apps.sample

- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
Changes:
- I changed  `owncloud-old-version-number` to `backup_owncloud` for convenience. If I go to the ownCloud folder and use tab completion I always get ownCloud-something because I update my server. If the back up copy of ownCloud is in the backup_ownCloud folder - I won't get that problem. I assume that I am not the only one with this issue.
- I removed the enterprise part of the upgrade docs because now we have only one single server package for enterprise and community.
- I restructured the re-enabling part of the document because it was weird **tripple** bullet points with a warning at the end. Now it looks unified.
this is how it looks now
> document improvement

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
the add-apt-repostory command effectively does the same as the echo|tee command. 
also, remove sudo, as we say in the beginning, that we assume the user is logged in as root.
> Do not register ondrey repo twice

- modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
The attribute name `page_alias` needed a correction to `page_aliases` (typo)
> Fix page_alias attribute name

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.6] [PR 3488] The share api endpoint does not end in `/pending`

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
> [10.7] [PR 3488] The share api endpoint does not end in `/pending`

- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
PHP-FPM is not officially supported as the QA teams is running our docker containers which are using mod_php.
SAML SSO with Shibboleth doesn't work using PHP-FPM
Needs backporting
> php-fpm support information

- modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
- modules/admin_manual/pages/enterprise/reporting/metrics.adoc
References to the new Splunk App for ownCloud give it more visibility in the auditing and monitoring context.
Backport to 10.7 necessary.
> Added references to the new Splunk-App-Section

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Added correct download link for version 10.6 and the -E parameter to the sudo command as suggested in PR #3374.
> [10.6] Fixing release version plus adding -E to sudo command.

- modules/developer_manual/pages/testing/acceptance-tests.adoc
> https://github.com/owncloud/QA/issues/670 added the ability to put `skip` `debugSuites` and/or `skipExceptParts` in the drone starlark config section of test pipelines in order to easily skip those in CI. This is useful when trying to run "suspect"  tests in CI - you don't need to waste lots of CI resources running tests that you do not care about.
Closes https://github.com/owncloud/docs/issues/3549
> Add docs about skip and debug tests suites in CI

- modules/admin_manual/pages/maintenance/package_upgrade.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
This fixes issue #2631 by providing the appropriate warnings to users relying on their distribution's package manager for upgrades.
> Added warnings to packagemanager upgrades

- bin/find-orphaned-files.sh
- bin/instructions_makepdf.md
- bin/makepdf
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- site.yml
`makepdf` is improved similar as we have it now in the `docs-client-desktop` repo.
This eases the setup for the new docs structure a lot as we just need to copy/paste things now and set the right variables in the script!
An additional fix has been made in site.yml pointing to the correct docs domain...
@tbsbdr @jnweiger fyi
Backport to 10.7 and 10.6 necessary
Info, in the desktop repo, we already have a instruction manual for this. Will improve it first and copy it afterwards.
> Fix makepdf (script which creates the pdf)

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Add docs for running acceptance tests in CI using release tarballs.
Fixes https://github.com/owncloud/docs/issues/3559
New feature in 10.8 no backport required.
> [Docs-Only] add docs for running tests with release tarballs in CI

- bin/find-orphaned-adoc-files
Updates the find-orphand-adoc files script to catch false positives when using the `include::` directive.
> Improved find adoc files catching false-positive incudes

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
The Quick Install Guide cant handle all situations, note to use the manual install section in case of issues.
Closes: https://github.com/owncloud/docs/issues/3570
Backport to 10.6 and 10.7 necessary
> Note that the Quick Install guide for Ubuntu 20.04 has its limits

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
Also: e.g. files_lifecycle needs a daily cron job, which is not done by occ system:cron -- it needs an exlicit cronjob entry.
Do we want to give an example for this  here or in the files_lifecycle section?
> Do not suggest cron every minute

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/user_commands.adoc
Refernces: owncloud/core#38742 (Add row for guest users to command occ user:report)
No backport needed - ~PR not merges yet~ -->core PR merged
> Add guest content for command occ user:report

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
New **config.sample** changes coming from core.
**References:**
https://github.com/owncloud/docs/issues/3586 ([QA] add files_antivirus.av_* variables to admin_manual/configuration/server/config_sample_php_parameters.html)
(_this is part one of two tasks_)
https://github.com/owncloud/docs/issues/3571 (New config.sample parameters in core (Trashbin skip list)
No backport necessary, new parameters for the upcoming 10.8 release
> config.sample changes coming from core (config-to-docs run)

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
The occ config: section was "scrambled", example commands were set at the wrong config, subsections unordered. Found while working on the anti virus documentation.
Cant provide a rendered version as it is part of the whole occ command set, does not render on it self and a pdf would be too big. A test build renders fine.
> Fix of occ config commands

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/wnd_commands.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Fixes: https://github.com/owncloud/docs/issues/3585 (All configuration options for mount points will be encrypted if they're passwords)
`wnd:set-service-account` is depreciated, passwords are encrypted from the beginning.
No backport as this will go into master (and the upcoming 10.8) only.
@jnweiger @cdamken fyi
> Configuration options for mount points will be encrypted if they are passwords

- modules/admin_manual/pages/configuration/files/file_versioning.adoc
- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Add config.apps settings for `files_versions`. These settings were forgotten to be documented.
Done via a `config-to-docs` run.
In addition, fixed some text in the app description.
Origins from core see: https://github.com/owncloud/core/pull/38801
Fixes: https://github.com/owncloud/docs/issues/3518 (config.php setting for files_versioning)
Note: Because nobody told that the `web.rewriteLinks` key has been added in core, it is now part of this PR which I do not see as a big problem at all, but it should not happen.
Backports to 10.6 and 10.7
@cdamken fyi
> Missing config key for files_version

- modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
References: https://github.com/owncloud/docs/issues/2770 (lifecycle_restored description)
Correcting the text in admin_audit in the table in section lifecycle_restored
> Text fix for enterprise/logging/admin_audit.html#lifecycle_restored

- modules/admin_manual/pages/configuration/integration/ms-teams.adoc
References: https://github.com/owncloud/docs/issues/3617 (Correct Apache header information for msteamsbridge)
The header information needs the `self` directive to work properly.
`Header merge Content-Security-Policy "frame-ancestors 'self' teams.microsoft.com *.teams.microsoft.com"`
@tbsbdr @micbar @jnweiger @cdamken
> Correct Apache header information for msteamsbridge

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
References:
https://github.com/owncloud/core/pull/38807 (Fix config.sample and preview provider)
https://github.com/owncloud/docs/issues/2735 (Document the support for SGI Images)
This is the corresponding `config-to-docs` run.
> Fix config.sample for preview providers

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Fixes the need to set the proper security policy for imagick when the preview provider should make  thumbnails for pdf files.
References: https://github.com/owncloud/core/pull/38810
Only merge if core has merged.
> Fix PDF preview provider

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Fixes: https://github.com/owncloud/docs/issues/3626 (Set http.cookie.samesite to 'none' for OIDC)
This required setting is, even present in config.sample.php, not prominent described in the admin/user/oidc document in section prerequisites.
This is how it renders now with this PR
@IljaN @DeepDiver1975 @tbsbdr @fschade @jerrac fyi
> Add the correct http.cookie.samesite for OIDC

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
References: https://github.com/owncloud/docs/issues/3537 (Document auto-provision for AzureAD OIDC)
This is part 1 of 2 to fix the referenced issue - it covers the `config-to-docs` run for changes from core
> Improved config key description for auto-provision for OIDC

- modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
References: https://github.com/owncloud/docs/issues/3537
Fix 2 of 2
Set proper `auto-provision` in `configuration/user/oidc/ms-azure-setup.adoc`
Section: Example config.php setup
> Document auto-provision for AzureAD OIDC

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Add missing Workflow / Tagging config key to config.apps.sample.php
References: https://github.com/owncloud/docs/issues/3519 (config.php setting for files_tagging)
References: https://github.com/owncloud/core/pull/38816
This is fix 1 of 2
> Add Workflow / Tagging config key

- docs/build-the-docs.md
This PR updates `build-the-docs.md` reflecting the recent changes of the drone pipline which got beside many other things updated to use node v14.
Now we can use node v14.17.0 (LTS) for local builds. There were troubles using particular ranges of node versions, especially with `serve`. With v14.17.0 this is not longer the case - tested locally.
Backport to 10.7 (leaving 10.6 as it is soon not longer actively maintained)
> Update build-the-docs.md to reflect the changes on node

- .drone.star
- .gitignore
- adds a starlark syntax check
- adds a new variable `pdf_branch`, this way the drone file works with all branches and only the variables defined at the beginning of the file need to be adjusted
Master:
```
def main(ctx):
latest_version = "10.7"
default_branch = "master"
base_branch = latest_version
deployment_branch = default_branch
pdf_branch = default_branch
```
Version e.g. 10.6:
```
def main(ctx):
latest_version = "10.6"
default_branch = "master"
base_branch = latest_version
deployment_branch = default_branch
pdf_branch = base_branch
```
Needs backport to 10.7 and 10.6
> refactor ci to work with all branches

- modules/user_manual/nav.adoc
For some unknown reason, these two entries slipped into the 10.6 user_manual navigation and should not be there. Found by @xoxys by a check of the pdf creation output of the CI build https://drone.owncloud.com/owncloud/docs/11286/1/6. Interestingly the antora build did not complain - but this will be past when the new antora 3 will be available which contains proper logging.
For 10.6 only, no porting
(the commit name is misleading, I first thought files were missing)
> 10.6 fix user_manual nav for non existing references

- modules/admin_manual/pages/configuration/server/harden_server.adoc
References: https://github.com/owncloud/docs/issues/3660 (oC 10.7 X-XSS-Protection)
The X-XSS-Protection setting needed to be corrected to be inline with 10.7 core.
> Correct X-XSS-Protection

- bin/makepdf
Add an option to set the log-level to ERROR for printing errors (default would be FATAL only)
@xoxys fyi
> makepdf: add option for error output

- modules/admin_manual/pages/configuration/server/harden_server.adoc
Change to #3664 (also see #3037, #3660). If X-XSS-Protection disable not having `; mode=block` should be included.
> Kick block; from X-XSS-Protection

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Refernces: https://github.com/owncloud/docs/issues/3675 (New WND config key for Ldapmembership cache)
Adds a new config key for WND
This is the `config-to-docs` run for the referenced core PR https://github.com/owncloud/core/pull/38840
**No** Backport, will go into 10.8
> New WND config key for Ldapmembership cache

- modules/developer_manual/examples/core/scripts/responses/shares/update-share-success.xml
- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
- modules/user_manual/pages/files/public_link_shares.adoc
Fixes issue #3680 
Documents core PR https://github.com/owncloud/core/pull/38813
- update the example of an `expiration` in a share response to show the time `23:59:59` (the time is changed for core 10.8)
- add words in a couple of places to remind readers that shares expire at the end of the specified day (this is the existing behavior in all recent 10.* releases, but was not always clear)
> Shares expire at the end of the specified day

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
References: https://github.com/owncloud/docs/issues/3675 (New WND config key for Ldapmembership cache)
Adding descriptive text in the WND documentation in section troubleshooting.
Took the text from config.apps.sample (already merged)
This is part 2 of 2
No Backports
@JanAckermann @jvillafanez @cdamken fyi
> Update WND documentation for wnd.groupmembership.checkUserFirst

- modules/ROOT/pages/index.adoc
Entry for manual installation linked to quick installation guide, now it's pointing to the correct section.
> fixed reference to manual installation

- modules/developer_manual/examples/core/scripts/responses/shares/update-share-success.xml
Docs PR #3681 implemented the docs changes for issue #3680 
But the change in core PR https://github.com/owncloud/core/pull/38813 had to be reverted due to client problems - see core PR https://github.com/owncloud/core/pull/38856
This docs PR reverts the change to the expiration example.
The other changes in docs PR #3681 are correct. Shares do work during the day of their expiry, right up to and including 23:59:59. So the text explanations are correct. It is just that the technical share response has `00:00:00` in it.
No backports needed. (This change was only made to master, because it was planned for 10.8)
> Revert change to share expiration example

- modules/admin_manual/pages/installation/docker/index.adoc
So far we left users hanging after they started the docker evaluation. Now they can get rid of the eval version before they continue.
Backports to 10.7 and 10.6 needed.
> added proper eval guidance

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Fixes: https://github.com/owncloud/docs/issues/3689 (Missing period or other sentence separator)
Make the values more distinctable.
Adding a supportive website for oidc, same we have already in docs.
This is the `config-to-docs` run for: https://github.com/owncloud/core/pull/38864
> Make text for the http.cookie.samesite config value more clear

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
> [10.7] [PR 3708] Make text for the http.cookie.samesite config value more clear

- modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
- modules/user_manual/pages/files/webgui/sharing.adoc
Fixes #2759 
Note: On the admin sharing settings UI page these are called "remote" shares.
When an ordinary user shares on the webUI, the word "Federated" is shown as the share type.
So there is a mismatch between the way these are named fpr the admin and for the regular user. That is something outside the scope of this PR and issue. I have documented what currently shows on the UI of oC10 core, and raised core issue https://github.com/owncloud/core/issues/38871 to discuss.
This applies to a few recent oC10 versions, so backport to 10.6 and 10.7 is needed.
> Document expiration of outgoing remote shares

- modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
As the title says, small fixes setting attributes correctly.
> Small fixes setting attributes correctly

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Fixes #3128 
1) adjust some commas, minor crud
2) update some out-of-date information about skeleton files in tests
3) Fix test example for DEBUG_ACCEPTANCE_API_CALLS
4) Add docs for 'tries to' in acceptance tests
Backport not needed. This is intended to describe "real time" development against the latest branches of repos that have acceptance tests.
> Add docs for 'tries to' in acceptance tests 

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Fixes: https://github.com/owncloud/docs/issues/3724 (occ commands for HSM not documented)
Add missing occ commands identified in #3724 
**Note**
Not all possible commands in the issue will be documented as they are focused on development and testing. Will add them to the readme in encryption so they will not get lost.
Backporting to 10.6 and 10.7
> Add missing occ encryption commands

- modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
This document appears to be generally working.
But it has several smaller defects:
* sudo is used inconsistently
* occ is used inconsistently
* The TIP about analyzing the own PATH shows some misunderstandings.  Calling `./hsmdaemon install` actually creates a service file with the current PWD hardcoded. No path lookup is ever done during service invocation. It is safer to use the install subcommand with the binary that was placed in the final destination, e.g. `/usr/local/bin/hsmdaemon install`
* chmod 750 includes execute permission. This is useless for the toml file. use 640 instead.
As this manual is in the public, I miss some instruction how to actually obtain the hsmdaemon code. It is not opensource. Maybe ooint to the consulting team?
> hsmdaemon install consistency and accuracy

- modules/ROOT/pages/index.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
- modules/admin_manual/pages/installation/docker/index.adoc
Adding important piece of information on how to run occ commands with docker installations of ownCloud.
This fixes issue #3722.
Backports to 10.7 and 10.6 needed.
> occ usage with docker installations

- docs/best-practices.md
- modules/ROOT/pages/index.adoc
2 fixes:
- Update of the best practice guide with latest findings so they will not get forgotten
- Update of the landing page using a neutral link for manual installation and adding the info that the usful link section by default always points to the latest version
> Small fixes to the BPG and the landing page

- modules/developer_manual/pages/core/apis/ocs-share-api.adoc
The response actually contains a  string like "expiration":"2021-06-30 00:00:00"
Note: the share expires at the end of the specified date, even though the response has a 00:00:000 timestamp in it. That is mentioned elsewhere in documentation.
> Fix share expiration response description

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Recent changes in `config.sample.php` in core:
https://github.com/owncloud/core/pull/38917 (Added password option to redis cluster mode)
Fixes: https://github.com/owncloud/docs/issues/3756 (Run config-to-docs for redis.cluster password)
**Please merge only if the core PR has been merged.**
NO backport!
> Redis Cluster Password config.sample

- .drone.star
- site.yml
This PR is about providing and rolling out 10.8 for docs after the go of @micbar in chat.
Fixes: https://github.com/owncloud/docs/issues/3729 (Prepare branch 10.8)
> Configure master for 10.8

- modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Fixes: https://github.com/owncloud/docs/issues/3715 (Preview HEIC needs a minimum php-imagick release)
When using QNAP, we have to expect Apple users or users who are in the graphical business and will deal with image formats like HEIC or SVG where the preview provider is implemented in core but not available in the default shipped imagick version, see linked issue. This PR fixes this issue by providing a way how to install an updated version of imagick which supports the needed graphical formats.
Backports to 10.7 and 10.8
@jnweiger @wkloucek @xoxys fyi, may be a guideline for the default ownCloud docker container also used in QNAP.
> Update Imagick to v7 for enhanced preview provider support

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- modules/developer_manual/pages/app/tutorial/requirements.adoc
- site.yml
Fixes: https://github.com/owncloud/docs/issues/3767 (Update PHP min version to 7.2.5)
Core changed the minimum PHP version for ownCloud 10.8 from 7.2.0 to 7.2.5.
Backport to 10.8 necessary
> Update PHP min version to 7.2.5

- site.yml
This is a cleanup of site.yml removing unused variables and repos, for 10.7 only
No backport needed
master and 10.8 have their own PR for this
> Cleanup site.yml for 10.7 only

- modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
- modules/user_manual/pages/files/encrypting_files.adoc
Fixes: https://github.com/owncloud/docs/issues/3774 (Error reported in docs-pdf drone CI step)
At the moment, inter-module-references cant be done when creating a pdf - works well with html.
See the referenced issue for an explanation.
Backporting to 10.8
> User Manual Encryption, pdf fix file not found

- docs/new-version-branch.md
Updates the create new version documentation with a new item.
When creating a new version branch, QA needs to be informed to update internal redirects from `go.php`.
Backporting to 10.8 and 10.7
> Fix Internal Redirects

- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
References: https://github.com/owncloud/user_ldap/issues/643#issuecomment-871821783
Removes the reference to php 5.6 and ownCloud 5
The whole text needs a revision. This is just to fix these two issues and some minor texts that catched my eyes.
> Remove outdated text references in LDAP

- modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
Firebug link is more or less defunct, so we better point readers to the Mozilla and Chrome/Chromium dev tools.
Backports to 10.7 and 10.8 needed.
> Replaced outdated Firebug URL

- modules/admin_manual/pages/configuration/server/security/password_policy.adoc
It does not match to [cols="2,1,1",options="header"]
configuration. There are extra '|'.
> Fix broken table markup for password_policy extention

- modules/admin_manual/pages/configuration/server/security/password_policy.adoc
It does not match to [cols="2,1,1",options="header"]
configuration. There are extra '|'.
Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>
Backport #3803
> [10.8] Fix broken table markup for password_policy extention

- modules/admin_manual/pages/configuration/server/security/password_policy.adoc
It does not match to [cols="2,1,1",options="header"]
configuration. There are extra '|'.
Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>
Backport #3803
> [10.7] Fix broken table markup for password_policy extention

- modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
occ is redundant. {occ-command-example-prefix} includes occ.
> occ is redundant

- modules/admin_manual/pages/installation/docker/index.adoc
The troubleshooting section only has info about one raspberry corner case.
I'd like to address a much more prominent issue with docker, that was left undocumented so far: collect defunct elements in the admin UI.
> Add hints about loglevel

- modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
The referenced script has been updated on my request and is now a more streamelined installation. Before, the configuration directory was not been able to be defined in the script even the configure script of imagemagick was able to use it. Now, the config base directory of imagemagic7 is the same as with imagemagic6.
Backporting to 10.8 and 10.7 necessary
> Update the ImageMagick install documentation

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
`config-to-docs` run of: https://github.com/owncloud/core/pull/38975
Fixes: https://github.com/owncloud/docs/pull/3793 (add code snipplet rendering)
> Fixes a config sample typo

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Based on a discussion with @xoxys, this is a test if a `page_aliases` used in antora fixes a page miss due to a page rename.
**alias needed for** (valid in 10.6)
`admin_manual/configuration/files/external_storage_configuration_gui.html`
**to** (from 10.7 onwards)
`admin_manual/configuration/files/external_storage/configuration.html`
**This created a file locally**
`server/admin_manual/configuration/files/external_storage_configuration_gui.html`
with following content:
```
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="canonical" href="https://doc.owncloud.com/server/admin_manual/configuration/files/external_storage/configuration.html">
<script>location="external_storage/configuration.html"</script>
<meta http-equiv="refresh" content="0; url=external_storage/configuration.html">
<meta …
```
> Set page-aliases for external_storage_configuration_gui.adoc

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
The doc mixes APCu and Zend opcache in one entry. This is confusing.
This change clarifies that APCu is only a data cache and opcache is a opcode cache.
Note: Zend opcache is now part of PHP, so it's referred directly as opcache.
> Caching Doc: Create separate entry for opcache

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Fixes: https://github.com/owncloud/docs/issues/3820 (config-to-docs from release-10.8.0)
Added a text for the trashbin for the 10.8 release
Backport to 10.8 necessary
> config-to-docs from release-10.8.0

- docs/best-practices.md
Adds a new info to the Best Practice Guide in section tables.
> Add an item in the BPG at the table section

- modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
This PR :
* Reorders a sub-list block plus fixes the intent of the example command to the correponding first list item level. 
* The source of the page got improved to be better readable as there are many ordered list items where you can lose quickly the overview what belongs where.
No content change
> Formatting fix for the IM7 document - no content change

- modules/admin_manual/pages/installation/manual_installation/index.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
- modules/admin_manual/pages/installation/quick_guides/index.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
In the quick install guide for Ubuntu 20.4 the suggestion to install php-smbclient via ondrej ppa is now gone as decided by the product own in issue: #3450.
This PR also fixes issue  #3842 by prominently referencing the Server Hardening and Security Guidance in the Quick and the Detailed Installation Guides.
Language and clarity issues fixed.
> Removing ondrej ppa/adding refs to server hardening

- modules/admin_manual/pages/appliance/configuration/login_information.adoc
- modules/admin_manual/pages/configuration/server/occ_command.adoc
Adding information on how to use occ on the Appliance. This fixes issue #3590.
> How to use occ commands with the Appliance

- modules/admin_manual/pages/release_notes.adoc
This is a "known issue" that I expect effects all 10.* releases, because it is related to a combination of using `open_basedir` and PHP 7.4.21 that "brings out" a code issue that has been present all along.
Do we paste it into the "known issues" section of every release notes section?
> Add issue 39034 about PHP 7.4.21 and open_basedir to known issues

- docs/new-version-branch.md
This fixes the current text with the newly implemented automatical process - see text.
@xoxys fyi
> Update new version branch when and how latest is set

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
Fixes: https://github.com/owncloud/docs/issues/3594#issuecomment-870439190
There was no reason stated when the command is needed - fixed:
@IljaN fyi
> Add reason when to use occ encryption:fix-encrypted-version

- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Based on a user chat in talk, I identified that the necessary occ setup link for Collabora was missing in the Collabora documentation. This is now fixed.
@micbar fyi
> Fix missing occ link how to setup Collabora

- modules/developer_manual/pages/testing/acceptance-tests.adoc
Fixes #3881 
This is a new acceptance test feature added to core after 10.8. No backport needed.
> Docs for API  acceptance test SEND_SCENARIO_LINE_REFERENCES

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Leftover from #3858 (Removing ondrej ppa/adding refs to server hardening)
Thanks to @JanAckermann 
> Fix QuickGuide php no installation candidate

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.8] [PR 3887] Fix QuickGuide php no installation candidate

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.7] [PR 3887] Fix QuickGuide php no installation candidate

- modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
This fixes issue #3711.
Backport to 10.7 and 10.8 needed.
> Clarified how to find and enable a SUSE security repo

- modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
Changed the example to the current version of SUSE Leap.
> SUSE security example upgraded to 15.3

- modules/developer_manual/examples/scripts/backport.sh
This PR fixes the issue in the backporting script when you use a message like:
`fix for #1234` which confuses the scripts flow as it thinks it should reference 1234 instead of the queried real PR number.
Beside that, some improvements are made to ease handling:
* adding more descriptive comments and error messages
* changed the way how variables are used
* remove new-line characters in the pullTitle variable
* check if the target branch exists in remote respectively in local with proper messages to explain. This was annoying when you accidentially mistyped your target branch
* check if the source branch is clean (has no uncomitted changes)
* check if a commit of the source branch is already present in the target branch
Note: you can now run all commands used manually on the command shell …
> Fixes and improvments for the backporting script

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
OIDC App release 2.1.0 requires this changes, see status here: https://github.com/owncloud/openidconnect/issues/168
> Add database as storage backend for settings

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
Small change to tell that occ config:app:get|set|delete are handled via the database.
> State that occ config:app is handled via the database

- modules/developer_manual/examples/scripts/backport.sh
After a lot of testing (kudos to @EParzefall), we identified how to proper remove the need for perl in the backport script and replace it with bash commands. Not knowing why, but the use of perl caused issues - this is now eliminated.
> Remove the need for perl from the backport script

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc
References: https://github.com/owncloud/docs/issues/3921 (Richdocuments/Collabora open in same tab)
References: https://github.com/owncloud/richdocuments/pull/329 (A global config switch to (not) open in a new tab) (March 2020...)
An occ command has been implemented but forgotten to be added to the documentation.
@cdamken
> Richdocuments: occ - Open documents in a new tab

- modules/ROOT/pages/index.adoc
- site.yml
Move a adoc variable located in a page to site.yml for better maintainability.
> Move a adoc varaible from a page to site.yml

- modules/admin_manual/pages/installation/docker/index.adoc
Added the missing docker-compose exec owncloud occ maintenance:mode --off.
Backports to 10.7 and 10.8 needed.
> Docker upgrade missed end of maintenance step

- modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
References: https://github.com/owncloud/docs/issues/3861
Add text about the default NFS mount options if not explicit set differently.
> Describe which mount options are default for NFS

- modules/admin_manual/pages/configuration/user/guests_app.adoc
Fixes: https://github.com/owncloud/docs/issues/3649
(Documentation for Guests App shows a video with an outdated process for user provisioning)
After a discussion with @jamu85 I fixed the issue and did a mini overall improvement of the document.
> Fix guest app document

- modules/admin_manual/nav.adoc
- modules/admin_manual/pages/troubleshooting/path_filename_length.adoc
Fixes: https://github.com/owncloud/docs/issues/3945 (Maximum file name and path name lengths)
This was undocumented before.
I do not know if we should add this to the user docs too, maybe too technical.
> Document Path and Filename Length Limitations

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
Add a note to enter proper storage config as config changes create a new storage ID making existing database entries orphans increasing overhead. Manual deletion is necessary.
> Add warning around removal of external storage configuration

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
Fixes: https://github.com/owncloud/core/issues/39119 (Security information regarding redis)
Based on the request, we need to document that ownCloud currently does not support Redis ACL´s which was introduced with Redis v6
@JammingBen FYI
> ownCloud does currently not support Redis ACL´s

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.8] [PR 3966] ownCloud does currently not support Redis ACL´s

- modules/admin_manual/pages/configuration/server/caching_configuration.adoc
> [10.7] [PR 3966] ownCloud does currently not support Redis ACL´s

- modules/admin_manual/pages/installation/installation_wizard.adoc
Emphasized the already present recommendation to not keep the data directory in the web root. This fixes issue #2729.
Backports to 10.8 and 10.7 necessary.
> recommendation to not locate the data directory in the webroot

- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/language_configuration.adoc
- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
This PR weeds out last instances of "he" as pronoun for our users. Replaced with proper plural. 
> gender neutral language

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Updates the Ubuntu 20.04 server preperation document to use the latest stable pear release.
Backport to 10.7 and 10.8 necessary
> Use the latest stable PEAR release

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/pages/installation/manual_installation/upgrade_install_phpmyadmin.adoc
I am about to do the docs changes for "Drop PHP 7.2". Before doing that, these are some minor changes that will be best to get committed first.
> Fix a few small typos in manual installation docs

- modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- site.yml
core PR https://github.com/owncloud/core/pull/38697 dropped support for PHP 7.2 in ownCloud core. That will be released in core 10.9.0. ownCloud 10.9.0 will only support PHP 7.3 and PHP 7.4.
Issue https://github.com/owncloud/core/issues/39134
This PR updates the docs to change the appropriate references from PHP 7.2 to PHP 7.3. 
No backport needed.
> Drop PHP 7.2

- modules/ROOT/pages/releases.adoc
> Fix pdf link for 8.2 admin manual

- modules/ROOT/pages/releases.adoc
The link to the pdf files for desktop needed a correction.
> Fix pdf link for desktop

- docs/new-version-branch.md
Some text fixes
Backport #4022 
Note: when backporting there were conflicts reported. I chose the newer instructions that come from `master`. Maybe there was some other backport that missed that out? Please check when reviewing if the changes all look correct.
> [10.7] Minor fixes to the create version branch steps

- site.yml
Referencing: https://github.com/owncloud/docs-client-desktop/pull/103 (Changes necessary for the 2.9 branch)
This PR sets the desktop branch to 2.9
No changes necessary in the releases.adoc file because of using:
`latest-desktop-version` and `previous-desktop-version`
Backporting to 10.8 and 10.7
> Set desktop to 2.9

- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
Cannot work with backticks this was illegal shell syntax.
As a general rule, backticks should never appear anywhere in shell scripts. When command interpolation is actually intended, `$()` should be used instead of backticks.
Backports optional.
> backtick removed from wnd examples.

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Referencing: #4036 (config-to-docs run for skeletondirectory change)
NO backport as this is for the upcoming 10.9 release
> Config To Docs run for recent changes

- modules/developer_manual/pages/testing/acceptance-tests.adoc
core PR https://github.com/owncloud/core/pull/39253 added a new tag to the acceptance test system for tagging scenarios to skip scenarios on versions of ownCloud10.
This adds the information to the docs.
> Document skipOnAllVersionsGreaterThanOcV10.8.0 test tag

- modules/admin_manual/pages/configuration/integration/ms-teams.adoc
- Replaced references to the generator app for Admins with the "raw" generator url, to enable users to integrate ownCloud into MS Teams right now.
**Context:** The app submission of the generator app for Admins to the MS Teams App Store is still delayed. Meanwhile we don't want to prevent users from integrating ownCloud into MS Teams, because this is actually possible without the official generator app for Admins. It can be directly done via https://msteamsgen.owncloud.com/. (the generator app for Admins actually just encapsulates the generator on https://msteamsgen.owncloud.com/ )
> replaced references of the generator app with the generator URL directly

- modules/ROOT/pages/releases.adoc
- site.yml
This PR enables the new `docs-client-ios-app` as base for the iOS documentation.
That repo has been prepared including a master (next) branch and the currently stable branch 11.7
Builds for html and pdf including master and 11.7 run fine.
If there is a new iOS version coming, we can proceed as usual in the `docs-client-ios-app`, only an adoption of `site.yml` and the `release.adoc` file in this repo is necessary (plus backports).
The `previous-ios-version` attribute has been added in advance, but is currently unused until a new ios version will be published.
Dependency: https://github.com/owncloud/docs-client-ios-app/issues/2 (Enable CI)
Note that there is (most likely) a manual intervention necessary to tag `latest` for iOS to 11.7 in gitea
Backports to 10.8 and 10.7
@EParzefall …
> Use the new docs ios repo

- .drone.star
- bin/optimize_crawl
Refernces: https://github.com/owncloud/docs/issues/4044 (Fix sitemap(s).xml and robots.txt)
This PR adds a pure bash script which can be run locally for testing or is triggered via CI post building the docs but before copying to the web.
This scrip transforms the robots and sitemap files which are built automatically from scratch on each merge with following rules (see examples below):
**robots.txt**
* Keep a safe copy of the original file
* Add at the end a list of disallows of sub pages not to be crawled (everything except "product/next")
These lines are generated automatically, no need of manual intervention !
**sitemap-xxx.xml**
* Keep a safe copy of the original file
* Remove all nodes which do not have url/product/next/ at the beginning.
Nodes of this type start/end with `<url> …
> Improve robots and sitemap files automatically post building the docs

- modules/ROOT/pages/releases.adoc
This PR just adds a missing text line for a common looka and feel at the releases file.
> Add missing text line in releases file

- modules/ROOT/pages/releases.adoc
- site.yml
Referencing https://github.com/owncloud/docs-client-ios-app/pull/8
Updates the needed docs files to have the new release available.
> New iOS App release

- modules/ROOT/pages/releases.adoc
Referencing: #4066 (New iOS App release)
Use the correct release variable
> Mini fix for using the correct release variable in releases file

- modules/ROOT/pages/releases.adoc
- site.yml
Due to a recent decision, we only use major and minor but not patch releases.
This PR takes back a minor iOS release.
Backports to 10.7 and 10.8
> Takes back a minor iOS release

- modules/admin_manual/pages/installation/system_requirements.adoc
Related to issue https://github.com/owncloud/core/issues/39283
MariaDb 10.6 stable was recently released. There seem to be some different settings that are needed (see the issue).
For now, we could adjust the docs so that the actual supported MariaDb minor versions are mentioned.
https://downloads.mariadb.org/mariadb/+releases/ - patch releases are coming out regularly for 10.2 10.3 10.4 10.5 - so that is why I put those in the list. And full CI passes with each of those versions.
> Specify minor versions of MariaDb that are supported

- modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Reference: #4078 
Fixes a small issue with a missing comma which, if the example is copy and pasted, will cause ownCloud to crash until the issue is tracked down and fixed.
Needs backported to 10.8 and 10.7.
> Fix syntax error in preview provider example.

- modules/ROOT/pages/releases.adoc
- site.yml
This PR enables the new `docs-client-android` as base for the Android documentation.
That repo has been prepared including a master (next) branch and the currently stable branch 2.18
Builds for html and pdf including master and 2.18 run fine.
If there is a new Android major/minor version coming, we can proceed as usual in the `docs-client-android` repo, only an adoption of `site.yml` and the `release.adoc` file in **this** repo is necessary (plus backports).
The `previous-android-version` attribute has been added in advance, but is currently unused until a new android version will be published.
Needs checking at gitea regarding getting the proper version number tag from the android repo.
Backports to 10.8 and 10.7
@EParzefall @phil-davis fyi
> Make the new docs-Android branch available for docs

- bin/optimize_crawl
As the title says, this change is necessary to add `android` to the `optimize_crawl` script as we recently added the new `docs-client-android` repo.
Tested locally, the changes have the correct script outcome.
> Add android to optimize_crawl script

- modules/admin_manual/pages/qnap/index.adoc
Added a link to the QNAP support page on how to add ssl certificates.
Backport to 10.8 needed.
> referencing ssl article for qnap

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
The already existing page alias in oidc.adoc had a typo `index.html` --> `index.adoc`
Backport to 10.8
> Fix typo in page-alias for oidc.adoc

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
> [10.8] [PR 4105] Fix typo in page-alias for oidc.adoc

- modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
The page alias attribute itself at oidc.adoc had a typo and the path set was incorrect.
Backport to 10.8
> Another page aliases typo fixed

- modules/user_manual/nav.adoc
- modules/user_manual/pages/whats_new.adoc
Outdated section with little content needs to go.
This fixes issue #4046 
Backport to 10.8 and 10.7.
> Removing What's New section

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
This fixes issue #4016, limiting encryption key placement to folders within the data directory.
Backports to 10.7 and 10.8 necessary.
> encryption key movement within data only

- modules/admin_manual/pages/configuration/search/index.adoc
While fixing the link to the occ commands for the full text search I also adjusted the text somewhat in preparation for version 2.0.0 of the app.
This fixes issue #3547
Backports to 10.8 and 10.7
> correct link to occ search commands 

- modules/admin_manual/pages/configuration/server/occ_command.adoc
Richdocuments was accidentially added in the occ commands at 10.7 with the last backport.
This is now fixed. In addition, the list of page-aliases is now not one single big line but line by line for better readability. This is based on the input
https://antora.zulipchat.com/#narrow/stream/282400-users/topic/Feature.20Request.20.3Apage-aliases.3A
Will do this for occ for master and 10.8 too.
No backport, 10.7 only
> Fix accidentially added occ richdocuments at 10.7

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
Minor text fix because it are already six commands and not five - making it neutral.
> Minor text fix in occ files commands document

- modules/admin_manual/pages/configuration/files/encryption/index.adoc
The page alias attribute had a typo and the path was incomplete - fixed.
Checked the modules directory with `grep -rn page_alias`
> Fix page alias for encryption

- modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
References: https://github.com/owncloud/admin_audit/pull/392 (Update info.xml)
This is the short term fix for the above reference.
Note, the page alias attribute had a typo and the path was incomplete - fixed.
Backport to 10.8
@ChrisEdS @pmaier1 fyi
> Fix page alias for admin audit

- modules/user_manual/pages/_partials/nav.adoc
A component entry was accidentially double present - fixed
> Fix one item double component entry in user manual nav

- .gitignore
- modules/ROOT/pages/client_releases.adoc
- modules/ROOT/pages/server_release_notes.adoc
- modules/ROOT/pages/server_releases.adoc
- modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/admin_manual/pages/installation/troubleshooting.adoc
- modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc
- modules/developer_manual/pages/app/fundamentals/hooks.adoc
- modules/developer_manual/pages/app/tutorial/database_connectivity.adoc
- modules/developer_manual/pages/app/tutorial/request.adoc
- modules/developer_manual/pages/general/_devenv_docker.adoc
- modules/developer_manual/pages/general/devenv.adoc
- modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
- modules/developer_manual/pages/testing/test-pilots.adoc
- modules/developer_manual/pages/testing/ui-testing.adoc
- modules/developer_manual/pages/webdav_api/files_versions.adoc
- modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
This is the first part fixing broken anchors...
Backport to 10.8 and 10.7 (needs removal of 10.8 references in the server release notes)
> Part one fixing broken anchors (in- and inter-document references)

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
Referencing #4233 (Remove the page-noindex attribute for occ files (no longer necessary))
This is for _richdocuments.adoc only.
Backport to 10.8 only !
> Remove the page-noindex attribute for _richdocuments.adoc

- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
This is part five fixing broken anchors...
This is, according the tests, at the moment the last PR of the big block fixing broken anchors.
No backport, for 10.7 only
> Part five fixing broken anchors (in- and inter-document references)

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Fixes: https://github.com/owncloud/docs/issues/4242 (Added user:list option: show-all-attributes)
No backport, master only
> Add new user:list option

- modules/ROOT/pages/server_release_notes.adoc
This PR fixes that a link in the server release notes point to a protected repo. It exchanges the original link with the link to the public core PR.
Note that this is the only link for that case I have identified to be fixed.
Backport to 10.8 only
@pmaier1 fyi
> Exchange the enterprise repo link with the corresponding core PR link

- modules/ROOT/pages/client_releases.adoc
- modules/ROOT/pages/server_release_notes.adoc
- modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
- modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
- modules/admin_manual/pages/configuration/server/harden_server.adoc
- modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
- modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc
- modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/admin_manual/pages/installation/deployment_recommendations.adoc
- modules/developer_manual/pages/app/fundamentals/database.adoc
- modules/developer_manual/pages/app/fundamentals/info.adoc
- modules/developer_manual/pages/bugtracker/triaging.adoc
- modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
- modules/user_manual/pages/_partials/direct_file_access_tip.adoc
- modules/user_manual/pages/files/access_webdav.adoc
- modules/user_manual/pages/pim/sync_thunderbird.adoc
This PR fixes (hopefully all) external links returning a 404. This also includes example domains which are now printed but not presented as link. Depending on the checker, there maybe more to be found.
Note that dead links which do not have a replacement URL have been removed.
Some Microsoft URL´s which have been redirected are now corrected.
Texts have been adopted if needed in case a URL has changed or been removed.
> Fixing external links returning 404

- modules/ROOT/pages/client_releases.adoc
- modules/developer_manual/pages/app/fundamentals/info.adoc
- modules/developer_manual/pages/bugtracker/triaging.adoc
Continuing of #4247 (Fixing external links returning 404)
More linkes found returning a 404 or making problems.
Had a typo for the android pdf documentation 🤦‍♂️
found more links needed a in depth analysis to fix.
The remaining 404's reported are false positives.
`htmltest` also reports a lot of 503 pointing to https://www.php.net, but we can ignore them as the links work (all corrected and harmonized in part two).
Some links need to be checked in config-sample but this is made in core and there is no hurry for fixing it due to 10.9 code freeze.
Seems that we are more or less done post backporting 😅 
> Fixing external links returning 404 (part three)

- modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
- modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Refernces: https://github.com/owncloud/core/pull/39488 (Fix some broken links in config.sample)
> Config to docs run from recent changes in core

- modules/ROOT/pages/server_release_notes.adoc
- modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc
- modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc
- modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
- modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
- modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
- modules/admin_manual/pages/index.adoc
- modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc
- modules/admin_manual/pages/maintenance/manual_upgrade.adoc
- modules/developer_manual/pages/app/fundamentals/controllers.adoc
- modules/developer_manual/pages/app/fundamentals/logging.adoc
- modules/developer_manual/pages/bugtracker/index.adoc
- modules/developer_manual/pages/bugtracker/triaging.adoc
- modules/developer_manual/pages/general/debugging.adoc
- modules/developer_manual/pages/general/security.adoc
- modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
- modules/developer_manual/pages/testing/acceptance-tests.adoc
- modules/developer_manual/pages/testing/ui-testing.adoc
- modules/user_manual/pages/files/webgui/navigating.adoc
- modules/user_manual/pages/pim/sync_thunderbird.adoc
Using a different link checker, you get reports about borken *external* anchors and redirect issues. This PR fixes them.
> Fix redirect issues and external anchors

- modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Seems the {oc-marketplace-url} does not have the trailing /apps/ path component. 
Without that, we get 404 errors.
@mmattel should the /apps/ be inside {oc-marketplace-url} or appended, as per this PR?
See https://doc.owncloud.com/server/next/admin_manual/configuration/files/external_storage/s3_compatible_object_storage_as_primary.html
backports to 10.9  please (at least) :-)
> s3_compatible_object_storage_as_primary.adoc use marketplace with /apps/

- modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc
The `kopano` attributes had a missing url component. The variables did not resolve properly when building.
No backport, for 10.7 only !
> Fix konnect attributes (for 10.7 only)

- site.yml
New Android version available.
Branches have been added in
https://github.com/owncloud/docs-client-android/pull/15 (New Android version) and 
https://github.com/owncloud/docs-client-android/pull/18 (antora.yml fix for 2.19)
> New Android version

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Referencing: https://github.com/owncloud/docs/issues/4242 (Added user:list option: show-all-attributes)
* `show-all-attributes` had missing double dashes and missed the short form -s
* some additional table fixes
No backport
> Fix user:list command

- modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
This PR is necessary and part of a new occ command to move the users home.
Needed to clarify that the LDAP Home Connector has nothing to do with the `users:move` command, see https://github.com/owncloud/docs/issues/4252 (New command to move a user's home folder - occ user:move-home)
@pmaier1 fyi
> Revise LDAP Home Connector

- docs/new-version-branch.md
This PR corrects the server release notes file in the new version branch description.
Backport to 10.9 if already available, 10.8 and 10.7 if still available.
> correct name of the server release file

- modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Fixes: https://github.com/owncloud/docs/issues/4307 (go.php?to=admin-encryption is a 404)
Add a page alias
> Add page alias for encryption_configuration

- modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
- modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
Superseds: https://github.com/owncloud/docs/pull/4305 (Update s3_compatible_object_storage_as_primary.adoc)
* Make the encryption part more clear
* Adding serversideencryption for Ceph (was missing)
* Text Improvements
@jnweiger fyi
> Improve S3 primary

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Prerequisite to document occ `user:move`
The current page was a mess and needed a cleanup before adding the new command.
> Fix occ user commands

- modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
This is part one implementing MariaDB 10.6.
* To avoid when users read an older version of ownCloud (10.8 and 10.7), text has been added to highlight the need for oC 10.9 for **existing** installations when intending to upgrade to MariaDB 10.6.
* Text improvments
* Text fixes
Referencing: https://github.com/owncloud/docs/issues/4115 (MariaDb 10.6)
Having this (and backported) I can then make a description how to go for MariaDB 10.6 which needs a new upgrading document which will not go inot 10.8 or lower.
> Update MariaDB guide

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
Fixes #4335 (Empty system- and app config keys cannot be set)
Backport to 10.9 only - this is a minor fix that is coming in 10.9.
I am happy to take suggestions for the words to say here. Or even do we need to document this? It seems that it is something that "nobody" would want to try anyway???
> Empty system and app config keys cannot be set

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc
> [10.9] [PR 4354] Empty system and app config keys cannot be set

- modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Small text fix.
Improves the manual upgrade documentation with regards to the webserver management.
Based on an comment in #4360
> Improve webserver text in manual upgrade

- modules/admin_manual/pages/_partials/nav.adoc
- modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
This is part five implementing MariaDB 10.6.
* New upgrade guide for MariaDB 10.6
Fixes: #4115 (MariaDb 10.6)
> Upgrade guide for MariaDB 10.6

- modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
- modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
This is part three implementing MariaDB 10.6.
* Backup and restore got a big revision which is necessary when intending to upgrade to MariaDB 10.6.
* Recover encrypted files is moved from backup to restore
* Text improvments
* Text fixes
Referencing: #4115 (MariaDb 10.6)
> Fix Backup and Restore

- modules/admin_manual/pages/installation/system_requirements.adoc
References: https://github.com/owncloud/docs/issues/4115 (MariaDb 10.6)
Addon to the system requirement document with regards to MariaDB 10.6
**Backport to**
* 10.9 (ok) and
* 10.8 and 10.7
if the links to the database upgrade doc only available in 10.9 are removed before committing
> Add MariaDB 10.6 to system requirements

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
Before adding https://github.com/owncloud/docs/issues/4352 (New option local for dav:cleanup-chunks command), the dav document needs a revision.
> Cleanup of occ dav commands

- modules/admin_manual/pages/installation/docker/index.adoc
Fixes a typo in the documentation that would prevent the user from ever being able to set a default admin username / password.
> [10.8] Fix Admin Username / Password Typo

- modules/admin_manual/pages/configuration/user/user_management.adoc
A typo was introduced in #4361 which needs a fix.
PDF creation created a warning, for details also see https://github.com/owncloud/docs/pull/4382 (Revision of email settings documentation)
> Fix pdf unordered list warning

- modules/admin_manual/pages/_partials/nav.adoc
- modules/admin_manual/pages/configuration/server/security/oauth2.adoc
- modules/admin_manual/pages/configuration/user/user_oauth2.adoc
Added a warning not to attempt a login with a disabled user, added link to OAuth occ commands and a short section in the user part.
This fixes #4336 
Backports to 10.7, 10.8 and 10.9 necessary.
> Warning not to use disabled user with OAuth2, plus user section.

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_activity_commands.adoc
Fixes: https://github.com/owncloud/docs/issues/4392 (Activity rename- and move actions)
New occ commands for the activity app.
Because the change is app version and not core dependent, we can backport.
> New occ Activity commands

- modules/admin_manual/pages/configuration/server/email_configuration.adoc
Fix a typo in the email documentation.
Backport to10.9
> Fix email typo

- modules/user_manual/pages/files/version_control.adoc
- modules/user_manual/pages/files/webgui/navigating.adoc
When preparing for an upcoming PR, these fixes catched my eyes.
Language check welcomed (shown because of removing unnecessary line breakes)
> Small fixes in user doc

- modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
Not sure why it says that you'd need 2FA for the API. This is nonsense. Removing it.
> remove hint about 2FA in notifications API dev doc

- modules/developer_manual/pages/app/fundamentals/js.adoc
fixes https://github.com/owncloud/docs/issues/4439
The last sentence `In case multiple actions have been set as default for one mime type, ownCloud will show a context menu when clicking on the file.` goes for oC 10.9.0 only. The rest needs a backport.
> Add guide for registering file actions in JavaScript

- modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
> [10.9] [PR 4445] remove hint about 2FA in notifications API dev doc

- modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
> [10.8] [PR 4445] remove hint about 2FA in notifications API dev doc

- modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc
> [10.7] [PR 4445] remove hint about 2FA in notifications API dev doc

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Fixes: https://github.com/owncloud/docs/issues/4438 (user:move-home is only implemented for posix file systems)
Addnote that user:move is only implemented for posix file systems.
Backport to 10.9
> Add note for user:move occ command

- modules/ROOT/pages/client_releases.adoc
- site.yml
These are the changes necessary for the iOS 11.8 branch.
Note it is necessary to have https://github.com/owncloud/docs-client-ios-app/pull/21 (changes necessary for 11.8) merged first !
@hosy @michaelstingl @michl19  @xoxys fyi
> Changes necessary for the iOS 11.8 branch

- modules/ROOT/pages/client_releases.adoc
References: https://github.com/owncloud/docs/pull/4464
The change was not complete, needed to fix the attribute used
Backport to 10.9 only (correct in 10.8 and 10.7)
> Fixing the ios-app client attribute

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Fixes: #4479 (Detailed installation guide installs less than quick install guide (e.g. rsync is missing))
Adding `rsync` to the items to be installed
> Add rsync to the manuall install prerequisites

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
Fixes: #4481 (Temporary directories with occ user:move)
Add a note to not use temp directory tragets for the `user:move` command..
> Do not use temp directory targets for user:move

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
> [10.9] [PR 4483] Do not use temp directory targets for user:move

- modules/developer_manual/pages/core/apis/provisioning-api.adoc
Fixes #4490 (Explain the field values returned by the provisioning API)
Note: the actual `last_login` response field was added to the docs by #4202 
@mmattel  didn't find anywhere that we already describe response fields. So I couldn't copy an existing format. I am happy for you change the format to whatever you think is best. I just used a bullet-point list.
> Explain quota and last_login fields of Get User API response

- modules/developer_manual/pages/core/apis/provisioning-api.adoc
Backport of #4495
Last Login removed as this is 10.9 only
> [10.8] [PR 4495] Explain quota and last_login fields of Get User API response

- modules/developer_manual/pages/core/apis/provisioning-api.adoc
Backport of #4495
Last Login removed as this is 10.9 only
> [10.7] [PR 4495] Explain quota and last_login fields of Get User API response

- antora.yml
- site.yml
Related to: https://github.com/owncloud/docs/issues/4011 (PHP versions in published 10.8 docs are not correct)
This is the first of two PR's fixing the above issue.
It moves some global attributes from `site.yml` to `antora.yml` which is branch specific. This changes nothing from the desired output, but makes it possible to change the values in the particular branch in `antora.yml` accordingly post merging this PR.
Note, this PR **MUST** be backported to 10.9, 10.8 and 10.7.
There will be build warnings which are related to all branches but master as the attributes are now missing in (global) `site.yml`. Fixes itself when all backports have been made.
I made a dummy attribute in site.yml to remember where to look for branch specific attributes. No harm, can be removed at any time.
Tested …
> Move branch specific attributes from global site.yml to branch relevant antora.yml

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
- modules/admin_manual/pages/configuration/user/user_management.adoc
Fixes: https://github.com/owncloud/docs/issues/4492 (New occ commands extending user:move these are user:home:list-dir and user:home:list-users <path>)
* Add two new occ `user:home` commands
* Extend the `user:move` description in user management
> Document occ user:home

- antora.yml
Fixes: https://github.com/owncloud/docs/issues/4011 (PHP versions in published 10.8 docs are not correct)
This PR corrects php values for 10.8 only
NO BACKPORT
> Correct php values for 10.8 only

- antora.yml
Fixes: https://github.com/owncloud/docs/issues/4011 (PHP versions in published 10.8 docs are not correct)
This PR corrects php values for 10.7 only
NO BACKPORT
> Correct php values for 10.7 only

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc
- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Fixes #2513 
There are Ubuntu install docs in `manual_installation` and `quick_guides`. They have different subsets of PHP extensions listed. (I was hoping that the quick guide would just be a subset of those in the "full" installation)
I have added ones that I think are obviously missing from one or other, to get the lists more in sync. Maybe some are auto-installed anyway, and that is why this has not been a problem? But it seems good to have both lists as similar as reasonable.
The differences are now:
Extra in the quick guides: `php-apcu php-libsmbclient php-smbclient` (the quick guides have separate instructions for the smb stuff)
Extra in the manual installation guides: `php-igbinary php-gmp php-bcmath php-bz2` (I am not sure why these are not needed/useful to have for "quick …
> Add PHP extensions to various docs

- modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
While on the most locations the `user:move-home` command was written correctly, it was not on all - fixed.
> Small typo-fix for occ user:move-home

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
some guides have the current complete timestamp. Should this auto-update via variable?
IMO this is what @jnweiger is intending to do in PR #39608
Backport to 10.9
> Use the current complete tarball to install 10.9.0

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
PR #4515 (Add PHP extensions to various docs) has accidentially introduced adding the `php-gettext` extension to Ubuntu 20.04. This extension is not longer available starting with this release, functionality is already included in PHP7.4
Only the quick install guide is affected
@GeraldLeikam fyi
> Remove php-gettext from Ubuntu 20.04 quick install guide

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.9] [PR 4528] Remove php-gettext from Ubuntu 20.04 quick install guide

- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
> [10.8] [PR 4528] Remove php-gettext from Ubuntu 20.04 quick install guide

- modules/user_manual/pages/_partials/nav.adoc
Readding the search document in the user guide.
> Fix orphaned search in user docs

- modules/ROOT/pages/server_release_notes.adoc
Add an entry in the known issues section of the 10.9 release notes regarding marketplace not working (and a link how to solve it)
> Known Issue: Marketplace not working after upgrade from 10.8 to 10.9

- docs/best-practices.md
- docs/build-the-docs.md
- modules/developer_manual/pages/bugtracker/triaging.adoc
By chance looking into the detailed CI result regarding the pdf build (green!), I encountered an issue:
```
asciidoctor: ERROR: failed to parse formatted text: ​<a href="https://github.com/issues?q=is%3Aissue+user%3Aowncloud+is%3Aopen+label%3A"Needs+info"+sort%3Acreated-asc">Bugs which need info</a>
```
This is because the url contains double quotes which cant be rendered (but used...)
The fix is to utf8-encode the double quotes and manually replace them with %22.
This PR further adds a description about this process and fixes/adds some texts in the repo documentation.
> Fix a pdf build issue

- modules/ROOT/pages/server_release_notes.adoc
This is just a minor improvement for the known-issues section for 10.9 - itemize the two issues.
**Before**
marketplace...
encryption...
**After**
* marketplace...
* encryption...
> Itemize the known issues section for 10.9

- modules/ROOT/pages/server_release_notes.adoc
- modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
- modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
- modules/admin_manual/pages/configuration/integration/ms-teams.adoc
- modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
- modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
- modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
- modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
- modules/developer_manual/pages/commun/help_and_communication.adoc
- modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
- site.yml
Changes in global attributes used/new attributes created.
* Some url specific attributes used in site.yml did not have a unified naming convention.
* Introduction of a new global attribute for the ownCloud complete bundle.
This makes it easier to update a new oC version name at places where used.
Note for 10.8, this needs a manual fix to exclude 10.9 stuff (eg. at the release notes ect)
Note, there will be build warnings (but not errors) which will go away after backporting. Therefore backporting must be done immediately after merging!
> Global Attribute Cleanup

- modules/admin_manual/pages/installation/docker/index.adoc
Variable names have been changed, this causes errors / warnings doing the setup. 
You will get the following warnings:
WARNING: The ADMIN_USERNAME variable is not set. Defaulting to a blank string.
WARNING: The ADMIN_PASSWORD variable is not set. Defaulting to a blank string.
Those 2 Variables are being set to be the values of other variables in the yaml file.
If you remove / rename them - the variables aren't being set.
> revert #4381

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
ImageMagick is needed by 2FA and more, so I added it to the prerequisites.
Backports to 10.9 and 10.8 necessary.
> added imagemagick among the common prerequisites

- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
This fixes issue #4427 and more. Secure view is now only capitalized in headlines since it's a feature not a product.
Backports to 10.9 and 10.8.
> Lower case in secure view

- modules/ROOT/pages/client_releases.adoc
Missed to fix the access ink to the branded client documentation.
pdf works (was fixed before).
> fix branded clients access link

- modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
A bigger revision of the `big file upload` documentation.
> Update and fix big file upload

- modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
- modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
Add page-aliases for removed U18.04 documents to avoid a 404 if someone linked it.
> Add page-aliases for removed U18.04 documents

- modules/ROOT/pages/server_release_notes.adoc
- modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
- modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
- modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc
- modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
- site.yml
site.yml now also contains the installation site so we only need to touch one file if the link changes in the future.
Backports to 10.9 and 10.8 necessary.
> added link to installation repos

- README.md
- docs/antora-site-structure.md
Our docs/Antora site structure has not been documented before.
Nobody would know how things are glued together if not a deep insider.
This PR fixes this issue and gives an overview about the structure and setup
> Add Antora Site Structure Description for Docs

- .drone.star
- docs/build-the-docs.md
Updates the used `nodejs` version from v14 to v16
Note that v14 is already in maintenance mode while v16 is the actual active version, see https://nodejs.org/en/about/releases/
`docs-ui` has recently been upgraded to v16, so this step is to harmonize the environment, Antora also recommends nodejs v16
`nodejs:16` has been tested locally by:
```
nvm ls-remote | grep "Latest LTS"
...
v14.18.3   (Latest LTS: Fermium)
v16.13.2   (Latest LTS: Gallium)
...
nvm install 16.13.2
...
Now using node v16.13.2 (npm v8.1.2)
yarn antora-local
yarn serve
nvm alias default 16.13.2
default -> 16.13.2 (-> v16.13.2)
```
No html or pdf build or other errors are thrown, the content looks good
> Update nodejs to v16 (lts)

- .drone.star
> fix: fix elastic env vars in drone config

- site.yml
This PR is a prerequisite necessary for docs-ui to automatically add the correct opengraph images to each documentation, see issue https://github.com/owncloud/docs-ui/issues/396
Note that this PR and the backports must be merged before the docs-ui PR gets merged.
Note that the separator of the items in teh attribute can be a blank or a comma with a blank.
For better readability, comma with blank has been chosen.
> Add attribute necessary for embedding opengraph images in docs-ui automatically

- antora.yml
References: #4647
This is the 10.9 part of the antora.yml fix
No backport !
> 10.9 antora.yml attribute fix refs 4647

- docs/antora-site-structure.md
- site.yml
I seems that there is a "bug" in antora when it comes to attributes in a special case which can be solved easily.
Accidentally looking into https://doc.owncloud.com/server/next/client_releases.html to check if the updated desktop versions are shown, I saw that the value of `latest-desktop-version: 2.10` was not rendered as `2.10` but `2.1`. Even not explicit mandatory as stated in the antora documentation (https://docs.antora.org/antora/latest/page/define-and-modify-attributes/) I remember that it was _adviced_ to set values in single quotes. As this issue was never seen before, we did not put notice on that...
When doing tests, it turned out that using single quotes solved the issue. Therefore I added singe quotes at all attributes in site.yml. Because they are global, we can backport …
> Some fixes

- .drone.star
> [10.9] [PR 4659] chore: replace s3 server in drone config by secret

- .drone.star
> [10.8] [PR 4659] chore: replace s3 server in drone config by secret

- modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc
- modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Fixes: https://github.com/owncloud/docs/issues/4653 (Option secure_view_open_action_default needs documentation)
* Add a missing occ config key
* Improve and fix occ text
* Small fix to the Secure View documentation
> Fix Richdocuments and the corrsponding occ comand set

- modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
Updates the NFS document with an additional option describing how to avoid a stuck boot process when the NFS server is not available.
> Update nfs to avoid boot stuck when nfs server is not available

- modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
- modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc
- modules/admin_manual/partials/nav.adoc
References: https://github.com/owncloud/enterprise/issues/4938 (Remove old Jobs that does not exist)
* Add a new trouble shooting documentation how to remove non existent background jobs
* Remove not necessary linebreaks in `background_jobs_configuration.adoc`
@NannaBarz @jvillafanez @cdamken @JanAckermann fyi (feel free to add comments or your review)
> Add how to remove non existent background jobs

- site.yml
This PR tells Antora to use the following startpage: `/docs/next/index.html`
Necessary to use `https://docs.owncloud.com` where the webserver does not need to have a redirect defined. Antora points to the correct address automatically.
With this PR: `https://docs.owncloud.com` --> `https://docs.owncloud.com/docs/next/index.html`
@xoxys pls set the webserver config accordingly
> Define the start page of the documentation

- .drone.star
Remove the `latest_version` variable in `.drone.star`
Because we do not use branches in `docs` anymore, a final clean up is necessary.
Referencing: https://github.com/owncloud/docs-ui/pull/417 (Remove unused keys (cleanup))
@xoxys fyi
> Remove the latest_version variable in .drone.star

- site.yml
Add two attributes for the upcoming ocis documentation.
Necessary for test builds and later for production.
Note that these attributes are also present in the docs-ocis repo.
> update site.yml to include ocis attributes

- site.yml
This is a preperation for all repos which have to reference a "version" in docs.
ATM we do not have versioning, but this might change and adding this makes it possible to use standarized attributes we have in all repos for versioning.
Examples are repos (like server) which have backlinks to docs with regards to release info references.
> Add docs version attributes

- modules/ROOT/pages/server_release_notes.adoc
The release notes were moved but the page alias was not correct - fixed.
> Fix link to moved server release notes

- site.yml
The complete bundle name has changed in `owncloud.com/download`
There is no version date anymore...
`owncloud-complete-20220112` --> `owncloud-complete-latest`
> The complete bundle name has changed

- docs/best-practices.md
Add a note about the correct use of a language in souce blocks and its impacts.
> Add info for the correct use of the source langauge

- docs/best-practices.md
Add plaintext as default suggestion for source languages where none fits
> Include plaintext as source language

- site.yml
This PR prepares for the upcoming ios app version 11.9
**Prerequisite**: https://github.com/owncloud/docs-client-ios-app/pull/81 (Changes necessary for the upcoming 11.9 release)
Merge close the ios-app 11.9 release has been published
@michaelstingl @hosy fyi
(Setting it to WIP to avoid accidentially merging)
> Prepare for the upcoming ios app 11.9 release

- site.yml
Small fix to add apostrophs to an ocis attribute. No harm before but for harmionisation...
> Add missing atpostrophs to attribute

- modules/ROOT/pages/ocis_release_notes.adoc
- modules/ROOT/pages/ocis_releases.adoc
- modules/ROOT/partials/nav.adoc
- site.yml
This PR publishes the Infinite Scale Releases/Release Notes documents.
* The content of the release notes have been derived from [docs-only] Infinite Scale 2.0.0 beta1 Release Notes
* **NEW** 😄 
We do not need to manually maintain the table of contents in the ocis _release notes_ anymore. This is now automated
* The content of _releases_ has been adopted to how ocis docs are setup
@pmaier1 this is the followup PR to bring content into the prepared notes and publishes them. Created so that you have minimal efforts. Can you pls check and approve if ok.
> Publish ocis release notes with content

- site.yml
Adding a new global attribute for ocis. This eases maintaining links.
Will add this attribute in other repos too as next step and finally in the doc ocis repo itself
> Adding a new global attribute for ocis

- docs/build-the-docs.md
Just a small update of the `build-the-docs` documentation driven because asciidoctor-pdf got a version upgrade. Some not necessary linebreaks have been fixed too.
> Update build-the-docs (repo docu)

- site.yml
As the title says, this PR does the web publishing, references: https://github.com/owncloud/docs-ocis/pull/180
> Set ocis to beta 2

- site.yml
As the title says. Necessary for the ocis documentation
@pmaier1 @micbar
> Pushing ocis to beta.5

- modules/ROOT/pages/client_releases.adoc
- modules/ROOT/partials/nav.adoc
Kepp the name in sync with what we use in the docs-client-desktop repo.
> Harmonize the Desktop App naming

- site.yml
References: https://github.com/owncloud/docs-client-desktop/pull/249 (Changes necessary for 2.11)
This are the final changes necessary for the new Desktop 2.11 version.
Only merge AFTER the referenced Desktop PR has been merged and close to the release of the new Desktop version.
@TheOneRing @gabi18 fyi
> Changes necessary for Desktop 2.11

- site.yml
Only merge when ocis beta.8 is out, else it points to a not existing download of the new beta.
@pmaier1 @kulmann fyi
> Update site.yml for ocis beta.8

- site.yml
This are the changes necessary for the upcoming server version 10.11
Only merge when the server version has been published **and** the new version tag is set.
Making it a draft to avoid accidentially merging.
The corresponding necessary server PR is already merged, see: https://github.com/owncloud/docs-server/pull/616 (Changes necessary for 10.11) 
@pmaier1 @jnweiger fyi
> Changes necessary for server 10.11

- site.yml
References: https://github.com/owncloud/docs-client-ios-app/pull/116 (Changes Necessary For 11.11)
**Only merge** when the tag in the IOS repo has been set **and** the referenced PR above has been merged.
**IMPORTANT**: when 11.11 has been tagged, we need to fix the version attribute for mdm in antora.yml in the 11.11 branch.
@hosy @michaelstingl fyi
> Changes Necessary For IOS 11.11

- site.yml
References: #4797 (Changes necessary for Desktop 3.0)
Missed to add the changes on top where adding the git repo for the desktop
> Post fix for Desktop 3.0 prep

- site.yml
Referencing: https://github.com/owncloud/docs-client-desktop/pull/349 (Changes necessary for 3.1)
This is the docs part of the necessary changes.
Can safely be merged as the referenced PR is already merged.
@michaelstingl fyi
> Changes necessary for Desktop 3.1

- site.yml
This are the changes necessary for the upcoming Desktop 3.2 release.
References: https://github.com/owncloud/docs-client-desktop/pull/374 (Changes necessary for 3.2)
Only merge when the client team is close to set the 3.2 tag - setting to draft to avoid accidentially merging.
@michaelstingl @HanaGemela @TheOneRing
> Changes necessary for Desktop 3.2

- site.yml
References: https://github.com/owncloud/docs-server/pull/855 (Changes necessary for 10.12)
This is the change enabling ownCloud Server 10.12.
The referenced PR in docs-server preparing that repo has been merged already.
Do only merge short before the tag in the server repo changes.
Set on draft by purpose to avoid accidentially merging, technically ready.
@pako81 @jnweiger
> Enable ownCloud Server 10.12

- modules/ROOT/pages/server_release_notes.adoc
References: https://github.com/owncloud/core/issues/40696 ([QA] hardened .htaccess breaks index.php-less setup when ownCloud URL has a subfolder)
Add a Known Issue for 10.12
Jointly written with @jnweiger 
@cdamken fyi
> Update server_release_notes.adoc for 10.12

- site.yml
References: https://github.com/owncloud/docs-client-desktop/pull/405 (Changes necessary for desktop 4.0)
This are the final changes necessary for enabling desktop 4.0.
Only merge close **before** desktop 4.0 gets tagged.
Setting to draft to avoid accidentially merging.
Locally tested, works.
@michaelstingl @HanaGemela FYI
> Changes necessary for desktop 4.0

- site.yml
Referencing: https://github.com/owncloud/docs-client-android/pull/120 (Changes necessary for 4.0)
This are the final changes necessary to make the Android 4.0 branch available to docs.
The referenced Android PR has already been merged.
Setting to draft to avoid accidentially merging.
Merge close before tagging Android to 4.0
@michaelstingl @JuancaG05 FYI
> Changes necessary for Android 4.0

- modules/ROOT/pages/index.adoc
The overview page was outdated. Fixes were necessary:
* **Desktop**: naming, text and relaxing the version with "starting with" 
* **Android**: added as new block, naming, text and relaxing the version with "starting with"
* **IOS**: still commented but prepared to align with the others, naming, text and relaxing the version with "starting with".
Language review welcomed.
> Fix the overview page

- modules/ROOT/pages/ocis_releases.adoc
- site.yml
This sets the correct version in `ocis-releases.adoc`.
Renders fine locally.
> Set the Infinite Scale Versions in ocis-releases.adoc

- site.yml
This is a cleanup only.
The attribute is after merging https://github.com/owncloud/docs-ocis/pull/525 (Update and cleanup of attributes) not longer needed.
This can immediately be merged post approving.
> Remove attribute no longer needed

- modules/ROOT/pages/client_releases.adoc
References: https://github.com/owncloud/docs-client-ios-app/pull/146 (Remove iOS version in antora.yml)
We no longer have to differentiate between legacy iOS app and new iOs app.
> Remove IOS 11 reference from client releases

- site.yml
**Only merge** when https://github.com/owncloud/docs-server/pull/1082 (Changes necessary for 10.13) has been merged.
Changes necessary to finalize the 10.13 server documentation.
> Changes necessary for Server 10.13

- modules/ROOT/pages/server_release_notes.adoc
Added planned IE11 deprecation for next core version in the 10.13 Release Notes.
> IE11 deprecation note

- modules/ROOT/pages/ocis_release_notes.adoc
- site.yml
References: https://github.com/owncloud/docs-ocis/pull/608 (Render the ocis 4.0.1 version in tabs)
These are the release notes for Infinite Scale 4.0.1
@tbsbdr fyi
> Add release notes for Infinite Scale 4.0.1

- site.yml
References: https://github.com/owncloud/docs-client-android/pull/135 (Changes necessary for the 4.1 branch)
This are the changes necessary to enable Android 4.1 for docs.
Should be merged close BEFORE tagging Android 4.1 and AFTER the referenced PR got merged.
> Changes necessary for Android 4.1 (branch)

- modules/ROOT/pages/ocis_release_notes.adoc
- site.yml
References: https://github.com/owncloud/docs-ocis/pull/631 (Prepare for ocis 4.0.2)
Add release notes for recently released ocis 4.0.2
The source of the issues fixed is: https://github.com/owncloud/ocis/issues/7370 with the referenced PR's.
> Add release notes for ocis 4.0.2

- site.yml
Referencing: https://github.com/owncloud/docs-client-desktop/pull/530 (Changes necessary for 5.1)
This are the necessary changes for desktop 5.1 to appear properly in docs when released
@michaelstingl @HanaGemela @fmoc @TheOneRing FYI
> Changes for desktop 5.1

- modules/ROOT/pages/client_releases.adoc
This is just a small change to harmonize naming because we use App everywhere else.
> Small change to harmonize namings

- modules/ROOT/pages/ocis_release_notes.adoc
Fixes: #4913 (Add ocis changlog for 4.0.3 and 4.0.4)
Adds the missing ocis release notes.
@tbsbdr fyi, as discussed.
> Adding release notes for ocis 4.0.3 and 4.0.4

- README.md
This only adds an important note that one must update all of his local doc repos to use the latest antora version.
> Add Antora upgrade info for local repos

- site.yml
References: https://github.com/owncloud/docs-client-ios-app/pull/188 (Changes necessary for the 12.1 branch)
This are the changes necessary to make iOS 12.1 docs available.
@hosy @TheOneRing please also set the version tag in the ios-app repo accordingly to update the latest pointer automatically.
> Changes necessary to make iOS 12.1 docs available

- .drone.star
- ext-antora/comp-version.js
- site.yml
This PR adds an extension to extend the output of the full build process.
Also see [Show all components and versions processed when building](https://antora.zulipchat.com/#narrow/stream/282405-tips-.F0.9F.92.A1/topic/Show.20all.20components.20and.20versions.20processed.20when.20building) on the Antora Zulip Tip Channel for an output.
Plus added a small text addon for ocis attributes.
Plus added a missing build attribute relevant for docs-server in .drone.star
> Add a component + version + files console output to the build process

- antora.yml
- site.yml
This is a cleanup PR.
* Removing the version descriptor `antora.yml` as there is no module present = descriptor not necessary
* Cleanup of `-version` attributes.
* Remove the trailing `@` as this has no effect here, though it has one in each doc-xxx repo (1)
* Updating some version values to proper show up things in docs
1 ... I need to do some small text fix in each (versioned) repo where we describe how to do versioning.
> Playbook and version descriptor cleanup

- ext-antora/attributes-used-in-antora-yml.js
- ext-antora/attributes-used-in-site-yml.js
- site.yml
References: Antora Zulip Channel [generate all attribute names and value](https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20generate.20all.20attribute.20names.20and.20value.3F)
Adds two extension to printout attributes used depending if `site.yml` or `antora.yml`.
They are currently commented and are only necessary for testing.
> Add attribute testing extensions

- site.yml
References: https://github.com/owncloud/docs-client-android/pull/169 (Changes necessary for the 4.2 branch)
This are the changes finalizing the provision of the Android 4.2 documentation.
Note that the referenced PR **MUST** be merged first!
@TheOneRing @JuancaG05 @Aitorbp fyi
> Changes necessary for Android 4.2

- docs/build-the-docs.md
- ext-antora/generate-index.js
Though CI returned on the last PR green, merge failed with an ES error coming from the ES script:
```
ElasticSearch: indexing requested
ElasticSearch: remove old search index
ElasticSearch: ERROR: 404 - no such index [******]
error Command failed with exit code 1.
```
Local rebuilding was free of errors, though - lets see what CI tells now...
> Commit to trigger CI with a minor text change

- site.yml
This PR prepares to make the landing page of the site commponent and version less:
`doc.owncloud.com` will not longer redirect to `doc.owncloud.com/docs_main/next`
This is a great improvement as robots.txt and site.yml will now work correctly in Google indexing.
Mandatory needs https://github.com/owncloud/docs-main/pull/23 merged first. ✔️
> Make the landing page component and versionless

- site.yml
This changes the title of the documentation web page from:
`ownCloud Documentation` to `Documentation for ownCloud (A Kiteworks Company)`
> Update site.yml: Change web page title

- site.yml
This are the changes necessary to show the ocis 5 documentation.
The branch necessary is already available in docs-ocis - any references are resolved correctly.
Any content changes must occur in docs-ocis in the master branch backporting to 5.0
**Setting to draft to avoid accidentially merging.**
**Only merge when ocis 5 is very close to be released, respectively short after.**
@tbsbdr @micbar @kulmann adding you here if I am not available when ocis 5 gets released and merging is needed.
> Changes necessary to show ocis 5.0

- site.yml
References: https://github.com/owncloud/docs-main/pull/35 (Update the ocis release notes for 4.0.7)
As informed by @micbar
> Update site.yml for ocis 4.0.7

- site.yml
References: https://github.com/owncloud/docs-main/pull/37 (Add release notes for ocis 5.0.1)
Make the ocis 5.0.1 release visible in the docs.
Note that no other special docs releasing is necessary.
Should be merged close after the new version is publicly available.
Can be merged independently of the referenced PR.
> Make ocis 5.0.1 visible

- site.yml
References:
https://github.com/owncloud/docs-main/pull/38 (Add ocis 5.0.2 release notes)
https://github.com/owncloud/docs-ocis/pull/796 (ocis 5.0.2 patch release)
Updates a necessary attribute for ocis 5.0.2
Can be merged independently of the referenced PR.
> Make ocis 5.0.2 the new latest

- site.yml
Refrencing: https://github.com/owncloud/docs-client-ios-app/pull/204 (Changes necessary for iOS 12.2)
This are the changes necessary to enable the upcoming iOS 12.2 docs.
Note, the referenced PR needs to be merged first.
TODO: iOS 12.2 release notes in the docs-main branch
@TheOneRing @hosy
> Changes necessary for iOS 12.2 docs availability

- site.yml
References: https://github.com/owncloud/docs-main/pull/42 (Add release notes for ocis 5.0.4)
> Publish ocis 5.0.4

- site.yml
Refernces: https://github.com/owncloud/docs-client-android/pull/182 (Changes necessary for 4.3)
Only merge after the referenced PR has been merged.
Set to draft to avoid accidentially merging.
Merge close before that tag of Android 4.3 gets created.
> Changes necessary to show android 4.3

- docs/antora-site-structure.md
- site.yml
This PR enables / prepares for ocis rolling releases.
The tab text in a service in the ocis admin docs for the `next` release named `master` is then printed
as `master + Rolling 6.1.0`. A PR in the docs-ocis repo will follow asap.
This does not affect branched releases. They stay with their defined number in the tab text.
Additionally I found an improvement in the site structure docs which I added to the fix.
> Enable ocis rolling releases

- site.yml
References: https://github.com/owncloud/docs-main/pull/62 (Prepare for ocis 5.0.6 release notes)
Set the correct attribute for ocis 5.0.6
Only merge when the release has been published!
> Prepare for ocis 5.0.6

- site.yml
References: https://github.com/owncloud/docs-server/pull/1318 (Changes necessary for 10.15)
Makes the new server 10.15 version available to the docs.
Merge close before the server 10.15 tag is set.
A local build ran fine showing 10.15 without errors.
(Note that I also fixed the value for the latest ocis 5.0.5 patch release)
Putting to draft to avoid accidentially merging.
> Changes necessary to show server 10.15

- site.yml
Make the rolling release visible in the ocis admin docs.
> Update ocis to rolling 6.2.0

- docs/build-the-docs.md
I needed to resetup my dev machine from scratch where it turned out the `curl` was missing in the prerequisites.
Fixed now, added.
> Add curl to the prerequisites for building

- site.yml
References: https://github.com/owncloud/docs-main/pull/71 (Add release notes for ocis 5.0.7)
Only merge after release notes have been merged - setting to draft therefore.
@tbsbdr fyi
> Make ocis 5.0.7 as default production

- site.yml
References: https://github.com/owncloud/docs-main/pull/73 (Added Release Notes 6.4.0)
Merge only after the release has been published - putting to draft therefore.
@tbsbdr fyi
> Make ocis 6.4.0 as default rolling

- site.yml
References: https://github.com/owncloud/docs-client-ios-app/pull/222 (Changes necessary to enable IOS 12.3)
Merge only after the release AND the referenced PR have been published - putting to draft therefore.
> Make IOS 12.3.0 as default production

- site.yml
References: https://github.com/owncloud/docs-client-android/pull/194 (Changes necessary for Android 4.4)
The Android 4.4 release is already out.
Merge after the referenced PR has been merged.
> Add Android 4.4

- site.yml
References: https://github.com/owncloud/docs-main/pull/72 (Add release notes for ocis 5.0.8)
Merge only after the release has been published - putting to draft therefore.
@tbsbdr fyi
> Make ocis 5.0.8 as default production

- site.yml
With that PR, the rolling release printed is now correct. Missed to update that last time.
> Update the ocis rolling release numbner

- site.yml
References:
https://github.com/owncloud/docs-main/pull/80 (Added Release Notes 6.6.0)
https://github.com/owncloud/docs-ocis/pull/1015 (Prepare for ocis 6.6.0 (local build relevant only))
Set the attribute to use ocis 6.6.0
Only merge when the release has been published!!
> Prepare for ocis 6.6.0 rolling

- site.yml
Referencing: https://github.com/owncloud/docs-ocis/pull/1098 (Changes necessary for ocis 7.0)
These are the changes necessary for ocis 7.0
> Prepare for ocis 7.0

- yarn.lock
> chore: recreate yarn.lock with latest package versions

- .drone.star
Refernces: https://github.com/owncloud/docs-server/pull/1417 (Two build relevant updates)
* Finally remove the already commented yarn comand
The attribute used is now part of the servers antora.yml configuration
* Replace npx with the correct npm command
> Fix .drone.start post merging a docs-server PR

- site.yml
References: https://github.com/owncloud/docs-main/pull/95 (Remove the Branding docs from the main page)
Based on the request of @DeepDiver1975
This PR removes the branding docs from the build process and must be merged AFTER [docs-main #95](https://github.com/owncloud/docs-main/pull/95) has been merged.
A local build runs without errors.
> Remove the Branding docs from the build process

- global-attributes.yml
- site.yml
Referencing: https://github.com/owncloud/docs-client-ios-app/pull/238 (Changes necessary for the 12.4 branch)
This PR enables the documentation for iOS 12.4 and drops 12.2
Tested, a local build runs fine.
> Enable iOS 12.4

- global-attributes.yml
- site.yml
Referencing: https://github.com/owncloud/docs-ocis/pull/1115 (Changes necessary for 7.1)
This PR enables the documetation for Infinite Scale 7.1 and drops 5.0
Currently on draft to avoid accidentially merging before 7.1 is out.
Tested, a local build runs fine.
> Enable ocis 7.1

- docs/build-the-docs.md
- es-docker-compose.yml
The version tag in the docker compose file for ElasticSearch is no longer necessary.
Removing it silences the docker compose startup.
Additionally, the missing `run` command was added: `npm antora` --> `npm run antora`
> Remove the version from the ES docker compose file

- global-attributes.yml
- site.yml
Referencing: https://github.com/owncloud/docs-client-android/pull/213 (Changes necessary for 4.5)
This PR enables the documentation for Android 4.5 and drops version 4.4
Currently on draft to avoid accidentally merging before Android 4.5 is finally out.
Only merge close before the product tag gets released.
When this PR is merged, the dropped branch can be archived.
For more details see the `Create a New Version Branch` section in the README.md of the respective docs-client-android repo.
The `latest` pointer on the web will be set automatically when the tag in the product repo is set.
Tested, a local build runs fine.
@mmattel @phil-davis
> Enable Android 4.5

- global-attributes.yml
- site.yml
Referencing: https://github.com/owncloud/docs-client-ios-app/pull/247 (Changes necessary for 12.5)
This PR enables the documentation forIOS 12.5 and drops version 12.4
When this PR is merged, the dropped branch can be archived.
For more details see the `Create a New Version Branch` section in the README.md of the respective docs-client-ios-app  repo.
The `latest` pointer on the web will be set automatically when the tag in the product repo is set.
Tested, a local build runs fine.
@mmattel @phil-davis
> Changes necessary for IOS 12.5

- global-attributes.yml
- site.yml
Referencing: https://github.com/owncloud/docs-client-android/pull/225 (Changes necessary for 4.6)
These are the changes necessary to finalize the creation of the Android 4.6 branch.
* The 4.6 branch is already pushed, prepared and is included in the branch protection rules.
* Note that this PR can be merged at any time.
* Post merging this, we need to backport all relevant Android changes created in master to 4.6
> Enable Android 4.6
