site.yml
=> [10.6] [PR 3426] Switch Desktop branch to 2.8

site.yml
=> [10.7] [PR 3426] Switch Desktop branch to 2.8

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
This is a `config-to-docs` run.
References: https://github.com/owncloud/core/pull/38610
Merge only when core PR was merged.
=> config.apps.sample core update

modules/admin_manual/nav.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
Some improvememts and fixes to richdocuments (Collabora). Due to some writing styles, the document did not render properly. Included a toc and Improvement section.
Backport to 10.7 and 10.6 necessary
=> Collabora Fixes

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.7] [PR 3433] config.apps.sample core update

modules/admin_manual/nav.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
=> [10.7] [PR 3432] Collabora Fixes

modules/admin_manual/nav.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_online_integration.adoc
=> [10.6] [PR 3432] Collabora Fixes

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.7][PR 3437] Typo and rendering fix in config.apps.sample

modules/admin_manual/nav.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.6][PR3438] Fix Collabora Secure View file naming

modules/admin_manual/nav.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.7][PR3438] Fix Collabora Secure View file naming

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
back port of  https://github.com/owncloud/docs/pull/3442
=> [10.7] document improvement

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
back port of https://github.com/owncloud/docs/pull/3442
=> [10.6] document improvement

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.6] [PR 3451] Update system_requirements.adoc

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.7] [PR 3451] Update system_requirements.adoc

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.6] [PR 3449] Do not register ondrey repo twice

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
Some fixes to the WOPI documentation.
=> Some WOPI fixes

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.7] [PR 3459] Fix page_alias attribute name

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.6] [PR 3458] Some WOPI fixes

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.7] [PR 3458] Some WOPI fixes

docs/best-practices.md
Update BPG using manually created anchors
No backport needed as it is part of the repo documentation
=> Update BPG using manually created anchors

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.7] [PR 3472] config.apps.sample changes from core

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> Fix link (typo) for MS Teams

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.7] [PR 3476] Fix link (typo) for MS Teams

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
Add the config for Microsoft Teams Bridge into config.apps.sample coming from core https://github.com/owncloud/core/pull/38640
Note: I have reordered the apps aphabetical for having a better list. No change in SEO.
Merge only after core got merged
=> Add Microsoft Teams Bridge to config.apps.sample

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.7] [PR 3475] Add Microsoft Teams Bridge to config.apps.sample

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.6] [PR 3457] added listing instructions

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.7] [PR 3457] added listing instructions

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/integration/index.adoc, modules/admin_manual/pages/configuration/integration/splunk.adoc
@mmattel @EParzefall can one of you take over? Let me know if there are questions.
=> Document the ownCloud App for Splunk

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/integration/index.adoc, modules/admin_manual/pages/configuration/integration/splunk.adoc
=> [10.7] [PR 3495] Document the ownCloud App for Splunk

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.7] Add supported IdPs to OIDC docs

modules/admin_manual/pages/configuration/user/user_roles.adoc
Added information about guests:
- only available after installing app
- where to get app
Let me know if you need more for this PR
=> Guests only available after installing app

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.7] Guests only available after installing app

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.6] Guests only available after installing app

modules/admin_manual/pages/release_notes.adoc
=> Add 10.7 known issue to release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.7] [PR 3509] Add 10.7 known issue to release notes

modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
=> [10.6] Update linux_packetmanager_install.adoc

modules/admin_manual/pages/installation/linux_packetmanager_install.adoc
=> [10.7] Update linux_packetmanager_install.adoc

modules/user_manual/pages/files/access_webdav.adoc
=> Typo TSL -> TLS

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc, modules/admin_manual/pages/enterprise/reporting/metrics.adoc
=> [10.7] Added references to the new Splunk-App-Section

modules/user_manual/pages/files/access_webdav.adoc
=> [10.7] Typo TSL -> TLS

modules/user_manual/pages/files/access_webdav.adoc
=> [10.6] Typo TSL -> TLS

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.7] [PR 3374] Fixing release version plus adding -E to sudo command

modules/admin_manual/pages/configuration/files/external_storage/google.adoc
correction typo in the word beneficial
Backport #3534 and #3536
=> [10.7] Update google.adoc

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> Replacing change log link with Server Packages link

modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc
=> [10.7] php-fpm support information

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.6] Replacing change log link with Server Packages link to fix issue #3035.

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.7] Replacing change log link with Server Packages link to fix issue #3035.

.drone.star, bin/makepdf, docs/build-the-docs.md
Give the script a meaninful name. Template for the other doc repos
=> Rename script cli to makepdf

.drone.star, bin/makepdf, docs/build-the-docs.md
=> [10.6] [PR 3543] Rename script cli to makepdf

.drone.star, bin/makepdf, docs/build-the-docs.md
=> [10.7] [PR 3543] Rename script cli to makepdf

modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
=> [10.7] [PR 3551] Added warnings to packagemanager upgrades

modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc
=> [10.6] [PR 3551] Added warnings to packagemanager upgrades

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/makepdf, modules/admin_manual/pages/configuration/server/security/oauth2.adoc, site.yml
=> [10.6] [PR 3548] Fix makepdf (script which creates the pdf)

bin/find-orphaned-files.sh, bin/instructions_makepdf.md, bin/makepdf, modules/admin_manual/pages/configuration/server/security/oauth2.adoc, site.yml
=> [10.7] [PR 3548] Fix makepdf (script which creates the pdf)

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrade.adoc
Fixed issue #3445 and  #3383 as well as a broken link, plus general improvements for clarity.
=> Upgrade revised

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrade.adoc
=> [10.6] [PR 3560] Upgrade revised

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrade.adoc
=> [10.7] [PR 3560] Upgrade revised

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc
Added reference to script-guided upgrade and other minor additions/fixes as @mmattel suggested.
=> Pointer to script guided upgrade

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.6] [PR 3563] Pointer to script guided upgrade

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.7] [PR 3563] Pointer to script guided upgrade

modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
=> Samba text improvement

modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
=> [10.6] [PR 3566] Samba text improvement

modules/admin_manual/pages/installation/manual_installation/compile_samba.adoc
=> [10.7] [PR 3566] Samba text improvement

bin/find-orphaned-adoc-files
=> [10.7] [PR 3573] Improved find adoc files catching false-positive incudes

bin/find-orphaned-adoc-files
=> [10.6] [PR 3573] Improved find adoc files catching false-positive incudes

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.7] [PR 3576] Note that the Quick Install guide for Ubuntu 20.04 has its limits

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.6] [PR 3576] Note that the Quick Install guide for Ubuntu 20.04 has its limits

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
=> [10.6] [PR 3583] Do not suggest cron every minute

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
=> [10.7] [PR 3583] Do not suggest cron every minute

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
=> [10.7] [PR 3593] Fix of occ config commands

modules/admin_manual/pages/configuration/server/occ_command/config_commands.adoc
=> [10.6] [PR 3593] Fix of occ config commands

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> Fix some typos in virus-scanner-support

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.7] Fix some typos in virus-scanner-support

bin/find-orphaned-attachment-files, bin/find-orphaned-image-files
Updates following find-orphaned* scripts:
`find-orphaned-image-files`
`find-orphaned-example-files`
`find-orphaned-attachment-files`
=> Update to the find orphaned scripts

bin/find-orphaned-attachment-files, bin/find-orphaned-image-files
=> [10.7] [PR 3600] Update to the find orphaned scripts

modules/admin_manual/pages/configuration/files/external_storage/local.adoc
=> [10.6] [PR 3603] Update local.adoc

modules/admin_manual/pages/configuration/files/external_storage/local.adoc
=> [10.7] [PR 3603] Update local.adoc

modules/admin_manual/pages/configuration/files/file_versioning.adoc, modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.6] [PR 3611] Missing config key for files_version

modules/admin_manual/pages/configuration/files/file_versioning.adoc, modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.7] [PR 3611] Missing config key for files_version

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.7] [PR 3619] Text fix for enterprise/logging/admin_audit.html#lifecycle_restored

modules/admin_manual/pages/enterprise/reporting/metrics.adoc
References: https://github.com/owncloud/docs/issues/3494 (Metrics App is not compatible with IE 11)
Adda a note about that fact.
=> Note that IE 11 is not compatible with Metrics

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.7] [PR 3620] Correct Apache header information for msteamsbridge

modules/admin_manual/pages/enterprise/reporting/metrics.adoc
=> [10.7] [PR 3618] Note that IE 11 is not compatible with Metrics

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.7] [PR 3621] Fix config.sample for preview providers

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.7] [PR 3627] Fix PDF preview provider

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.7] [PR 3628] Add the correct http.cookie.samesite for OIDC

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.7] [PR 3631] Improved config key description for auto-provision for OIDC

modules/admin_manual/pages/configuration/files/encryption/index.adoc
=> update encryption size overhead note

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc
=> [10.7] [PR 3634] Document auto-provision for AzureAD OIDC

modules/admin_manual/pages/configuration/files/encryption/index.adoc
=> [10.7] [PR 3636] update encryption size overhead note

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc
=> [10.7] [PR 3640] Add Workflow / Tagging config key

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc
Clarified some information after testing the script-guided installation.
=> Improved script-guided installation.

.drone.star, bin/instructions_makepdf.md, modules/ROOT/pages/how_to_contribute.adoc, site.yml
=> migrate client docs to new repo

.drone.star, bin/instructions_makepdf.md, modules/ROOT/pages/how_to_contribute.adoc, site.yml
=> [10.7] [PR 3647] migrate client docs to new repo

.drone.star, bin/instructions_makepdf.md, modules/ROOT/pages/how_to_contribute.adoc, site.yml
=> [10.6] [PR 3647] migrate client docs to new repo

docs/build-the-docs.md
=> [10.7] [PR 3656] Update build-the-docs.md to reflect the changes on node

.drone.star, .gitignore
=> [10.6] [PR 3655] refactor ci to work with all branches

.drone.star, .gitignore
=> [10.7] [PR 3655] refactor ci to work with all branches

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.7] [PR 3664] Correct X-XSS-Protection

bin/makepdf
=> [10.6] [PR 3666] makepdf: add option for error output

bin/makepdf
=> [10.7] [PR 3666] makepdf: add option for error output

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.6] Docker install revision

modules/admin_manual/pages/installation/docker/index.adoc
Fixed some language issues and removed a misplaced sudo.
Backports to 10.7 and 10.6 needed
=> minor fixes

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] Docker install revision

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.7] [PR 3673] Kick block; from X-XSS-Protection

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Refernces: https://github.com/owncloud/core/pull/38837 (Correct Preview config.sample.php)
Fixes a lower/uppercase issue
@ho4ho fyi
=> Correct_Preview_config.sample.php

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.7] Correct_Preview_config.sample.php

modules/developer_manual/examples/core/scripts/responses/shares/update-share-success.xml, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/user_manual/pages/files/public_link_shares.adoc
Backport the words from PR  #3681 
The words are applicable to 10.7. The technical example of the expiration time is only for 10.8.
=> [10.7] Shares expire at the end of the specified day

modules/developer_manual/examples/core/scripts/responses/shares/update-share-success.xml, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/user_manual/pages/files/public_link_shares.adoc
Backport the words from PR  #3681 
The words are applicable to 10.6. The technical example of the expiration time is only for 10.8.
=> [10.6] Shares expire at the end of the specified day

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
Backport of #3688 
(checked, content exists)
=> [10.6] [PR 3688] Update server_prep_ubuntu_20.04.adoc

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.7] [PR 3688] Update server_prep_ubuntu_20.04.adoc

modules/developer_manual/pages/app/advanced/code_signing.adoc
=> [10.7] Removed unnecessary char

modules/admin_manual/pages/enterprise/installation/install.adoc
Fixes: https://github.com/owncloud/docs/issues/3694 (Add a paragraph to show how to remove the ownCloud license)
No backport !
=> Added tip to show how to remove the current licsense

modules/ROOT/pages/index.adoc
=> [10.6] [PR 3701] fixed reference to manual installation

modules/ROOT/pages/index.adoc
=> [10.7] [PR 3701] fixed reference to manual installation

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] [PR 3691] added proper eval guidance

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.6] [PR 3691] added proper eval guidance

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
Fixes: https://github.com/owncloud/docs/issues/3608 (New occ commands for richdocuments)
New occ commands in `richdocuments` app.
RD changes have been merged, ready to go into master.
No backport!
@cdamken fyi
=> New occ commands for richdocuments

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.6] [PR 3712] Document expiration of outgoing remote shares

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.7] [PR 3712] Document expiration of outgoing remote shares

modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
=> [10.6] [PR 3716] Small fixes setting attributes correctly

modules/admin_manual/pages/configuration/files/manual_file_locking.adoc
=> [10.7] [PR 3716] Small fixes setting attributes correctly

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc, modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
Make a note that the desktop/mobile apps do not work by default with Azure AD.
=> Desktop/mobile apps need branding to work with OIDC

modules/admin_manual/pages/configuration/user/oidc/ms-azure-setup.adoc, modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.7] [PR 3492] Desktop/mobile apps need branding to work with OIDC

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
owncloud/windows_network_drive#321
=> Example using Vault to fetch wnd password

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.7] [PR 3250] Example using Vault to fetch wnd password

modules/admin_manual/pages/configuration/server/occ_command/encryption_commands.adoc
=> [10.6] [PR 3727] Add missing occ encryption commands

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
=> [10.7] [PR 3727] Add missing occ encryption commands

package.json, yarn.lock
=> chore: update node dependencies

modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
=> [10.6] [PR 3710] hsmdaemon install consistency and accuracy

modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc
=> [10.7] [PR 3710] hsmdaemon install consistency and accuracy

package.json, yarn.lock
=> [10.7] [PR 3730] chore: update node dependencies

package.json, yarn.lock
=> [10.6] [PR 3730] chore: update node dependencies

modules/ROOT/pages/index.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] [PR 3737] occ usage with docker installations

modules/ROOT/pages/index.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.6] [PR 3737] occ usage with docker installations

modules/admin_manual/pages/installation/docker/index.adoc
=> Delete single quotes in docker run command

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] [PR 3744] Delete single quotes in docker run command

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.6] [PR 3744] Delete single quotes in docker run command

docs/best-practices.md, modules/ROOT/pages/index.adoc
=> [10.7] [PR 3745] Small fixes to the BPG and the landing page

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.7] [PR 3742] Add Secure View sharing note

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.6] [PR 3742] Add Secure View sharing note

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.7] Fix share expiration response description

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.6] Fix share expiration response description

docs/build-the-docs.md
=> [10.6] [PR 3757] Fixing Building the Documentation Guide

docs/build-the-docs.md
=> [10.7] [PR 3757] Fixing Building the Documentation Guide

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.7] Fix slashes in URLs

modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc, modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.8] [PR 3765] Update Imagick to v7 for enhanced preview provider support

modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc, modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.7] [PR 3765] Update Imagick to v7 for enhanced preview provider support

modules/admin_manual/pages/configuration/server/caching_configuration.adoc, modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc, modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc, modules/developer_manual/pages/app/tutorial/requirements.adoc, site.yml
=> [10.8] [PR 3768] Update PHP min version to 7.2.5

site.yml
This is a cleanup of site.yml removing unused variables and repos
Backport to 10.8 needed
10.7 will get it´s onw PR for this
=> Cleanup site.yml

modules/admin_manual/pages/release_notes.adoc
Part of issue #3767 
Follow-on from #3768 
Nite: my IDE automagically removed whitespace from the end of existing lines>
=> Add PHP minimum version 7.2.5 to 10.8 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.8] [PR 3773] Add PHP minimum version 7.2.5 to 10.8 release notes

modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc, modules/user_manual/pages/files/encrypting_files.adoc
=> [10.8] [PR 3778] User Manual Encryption, pdf fix file not found

modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc, modules/user_manual/pages/files/encrypting_files.adoc
=> [10.7] [PR 3778] User Manual Encryption, pdf fix file not found

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> ImageMagick revision

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.7] [PR 3783] ImageMagick revision

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.8] [PR 3783] ImageMagick revision

docs/new-version-branch.md
=> [10.8] [PR 3786] Fix Internal Redirects

docs/new-version-branch.md
=> [10.7] [PR 3786] Fix Internal Redirects

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.7] Remove outdated text references in LDAP

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.8] Remove outdated text references in LDAP

site.yml
Backport of PR #3772
(This backport was missing)
=> [10.8] [PR 3772] Cleanup site.yml

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
=> [10.8] [PR 3796] Replaced outdated Firebug URL

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
=> [10.7] [PR 3796] Replaced outdated Firebug URL

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
=> spelling mistake

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
=> [10.8] spelling mistake

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/market_commands.adoc
=> [10.7] spelling mistake

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.8] [PR 3806] occ is redundant

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.7] [PR 3806] occ is redundant

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] [PR 3799] Add hints about loglevel

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.8] [PR 3799] Add hints about loglevel

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.8] [PR 3807] Update the ImageMagick install documentation

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.7] [PR 3807] Update the ImageMagick install documentation

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.8] [PR 3814] Fixes a config sample typo

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
=> [10.8] [PR 3822] Set page-aliases for external_storage_configuration_gui.adoc

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
=> [10.7] [PR 3822] Set page-aliases for external_storage_configuration_gui.adoc

modules/admin_manual/pages/configuration/server/caching_configuration.adoc
=> [10.8] [PR 3819] Caching Doc: Create separate entry for opcache

modules/admin_manual/pages/configuration/server/caching_configuration.adoc
=> [10.7] [PR 3819] Caching Doc: Create separate entry for opcache

modules/developer_manual/pages/testing/acceptance-tests.adoc
- update running acceptance tests description
- fixes https://github.com/owncloud/core/issues/38918
=> Added information about environment variables used while running acceptance tests

modules/developer_manual/pages/testing/acceptance-tests.adoc
=> [10.8] Added information about environment variables used while running acceptance tests

docs/best-practices.md
=> [10.8] Add an item in the BPG at the table section

docs/best-practices.md
=> [10.7] Add an item in the BPG at the table section

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.8] config-to-docs from release-10.8.0

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.7] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.8] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.8] [PR 3838] Formatting fix for the IM7 document - no content change

modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.7] [PR 3838] Formatting fix for the IM7 document - no content change

modules/developer_manual/pages/testing/test-pilots.adoc
=> [10.7] [PR 3844] Update test-pilots.adoc

modules/developer_manual/pages/testing/test-pilots.adoc
=> [10.8] [PR 3844] Update test-pilots.adoc

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.8] [PR 3849] config-to-docs run

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.7] [PR 3849] config-to-docs run

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/developer_manual/pages/bugtracker/codereviews.adoc
Post fix of #3850 (Link and owncloud tld fixes)
Some suggestions have not been commited, this is now post fixed.
=> Post fix of #3850

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/developer_manual/pages/bugtracker/codereviews.adoc
=> [10.8] [PR 3855] Post fix of #3850

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/developer_manual/pages/bugtracker/codereviews.adoc
=> [10.7] [PR 3855] Post fix of #3850

modules/admin_manual/pages/installation/manual_installation/index.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/quick_guides/index.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 3858] Removing ondrej ppa/adding refs to server hardening

modules/admin_manual/pages/installation/manual_installation/index.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/quick_guides/index.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.7] [PR 3858] Removing ondrej ppa/adding refs to server hardening

modules/admin_manual/pages/appliance/configuration/login_information.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.8] [PR 3862] How to use occ commands with the Appliance

modules/admin_manual/pages/appliance/configuration/login_information.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.7] [PR 3862] How to use occ commands with the Appliance

modules/admin_manual/pages/release_notes.adoc
=> [10.8] [PR 3865] 10.8 release notes corrections

modules/admin_manual/pages/release_notes.adoc
=> [10.8] [PR 3867] Add issue 39034 about PHP 7.4.21 and open_basedir to known issues

docs/new-version-branch.md
=> [10.8] [PR 3871] Update new version branch when and how latest is set

docs/new-version-branch.md
=> [10.7] [PR 3871] Update new version branch when and how latest is set

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
=> [10.8] [PR 3876] Add reason when to use occ encryption:fix-encrypted-version

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
=> [10.7] [PR 3876] Add reason when to use occ encryption:fix-encrypted-version

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.8] [PR 3875] Fix missing occ link how to setup Collabora

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.7] [PR 3875] Fix missing occ link how to setup Collabora

modules/admin_manual/pages/release_notes.adoc
=> [master] [PR 3870] add hint about custom themes for login page to 10.8 release notes

modules/ROOT/pages/index.adoc
=> [10.7] [PR 3884] Fix OwnCloud -> ownCloud

modules/ROOT/pages/index.adoc
=> [10.8] [PR 3884] Fix OwnCloud -> ownCloud

modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
This fixes issue #3579 and other outdated information.
Backport needed for 10.8 and 10.7.
=> Dropbox integration updated

modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
=> [10.8] [PR 3897] Clarified how to find and enable a SUSE security repo

modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
=> [10.7] [PR 3897] Clarified how to find and enable a SUSE security repo

modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
=> [10.8] [PR 3895] Dropbox integration updated and fixing issue

modules/admin_manual/pages/configuration/files/external_storage/dropbox.adoc
=> [10.7] [PR 3895]  Dropbox integration updated and fixing issue #3903

modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
=> [10.8] [PR 3902] SUSE security example upgraded to 15.3

modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc
=> [10.7] [PR 3902] SUSE security example upgraded to 15.3

modules/developer_manual/examples/scripts/backport.sh
=> [10.8] [PR 3908] Fixes and improvments for the backporting script

modules/developer_manual/examples/scripts/backport.sh
=> [10.7] [PR 3908] Fixes and improvments for the backporting script

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
References: https://github.com/owncloud/docs/pull/3908
A small post fix that has been overseen while doing a real life backport with the new script
Backport to 10.8 and 10.7 needed
=> Fix query and fix documentation in bp script/documentation

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.8] [PR 3911] Fix query and fix documentation in bp script/documentation

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.7] [PR 3911] Fix query and fix documentation in bp script/documentation

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.8] [PR 3890] Add database as storage backend for settings

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
=> [10.8] [PR 3914] State that occ config:app is handled via the database

modules/developer_manual/examples/scripts/backport.sh
=> [10.7] [PR 3915] Remove the need for perl from the backport script

modules/developer_manual/examples/scripts/backport.sh
=> [10.8] [PR 3915] Remove the need for perl from the backport script

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/config_commands.adoc
=> [10.7] [PR 3914] State that occ config:app is handled via the database

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/richdocuments.adoc
=> [10.8] [PR 3923] Richdocuments: occ - Open documents in a new tab

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
Better describe the limits of the preview generation.
=> Describe limits of preview generation

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.8] [PR 3925] Describe limits of preview generation

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.7] [PR 3925] Describe limits of preview generation

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
With some commands sudo was missing. 
Backport to 10.7 and 10.8 needed.
=> added sudo where necessary in upgrade description

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.7] [PR 3930] added sudo where necessary in upgrade description

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.8] [PR 3930] added sudo where necessary in upgrade description

modules/ROOT/pages/index.adoc, site.yml
=> [10.8] [PR 3933] Move a adoc varaible from a page to site.yml

modules/ROOT/pages/index.adoc, site.yml
=> [10.7] [PR 3933] Move a adoc varaible from a page to site.yml

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] [PR 3936] Docker upgrade missed end of maintenance step

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.8] [PR 3936] Docker upgrade missed end of maintenance step

modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.8] [PR 3939] Describe which mount options are default for NFS

modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.7] [PR 3939] Describe which mount options are default for NFS

modules/admin_manual/pages/configuration/user/guests_app.adoc
=> [10.8] [PR 3946] Fix guest app document

modules/admin_manual/pages/configuration/user/guests_app.adoc
=> [10.7] [PR 3946] Fix guest app document

modules/admin_manual/nav.adoc, modules/admin_manual/pages/troubleshooting/path_filename_length.adoc
=> [10.8] [PR 3950] Document Path and Filename Length Limitations

modules/admin_manual/nav.adoc, modules/admin_manual/pages/troubleshooting/path_filename_length.adoc
=> [10.7] [PR 3950] Document Path and Filename Length Limitations

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.8] [PR 3954] Update ms-teams.adoc

README.md, docs/doc-guidelines.md
Writing down the doc guidelines as part of the readme section based on the work done before.
@michl19 fyi
=> Add doc guidelines

README.md, docs/doc-guidelines.md
=> [10.8] [PR 3951] Add doc guidelines

README.md, docs/doc-guidelines.md
=> [10.7] [PR 3951] Add doc guidelines

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
=> [10.8] [PR 3959] Add warning around removal of external storage configuration

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc
=> [10.7] [PR 3959] Add warning around removal of external storage configuration

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Information on av_background_scan has been missing. This fixes issue #3944.
Backports to 10.8 and 10.7 needed
=> added info on av_background_scan

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.8] [PR 3972] added info on av_background_scan

modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
=> [10.7] [PR 3972] added info on av_background_scan

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/language_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.8] [PR 3978] gender neutral language

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/language_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/file_commands.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.7] [PR 3978] gender neutral language

docs/style-guide.md
Added gender neutral wording and smaller updates.
=> styleguide: tips on gender neutral wording

modules/admin_manual/pages/configuration/server/harden_server.adoc
Revision with regard to clarity and language.
Backports to 10.7 and 10.8 needed.
=> Revised server hardening

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.8] [PR 3983] Revised server hardening

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.7] [PR 3983] Revised server hardening

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.8] [PR 3986] Use the latest stable PEAR release

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.7] [PR 3986] Use the latest stable PEAR release

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/manual_installation/upgrade_install_phpmyadmin.adoc
=> [10.8] Fix a few small typos in manual installation docs

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/manual_installation/upgrade_install_phpmyadmin.adoc
=> [10.7] Fix a few small typos in manual installation docs

modules/ROOT/pages/releases.adoc
=> [10.7] [PR 3999] Fix pdf link for 8.2 admin manual

modules/ROOT/pages/releases.adoc
=> [10.8] [PR 3999] Fix pdf link for 8.2 admin manual

overlay/ui.yml
We need another round... Forgot to add it to the ui.yml, I'm really sorry :( Thanks for taking care. Needs backport.
=> fix: add favicon.ico to static files list

overlay/ui.yml
=> [10.7] [PR 4008] fix: add favicon.ico to static files list

overlay/ui.yml
=> [10.8] [PR 4008] fix: add favicon.ico to static files list

modules/ROOT/pages/releases.adoc
=> [10.8] [PR 4012] Fix pdf link for desktop

modules/ROOT/pages/releases.adoc
=> [10.7] [PR 4012] Fix pdf link for desktop

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.8] typo

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.7] typo

modules/admin_manual/pages/configuration/server/email_configuration.adoc
closes: https://github.com/owncloud/docs/issues/3995
target problem: https://github.com/owncloud/enterprise/issues/4516#issuecomment-913454278
=> Mailer sending modes

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
relates to problem with exceptions as in https://github.com/owncloud/user_ldap/pull/677 and https://github.com/owncloud/enterprise/issues/4686#issue-951464336
=> add comment on initial user sync

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.8] [PR 4018] Mailer sending modes

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.7] [PR 4018] Mailer sending modes

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.7] [PR 4017] add comment on initial user sync

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.8] [PR 4017] add comment on initial user sync

docs/new-version-branch.md
Some small text fixes.
Backporting to 10.8 and 10.7
=> Minor text fixes to the create version branch steps

docs/new-version-branch.md
Some text fixes
Backport #4022
=> [10.8] Minor fixes to the create version branch steps

site.yml
=> [10.8] [PR 4029] Set desktop to 2.9

site.yml
=> [10.7] [PR 4029] Set desktop to 2.9

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.8] [PR 4037] backtick removed from wnd examples

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.7] [PR 4037] backtick removed from wnd examples

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [master] [PR 4045] replaced references of the generator app with the generator URL directly

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Since I committed to a forward port, I'm cherry-picking a fix for language clarity in a backport to 10.8.
=> [10.8] [PR 4045] Backport of last commit to master

modules/ROOT/pages/releases.adoc, site.yml
=> [10.7] [PR 4047] Use the new docs ios repo

.drone.star, bin/optimize_crawl
=> [10.8] [PR 4055] Improve robots and sitemap files automatically post building the docs

.drone.star, bin/optimize_crawl
=> [10.7] [PR 4055] Improve robots and sitemap files automatically post building the docs

bin/makepdf, bin/manual_config
Just a small update, it handles the case that the first letter is not capital (see iOS)
=> Update of the makepdf script and configuration to be inline with the other repos

bin/makepdf, bin/manual_config
=> [10.7] [PR 4061] Update of the makepdf script and configuration to be inline with the other repos

bin/makepdf, bin/manual_config
=> [10.8] [PR 4061] Update of the makepdf script and configuration to be inline with the other repos

modules/ROOT/pages/releases.adoc
=> [10.8] [PR 4056] Add missing text line in releases file

modules/ROOT/pages/releases.adoc
=> [10.7] [PR 4056] Add missing text line in releases file

modules/ROOT/pages/releases.adoc, site.yml
=> [10.7] [PR 4066] New iOS App release

modules/ROOT/pages/releases.adoc, site.yml
=> [10.8] [PR 4066] New iOS App release

modules/ROOT/pages/releases.adoc
=> [10.7] [PR 4069] Mini fix for using the correct release variable in releases file

modules/ROOT/pages/releases.adoc
=> [10.8] [PR 4069] Mini fix for using the correct release variable in releases file

modules/ROOT/pages/releases.adoc, site.yml
=> [10.7] [PR 4072] Takes back a minor iOS release

modules/ROOT/pages/releases.adoc, site.yml
=> [10.8] [PR 4072] Takes back a minor iOS release

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.8] [PR 4075] Specify minor versions of MariaDb that are supported

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.7] [PR 4075] Specify minor versions of MariaDb that are supported

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.8] [PR 4079] Fix syntax error in preview provider example.

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.7] [PR 4079] Fix syntax error in preview provider example.

modules/ROOT/pages/releases.adoc, site.yml
=> [10.8] [PR 4084] Make the new docs-Android branch available for docs

modules/ROOT/pages/releases.adoc, site.yml
=> [10.7] [PR 4084] Make the new docs-Android branch available for docs

bin/optimize_crawl
=> [10.7] [PR 4088] Add android to optimize_crawl script

bin/optimize_crawl
=> [10.8] [PR 4088] Add android to optimize_crawl script

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Some recent config.sample updates from core, part 2 of 2
Fixes: https://github.com/owncloud/docs/issues/4087 (Run config-to-docs after PR #39288 has been merged)
No backport !
@JanAckermann fyi
=> config sample updates part two (no backports needed)

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
Some recent config.sample updates from core, part 1 of  2
Backport to 10.8
=> config sample updates part one (backports needed)

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.8] [PR 4093] config sample updates part one (backports needed)

modules/admin_manual/pages/qnap/index.adoc
QTS version specified under System Requirements.
=> added OS requirements

modules/admin_manual/pages/qnap/index.adoc
=> [10.8] [PR 4098] added OS requirements

modules/admin_manual/pages/qnap/index.adoc
=> [10.8] [PR 4100] referencing ssl article for qnap

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.8] Remove wrong "does" [typo]

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.7] Remove wrong "does" [typo]

modules/admin_manual/pages/configuration/user/oidc/oidc.adoc
=> [10.8] [PR 4107] Another page aliases typo fixed

modules/user_manual/nav.adoc, modules/user_manual/pages/whats_new.adoc
=> [10.8] [PR 4109] Removing What's New section

modules/user_manual/nav.adoc, modules/user_manual/pages/whats_new.adoc
=> [10.7] [PR 4109] Removing What's New section

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
=> [10.7] [PR 4112] encryption key movement within data only

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/encryption_commands.adoc
=> [10.8] [PR 4112] encryption key movement within data only

modules/admin_manual/pages/configuration/search/index.adoc
=> [10.8] [PR 4118] correct link to occ search commands

modules/admin_manual/pages/configuration/search/index.adoc
=> [10.7] [PR 4118] correct link to occ search commands

bin/makepdf, lib/extensions/remote-include-processor.js, site.yml
=> [10.8] [PR 4186] Prepare the repo to include external adoc files

bin/makepdf, lib/extensions/remote-include-processor.js, site.yml
=> [10.7] [PR 4186] Prepare the repo to include external adoc files

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
=> [10.8] Minor text fix

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_file_commands.adoc
=> [10.7] Minor text fix

modules/admin_manual/pages/configuration/files/encryption/index.adoc
=> [10.8] [PR 4211] Fix page alias for encryption

modules/admin_manual/pages/configuration/files/encryption/index.adoc
=> [10.7] [PR 4211] Fix page alias for encryption

modules/admin_manual/pages/enterprise/logging/admin_audit.adoc
=> [10.8] [PR 4210] Fix page alias for admin audit

modules/user_manual/pages/_partials/nav.adoc
=> [10.8] [PR 4216] Fix one item double component entry in user manual nav

modules/admin_manual/pages/maintenance/backup.adoc
minimal fix for issue #4096 
Backports to 10.8 and 10.7
=> folder description in backup section

modules/admin_manual/pages/maintenance/backup.adoc
=> [10.8] [PR 4206] folder description in backup section

modules/admin_manual/pages/maintenance/backup.adoc
=> [10.7] [PR 4206] folder description in backup section

.gitignore, modules/ROOT/pages/client_releases.adoc, modules/ROOT/pages/server_release_notes.adoc, modules/ROOT/pages/server_releases.adoc, modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc, modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/troubleshooting.adoc, modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc, modules/developer_manual/pages/app/fundamentals/hooks.adoc, modules/developer_manual/pages/app/tutorial/database_connectivity.adoc, modules/developer_manual/pages/app/tutorial/request.adoc, modules/developer_manual/pages/general/_devenv_docker.adoc, modules/developer_manual/pages/general/devenv.adoc, modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc, modules/developer_manual/pages/testing/test-pilots.adoc, modules/developer_manual/pages/testing/ui-testing.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
=> [10.8] [PR 4220] Part one fixing broken anchors (in- and inter-document references)

.gitignore, modules/ROOT/pages/client_releases.adoc, modules/ROOT/pages/server_release_notes.adoc, modules/ROOT/pages/server_releases.adoc, modules/admin_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc, modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/troubleshooting.adoc, modules/developer_manual/pages/app/advanced/custom-cache-backend.adoc, modules/developer_manual/pages/app/fundamentals/hooks.adoc, modules/developer_manual/pages/app/tutorial/database_connectivity.adoc, modules/developer_manual/pages/app/tutorial/request.adoc, modules/developer_manual/pages/general/_devenv_docker.adoc, modules/developer_manual/pages/general/devenv.adoc, modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc, modules/developer_manual/pages/testing/test-pilots.adoc, modules/developer_manual/pages/testing/ui-testing.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/user_manual/pages/_partials/configuration/files/encryption/not-encrypted-files.adoc
=> [10.7] [PR 4220] Part one fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/restore.adoc, modules/admin_manual/pages/maintenance/update.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc, modules/developer_manual/pages/general/devenv.adoc
This is the second part fixing broken anchors...
=> Part two fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/restore.adoc, modules/admin_manual/pages/maintenance/update.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc, modules/developer_manual/pages/general/devenv.adoc
=> [10.8] [PR 4224] Part two fixing broken anchors (in- and inter-document references)

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/restore.adoc, modules/admin_manual/pages/maintenance/update.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc, modules/developer_manual/pages/general/devenv.adoc
=> [10.7] [PR 4224] Part two fixing broken anchors (in- and inter-document references)

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/search/index.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
=> [10.8] [PR 4230] Part four fixing broken anchors (in- and inter-document references)

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/search/index.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/softhsm2.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc
=> [10.7] [PR 4230] Part four fixing broken anchors (in- and inter-document references)

docs/checking-broken-links.md, package.json, yarn.lock
This PR updates the broken link description page and package.json.
=> Update checking broken link page and package.json

docs/checking-broken-links.md, package.json, yarn.lock
=> [10.8] [PR 4238] Update checking broken link page and package.json

docs/checking-broken-links.md, package.json, yarn.lock
=> [10.7] [PR 4238] Update checking broken link page and package.json

modules/ROOT/pages/server_release_notes.adoc
=> [10.8] [PR 4244] Exchange the enterprise repo link with the corresponding core PR link

modules/ROOT/pages/client_releases.adoc, modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc, modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc, modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/developer_manual/pages/app/fundamentals/database.adoc, modules/developer_manual/pages/app/fundamentals/info.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc, modules/developer_manual/pages/core/apis/ocs-notification-endpoint-v1.adoc, modules/user_manual/pages/_partials/direct_file_access_tip.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/pim/sync_thunderbird.adoc
=> [10.8] [PR 4247] Fixing external links returning 404

modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc, modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
Small fixes/corrections (section name, missing toc)
=> Small fixes (section name, missing toc)

modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc, modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.7] [PR 4256] Small fixes (section name, missing toc)

modules/admin_manual/pages/enterprise/external_storage/enterprise_only_auth.adoc, modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.8] [PR 4256] Small fixes (section name, missing toc)

modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
=> [10.7] [PR 4259] Update the Apache and Lets Encrypt documentation

modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_apache.adoc
=> [10.8] [PR 4259] Update the Apache and Lets Encrypt documentation

modules/ROOT/pages/client_releases.adoc, modules/developer_manual/pages/app/fundamentals/info.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc
=> [10.8] [PR 4264] Fixing external links returning 404 (part three)

modules/ROOT/pages/client_releases.adoc, modules/developer_manual/pages/app/fundamentals/info.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc
=> [10.7] [PR 4264] Fixing external links returning 404 (part three)

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.7] [PR 4268] Config to docs run from recent changes in core

modules/admin_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.8] [PR 4268] Config to docs run from recent changes in core

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc, modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc, modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/index.adoc, modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/developer_manual/pages/app/fundamentals/controllers.adoc, modules/developer_manual/pages/app/fundamentals/logging.adoc, modules/developer_manual/pages/bugtracker/index.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc, modules/developer_manual/pages/general/debugging.adoc, modules/developer_manual/pages/general/security.adoc, modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc, modules/developer_manual/pages/testing/acceptance-tests.adoc, modules/developer_manual/pages/testing/ui-testing.adoc, modules/user_manual/pages/files/webgui/navigating.adoc, modules/user_manual/pages/pim/sync_thunderbird.adoc
=> [10.7] [PR 4267] Fix redirect issues and external anchors

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/configuration/server/legal_settings_configuration.adoc, modules/admin_manual/pages/configuration/server/oc_server_tuning.adoc, modules/admin_manual/pages/configuration/user/oidc/kopano-setup.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/index.adoc, modules/admin_manual/pages/installation/apps/mediaviewer/index.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_prerequisites.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/developer_manual/pages/app/fundamentals/controllers.adoc, modules/developer_manual/pages/app/fundamentals/logging.adoc, modules/developer_manual/pages/bugtracker/index.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc, modules/developer_manual/pages/general/debugging.adoc, modules/developer_manual/pages/general/security.adoc, modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc, modules/developer_manual/pages/testing/acceptance-tests.adoc, modules/developer_manual/pages/testing/ui-testing.adoc, modules/user_manual/pages/files/webgui/navigating.adoc, modules/user_manual/pages/pim/sync_thunderbird.adoc
=> [10.8] [PR 4267] Fix redirect issues and external anchors

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.8] [PR 4274] s3_compatible_object_storage_as_primary.adoc use marketplace with /apps/

modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.7] [PR 4274] s3_compatible_object_storage_as_primary.adoc use marketplace with /apps/

site.yml
=> [10.8] [PR 4282] New Android version

site.yml
=> [10.7] [PR 4282] New Android version

modules/ROOT/pages/client_releases.adoc
Adding the Android previos release line in the clients section.
=> Adding Android previous release

modules/ROOT/pages/client_releases.adoc
=> [10.7] [PR 4285] Adding Android previous release

modules/ROOT/pages/client_releases.adoc
=> [10.8] [PR 4285] Adding Android previous release

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_app_commands.adoc
Fixes: https://github.com/owncloud/docs/issues/4117 ("occ app:list -m" option for minimalistic app list view)
* A new option has been added to the occ app:list command
* Added missing sections
* Table fixes
* Text fixes
No Backport
=> Add new app:list option -m

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_encryption_commands.adoc
Fixes: #4153 ("New option in occ encryption:fix-encrypted-version)
* A new option has been added to the occ encryption:fix-encrypted-version command
* Fixed section levels
* Table fixes
* Text fixes
No Backport
=> Add new encryption:fix-encrypted-version option -i

modules/admin_manual/pages/installation/deployment_recommendations.adoc
Based on feedback, the Deployment Recommendation document got revised.
* General text cleanup
* Table cleanup
* Separate technical recommendations from ownCloud Edition selection
=> Revision of the Deployment Recommendation document

modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
=> [10.8] [PR 4297] Revise LDAP Home Connector

modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc
=> [10.7] [PR 4297] Revise LDAP Home Connector

modules/admin_manual/pages/installation/deployment_recommendations.adoc
=> [10.7] [PR 4295] Revision of the Deployment Recommendation document

modules/admin_manual/pages/installation/deployment_recommendations.adoc
=> [10.8] [PR 4295] Revision of the Deployment Recommendation document

docs/new-version-branch.md
=> [10.8] [PR 4310] correct name of the server release file

docs/new-version-branch.md
=> [10.7] [PR 4310] correct name of the server release file

docs/new-version-branch.md
This is a text suggestion for the PR to be created. It eases the process in step 2 creating a PR and helps keeping things in mind before pressing the merge button.
=> Improve new version branch text

docs/new-version-branch.md
=> [10.9] [PR 4310] correct name of the server release file

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.7] [PR 4316] Add page alias for encryption_configuration

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.9] [PR 4316] Add page alias for encryption_configuration

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.8] [PR 4316] Add page alias for encryption_configuration

docs/new-version-branch.md
=> [10.7] [PR 4313] Improve new version branch text

docs/new-version-branch.md
=> [10.8] [PR 4313] Improve new version branch text

docs/new-version-branch.md
=> [10.9] [PR 4313] Improve new version branch text

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Fixes: https://github.com/owncloud/docs/issues/4269 (Let's encrypt docs improvement v2)
Based on the comments in the issue above, some improvements and fixes have been made.
=> Improve Letsencrypt and Apache

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.9] [PR 4314] Improve Letsencrypt and Apache

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.8] [PR 4314] Improve Letsencrypt and Apache

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.7] [PR 4314] Improve Letsencrypt and Apache

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
Fixes issue #4307
Needs backports to 10.9 10.8 10.7
=> Add missing comma in page-aliases

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.9] Add missing comma in page-aliases

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.8] Add missing comma in page-aliases

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.7] Add missing comma in page-aliases

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc, modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.8] [PR 4330] Improve S3 primary

modules/admin_manual/pages/configuration/files/external_storage/configuration.adoc, modules/admin_manual/pages/configuration/files/external_storage/s3_compatible_object_storage_as_primary.adoc
=> [10.7] [PR 4330] Improve S3 primary

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
=> [10.8] [PR 4331] Fix occ user commands

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
=> [10.9] [PR 4331] Fix occ user commands

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
=> [10.7] [PR 4331] Fix occ user commands

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
=> [10.9] [PR 4340] Update MariaDB guide

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
=> [10.8] [PR 4340] Update MariaDB guide

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation_db.adoc
=> [10.7] [PR 4340] Update MariaDB guide

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] Minor installation doc changes

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] Minor installation doc changes

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
Just a couple more changes to `mariadb.adoc`
And while I was there, I read through `useful_tips.adoc`
And minor fixes to `manual_upgrade.adoc`
=> Minor installation doc changes

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc, modules/admin_manual/pages/_partials/installation/manual_installation/useful_tips.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.7] Minor installation doc changes

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
This is part four implementing MariaDB 10.6.
* Text improvements making the topic more clear
Referencing: #4115 (MariaDb 10.6)
=> MariaDB text improvements

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
=> [10.9] [PR 4355] MariaDB text improvements

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
=> [10.8] [PR 4355] MariaDB text improvements

modules/admin_manual/pages/_partials/installation/manual_installation/mariadb.adoc
=> [10.7] [PR 4355] MariaDB text improvements

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 4362] Improve webserver text in manual upgrade

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 4362] Improve webserver text in manual upgrade

modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.7] [PR 4362] Improve webserver text in manual upgrade

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc, modules/admin_manual/pages/configuration/user/user_management.adoc
Fixes: https://github.com/owncloud/docs/issues/3971 (New occ command: occ user:move.home)
New occ command `user:move`
* Add occ description
* Add section in User Management
=> New occ command user:move

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc, modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.9] [PR 4361] New occ command user:move

modules/admin_manual/pages/_partials/nav.adoc, modules/admin_manual/pages/maintenance/upgrading/database_upgrade.adoc
=> [10.9] [PR 4360] Upgrade guide for MariaDB 10.6

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
=> [10.7] [PR 4353] Fix Backup and Restore

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
=> [10.8] [PR 4353] Fix Backup and Restore

modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/restore.adoc
=> [10.9] [PR 4353] Fix Backup and Restore

.drone.star
fixes #4253 
Other doc repos:
- https://github.com/owncloud/docs-client-android/pull/24
- https://github.com/owncloud/docs-client-ios-app/pull/20
- https://github.com/owncloud/docs-client-desktop/pull/153
=> cancel recent builds

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.9] [PR 4371] Add MariaDB 10.6 to system requirements

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.8] [PR 4371] Add MariaDB 10.6 to system requirements

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.7] [PR 4371] Add MariaDB 10.6 to system requirements

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
=> [10.9] [PR 4372] Cleanup of occ dav commands

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
=> [10.7] [PR 4372] Cleanup of occ dav commands

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_dav_commands.adoc
=> [10.8] [PR 4372] Cleanup of occ dav commands

modules/admin_manual/pages/installation/system_requirements.adoc
This was only a problem in 10.8 and 10.7.
PR for 10.7 is #4380
=> [10.8] Fix typo

modules/admin_manual/pages/installation/system_requirements.adoc
This was only a problem in 10.8 and 10.7.
PR for 10.8 is #4379
=> [10.7] Fix typo

modules/admin_manual/pages/installation/docker/index.adoc
=> [master] [PR 4381] [10.8] Fix Admin Username / Password Typo

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.9] [PR 4381] [10.8] Fix Admin Username / Password Typo

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.7] [PR 4381] [10.8] Fix Admin Username / Password Typo

modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.9] Fix pdf unordered list warning

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
- Added MS Teams Bridge-App link
- Added note for basic auth
=> Added Microsoft Teams Bridge-App link

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.9] [PR 4391] Added Microsoft Teams Bridge-App link

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.8] [PR 4391] Added Microsoft Teams Bridge-App link

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
=> [10.7] [PR 4391] Added Microsoft Teams Bridge-App link

modules/admin_manual/pages/configuration/integration/ms-teams.adoc
Fixes a missing attribute in 10.7
No backport
=> [10.7 only] fix missing attribute

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_activity_commands.adoc
=> [10.9] [PR 4404] New occ Activity commands

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_activity_commands.adoc
=> [10.8] [PR 4404] New occ Activity commands

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_activity_commands.adoc
=> [10.7] [PR 4404] New occ Activity commands

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.9] [PR 4401] Improve manual and script guided upgrade

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.8] [PR 4401] Improve manual and script guided upgrade

modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc, modules/admin_manual/pages/maintenance/upgrading/manual_upgrade.adoc
=> [10.7] [PR 4401] Improve manual and script guided upgrade

modules/developer_manual/pages/core/theming.adoc
=> [10.7] [PR 4409] Fix and update theming

modules/developer_manual/pages/core/theming.adoc
=> [10.9] [PR 4409] Fix and update theming

modules/admin_manual/pages/configuration/server/email_configuration.adoc
=> [10.9] [PR 4418] Fix email typo

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 4421] LDAP Module missing

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.7] [PR 4421] LDAP Module missing

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.7] [PR 4420] add complete tar ball

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] [PR 4420] add complete tar ball

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 4420] add complete tar ball

modules/user_manual/pages/files/version_control.adoc, modules/user_manual/pages/files/webgui/navigating.adoc
=> [10.7] [PR 4423] Small fixes in user doc

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
We recently received more reports about jquery warnings.
I updated this page so that we can just link to the docs.
=> add more known and patched jquery issues

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.9] [PR 4441] add more known and patched jquery issues

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.8] [PR 4441] add more known and patched jquery issues

modules/admin_manual/pages/configuration/server/security/jquery_warnings.adoc
=> [10.7] [PR 4441] add more known and patched jquery issues

modules/developer_manual/pages/app/fundamentals/js.adoc
=> [10.9] [PR 4440] Add guide for registering file actions in JavaScript

modules/developer_manual/pages/app/fundamentals/js.adoc
=> [10.8] [PR 4440] Add guide for registering file actions in JavaScript

modules/developer_manual/pages/app/fundamentals/js.adoc
=> [10.7] [PR 4440] Add guide for registering file actions in JavaScript

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.9] [PR 4300] occ LDAP update

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.8] [PR 4300] occ LDAP update

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.8] [PR 4455] Minor edits after occ LDAP update PR 4300

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_ldap_integration_commands.adoc
=> [10.9] [PR 4455] Minor edits after occ LDAP update PR 4300

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
=> [10.9] [PR 4454] Add note for user:move occ command

modules/ROOT/pages/client_releases.adoc, site.yml
=> [10.9] [4464] Changes necessary for the iOS 11.8 branch

modules/ROOT/pages/client_releases.adoc, site.yml
=> [10.7] [4464] Changes necessary for the iOS 11.8 branch

modules/ROOT/pages/client_releases.adoc, site.yml
=> [10.8] [4464] Changes necessary for the iOS 11.8 branch 

modules/ROOT/pages/client_releases.adoc
=> [10.9] [PR 4470] Fixing the ios-app client attribute

modules/admin_manual/pages/configuration/search/index.adoc, modules/user_manual/pages/files/webgui/search.adoc
=> [10.9] [PR 4155] Content for search elastic v2

modules/admin_manual/pages/configuration/search/index.adoc, modules/user_manual/pages/files/webgui/search.adoc
=> [10.8] [PR 4155] Content for search elastic v2

modules/admin_manual/pages/configuration/search/index.adoc, modules/user_manual/pages/files/webgui/search.adoc
=> [10.7] [PR 4155] Content for search elastic v2

modules/user_manual/pages/files/webgui/search.adoc
Error in wildcard descriptions fixed.
Backports to 10.9, 10.8, 10.7 needed
=> fixing error in wildcards

modules/user_manual/pages/files/webgui/search.adoc
=> [10.9] [PR 4475] fixing error in wildcards

modules/user_manual/pages/files/webgui/search.adoc
=> [10.8] [PR 4475] fixing error in wildcards

modules/user_manual/pages/files/webgui/search.adoc
=> [10.7] [PR 4475] fixing error in wildcards

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
General recommendations. Needs backports to all versions.
=> Add limitations to Secure View documentation

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.9] [PR 4484] Add limitations to Secure View documentation

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.8] [PR 4484] Add limitations to Secure View documentation

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.7] [PR 4484] Add limitations to Secure View documentation

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.9] [PR 4482] Add rsync to the manuall install prerequisites

modules/admin_manual/pages/configuration/server/config_sample_php_parameters.adoc
=> [10.9] [PR 4493] config-to-docs run

modules/developer_manual/pages/core/apis/provisioning-api.adoc
=> [10.9] [PR 4495] Explain quota and last_login fields of Get User API response

antora.yml, site.yml
=> [10.9] [PR 4500] Move branch specific attributes from global site.yml to branch relevant antora.yml

antora.yml, site.yml
=> [10.8] [PR 4500] Move branch specific attributes from global site.yml to branch relevant antora.yml

antora.yml, site.yml
=> [10.7] [PR 4500] Move branch specific attributes from global site.yml to branch relevant antora.yml

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc, modules/admin_manual/pages/configuration/user/user_management.adoc
=> [10.9] [PR 4499] Document occ user:home

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] Add PHP extensions to various docs

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_18.04.adoc, modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_18_04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.8] Add PHP extensions to various docs

modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_user_commands.adoc
=> [10.9] Small typo-fix for occ user:move-home

modules/ROOT/pages/server_release_notes.adoc
Draft mode. Still some parts missing.
=> 10.9 Release Notes

modules/ROOT/pages/server_release_notes.adoc
=> [10.9] Release Notes for 10.9

modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] Use the current tarball to install 10.9.0

modules/user_manual/pages/_partials/nav.adoc
=> [10.9] [PR 4531] Fix orphaned search in user docs

modules/user_manual/pages/_partials/nav.adoc
=> [10.8] [PR 4531] Fix orphaned search in user docs

modules/admin_manual/pages/configuration/search/index.adoc, modules/user_manual/pages/files/webgui/search.adoc
=> Updates for the Full Text Search App

modules/admin_manual/pages/configuration/search/index.adoc, modules/user_manual/pages/files/webgui/search.adoc
=> [10.9] [PR 4534] Updates for the Full Text Search App

modules/admin_manual/pages/configuration/search/index.adoc, modules/user_manual/pages/files/webgui/search.adoc
=> [10.8] [PR 4534] Updates for the Full Text Search App

modules/ROOT/pages/server_release_notes.adoc
=> [10.9] [PR 4539] Known Issue: Marketplace not working after upgrade from 10.8 to 10.9

docs/best-practices.md, docs/build-the-docs.md, modules/developer_manual/pages/bugtracker/triaging.adoc
=> [10.9] [PR 4541] Fix a pdf build issue

docs/best-practices.md, docs/build-the-docs.md, modules/developer_manual/pages/bugtracker/triaging.adoc
=> [10.8] [PR 4541] Fix a pdf build issue

modules/ROOT/pages/server_release_notes.adoc
=> [10.9] [PR 4546] Added Known issue (encryption)

modules/ROOT/pages/server_release_notes.adoc
=> [10.9] [PR 4550] Itemize the known issues section for 10.9

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/integration/ms-teams.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/manual_installation/manual_installation.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc, modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc, modules/developer_manual/pages/commun/help_and_communication.adoc, modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc, site.yml
=> [10.9] [PR 4554] Global Attribute Cleanup

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.8] [PR 4553] revert #4381

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.9] [PR 4553] revert #4381

modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
Fix for issue #4507.
Backports to 10.9 and 10.8 necessary.
=> imagemagick required for 2FA

modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
=> [10.9] [PR 4559] imagemagick required for 2FA

modules/admin_manual/pages/configuration/user/user_auth_twofactor.adoc
=> [10.8] [PR 4559] imagemagick required for 2FA

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.9] [PR 4566] added imagemagick among the common prerequisites

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc
=> [10.8] [PR 4566] added imagemagick among the common prerequisites

modules/admin_manual/pages/configuration/files/previews_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
Cleaning up the last references to Ubuntu 18.4.
=> Last references to Ubuntu 18.04

modules/admin_manual/pages/configuration/files/previews_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/server/occ_commands/core_commands/_config_commands.adoc, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/manual_installation/manual_imagick7.adoc
=> [10.9] [PR 4569] Last references to Ubuntu 18.04

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.9] [PR 4571] Lower case in secure view

modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.8] [PR 4571] Lower case in secure view

modules/ROOT/pages/client_releases.adoc, site.yml
=> [10.9] [PR 4577] change the branding client url

modules/ROOT/pages/client_releases.adoc, site.yml
=> [10.8] [PR 4577] change the branding client url

modules/ROOT/pages/client_releases.adoc
=> [10.9] [PR 4580] fix branded clients access link

modules/ROOT/pages/client_releases.adoc
=> [10.8] [PR 4580] fix branded clients access link

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.9] [PR 4585] Update and fix big file upload

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.8] [PR 4585] Update and fix big file upload

modules/admin_manual/pages/installation/manual_installation/server_prep_ubuntu_20.04.adoc, modules/admin_manual/pages/installation/quick_guides/ubuntu_20_04.adoc
=> [10.9] [PR 4588] Add page-aliases for removed U18.04 documents

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
=> removing deprecated repo url

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc
=> [10.9] [PR 4591] removing deprecated repo url

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc, site.yml
=> [10.9] [PR 4594] added link to installation repos

modules/ROOT/pages/server_release_notes.adoc, modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc, modules/admin_manual/pages/installation/linux_packetmanager_install.adoc, modules/admin_manual/pages/maintenance/backup_and_restore/backup.adoc, modules/admin_manual/pages/maintenance/upgrading/package_upgrade.adoc, site.yml
=> [10.8] [PR 4594] added link to installation repos

modules/ROOT/pages/server_release_notes.adoc, site.yml
Preliminary release notes for 10.9.1
**do not merge before release of 10.9.1**
=> Added preliminary Releasenotes for 10.9.1

modules/ROOT/pages/server_release_notes.adoc, site.yml
=> [10.9] [PR 4552] Added preliminary Releasenotes for 10.9.1

modules/user_manual/pages/personal_settings/security.adoc
This fixes issue #4538.
Backports to 10.9 and 10.8.
=> layout error fixed

modules/user_manual/pages/personal_settings/security.adoc
=> [10.9] [PR 4607] layout error fixed

modules/user_manual/pages/personal_settings/security.adoc
=> [10.8] [PR 4607] layout error fixed

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> Add limitation about encryption to WOPI docs

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.9] [PR 4610] Add limitation about encryption to WOPI docs

README.md, docs/antora-site-structure.md
=> [10.9] [PR 4616] Add Antora Site Structure Description for Docs

README.md, docs/antora-site-structure.md
=> [10.8] [PR 4616] Add Antora Site Structure Description for Docs

docs/antora-site-structure.md
Adjusts the text added in #4616 
I will also push to the other copies of this.
Backports done:
10.9 #4620 
10.8 #4621
=> Fix typos in antora-site-structure.md

docs/antora-site-structure.md
=> [10.9] Fix typos in antora-site-structure.md

docs/antora-site-structure.md
=> [10.8] Fix typos in antora-site-structure.md

docs/antora-site-structure.md
Adding some clarifying information.
Backport of #4622
=> [10.9] Update antora-site-structure.md

docs/antora-site-structure.md
Adding some clarifying information.
Backport of #4622
=> [10.8] Update antora-site-structure.md

site.yml
=> [10.8] [PR 4520] Prepare for Desktop 2.10

site.yml
=> [10.9] [PR 4520] Prepare for Desktop 2.10

.prettierrc, generator/generate-site.js, package.json, yarn.lock
=> fix: fix elastic index handling

.prettierrc, generator/generate-site.js, package.json, yarn.lock
=> [10.9] [PR 4633] fix: fix elastic index handling

.prettierrc, generator/generate-site.js, package.json, yarn.lock
=> [10.8] [PR 4633] fix: fix elastic index handling

.drone.star
=> [10.9] [PR 4636] fix: fix elastic env vars in drone config

.drone.star
=> [10.8] [PR 4636] fix: fix elastic env vars in drone config

site.yml
=> [10.9] [PR 4640] Update site.yml

site.yml
=> [10.8] [PR 4640] Update site.yml

site.yml
=> [10.9] [PR 4639] Add attribute necessary for embedding opengraph images in docs-ui automatically

site.yml
=> [10.8] [PR 4639] Add attribute necessary for embedding opengraph images in docs-ui automatically

modules/admin_manual/pages/enterprise/reporting/metrics.adoc
=> [10.9] [PR 4223] New metrics features

modules/admin_manual/pages/enterprise/reporting/metrics.adoc
=> [10.8] [PR 4223] New metrics features

antora.yml
References: #4647
This is the master part of the antora.yml fix
No backport !
=> master antora.yml attribute fix refs 4647

docs/antora-site-structure.md, site.yml
=> [10.9] [PR 4647] Some fixes

docs/antora-site-structure.md
Clarifications and improvements
=> antora site structure documentation update

docs/antora-site-structure.md
=> [10.9] [PR 4655] antora site structure documentation update

docs/antora-site-structure.md
=> [10.8] [PR 4655] antora site structure documentation update

docs/new-version-branch.md
=> [10.9] [PR 4658] update of the new version branch documentation

docs/new-version-branch.md
=> [10.8] [PR 4658] update of the new version branch documentation

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
Small improvements of the backport script and description.
* The description changes were mostly removing unecessary linebreakes which are anyways removed by the build process and some text improvements.
* The variables in the script got curly braces around them
=> update the backport script

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.9] [PR 4664] update the backport script

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.8] [PR 4664] update the backport script

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.9] [PR 4667] Fix Richdocuments and the corrsponding occ comand set

modules/admin_manual/pages/configuration/server/occ_commands/app_commands/_richdocuments.adoc, modules/admin_manual/pages/enterprise/collaboration/collabora_secure_view.adoc
=> [10.8] [PR 4667] Fix Richdocuments and the corrsponding occ comand set

modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.9] [PR 4671] Update nfs to avoid boot stuck when nfs server is not available

modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.8] [PR 4671] Update nfs to avoid boot stuck when nfs server is not available

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc, modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc, modules/admin_manual/partials/nav.adoc
=> [10.9] [PR 4674] Add how to remove non existent background jobs

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc, modules/admin_manual/pages/troubleshooting/remove_non_existent_bg_jobs.adoc, modules/admin_manual/partials/nav.adoc
=> [10.8] [PR 4674] Add how to remove non existent background jobs

package.json
=> [10.8] [PR 4676] adding a build command for staging

package.json
=> [10.9] [PR 4676] adding a build command for staging

modules/ROOT/pages/index.adoc
Fix missing component in reference.
This made the reference not resolvable and the link look weired
=> Fix missing component in reference

site.yml
Update site.yml version attribute for Android
=> Update site.yml version attribute for Android

docs/best-practices.md
=> Minor language fixes

modules/ROOT/pages/server_release_notes.adoc
Some links to the server dev docs were broken - fixed
=> Fix release notes links to server dev docs

site.yml
Prepare ocis relevant attributes for the upcoming deployment.
=> Prepare ocis relevant attributes

modules/ROOT/partials/nav.adoc
Nav text fix `ownCloud Infinite Scale Documentation` --> `Infinite Scale Documentation`
=> Nav text fix

.github/settings.yml
Found the last instance of "enterpise" for now.
=> enterpise typo

site.yml
Updates the attribute for ocis beta 3
Merging when we get the ok from @micbar
=> Prepare for ocis beta 3

README.md, docs/checking-broken-links.md, site.yml
This is just a small PR to remove an unused ocis attribute plus some small text changes in the internal docs.
=> small fixes

modules/ROOT/pages/ocis_release_notes.adoc
Let me know or add yourself if something important is missing. THX.
=> 2.0.0beta6 release notes

site.yml
=> Update site.yml for ocis beta.6

site.yml
Add missing `./` at the occ command attribute (occ --> ./occ)
=> The occ command missed a ./ in the attribute

site.yml
Merge when the files are availabe for download else the ocis download link in the documentation will not work.
@kulmann @pmaier1 fyi
=> Prepare for ocis beta.7

modules/ROOT/pages/server_release_notes.adoc
Draft. List of updated apps still missing.
=> Server 10.11 Release Notes

modules/ROOT/pages/server_release_notes.adoc
Does that make sense in the known issues section?
Or should it be else where?
=> Add a guzzle notice

modules/ROOT/pages/server_release_notes.adoc
https://github.com/owncloud/enterprise/issues/5428
Not sure if my proposed list is complete, please double check
Backport to 10.11 and 10.10
=> Known issue guests app

modules/ROOT/pages/client_releases.adoc, modules/ROOT/pages/how_to_contribute.adoc, modules/ROOT/partials/nav.adoc
This is a post fix/improvement for #4792 (Rename Classic Server (no reference changes))
* Improve nav (no reference changes)
* Fix contribution document
=> Harmonize nav and fix contribute

modules/ROOT/pages/ocis_release_notes.adoc
=> Added Releasenotes 2.0.0

site.yml
Referencing: https://github.com/owncloud/docs-client-desktop/pull/292 (Changes necessary for 3.0)
**ONLY MERGE** when the referenced PR above has been merged.
This PR finalizes the Desktop 3.0 preparation from the docs pov.
Content changes are to be made post merging in the docs-client-desktop repo.
=> Changes necessary for Desktop 3.0

modules/ROOT/pages/index.adoc, modules/ROOT/pages/ocis_release_notes.adoc, modules/ROOT/partials/nav.adoc
This update:
* Move content to the correct location
* Correct release notes + add breaking changes for ocis
* Improve the overview section
Language review welcomed
@EParzefall pls do a local build and check the links changed, 4 eyes is better than 2 😄
=> Update release notes the overview and other pages

README.md, docs/checking-broken-links.md
Just a small fix for a broken link.
=> Fix broken link in readme.md

modules/ROOT/pages/index.adoc, modules/ROOT/pages/server_release_notes.adoc, site.yml
Draft of 10.12.1 Release Notes. More items to be still documented.
=> Server 10.12.1 Release Notes

modules/ROOT/pages/server_release_notes.adoc
Note: I also deleted the description of a workaround. If someone has this problem, the current solution is now to upgrade to 10.12.1
=> Adjust known issues in 10.12.0

modules/ROOT/pages/server_release_notes.adoc, site.yml
=> 10.12.2 Release Notes

docs/checking-broken-links.md
As the title says, updates based on actual work
=> Update the broken linkchecker documentation

modules/ROOT/pages/client_releases.adoc, modules/ROOT/pages/ocis_release_notes.adoc, modules/ROOT/pages/server_release_notes.adoc
=> Fix Broken Links

modules/ROOT/pages/index.adoc
https://github.com/owncloud/ios-app/releases
=> iOS app 12+ with Spaces support

bin/optimize_crawl
This updates the script as now all manuals follow the same scheme.
There are no changes in the output but we are now prepared _if_ we are going to versionize the added ones.
Locally tested, works fine.
=> Update the optimize-crawl script

site.yml
References: https://github.com/owncloud/docs-client-desktop/pull/503 (Changes necessary for 4.2)
This are the changes neccessary for Desktop 4.2
**ONLY MERGE** after the referenced PR got merged.
@fmoc @HanaGemela @michaelstingl FYI
=> Changes necessary for Desktop 4.2

modules/ROOT/pages/server_release_notes.adoc
Now, we are final. ready to rumble.
=> updated apps list to RC2

modules/ROOT/pages/index.adoc
Fixes: #4872 ([QA] stuck with very short "Desktop App" doc page.)
The intro page needed an update:
* Reorderd sections
* Added missing web interfaces section
* Fixed some text to be up-to-date
@phil-davis a language review is welcomed
=> Update the intro page

.gitignore, modules/ROOT/pages/ocis_release_notes.adoc, site.yml
1. Paste to upload
2. Fulltext Search: Highlight Matches
3. Search: Location filter
4. Search: Tag Filter
5. Cloud Importer (extension)
6. Simplified Sharing Links
7. File Control Bar
8. Links: Directly Open in Editor
9. Drop files to the breadcrumb
10. Context Menu on whitespace
11. View Spaces as List
=> Release Note for ocis 4.0.0

site.yml
References: https://github.com/owncloud/docs-client-desktop/pull/518 (Changes necessary for 5.0)
Should be merged close to the release of Desktop 5.0
@HanaGemela @michaelstingl
=> Changes necessary for Desktop 5.0

modules/ROOT/pages/server_release_notes.adoc
Just a minor fix to render server release notes correctly
=> Update server_release_notes.adoc (minor fix)

modules/ROOT/pages/server_release_notes.adoc, site.yml
These are the release notes for ownCloud Server 10.13.2.
=> Server 10.13.2 Release Notes

modules/ROOT/pages/server_release_notes.adoc
I guess it is the other syntax.
=> fix URL syntax in server_release_notes.adoc

modules/ROOT/pages/server_release_notes.adoc, site.yml
These are the release notes for ownCloud Server 10.13.3.
=> Server 10.13.3 Release Notes

.gitignore, README.md, bin/prepare_site_yml, docs/build-the-docs.md, package.json
This PR is a first step describing an setting up a dev env.
Most likely more to come.
Some of the changes will also be transported to the other doc repos.
=> Setting up an Antora dev env

.gitignore, README.md
Just a small readme fix and allowing to change .drone.star
=> Small readme fix

docs/build-the-docs.md
References: #4853 (Upgrade the documentation framework)
This PR updates the development section plus adds a new section what to do when one wants to add/test the search field.
=> Update dev doc section and add search

README.md, docs/html-to-pdf.md
Move html to pdf to its own page giving readme a better overview.
=> Move html to pdf to its own page

modules/ROOT/pages/server_release_notes.adoc, site.yml
These are the release notes for ownCloud Server 10.13.4.
=> Server 10.13.4 Release Notes

docs/build-the-docs.md
=> Fix typo in build-the-docs.md

docs/build-the-docs.md
Describe how `Edit this page` gets resolved to Github when building locally.
=> Update build-the-docs.md (Edith this page)

ext-antora/comp-version.js
Improve the component output to be a table for ease of readbility.
=> Improve build component table output

site.yml
References: https://github.com/owncloud/docs-server/pull/1276 (Changes necessary for the 10.14 branch)
This are the changes necessary to render the 10.14 Server branch.
=> Changes necessary to provide Server 10.14

site.yml
=> Just a small fix to correct the ocis compile date

site.yml
Just a small change to set the correct ocis values for:
* Compile date
* Last stable version
=> Update site.yml to set correct ocis parameters

site.yml
This is just a small fix for a comment to make the case more clear
=> Fix comment in site.yml to make a usecase more clear

site.yml
Referencing: https://github.com/owncloud/docs-main/pull/39 (Release notes for ocis 5.0.3)
=> Referencing Infinite Scale 5.0.3

docs/build-the-docs.md
Based on experience, add a small docs to describe how to do that properly including "backporting".
=> Docs: Package and Dependency Management

site.yml
Only merge after the rolling release has been published.
=> Update ocis to rolling 6.3.0

site.yml
References: https://github.com/owncloud/docs-ocis/pull/1010 (Make the dynamics of stable/production more robust)
This PR must be merged together with the referenced PR to complete it. The sort order is not essential but all must be merged in a timely manner.
=> Update site.yml attribute for ocis

site.yml
=> Add ocis rolling 6.6.1

site.yml
References: https://github.com/owncloud/docs-main/pull/83 (Add ocis 5.0.9 release notes)
=> Set ocis to 5.0.9

global-attributes.yml
This PR is a preperation to handle a global attributes file for all repos.
With a subsequent PR, the relevant code and other changes will be added.
This will also be done in other doc repos!
Currently, this change only adds a file with attributes copied from site.yml
That file is the basis for all other repos and the future single point of maintenance.
With the next PR, the attributes will get removed from site.yml and code will be added that loads the attributes dynamically.
=> Create a global attributes file

site.yml
This is just a cleanup to remove already commented sources.
=> Remove commented sources

README.md, bin/git_commands/backport.sh, bin/git_commands/getcommits.sh, bin/git_commands/getpull.sh, bin/git_commands/squash.sh, docs/antora-site-structure.md, docs/build-the-docs.md, docs/doc-guidelines.md, docs/extensions.md, docs/getting-started.md, docs/new-version-branch.md, docs/the-build-pipeline.md
This PR updates the documentation about docs and adds git helper scripts for ease of use
=> Update docs about docs

docs/antora-site-structure.md, docs/getting-started.md
References: #5013 (Update docs about docs)
This is a follow up PR to do text fixes missed to commit in the referenced PR.
=> Text fixes

global-attributes.yml
References: https://github.com/owncloud/docs-ocis/pull/1146 (Update ocis to 7.1.1)
This PR updates ocis to 7.1.1
=> Update ocis to 7.1.1

global-attributes.yml
This PR updates release version for oC server and ocis.
=> Update several release versions

docs/antora-site-structure.md
=> Typo fix in antora-site-structure.md

global-attributes.yml
Update docs version for ocis to 7.1.2
Release notes will be added soon.
=> Switch ocis to 7.1.2

ext-antora/find-orphaned-files.js, false-positives.txt
Add the `Find Orphaned Files Extension` Antora extension (was missing here, added for completeness)
=> Update add antora extension
