owncloud/docs

modules/user_manual/pages/files/webgui/custom_groups.adoc
This backports
https://github.com/owncloud/documentation/pull/4363/files.
=> Backport 4363 from the documentation repo

modules/ROOT/pages/appliance/Office.adoc
Backports https://github.com/owncloud/documentation/pull/4355 to this repo.
=> Backport #4355 from the documentation repository

modules/ROOT/pages/configuration/server/occ_command.adoc
This commit backports https://github.com/owncloud/documentation/pull/4361, "_update occ command list for files external_".
=> Backport update occ command list for files external

modules/ROOT/pages/appliance/certificates.adoc
https://github.com/owncloud/documentation/pull/4370/files
=> Backport #4370 from the old documentation

modules/developer_manual/pages/general/devenv.adoc
https://github.com/owncloud/documentation/pull/4372
=> Backport #4268 from the old documentation

modules/ROOT/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
See: https://github.com/owncloud/documentation/pull/4339/files.
=> Backport #4339 from the old documentation

modules/ROOT/pages/configuration/server/occ_command.adoc
document the 2 new commands
Closes https://github.com/owncloud/documentation/issues/4403.
=> decrypt all options

modules/ROOT/pages/configuration/server/caching_configuration.adoc
Clarify that this is enabled by default.
=> transactional file locking enabled by default

modules/ROOT/nav.adoc
put docker on top, then manual installation, then packages
=> installation order

modules/ROOT/pages/appliance/installation.adoc
rework of the installation process.
renaming of links and titles .
=> appliance-installation

modules/ROOT/pages/faq/index.adoc
Info about upgrade from Community Version to Enterprise Version
=>  Info about upgrade from Community Version to Enterprise Version

modules/ROOT/pages/installation/manual_installation.adoc
put the code part on top of the document
=> restructured installation

modules/ROOT/pages/configuration/server/occ_command.adoc
The scenario without downtime has been missing. Add it.
=> Add second scenario to files:scan --repair

modules/ROOT/pages/configuration/server/antivirus_configuration.adoc
=> fixed image path

modules/ROOT/pages/configuration/server/occ_command.adoc
This info has duplicated the line below and just had less details.
=> Remove duplicated (and less detailed) docs about data-fingerprint

modules/ROOT/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/ROOT/pages/configuration/server/occ_app_command.adoc
This is a port of the file from the documentation repository.
=> Port occ_app_command.adoc and config_apps_sample_php_parameters from documentation

modules/ROOT/pages/appliance/login_information.adoc
added path in the container for the file extension blacklist
=> added path for ransomware

modules/ROOT/pages/configuration/server/occ_app_command.adoc, modules/ROOT/pages/configuration/server/occ_command.adoc
This PR adds the documentation to configure the Brute Force Protection app via the commandline.
Referencing: doc: https://github.com/owncloud/docs/issues/88 (Brute Force Protection parameters and description needs implementation in occ_app_command)
=> occ core/app command improvement including brute force protection

modules/ROOT/examples/installation/nginx/default-configuration.conf, modules/ROOT/examples/installation/nginx/subdirectory-configuration.conf
Small change: just adding json to the location directive.
Referencing core:
master: https://github.com/owncloud/core/pull/32718/ (When allowing pretty urls json files can also be loaded directly)
stable10: in progress (does not prevent merging)
=> Adding json to the nginx location directive

modules/ROOT/pages/configuration/server/occ_app_command.adoc, modules/ROOT/pages/configuration/server/occ_command.adoc
These are more fixes to the occ command files
- Notification was in the wrong file
- Creating tables for Arguments and Options 
- Creating a unified look and feel for Arguments for Options
- Various optical fixes
=> more occ fixes

site.yml
The referenced branches have been pushed by me, they are far away from being final but I wanted to start with that to get it into a working state.
=> Start to add client docs/repos

modules/user_manual/pages/files/desktop_mobile_sync.adoc
- https://github.com/owncloud/documentation/pull/4436 
- https://github.com/owncloud/documentation/pull/4437
=> Backport fix download links

modules/ROOT/pages/configuration/server/occ_command.adoc
This is a the first part of a set of fixes for the occ command file after the base fix PR has been made and merge (#113).
There will be more fixes to come but I will keep them in separate PR´s so working on it is easier and others can do changes and updates too.
=> Even more occ_command fixes I

modules/ROOT/pages/configuration/server/occ_app_command.adoc, modules/ROOT/pages/configuration/server/occ_command.adoc
The next update...
- password policy had entries in both occ files
- harmonisation
- consistently adding the sudo commands 
- many new tables for arguments and options
- fixed sort order of user commands (was distributed around in the document and not sorted)
- and much more
To see the result you need to render it 😃
=> The next occ (app) command update

modules/ROOT/pages/enterprise/file_management/files_tagging.adoc
install the Collaborative tag management app for managing tags
Edit:
References issue: https://github.com/owncloud/docs/issues/129 (Installing Collaborative tag management app missing from doc)
=> install the Collaborative tag management app

modules/ROOT/nav.adoc, modules/ROOT/pages/configuration/server/occ_app_command.adoc, modules/ROOT/pages/configuration/server/occ_command.adoc
- removed a non working rst label (before pwd protection)
the reference to must be corrected in https://github.com/owncloud/docs/blob/f4267d7c426c8d080f509712e1fb5f1404d2e536/modules/ROOT/pages/configuration/server/security/password_policy.adoc
- added correct tables to ransomware
- did a text line break, no change in rendering, just for better readbility in the file
=> The next occ fix

modules/ROOT/pages/configuration/user/user_provisioning_api.adoc, modules/developer_manual/pages/app/fundamentals/controllers.adoc, modules/developer_manual/pages/app/fundamentals/info.adoc, modules/developer_manual/pages/app/fundamentals/routes.adoc
This PR corrects a series of small issues that cause the build process to throw warnings and errors.
=> Fix build issues

modules/administration_manual/pages/configuration/server/occ_command.adoc
This is a minor occ system command update.
For whatever reason, it slipped thru updating #144 
(my commit with these changes was not uploaded)
=> minor occ system command update

modules/administration_manual/nav.adoc, modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
This adds the required content to the enterprise section of the documentation. It fixes #159.
=> Add Document Classification and Policy Enforcement section

.drone.yml, resources/themes/owncloud-theme.yml
Two of the Open Sans fonts in the ownCloud PDF configuration file had filename errors. This PR corrects the errors.
=> Fix fonts configuration in owncloud theme

modules/administration_manual/pages/appliance/Office.adoc
This PR fixes the image names for Office.adoc
Copied 1:1 from documentation as manual task
Another million image names from other files left, but a start... 😄
=> Fixing the image names from Office.adoc

.gitignore
=> Ignore the cache directory

package-lock.json, package.json
After a lot of thought, and some troubleshooting, it makes sense (to me at least, if no one else) to install all required packages locally for building the documentation. To simplify that process, this commit provides an initial package.json and package-lock.json file, that contain the core dependencies, along with other package metadata.
=> Add package.json and package-lock.json

docs/build-the-docs.md, docs/checking-broken-links.md, docs/getting-started.md
This adds example outputs to the broken link checkers
=> adding example outputs to broken link checkers

modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
This backports https://github.com/owncloud/documentation/pull/4453 to the new documentation.
=> Backport Updates to Classification and Policy Enforcement (4453)

modules/administration_manual/pages/configuration/database/linux_database_configuration.adoc, modules/administration_manual/pages/enterprise/user_management/saml_2.0_sso.adoc, modules/administration_manual/pages/installation/deployment_recommendations.adoc, modules/administration_manual/pages/installation/linux_installation.adoc, modules/developer_manual/pages/app/advanced/extstorage.adoc, modules/developer_manual/pages/app/fundamentals/css.adoc, modules/developer_manual/pages/app/fundamentals/database.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc, modules/developer_manual/pages/core/translation.adoc, modules/developer_manual/pages/core/ui-testing.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/security.adoc, modules/developer_manual/pages/mobile_development/ios_library/library_installation.adoc
This is the next step in fixing broken links.
- fixing external broken or redirected links
- using link: on any real external http(s) link 
- text fixes
- link text improvements
- line breaking for better readability
=> next step fixing broken links

modules/administration_manual/pages/installation/system_requirements.adoc
- We cannot support tumbleweed.
- Add fedora 29 and remove 26 that is out of support
- Remove no longer supported LEAP releases, add LEAP 15
=> Update supported distributions

README.md, docs/test-ui-bundle.md
This is an improvement of README.md based on a discussion with @settermjd 
There will be a another commit in docs-ui to improve that readme .
=> Improve readme

README.md, docs/best-practices.md
This is the starting point for a "living" document giving contributors a page to quickly lookup common things you have to usually search for when adding content.
The intention is to avoid common pitfalls respctively reduce the time to be productive.
=> Best practices

modules/administration_manual/pages/configuration/server/occ_command.adoc
Fixes https://github.com/owncloud/docs/issues/419 (New option in occ command files_external:list --short)
=> New option in occ command files_external:list `--short`

docs/best-practices.md
Small text fixes / improvemets for Best Practices
=> Small text fixes / improvements for Best Practices

README.md, docs/best-practices.md, docs/build-the-docs.md, docs/checking-broken-links.md, docs/getting-started.md, docs/install-antora.md
This PR fixes and updates some parts of docs readme files.
- fix render issue
- adding preraration items
- resorting preparation items
- adding yarn as prerequisite
- adding make install for the dependencies
- some text fixes
- fixing anchor definition (https://github.com/owncloud/docs/pull/435)
=> Fixes and updates to 

generators/validator.js
Without this fix the validator exists with code 1 even if there are not any validation issues.
=> Just exit 0 if no validation errors

.drone.yml, site.yml
Just set the correct production domain to doc.owncloud.com
=> Set the correct base domain

modules/administration_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/administration_manual/pages/configuration/server/config_sample_php_parameters.adoc
These are some fixes to the config sample files.
- changing header end name to be more precise
- fixing missing level text
- fixing missing code block definition
most of the fixes need also a fix in core to avoid manual post processing - will file a PR.
=> config sample fixes

modules/administration_manual/nav.adoc, modules/developer_manual/nav.adoc, modules/user_manual/nav.adoc
Enhances the navigation and fixes orphand entries
**Example Before**
**Example After**
=> navigation improvement

docs/best-practices.md
This PR enhances the admonition and tables section in best-practices.md
=> improve best practices: admonition and tables

modules/administration_manual/pages/configuration/server/occ_app_command.adoc
This PR fixes: https://github.com/owncloud/docs/issues/449 (Document new install and upgrade options)
Plus some additional minor fixes.
=> market app update

modules/administration_manual/pages/configuration/files/file_sharing_configuration.adoc
Rewording a sentence, removing "I think" ...
=> fix "I think"

modules/developer_manual/examples/core/webdav_api/group/report-customgroups.xml, modules/developer_manual/examples/core/webdav_api/group/request/list-custom-group-members.xml, modules/developer_manual/examples/core/webdav_api/group/request/list-custom-groups.xml, modules/developer_manual/examples/core/webdav_api/group/request/rename-custom-group.xml, modules/developer_manual/examples/core/webdav_api/group/response-success.xml, modules/developer_manual/examples/core/webdav_api/group/response/list-group-members-successful-response.xml, modules/developer_manual/examples/core/webdav_api/group/response/list-group-memberships-of-a-given-user-successful-response.xml, modules/developer_manual/examples/core/webdav_api/group/response/list-groups-missing-group-response.xml, modules/developer_manual/examples/core/webdav_api/group/response/list-groups-no-results-response.xml, modules/developer_manual/examples/core/webdav_api/group/response/list-groups-successful-response.xml, modules/developer_manual/nav.adoc, modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc, modules/developer_manual/pages/_partials/webdav_api/responses/insufficient-privileges-overview.adoc, modules/developer_manual/pages/_partials/webdav_api/uri_request_table.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
This relates to https://github.com/owncloud/customgroups/issues/3 and fixes #413.
=> Document the WebDAV Custom Groups Management API

modules/administration_manual/pages/enterprise/classification_and_policy_enforcement.adoc
=> Fixed broken link to ISO 27001

modules/developer_manual/pages/core/semantic-versioning-guidelines.adoc
=> Document the Semantic Versioning guidelines

modules/administration_manual/pages/installation/manual_installation.adoc
=> Missing dots CentOS

modules/administration_manual/pages/configuration/server/config_apps_sample_php_parameters.adoc, modules/administration_manual/pages/configuration/server/config_sample_php_parameters.adoc
This is a `config-to-docs` step for the config sample files which have been recently updated in core.
=> updated config sample files

modules/administration_manual/pages/release_notes.adoc
Please check wording and content @PVince81 @settermjd @phil-davis. Some information is still missing. I set the locations to bold :)
THX!
=> 10.1 Release Notes

modules/administration_manual/pages/installation/system_requirements.adoc
=> Document the minimum supported PostgreSQL version

modules/administration_manual/examples/installation/nginx/default-configuration.conf, modules/administration_manual/examples/installation/nginx/subdirectory-configuration.conf, modules/administration_manual/pages/installation/nginx_configuration.adoc
This PR enhances the nginx configuration.
- adding `always` to `add_header` (see comment text)
- imporving the configuration text
=> nginx improvements

modules/administration_manual/pages/installation/system_requirements.adoc, modules/administration_manual/pages/issues/general_troubleshooting.adoc
=> Fix two broken (legacy) rST links

modules/administration_manual/pages/installation/manual_installation.adoc
=> Revert "Apache - Always set headers"

modules/administration_manual/nav.adoc
This PR improves the navigation sort order at admin docs which follows now a more natural flow.
**Before**
**After**
=> Better sort order of main nav items

site.yml
This change adds support for Piwik tracking.
💁‍♂️ Don't merge until https://github.com/owncloud/docs-ui/pull/27 has been merged.
=> Add Piwik support

modules/developer_manual/examples/app/fundamentals/filesystem/getOwnerByFileId.php, modules/developer_manual/pages/app/fundamentals/filesystem.adoc
=> Document how to retrieve a storage's owner using a file id

Makefile
This relates to:
- https://github.com/owncloud/administration-internal/issues/101
- https://github.com/owncloud/enterprise/issues/2528
=> Update version to 10.1.0

antora.yml
This change updates the version in the 10.0.10 branch's component descriptor to be the correct one.
=> Update 10.0.10 branch component descriptor version

modules/developer_manual/examples/core/unit-testing/MyClass.php, modules/developer_manual/examples/core/unit-testing/MyClassTest.php, modules/developer_manual/pages/core/unit-testing.adoc
This ports https://github.com/owncloud/documentation/pull/3889/files from the documentation PR to the new docs.
💁‍♂️ backport to 10.1 & 10.0
=> Port Documentation PR #3889

modules/administration_manual/nav.adoc, modules/administration_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, site.yml
This fixes https://github.com/owncloud/enterprise/issues/2931.
💁‍♂️ I still need to check occ commands, and if anything else is required.
=> WIP: Document the WOPI integration in oC enterprise

modules/ROOT/pages/index.adoc
...for admin, dev, and user manual for 10.0.10 Release.
=> fixed PDF download links

modules/ROOT/pages/index.adoc
.. for admin, dev and user manual for 10.0.10
=> fixed PDF manual links

modules/ROOT/pages/index.adoc
for admin, dev and user manual for 10.1
=> FIX PDF 10.1

modules/ROOT/pages/how_to_contribute.adoc
=> Fix broken links on how to contribute page

modules/administration_manual/pages/installation/system_requirements.adoc, site.yml
=> Fix the stated minimum PHP version

modules/developer_manual/pages/core/acceptance-tests.adoc
in preparation for writing more about acceptance testing.
Part of issue #156
=> Fix minor wording in acceptance-tests.adoc

modules/user_manual/pages/files/webgui/tagging.adoc
Change system tag internal name to collaborative, due to system tags is the internal code name.
. Collaborative tags is the user facing name.
=> Change system tag internal name to collaborative

modules/developer_manual/pages/core/acceptance-tests.adoc
Backport #617 to `10.1` branch.
=> [10.1] Fix minor wording in acceptance-tests.adoc

modules/developer_manual/pages/core/acceptance-tests.adoc
Backport #617 to `10.0` branch.
=> [10.0] Fix minor wording in acceptance-tests.adoc

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.0] Add section about tagging scenarios to acceptance-tests.adoc

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.1] Add section about tagging scenarios to acceptance-tests.adoc

modules/developer_manual/pages/core/acceptance-tests.adoc
Part of issue #156 
QA issue https://github.com/owncloud/QA/issues/601
=> Writing Scenarios For Bugs

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.1] Writing Scenarios For Bugs

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.0] Writing Scenarios For Bugs

modules/admin_manual/pages/configuration/server/occ_command.adoc
Issue #643 
Correction will need backport to 10.1 and 10.0 doc branches.
=> Correct files:scan --all documentation

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.1] Correct files:scan --all documentation

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.0] Correct files:scan --all documentation

modules/developer_manual/examples/core/acceptance-tests/given-step.php, modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php, modules/developer_manual/examples/core/acceptance-tests/then-step.php, modules/developer_manual/examples/core/acceptance-tests/when-step.php, modules/developer_manual/pages/core/acceptance-tests.adoc
=> Doc how to add new test steps 10.1

modules/developer_manual/examples/core/acceptance-tests/given-step.php, modules/developer_manual/examples/core/acceptance-tests/then-step-with-actions.php, modules/developer_manual/examples/core/acceptance-tests/then-step.php, modules/developer_manual/examples/core/acceptance-tests/when-step.php, modules/developer_manual/pages/core/acceptance-tests.adoc
=> Doc how to add new test steps 10.0

modules/developer_manual/nav.adoc
=> [10.0] fix Available APIs navigation link

modules/developer_manual/nav.adoc
=> [10.1] fix Available APIs navigation link

modules/developer_manual/pages/core/ocs-share-api.adoc
sending a DELETE does not result in any returned data, why should it, you just deleted that share.
=> DELETE commands do not return any data

modules/developer_manual/pages/core/ocs-share-api.adoc
=> DELETE commands do not return any data (#664)

modules/admin_manual/pages/installation/linux_installation.adoc
=> Recommend to hold updates to owncloud-files repository package

modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
Fixes https://github.com/owncloud/security-tracker/issues/302
=> Add shibboleth override warning

docs/getting-started.md
Adds text and a link to a script for backporting in getting-started.md 
Scriptupdate in #696
=> Add script link for backporting

modules/developer_manual/pages/general/devenv.adoc
=> [10.0] [PR 681] Development Docs Update: Install composer and yarn

modules/developer_manual/pages/general/devenv.adoc
=> [10.1] [PR 681] Development Docs Update: Install composer and yarn

modules/developer_manual/pages/general/backporting.adoc
Improves the text for how to use the backporting script
=> Improve how to use text in backport

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.0] [PR 719] Improving backport

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.1] [PR 719] Improving backport

modules/developer_manual/pages/app/fundamentals/info.adoc
This fixes #639, as pointed out by @alfredbuehler.
=> Remove duplicate entries for description and category

site.yml
=> [10.1] [PR 720] Explicitly specify the local branch to use in site.yml

modules/developer_manual/pages/app/fundamentals/info.adoc
=> [10.0] [PR 721] Remove duplicate entries for description and category

modules/developer_manual/pages/app/fundamentals/info.adoc
=> [10.1] [PR 721] Remove duplicate entries for description and category

site.yml
=> [10.0] [PR 720] Explicitly specify the local branch to use in site.yml

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.0] [PR 724] Add note when the script breakes

modules/admin_manual/pages/enterprise/logging/enterprise_logging_apps.adoc
just a small formatting enhancement
=> make complete log level string bold

modules/developer_manual/pages/general/backporting.adoc
I did some small imporvements, most of them cover macOS,
The rest is finetuning plus a fix for the include statement
=> Improve text to better cover macos

modules/admin_manual/pages/enterprise/logging/enterprise_logging_apps.adoc
=> [10.0] [PR 741] make complete log level string bold

modules/admin_manual/pages/enterprise/logging/enterprise_logging_apps.adoc
=> [master] [PR 741] make complete log level string bold

modules/developer_manual/examples/scripts/backport.sh
=> [10.1] [PR 731] Remeber the base branch and switch back when finished

modules/developer_manual/examples/scripts/backport.sh
=> [10.0] [PR 731] Remeber the base branch and switch back when finished

docs/best-practices.md
This is a small update to best-practices.md to better describe the necessary components when including a script.
=> Improving script include explanation in best-practices.md

docs/best-practices.md
=> Backport "improving script include explanation (#738)" to 10.1

docs/best-practices.md
=> Backport "improving script include explanation (#738)" to 10.0

modules/admin_manual/examples/installation/nginx/default-configuration.conf, modules/admin_manual/examples/installation/nginx/subdirectory-configuration.conf, modules/admin_manual/pages/installation/nginx_configuration.adoc
This is a small update to the nginx configuration.
Improved readability and added two missing "always" directives.
Found while reading the docs.
Backport to 10.0 and 10.1 recommended.
=> small nginx update

modules/admin_manual/examples/installation/nginx/default-configuration.conf, modules/admin_manual/examples/installation/nginx/subdirectory-configuration.conf, modules/admin_manual/pages/installation/nginx_configuration.adoc
=> [10.0] [PR 740] small nginx update

modules/admin_manual/examples/installation/nginx/default-configuration.conf, modules/admin_manual/examples/installation/nginx/subdirectory-configuration.conf, modules/admin_manual/pages/installation/nginx_configuration.adoc
=> [10.1] [PR 740] small nginx update

modules/admin_manual/pages/configuration/server/occ_command.adoc
changed config-reports-commands to config-reports
=> fix anchor for config reports

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.0] [PR 778] fix anchor for config reports

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.1] [PR 778] fix anchor for config reports

Makefile
=>  [10.0] [PR 769] Add Linters for Kotlin and Golang

Makefile
=>  [10.1] [PR 769] Add Linters for Kotlin and Golang

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
This is an improvement of the backporting script which handles the commits to be picked in a better way. Plus some output tuning and text improvements.
=> Improving the cherry pick procedure in backporting script

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.0] [PR 783] Improving the cherry pick procedure in backporting script

modules/developer_manual/examples/scripts/backport.sh, modules/developer_manual/pages/general/backporting.adoc
=> [10.1] [PR 783] Improving the cherry pick procedure in backporting script

.drone.yml, overlay/robots.txt, overlay/ui.yml, site.yml
This PR adds missing secrets/env variables which are required by the new search UI. It depends on https://github.com/owncloud/docs-ui/pull/34.
=> Add missing search secrets, use same style for all secrets

.drone.yml, overlay/robots.txt, overlay/ui.yml, site.yml
=> Backport search secrets to 10.1

modules/developer_manual/pages/core/ocs-share-api.adoc
=> Backport more fixes to ocs share api to 10.1

modules/developer_manual/pages/core/ocs-share-api.adoc
=> Fixes to ocs-share-api.adoc (#789)

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/examples/installation/lets_encrypt/your-domain-name.sh, modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
Fixes https://github.com/owncloud/docs/issues/791 (Unincluded (orphaned) example files in admin_manual) --> array item 5-10
- The page existed but has been now been moved one level deeper plus proper named.
- The missing example files are now included
- Some fixes to the example files
- Many text updates
=> Fixes includes and updates of the letsencrypt documentation

modules/admin_manual/pages/enterprise/installation/install.adoc
=> [10.0] [PR 812] fixing links

modules/admin_manual/pages/enterprise/installation/install.adoc
=> [10.1] [PR 812] fixing links

.drone.yml, overlay/robots.txt, overlay/ui.yml, site.yml
This reverts commit f415bbf4d46422b51ce6264ee20f31c1c93f1653. Fixes #816.
=> Revert "Add missing search secrets, use same style for all secrets (#790)"

modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
=> [10.1] [PR 820] Fix missing references in developer docs

modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
Reverts owncloud/docs#820
Reverting, need to resetup the PR because of a hard to identifyable mistake
Will revert also backport #826
=> Revert "Fix missing references in developer docs"

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/examples/installation/lets_encrypt/your-domain-name.sh, modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.1] [PR 801] Fixes includes and updates of the letsencrypt documentation

docs/checking-broken-links.md
=> [10.0] [PR 764] Improving Linkchecker

modules/admin_manual/examples/installation/lets_encrypt/cli.ini, modules/admin_manual/examples/installation/lets_encrypt/your-domain-name.sh, modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc
=> [10.0] [PR 801] Fixes includes and updates of the letsencrypt documentation

docs/checking-broken-links.md
=> [10.1] [PR 764] Improving Linkchecker

docs/build-the-docs.md
=> [10.0] [PR 766] yarn run (build-the-docs.md)

docs/build-the-docs.md
=> [10.1] [PR 766] yarn run (build-the-docs.md)

modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
=> [10.0] [PR 833] Comments, typo and formatting update in dev_docs

modules/developer_manual/pages/_partials/webdav_api/core_curl_request.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc
=> [10.1] [PR 833] Comments, typo and formatting update in dev_docs

modules/admin_manual/pages/maintenance/migrating.adoc
This is a fix for issue #803 (Server Migration Documentation Fix)
- add `apps` directory in rsync
- added some text
- improved some text
@pclemins fyi
=> Server Migration Documentation Fix

modules/developer_manual/pages/core/theming.adoc
add a note to inform users that the config php theming option is deprecated in ownCloud 10.
=> config.php theme deprecation mention

modules/developer_manual/pages/core/theming.adoc
=> [10.0] [PR 839] config.php theme deprecation mention

modules/developer_manual/pages/core/theming.adoc
=> [10.1] [PR 839] config.php theme deprecation mention

modules/admin_manual/pages/release_notes.adoc
=> [10.1] [PR 799] 10.1.1 hotfix release notes

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.1] [PR 849] Clarify that copying back apps also apply to enterprise apps

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.0] [PR 849] Clarify that copying back apps also apply to enterprise apps

modules/admin_manual/pages/maintenance/migrating.adoc
=> [10.0] [PR 811] Server Migration Documentation Fix

docs/getting-started.md, docs/the-build-pipeline.md
=> [10.1] [PR 830] Improve description how docs are built and deployed

docs/getting-started.md, docs/the-build-pipeline.md
=> [10.0] [PR 830] Improve description how docs are built and deployed

modules/developer_manual/pages/general/backporting.adoc
Small improvement for the backporting script to suggest using a git alias.
=> Suggestion to use a git alias for backport.sh

modules/developer_manual/pages/general/backporting.adoc
=> [10.0] [PR 825] Suggestion to use a git alias for backport.sh

modules/developer_manual/pages/general/backporting.adoc
=> [10.1] [PR 825] Suggestion to use a git alias for backport.sh

modules/developer_manual/pages/index.adoc
Thanks for pointing this out @felixboehm.
=> Fix broken links on developer manual index page

modules/admin_manual/nav.adoc, modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.0] [PR 845] Create providing_logs_and_config_files.adoc

modules/admin_manual/nav.adoc, modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.1] [PR 845] Create providing_logs_and_config_files.adoc

modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
This fixes #411.
💁‍♂️ I'm not sure what happened in #517, but a large number of commits ended up in the PR making it nigh-on impossible to know what problems merging it may cause. To the best of my knowledge, this PR contains the essential changes which have previously been approved, without any unnecessary extra information.
=> Document Min Samba / Windows Network Drive Listener combination

modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
=> [10.0] [PR 860] Document Min Samba / Windows Network Drive Listener combination

modules/admin_manual/pages/configuration/files/external_storage/smb.adoc
=> [10.1] [PR 860] Document Min Samba / Windows Network Drive Listener combination

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> app requirements

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> backport app requirements (#863)

modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.0] [PR 878] Document the renaming shares functionality

modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.1] [PR 878] Document the renaming shares functionality

modules/developer_manual/pages/general/devenv_docker.adoc
=> [10.1] [PR 880] xref fix missing module name

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.0] [PR 804] Replace 9.2 by 10.0

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.1] [PR 804] Replace 9.2 by 10.0

modules/admin_manual/examples/installation/post-installation-steps.sh
This is a small script update improving overall usage experience.
=> Small script improvement of post-installation-steps.sh

modules/admin_manual/examples/installation/post-installation-steps.sh
=> [10.1] [PR 866] Small script improvement of post-installation-steps.sh

modules/admin_manual/examples/installation/post-installation-steps.sh
=> [10.0] [PR 866] Small script improvement of post-installation-steps.sh

modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
=> [10.1] [PR 735] Preparation page for Ubuntu 18.04

modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
=> [10.0] [PR 735] Preparation page for Ubuntu 18.04

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.0] [PR 891] Fix omissions in the manual upgrade documentation

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.1] [PR 891] Fix omissions in the manual upgrade documentation

modules/admin_manual/examples/enterprise/user_management/shibboleth/apache-2.4-configuration.conf, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.0] [PR 897] Extract the Shibboleth Apache config example to an include file

modules/admin_manual/examples/enterprise/user_management/shibboleth/apache-2.4-configuration.conf, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.1] [PR 897] Extract the Shibboleth Apache config example to an include file

docs/best-practices.md, modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/nginx_configuration.adoc, modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc, modules/developer_manual/pages/app/advanced/extstorage.adoc, modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc, modules/developer_manual/pages/app/fundamentals/filesystem.adoc, modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search/filter_files.adoc, modules/developer_manual/pages/webdav_api/search/search_files.adoc
As per https://github.com/owncloud/docs/pull/890#discussion_r272900168, this PR has been created to update the include example syntax to Antora's new format.
=> Update example include syntax

modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/apps_supported.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/deployment_considerations.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/nginx.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/linux_installation.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/nginx_configuration.adoc, modules/admin_manual/pages/installation/selinux_configuration.adoc, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.1] [PR 872] TOC in admin manual - installation

modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/apps_supported.adoc, modules/admin_manual/pages/installation/configuration_notes_and_tips.adoc, modules/admin_manual/pages/installation/deployment_considerations.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/nginx.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/linux_installation.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/nginx_configuration.adoc, modules/admin_manual/pages/installation/selinux_configuration.adoc, modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.0] [PR 872] TOC in admin manual - installation

docs/best-practices.md, modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/nginx_configuration.adoc, modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc, modules/developer_manual/pages/app/advanced/extstorage.adoc, modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc, modules/developer_manual/pages/app/fundamentals/filesystem.adoc, modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search/filter_files.adoc, modules/developer_manual/pages/webdav_api/search/search_files.adoc
=> [10.1] [PR 901] Update example include syntax

docs/best-practices.md, modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/installation_wizard.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/nginx_configuration.adoc, modules/developer_manual/pages/_partials/webdav_api/search/common_error_responses.adoc, modules/developer_manual/pages/app/advanced/extstorage.adoc, modules/developer_manual/pages/app/fundamentals/backgroundjobs.adoc, modules/developer_manual/pages/app/fundamentals/filesystem.adoc, modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search/filter_files.adoc, modules/developer_manual/pages/webdav_api/search/search_files.adoc
=> [10.0] [PR 901] Update example include syntax

docs/best-practices.md
=> [10.1] [PR 871] Including ToC in Best Practices

docs/best-practices.md
=> [10.0] [PR 871] Including ToC in Best Practices

docs/best-practices.md
=> Fix one leftover {examplesdir} --> example$ in best practices

docs/best-practices.md
=> [10.1] [PR 910] Fix one leftover {examplesdir}  in best practices

docs/best-practices.md
=> [10.0] [PR 910] Fix one leftover {examplesdir} in best practices

modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/linux_installation.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/pages/installation/troubleshooting.adoc, modules/admin_manual/pages/issues/general_troubleshooting.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.1] [PR 916] Fixing orphaned references from old docs

modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/configuration/user/user_auth_ftp_smb_imap.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/linux_installation.adoc, modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, modules/admin_manual/pages/installation/troubleshooting.adoc, modules/admin_manual/pages/issues/general_troubleshooting.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.0] [PR 916] Fixing orphaned references from old docs

modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.0] [PR 898] Tidy up the Shibboleth documentation

modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.1] [PR 898] Tidy up the Shibboleth documentation

modules/admin_manual/nav.adoc
=> [10.0] [PR 921] Link the installation home page to the main installation nav item

modules/admin_manual/nav.adoc
=> [10.1] [PR 921] Link the installation home page to the main installation nav item

modules/admin_manual/pages/installation/selinux_configuration.adoc
=> Adding an introduction what SELinux is about

modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/nginx.adoc
=> [10.1] [PR 915] Improving Letsencrypt configuration for Apache and Nginx

modules/admin_manual/pages/installation/letsencrypt/apache.adoc, modules/admin_manual/pages/installation/letsencrypt/nginx.adoc
=> [10.0] [PR 915] Improving Letsencrypt configuration for Apache and Nginx

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.1] [PR 909] Update system requirements

modules/admin_manual/pages/installation/system_requirements.adoc
=> [10.0] [PR 909] Update system requirements

docs/best-practices.md
This PR enhances the description in docs/best practices how links can be written/used.
=> Improving how links can be written

docs/best-practices.md
Adding a description in the BPG about how and when to use paragraph titles
=> Adding Paragraph Titles to Best Practices Guide

docs/best-practices.md
=> [10.0] [PR 908] Improving how links can be written

docs/best-practices.md
=> [10.1] [PR 908] Improving how links can be written

docs/best-practices.md
=> [10.1] [PR 947] Adding Paragraph Titles to Best Practices Guide

docs/best-practices.md
=> [10.0] [PR 947] Adding Paragraph Titles to Best Practices Guide

modules/ROOT/pages/how_to_contribute.adoc
=> [10.1] [PR 939] Update how to contribute in production

modules/ROOT/pages/how_to_contribute.adoc
=> [10.0] [PR 939] Update how to contribute in production

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Backport of PR #957
Please merge after #955 is merged
=> [10.0] [PR 957] Fix typo in linux database configuration

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
Backport of PR #957
Please merge after #956 is merged
=> [10.1] [PR 957] Fix typo in linux database configuration

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.1] [PR 737] Always set headers

modules/admin_manual/pages/issues/general_troubleshooting.adoc
=> [10.1] [PR 973] Update general_troubleshooting.adoc

modules/admin_manual/pages/issues/general_troubleshooting.adoc
=> [10.0] [PR 973] Update general_troubleshooting.adoc

modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
=> [10.1] [PR 971] Update external_storage_configuration.adoc

modules/admin_manual/pages/configuration/files/external_storage_configuration.adoc
=> [10.0] [PR 971] Update external_storage_configuration.adoc

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.0] [PR 970] Update previews_configuration.adoc

modules/admin_manual/pages/configuration/files/previews_configuration.adoc
=> [10.1] [PR 970] Update previews_configuration.adoc

modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
=> [10.1] [PR 979] Update files_primary_s3 config examples to use correct path style syntax

modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc
=> [10.0] [PR 979] Update files_primary_s3 config examples to use correct path style syntax

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
This relates to #411, in response to https://github.com/owncloud/docs/issues/411#issuecomment-482062559 from @cdamken.
=> Linked to the SMB/CIFS config from the WND documentation

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.1] [PR 976] Linked to the SMB/CIFS config from the WND documentation

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.0] [PR 976] Linked to the SMB/CIFS config from the WND documentation

modules/admin_manual/pages/maintenance/migrating.adoc
=> Fix broken link to appliance main page

modules/developer_manual/examples/app/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php
=> [10.0] [PR 887] Fix code errors in MyStorage.php

modules/developer_manual/examples/app/storage-backend/OCA/MyStorageApp/Storage/MyStorage.php
=> [10.1] [PR 887] Fix code errors in MyStorage.php

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.2] Fixup --database-pass parameter of acceptance-tests install example

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.1] Fixup --database-pass parameter of acceptance-tests install example

modules/developer_manual/pages/core/acceptance-tests.adoc
=> [10.0] Fixup --database-pass parameter of acceptance-tests install example

modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
Fixes: https://github.com/owncloud/docs/issues/1009
https://doc.owncloud.com/server/10.1/admin_manual/configuration/files/encryption/encryption_configuration_quick_guide.html#enable-the-encryption-app
Tested by local site build
=> Fix encryption quick guide formatting errors

modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
=> [10.0] [PR 1010] Fix encryption quick guide formatting errors

modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
=> [10.1] [PR 1010] Fix encryption quick guide formatting errors

modules/admin_manual/pages/configuration/files/encryption/enable-encryption.adoc
=> [10.2] [PR 1010] Fix encryption quick guide formatting errors

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.0] [PR 969] Replace 9.2 by 10.0

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.1] [PR 969] Replace 9.2 by 10.0

modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.2] [PR 969] Replace 9.2 by 10.0

modules/admin_manual/pages/appliance/Clamav.adoc, modules/admin_manual/pages/appliance/Office.adoc, modules/admin_manual/pages/appliance/certificates.adoc, modules/admin_manual/pages/appliance/howto-update-owncloud.adoc, modules/admin_manual/pages/appliance/installation.adoc, modules/admin_manual/pages/appliance/ucs/add-groups-and-users.adoc, modules/admin_manual/pages/appliance/wnd_setup.adoc
=> TOC in admin manual - appliance

modules/admin_manual/pages/appliance/Clamav.adoc, modules/admin_manual/pages/appliance/Office.adoc, modules/admin_manual/pages/appliance/certificates.adoc, modules/admin_manual/pages/appliance/howto-update-owncloud.adoc, modules/admin_manual/pages/appliance/installation.adoc, modules/admin_manual/pages/appliance/ucs/add-groups-and-users.adoc, modules/admin_manual/pages/appliance/wnd_setup.adoc
=> [10.0] [PR 1018] TOC in admin manual - appliance

modules/admin_manual/pages/appliance/Clamav.adoc, modules/admin_manual/pages/appliance/Office.adoc, modules/admin_manual/pages/appliance/certificates.adoc, modules/admin_manual/pages/appliance/howto-update-owncloud.adoc, modules/admin_manual/pages/appliance/installation.adoc, modules/admin_manual/pages/appliance/ucs/add-groups-and-users.adoc, modules/admin_manual/pages/appliance/wnd_setup.adoc
=> [10.1] [PR 1018] TOC in admin manual - appliance

modules/admin_manual/pages/appliance/Clamav.adoc, modules/admin_manual/pages/appliance/Office.adoc, modules/admin_manual/pages/appliance/certificates.adoc, modules/admin_manual/pages/appliance/howto-update-owncloud.adoc, modules/admin_manual/pages/appliance/installation.adoc, modules/admin_manual/pages/appliance/ucs/add-groups-and-users.adoc, modules/admin_manual/pages/appliance/wnd_setup.adoc
=> [10.2] [PR 1018] TOC in admin manual - appliance

modules/admin_manual/pages/document_classification/index.adoc
=> [10.2] [PR 1027] TOC in admin manual - document classification

modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/general/code-of-conduct.adoc, modules/developer_manual/pages/general/codingguidelines.adoc, modules/developer_manual/pages/general/debugging.adoc, modules/developer_manual/pages/general/performance.adoc, modules/developer_manual/pages/general/security.adoc
=> TOC in developer manual - General Contributor Guidelines

modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/general/code-of-conduct.adoc, modules/developer_manual/pages/general/codingguidelines.adoc, modules/developer_manual/pages/general/debugging.adoc, modules/developer_manual/pages/general/performance.adoc, modules/developer_manual/pages/general/security.adoc
=> [10.2] [PR 1041] TOC in developer manual - General Contributor Guidelines

modules/developer_manual/pages/general/backporting.adoc, modules/developer_manual/pages/general/code-of-conduct.adoc, modules/developer_manual/pages/general/codingguidelines.adoc, modules/developer_manual/pages/general/debugging.adoc, modules/developer_manual/pages/general/performance.adoc, modules/developer_manual/pages/general/security.adoc
=> [10.1] [PR 1041] TOC in developer manual - General Contributor Guidelines

modules/developer_manual/pages/commun/help_and_communication.adoc
=> TOC in developer manual - Help and Communication

modules/developer_manual/pages/commun/help_and_communication.adoc
=> [10.2] [PR 1042] TOC in developer manual - Help and Communication

modules/developer_manual/pages/commun/help_and_communication.adoc
=> [10.1] [PR 1042] TOC in developer manual - Help and Communication

modules/user_manual/pages/external_storage/sharepoint_connecting.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/files/deleted_file_management.adoc, modules/user_manual/pages/files/encrypting_files.adoc, modules/user_manual/pages/files/federated_cloud_sharing.adoc, modules/user_manual/pages/files/gallery_app.adoc, modules/user_manual/pages/files/public_link_shares.adoc, modules/user_manual/pages/files/webgui/comments.adoc, modules/user_manual/pages/files/webgui/custom_groups.adoc, modules/user_manual/pages/files/webgui/navigating.adoc, modules/user_manual/pages/files/webgui/overview.adoc, modules/user_manual/pages/files/webgui/quota.adoc, modules/user_manual/pages/files/webgui/sharing.adoc, modules/user_manual/pages/files/webgui/tagging.adoc, modules/user_manual/pages/pim/sync_ios.adoc, modules/user_manual/pages/session_management.adoc, modules/user_manual/pages/troubleshooting.adoc
Some text, level and table fixes included
Fixes of header levels where necessary (because of beeing wrong).
This PR TOC´s the complete user manual
=> TOC in user manual - all

modules/user_manual/pages/external_storage/sharepoint_connecting.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/files/deleted_file_management.adoc, modules/user_manual/pages/files/encrypting_files.adoc, modules/user_manual/pages/files/federated_cloud_sharing.adoc, modules/user_manual/pages/files/gallery_app.adoc, modules/user_manual/pages/files/public_link_shares.adoc, modules/user_manual/pages/files/webgui/comments.adoc, modules/user_manual/pages/files/webgui/custom_groups.adoc, modules/user_manual/pages/files/webgui/navigating.adoc, modules/user_manual/pages/files/webgui/overview.adoc, modules/user_manual/pages/files/webgui/quota.adoc, modules/user_manual/pages/files/webgui/sharing.adoc, modules/user_manual/pages/files/webgui/tagging.adoc, modules/user_manual/pages/pim/sync_ios.adoc, modules/user_manual/pages/session_management.adoc, modules/user_manual/pages/troubleshooting.adoc
=> [10.2] [PR 1040] TOC in user manual - all

modules/user_manual/pages/external_storage/sharepoint_connecting.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/files/deleted_file_management.adoc, modules/user_manual/pages/files/encrypting_files.adoc, modules/user_manual/pages/files/federated_cloud_sharing.adoc, modules/user_manual/pages/files/gallery_app.adoc, modules/user_manual/pages/files/public_link_shares.adoc, modules/user_manual/pages/files/webgui/comments.adoc, modules/user_manual/pages/files/webgui/custom_groups.adoc, modules/user_manual/pages/files/webgui/navigating.adoc, modules/user_manual/pages/files/webgui/overview.adoc, modules/user_manual/pages/files/webgui/quota.adoc, modules/user_manual/pages/files/webgui/sharing.adoc, modules/user_manual/pages/files/webgui/tagging.adoc, modules/user_manual/pages/pim/sync_ios.adoc, modules/user_manual/pages/session_management.adoc, modules/user_manual/pages/troubleshooting.adoc
=> [10.1] [PR 1040] TOC in user manual - all

modules/admin_manual/pages/maintenance/backup.adoc
=> [10.1] [PR 1038] Fix wrong level in maintenance/backup.adoc

modules/admin_manual/pages/maintenance/backup.adoc
=> [10.2] [PR 1038] Fix wrong level in maintenance/backup.adoc

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.0] [PR 1054] Update package_upgrade.adoc

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.1] [PR 1054] Update package_upgrade.adoc

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.2] [PR 1054] Update package_upgrade.adoc

modules/admin_manual/pages/configuration/files/external_storage/google.adoc
=> Fix broken xref in configuration/external_storage/google.adoc

modules/admin_manual/pages/configuration/files/external_storage/google.adoc
=> [10.1] [PR 1035] Fix broken xref in configuration/external_storage/google.adoc

modules/admin_manual/pages/configuration/files/external_storage/google.adoc
=> [10.2] [PR 1035] Fix broken xref in configuration/external_storage/google.adoc

modules/admin_manual/pages/configuration/files/external_storage/google.adoc
=> [10.0] [PR 1035] Fix broken xref in configuration/external_storage/google.adoc

modules/admin_manual/pages/maintenance/backup.adoc
=> [10.0] [PR 1038] Fix wrong level in maintenance/backup.adoc

docs/best-practices.md
=> [10.2] [PR 1031] Best Practices - experimental attribute

docs/best-practices.md
=> [10.1] [PR 1031] Best Practices - experimental attribute

docs/best-practices.md
=> [10.0] [PR 1031] Best Practices - experimental attribute

docs/the-branching-workflow.md
=> [10.2] [PR 1050] Document why backports are made to older documentation branches

docs/the-branching-workflow.md
=> [10.1] [PR 1050] Document why backports are made to older documentation branches

package.json
=> [10.0] [PR 1069] Update the antora build script to support static redirects

package.json
=> [10.1] [PR 1069] Update the antora build script to support static redirects

package.json
=> [10.2] [PR 1069] Update the antora build script to support static redirects

modules/user_manual/pages/files/federated_cloud_sharing.adoc
=> [10.2] [PR 1081] user_manual fix list in federated_cloud_sharing.adoc

modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.0] [PR 1086] Fix section level out of order

modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.1] [PR 1086] Fix section level out of order

modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.2] [PR 1086] Fix section level out of order

modules/admin_manual/pages/installation/selinux_configuration.adoc
=> [10.2] [PR 1065] updated selinux configuration to reflect apps-external change with 10.2

modules/user_manual/pages/files/federated_cloud_sharing.adoc
=> [10.0] [PR 1081] user_manual fix list in federated_cloud_sharing.adoc

modules/user_manual/pages/files/federated_cloud_sharing.adoc
=> [10.1] [PR 1081] user_manual fix list in federated_cloud_sharing.adoc

modules/admin_manual/pages/configuration/server/language_configuration.adoc
=> [10.2] [PR 1092] Restructure and syntax highlighting

modules/admin_manual/pages/configuration/server/language_configuration.adoc
=> [10.0] [PR 1092] Restructure and syntax highlighting

modules/admin_manual/pages/configuration/server/language_configuration.adoc
=> [10.1] [PR 1092] Restructure and syntax highlighting

modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/externalapi.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-recipient-api.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/translation.adoc, modules/developer_manual/pages/core/ui-testing.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/devenv.adoc, modules/developer_manual/pages/testing/index.adoc, modules/developer_manual/pages/webdav_api/comments.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
Some text and level fixes included
Fixes of header levels where necessary (because of beeing wrong).
=> TOC in developer manual - Developing ownCloud Core

docs/best-practices.md
This PR adds `page-aliases` to the Best Practices guide
=> Add page-aliases to best practices

docs/best-practices.md
=> [10.2] [PR 1037] Prevent automatic linking of an URL

modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc, modules/admin_manual/pages/enterprise/clients/custom_client_repos.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc, modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/enterprise/installation/install.adoc, modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc, modules/admin_manual/pages/enterprise/ransomware-protection/index.adoc, modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.2] [PR 1039] TOC in admin manual - Enterprise

docs/best-practices.md
=> [10.0] [PR 1037] Prevent automatic linking of an URL

docs/best-practices.md
=> [10.1] [PR 1037] Prevent automatic linking of an URL

modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/externalapi.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-recipient-api.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/translation.adoc, modules/developer_manual/pages/core/ui-testing.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/devenv.adoc, modules/developer_manual/pages/testing/index.adoc, modules/developer_manual/pages/webdav_api/comments.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
=> [10.2] [PR 1043] TOC in developer manual - Developing ownCloud Core

modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc, modules/admin_manual/pages/enterprise/clients/custom_client_repos.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc, modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/enterprise/installation/install.adoc, modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc, modules/admin_manual/pages/enterprise/ransomware-protection/index.adoc, modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.1] [PR 1039] TOC in admin manual - Enterprise

modules/admin_manual/pages/enterprise/clients/creating_branded_apps.adoc, modules/admin_manual/pages/enterprise/clients/custom_client_repos.adoc, modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc, modules/admin_manual/pages/enterprise/external_storage/ldap_home_connector_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/onedrive.adoc, modules/admin_manual/pages/enterprise/external_storage/s3_swift_as_primary_object_store_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/sharepoint-integration_configuration.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/enterprise/file_management/files_tagging.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/enterprise/installation/install.adoc, modules/admin_manual/pages/enterprise/installation/oracle_db_configuration.adoc, modules/admin_manual/pages/enterprise/ransomware-protection/index.adoc, modules/admin_manual/pages/enterprise/user_management/saml_2.0_sso.adoc, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.0] [PR 1039] TOC in admin manual - Enterprise

modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/externalapi.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-recipient-api.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/translation.adoc, modules/developer_manual/pages/core/ui-testing.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/devenv.adoc, modules/developer_manual/pages/testing/index.adoc, modules/developer_manual/pages/webdav_api/comments.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
=> [10.0] [PR 1043] TOC in developer manual - Developing ownCloud Core

modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/externalapi.adoc, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/developer_manual/pages/core/ocs-recipient-api.adoc, modules/developer_manual/pages/core/ocs-share-api.adoc, modules/developer_manual/pages/core/theming.adoc, modules/developer_manual/pages/core/translation.adoc, modules/developer_manual/pages/core/ui-testing.adoc, modules/developer_manual/pages/core/unit-testing.adoc, modules/developer_manual/pages/general/devenv.adoc, modules/developer_manual/pages/testing/index.adoc, modules/developer_manual/pages/webdav_api/comments.adoc, modules/developer_manual/pages/webdav_api/files_versions.adoc, modules/developer_manual/pages/webdav_api/groups.adoc, modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc, modules/developer_manual/pages/webdav_api/groups/group_membership_endpoints.adoc, modules/developer_manual/pages/webdav_api/search.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
=> [10.1] [PR 1043] TOC in developer manual - Developing ownCloud Core

docs/best-practices.md
=> [10.2] [PR 1090] Add page-aliases to best practices

docs/best-practices.md
=> [10.0] [PR 1090] Add page-aliases to best practices

docs/best-practices.md
=> [10.1] [PR 1090] Add page-aliases to best practices

docs/best-practices.md
that was introduced in PR #1090
=> Fix 'physical' typo

docs/best-practices.md
=> [10.0] [PR 1120] Fix 'physical' typo

docs/best-practices.md
=> [10.1] [PR 1120] Fix 'physical' typo

docs/best-practices.md
=> [10.2] [PR 1120] Fix 'physical' typo

docs/checking-broken-links.md
=> [10.0] [PR 1124] Update Checking Broken Links page

docs/checking-broken-links.md
=> [10.1] [PR 1124] Update Checking Broken Links page

docs/checking-broken-links.md
=> [10.2] [PR 1124] Update Checking Broken Links page

modules/developer_manual/pages/webdav_api/files_versions.adoc
=> [10.1] [PR 1129] Update files_versions.adoc

modules/developer_manual/pages/webdav_api/files_versions.adoc
=> [10.2] [PR 1129] Update files_versions.adoc

Makefile
=> [10.1] [PR 1104] Improve makefile phony clean comment to make it clear that the pdf path is meant

Makefile
=> [10.2] [PR 1104] Improve makefile phony clean comment to make it clear that the pdf path is meant

modules/admin_manual/pages/configuration/server/occ_command.adoc
💁‍♂ - **Only backport to 10.2**
=> Extend the default recommendation for running occ incoming-shares:poll

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.2] [PR 1134] Extend the default recommendation for running occ incoming-shares:poll

modules/admin_manual/nav.adoc
Update link description for Encryption Configuration Quick Guide
=> Update link description

modules/admin_manual/nav.adoc
=> [10.1] [PR 1140] Update link description

modules/admin_manual/nav.adoc
=> [10.2] [PR 1140] Update link description

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
added a explanation + solution with guides on how to resolve this error
=> add deadlock error resolution

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.1] [PR 1138] add deadlock error resolution

site.yml
Fixes https://github.com/owncloud/docs/issues/1002
=> [10.1] add desktop client 2.6

site.yml
Fixes https://github.com/owncloud/docs/issues/1002
=> [master] add desktop client 2.6

.drone.yml, antora.yml, site.yml
Fixes https://github.com/owncloud/docs/issues/1002
=> [10.2] add desktop client 2.6

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.0] [PR 1138] add deadlock error resolution

modules/admin_manual/pages/configuration/database/linux_database_configuration.adoc
=> [10.2] [PR 1138] add deadlock error resolution

modules/admin_manual/pages/index.adoc
=> Remove redundant links

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.1] [PR 974] Update user_roles.adoc

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
this code was there double and in the wrong category
=> delete code duplication

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.1] [PR 1176] delete code duplication

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.2] [PR 1176] delete code duplication

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.2] [PR 974] Update user_roles.adoc

modules/developer_manual/pages/core/theming.adoc
=> [10.1] [PR 1183] update share icon path

modules/developer_manual/pages/core/theming.adoc
=> [10.0] [PR 1183] update share icon path

modules/developer_manual/pages/core/theming.adoc
=> [10.2] [PR 1183] update share icon path

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.2] [PR 962] Adding background:queue to occ command set

modules/admin_manual/examples/enterprise/user_management/shibboleth/other-login-mechanisms-vhost.conf, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.2] [PR 890] Add example for shibboleth and credentials login

modules/admin_manual/examples/enterprise/user_management/shibboleth/other-login-mechanisms-vhost.conf, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.1] [PR 890] Add example for shibboleth and credentials login

modules/admin_manual/examples/enterprise/user_management/shibboleth/other-login-mechanisms-vhost.conf, modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
=> [10.0] [PR 890] Add example for shibboleth and credentials login

modules/admin_manual/pages/installation/system_requirements.adoc
=> Update system_requirements.adoc (#1194)

modules/admin_manual/pages/release_notes.adoc
=> [10.2] [PR 967] 10.2 Release Notes

modules/admin_manual/pages/release_notes.adoc
=> [10.0] [PR 967] 10.2 Release Notes

modules/admin_manual/pages/release_notes.adoc
=> [10.1] [PR 967] 10.2 Release Notes

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> Document the changes to the maintenance:repair command

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.2] [PR 1206] Document the changes to the maintenance:repair command

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.1] [PR 1206] Document the changes to the maintenance:repair command

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.0] [PR 1206] Document the changes to the maintenance:repair command

modules/admin_manual/pages/release_notes.adoc
And change description of new sharing options for users
=> Add known issue about HTML email in plain text to 10.2 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.0] [PR 1222] Add known issue about HTML email in plain text to 10.2 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.1] [PR 1222]  Add known issue about HTML email in plain text to 10.2 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.2] [PR 1222] Add known issue about HTML email in plain text to 10.2 release notes

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.2] [PR 1204] Add a section on rate limiting in ownCloud

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.1] [PR 1204] Add a section on rate limiting in ownCloud

modules/admin_manual/pages/configuration/server/harden_server.adoc
=> [10.0] [PR 1204] Add a section on rate limiting in ownCloud

modules/admin_manual/pages/appliance/configuration/login_information.adoc
requested by many users on central
=> add set owncloud as default page

modules/admin_manual/examples/configuration/oc_permit.sh, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
I refined the upgrade documentation.
=> Refined upgrade documentation.

modules/admin_manual/examples/configuration/oc_permit.sh, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.0] [PR 1196] Refined upgrade documentation.

modules/admin_manual/pages/configuration/server/caching_configuration.adoc, modules/admin_manual/pages/configuration/server/email_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/developer_manual/pages/app/tutorial/restful_api.adoc, modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/ui-testing.adoc, site.yml
=> [10.0] [PR 1249] Replace standard ports with global attributes

modules/admin_manual/pages/configuration/server/caching_configuration.adoc, modules/admin_manual/pages/configuration/server/email_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/developer_manual/pages/app/tutorial/restful_api.adoc, modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/ui-testing.adoc, site.yml
=> [10.1] [PR 1249] Replace standard ports with global attributes

modules/admin_manual/pages/configuration/server/caching_configuration.adoc, modules/admin_manual/pages/configuration/server/email_configuration.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/docker/index.adoc, modules/developer_manual/pages/app/tutorial/restful_api.adoc, modules/developer_manual/pages/core/acceptance-tests.adoc, modules/developer_manual/pages/core/ui-testing.adoc, site.yml
=> [10.2] [PR 1249] Replace standard ports with global attributes

modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
=> [10.0] [PR 1264] [1173] Fix broken LDAP configuration image link

modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
=> [10.1] [PR 1264] [1173] Fix broken LDAP configuration image link

modules/admin_manual/pages/configuration/ldap/ldap_proxy_cache_server_setup.adoc
=> [10.2] [PR 1264] [1173] Fix broken LDAP configuration image link

modules/admin_manual/examples/configuration/oc_permit.sh, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.1] [PR 1196] Refined upgrade documentation.

modules/admin_manual/examples/configuration/oc_permit.sh, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security/hsmdaemon/index.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc
=> [10.2] [PR 1196] Refined upgrade documentation.

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.0] [PR 1268] Add a redirect from source_installation to manual_installation

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.1] [PR 1268] Add a redirect from source_installation to manual_installation

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.2] [PR 1268] Add a redirect from source_installation to manual_installation

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
added a command that disables the module that prevents big file uploads in ubuntu
=> add command for reqtimeout

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.2] [PR 1272] add command for reqtimeout

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.1] [PR 1272] add command for reqtimeout

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.0] [PR 1272] add command for reqtimeout

modules/admin_manual/pages/faq/index.adoc
We had a workshop, where we discussed the current state of the FAQ section and gave it a major overhaul.
=> updated FAQ section

modules/admin_manual/pages/configuration/server/occ_command.adoc
While reviewing the occ user commands documentation after reading #310, I came across a few errors and places where the documentation could be updated. Given that, these changes were made.
=> Minor fixes and updates to the occ user commands documentation

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.0] [PR 1233] Minor fixes and updates to the occ user commands documentation

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.1] [PR 1233] Minor fixes and updates to the occ user commands documentation

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.2] [PR 1233] Minor fixes and updates to the occ user commands documentation

modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/user_manual/pages/_partials/direct_file_access_tip.adoc, modules/user_manual/pages/files/version_control.adoc, modules/user_manual/pages/files/webgui/comments.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.2] [PR 1228] Document ability to open the file sidebar from a permalink

modules/developer_manual/examples/core/apis/ocs-capabilities/list-capabilities-response.json, modules/developer_manual/pages/core/ocs-capabilities.adoc, modules/user_manual/pages/_partials/direct_file_access_tip.adoc, modules/user_manual/pages/files/version_control.adoc, modules/user_manual/pages/files/webgui/comments.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.0] [PR 1228] Document ability to open the file sidebar from a permalink

modules/admin_manual/pages/enterprise/user_management/user_auth_shibboleth.adoc
In the Advanced tab are only 'User Search Attributes' and 'Group Search Attributes'
=> Additional Search Attributes don't exist

modules/admin_manual/pages/configuration/server/antivirus_configuration.adoc
added action descriptions
log and delete
=> added action descriptions

modules/admin_manual/pages/installation/ubuntu_18_04.adoc
added file locking and log roration
=> added file locking and log roration

modules/admin_manual/pages/faq/index.adoc
=> [10.2] [PR 1242] updated FAQ section

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
added a notion to enable external storage.
This was a missing step and new users could be confused without it.
will ad a screen shot for better understanding.
=> added notion

modules/admin_manual/nav.adoc
moved deployment recommendations and considerations higher up
=> reordered installation points

modules/admin_manual/pages/release_notes.adoc
=> Backport [10.1] [PR 1294] Add known issue with user avatars to release notes 

modules/admin_manual/pages/release_notes.adoc
=> Backport  [10.0] [PR 1294] Add known issue with user avatars to release notes 

modules/user_manual/pages/files/access_webdav.adoc
=> Backports [10.1] [PR 1317] Update access_webdav.adoc 

modules/user_manual/pages/files/access_webdav.adoc
=> Backport [10.2] [PR 1317] Update access_webdav.adoc 

modules/user_manual/pages/files/access_webdav.adoc
=> Backport [10.0] [PR 1317] Update access_webdav.adoc 

modules/admin_manual/pages/installation/system_requirements.adoc
We (success team) have reviewed and reworked this document according to the latest knowledge status.
=> rework of the whole page

modules/admin_manual/pages/configuration/server/occ_command.adoc
added an example for system occ command to set Redis.
=> add occ command for Redis

docs/style-guide.md
=> [10.0] [PR 1187] Introduce a style guide to the docs

docs/style-guide.md
=> [10.2] [PR 1187] Introduce a style guide to the docs

docs/style-guide.md
=> [10.1] [PR 1187] Introduce a style guide to the docs

modules/admin_manual/examples/installation/ubuntu/18.04/configure-log-rotation.sh, modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh, modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh, modules/admin_manual/examples/installation/ubuntu/18.04/memcache-configuration.php, modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/ubuntu_18_04.adoc
This change makes a number of changes with the view to making the guide
less terse, yet keeping it short, sweet, and to the point. It:
- Reworked the header structure
- Fixed spelling and grammatical errors
- Updated headers to follow the style guide
- Updated code examples to be that much simpler to read and to use
syntax highlighting, where possible
- Extracted some code samples out into example files, making them easier
to maintain and test/lint
- Updated code examples to use sudo, which is the convention on Ubuntu
- Linked to relevant information, both internal and external, to help
users of varying skill and knowledge levels
=> [10.0] Update the Ubuntu 18.04 installation example (#1302)

modules/admin_manual/examples/installation/ubuntu/18.04/configure-log-rotation.sh, modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh, modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh, modules/admin_manual/examples/installation/ubuntu/18.04/memcache-configuration.php, modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/ubuntu_18_04.adoc
This change makes a number of changes with the view to making the guide
less terse, yet keeping it short, sweet, and to the point. It:
- Reworked the header structure
- Fixed spelling and grammatical errors
- Updated headers to follow the style guide
- Updated code examples to be that much simpler to read and to use
syntax highlighting, where possible
- Extracted some code samples out into example files, making them easier
to maintain and test/lint
- Updated code examples to use sudo, which is the convention on Ubuntu
- Linked to relevant information, both internal and external, to help
users of varying skill and knowledge levels
=> [10.1] Update the Ubuntu 18.04 installation example (#1302)

modules/admin_manual/examples/installation/ubuntu/18.04/configure-log-rotation.sh, modules/admin_manual/examples/installation/ubuntu/18.04/create-vhost-config.sh, modules/admin_manual/examples/installation/ubuntu/18.04/finalise-install.sh, modules/admin_manual/examples/installation/ubuntu/18.04/memcache-configuration.php, modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/ubuntu_18_04.adoc
This change makes a number of changes with the view to making the guide
less terse, yet keeping it short, sweet, and to the point. It:
- Reworked the header structure
- Fixed spelling and grammatical errors
- Updated headers to follow the style guide
- Updated code examples to be that much simpler to read and to use
syntax highlighting, where possible
- Extracted some code samples out into example files, making them easier
to maintain and test/lint
- Updated code examples to use sudo, which is the convention on Ubuntu
- Linked to relevant information, both internal and external, to help
users of varying skill and knowledge levels
=> [10.2] Update the Ubuntu 18.04 installation example (#1302)

modules/admin_manual/pages/installation/ubuntu_18_04.adoc
noticed during installation, that this confused me.
=> Seperate chmod from script content

modules/admin_manual/pages/release_notes.adoc
=> [10.2] [PR 1313] 10.2.1 Release Notes

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.2] [PR 1364] Added YAML file and registry instructions

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.1] [PR 1364] Added YAML file and registry instructions

modules/admin_manual/examples/installation/docker/docker-compose.yml, modules/admin_manual/pages/installation/docker/index.adoc
=> [10.0] [PR 1364] Added YAML file and registry instructions

modules/ROOT/pages/index.adoc
This follows up a conversation with @michaelstingl, earlier today.
=> Link to the new iOS Mobile App on the docs root page

modules/admin_manual/pages/release_notes.adoc
=> Add another solved issue to 10.2.1 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.0] [PR 1375] Add another solved issue to 10.2.1 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.1] [PR 1375] Add another solved issue to 10.2.1 release notes

modules/admin_manual/pages/release_notes.adoc
=> [10.2] [PR 1375] Add another solved issue to 10.2.1 release notes

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.0] [PR 1326] Remove enterprise reference for password policy app

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.2] [PR 1326] Remove enterprise reference for password policy app

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.1] [PR 1326] Remove enterprise reference for password policy app

docs/style-guide.md
This should be a start to add a structure.
=> add document structure

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.2] [PR 1362] Update windows-network-drive_configuration.adoc

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.1] [PR 1362] Update windows-network-drive_configuration.adoc

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.0] [PR 1362] Update windows-network-drive_configuration.adoc

modules/developer_manual/pages/core/apis/externalapi.adoc, modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
=> [10.0] [PR 1399] Clean up some of the API documentation

modules/developer_manual/pages/core/apis/externalapi.adoc, modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
=> [10.1] [PR 1399] Clean up some of the API documentation

modules/developer_manual/pages/core/apis/externalapi.adoc, modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/developer_manual/pages/webdav_api/tags.adoc
=> [10.2] [PR 1399] Clean up some of the API documentation

lib/extensions/tabs.js, site.yml
=> [10.0] [PR 1397] Enable the Antora Tab Blocks Extension

lib/extensions/tabs.js, site.yml
=> [10.1] [PR 1397] Enable the Antora Tab Blocks Extension

lib/extensions/tabs.js, site.yml
=> [10.2] [PR 1397] Enable the Antora Tab Blocks Extension

modules/admin_manual/pages/installation/linux_installation.adoc
=> Backport #1392 to master

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.2] [PR 1396] Add Share permission to doc when creating shares

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.1] [PR 1396] Add Share permission to doc when creating shares

modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.0] [PR 1396] Add Share permission to doc when creating shares

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.2] [PR 1342] Minor fixes to the occ and manual installation documentation

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc, modules/admin_manual/pages/release_notes.adoc
=> [10.2] [PR 1412] Fix a set of links corrupted during the migration from Sphinx-Doc

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc, modules/admin_manual/pages/release_notes.adoc
=> [10.1] [PR 1412] Fix a set of links corrupted during the migration from Sphinx-Doc

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/server/index_php_less_urls.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc, modules/admin_manual/pages/installation/apps_management_installation.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/maintenance/upgrading/marketplace_apps.adoc, modules/admin_manual/pages/maintenance/upgrading/upgrade_php.adoc, modules/admin_manual/pages/release_notes.adoc
=> [10.0] [PR 1412] Fix a set of links corrupted during the migration from Sphinx-Doc

modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc, package-lock.json
=> Administrator: migration from user key to master key on mysql

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.1] [PR 1342] Minor fixes to the occ and manual installation documentation

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.0] [PR 1342] Minor fixes to the occ and manual installation documentation

modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc, package-lock.json
=> [10.0] [PR 1422] Administrator: migration from user key to master key on mysql

modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc, package-lock.json
=> [10.2] [PR 1422] Administrator: migration from user key to master key on mysql

modules/admin_manual/pages/maintenance/encryption/migrating-from-user-key-to-master-key.adoc, package-lock.json
=> [10.1] [PR 1422] Administrator: migration from user key to master key on mysql

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.2] [PR 1192] Update user_roles.adoc

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.1] [PR 1192] Update user_roles.adoc

modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.0] [PR 1192] Update user_roles.adoc

modules/admin_manual/pages/configuration/server/occ_command.adoc, site.yml
the ip address in the example was machine specific. replaced it with the loop back address.
=> redis address correction

modules/admin_manual/pages/configuration/server/occ_command.adoc, site.yml
=> [10.2] [PR 1437] redis address correction

modules/admin_manual/pages/configuration/server/occ_command.adoc, site.yml
=> [10.0] [PR 1437] redis address correction

modules/admin_manual/pages/configuration/server/occ_command.adoc, site.yml
=> [10.1] [PR 1437] redis address correction

modules/admin_manual/pages/maintenance/manual_upgrade.adoc
=> [10.2] [PR 1411] Fixed the upgrade docs

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.2] [PR 1322] Fix 404s to configuration/files/encryption/encryption_configuration.adoc

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration.adoc
=> [10.1] [PR 1322] Fix 404s to configuration/files/encryption/encryption_configuration.adoc

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.2] [PR 1341] [1256] Reuse Existing LDAP Accounts, If Available

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.1] [PR 1341] [1256] Reuse Existing LDAP Accounts, If Available

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.0] [PR 1341] [1256] Reuse Existing LDAP Accounts, If Available

modules/admin_manual/pages/configuration/files/encryption_configuration.adoc
=> [10.0] [PR 1322] Fix 404s to configuration/files/encryption/encryption_configuration.adoc

modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, site.yml
=> [10.2] [PR 1229] Update source installation documentation

docs/getting-started.md
=> [10.0] [PR 1453] link to firefox extension asciidoctor.js live

docs/getting-started.md
=> [10.1] [PR 1453] link to firefox extension asciidoctor.js live

docs/getting-started.md
=> [10.2] [PR 1453] link to firefox extension asciidoctor.js live

modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, site.yml
=> [10.0] [PR 1229] Update source installation documentation

modules/admin_manual/pages/installation/manual_installation.adoc, modules/admin_manual/pages/installation/system_requirements.adoc, site.yml
=> [10.1] [PR 1229] Update source installation documentation

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.0] [PR 1470] removed non apache2 instructions

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.1] [PR 1470] removed non apache2 instructions

modules/admin_manual/pages/installation/manual_installation.adoc
=> [10.2] [PR 1470] removed non apache2 instructions

modules/developer_manual/pages/core/theming.adoc
since the theming script was considered to complicated, I wrote down the 7 basic commands to get a theme. If the users want a more sophisticated approach, they can use the full script below this one.
=> 7 commands to get a theme

modules/admin_manual/pages/installation/ubuntu_18_04.adoc
=> [10.1] [PR 1469] restore Ubuntu 18.04 example to functional state

modules/admin_manual/pages/installation/ubuntu_18_04.adoc
=> [10.2] [PR 1469] restore Ubuntu 18.04 example to functional state

modules/admin_manual/nav.adoc, modules/admin_manual/pages/appliance/configuration/clamav.adoc, modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
backport of https://github.com/owncloud/docs/pull/1464
=> 10.2 Backport of Update and rename antivirus_configuration.adoc to virus-scanner-support.adoc

modules/admin_manual/nav.adoc, modules/admin_manual/pages/appliance/configuration/clamav.adoc, modules/admin_manual/pages/configuration/server/virus-scanner-support.adoc
Backport of https://github.com/owncloud/docs/pull/1464
=> 10.1 Backport of  Update and rename antivirus_configuration.adoc to virus-scanner-support.adoc

modules/admin_manual/pages/installation/letsencrypt/index.adoc
added references to sub pages
changed title
=> update let's encrypt

modules/developer_manual/pages/core/theming.adoc
=> [10.2] [PR 1478] 7 commands to get a theme

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
https://github.com/owncloud/docs/pull/1489
=> [10.1] [PR 1489] add decryption example

modules/admin_manual/pages/configuration/files/encryption/encryption_configuration_quick_guide.adoc
https://github.com/owncloud/docs/pull/1489
=> [10.2] [PR 1489] add decryption example

modules/admin_manual/pages/appliance/configuration/clamav.adoc
https://github.com/owncloud/docs/pull/1462
=> [10.1] [PR 1462] Changes to the clamAV document

modules/admin_manual/pages/appliance/configuration/clamav.adoc
https://github.com/owncloud/docs/pull/1462
=> [10.2] [PR 1462] Changes to the clamAV document

modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.1] [PR 1473] Update providing_logs_and_config_files.adoc

modules/admin_manual/pages/troubleshooting/providing_logs_and_config_files.adoc
=> [10.2] [PR 1473] Update providing_logs_and_config_files.adoc

modules/admin_manual/pages/configuration/server/activity_configuration.adoc
=> [10.1] [PR 1474] Update activity_configuration.adoc

modules/admin_manual/pages/configuration/server/activity_configuration.adoc
=> [10.2] [PR 1474] Update activity_configuration.adoc

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.2] [PR 1500] Update user_auth_ldap.adoc

modules/admin_manual/pages/configuration/user/user_auth_ldap.adoc
=> [10.1] [PR 1500] Update user_auth_ldap.adoc

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
of OAuth2
fixes this: https://github.com/owncloud/docs/issues/534
=> document limitations

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.1] [PR 1507] document limitations of OAuth2

modules/admin_manual/pages/configuration/server/security/oauth2.adoc
=> [10.2] [PR 1507] document limitations of OAuth2

modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml, modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh, modules/developer_manual/nav.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
=> [10.2] [PR 1479] Document the new OCS TOTP Validation API

modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml, modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh, modules/developer_manual/nav.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
=> [10.1] [PR 1479] Document the new OCS TOTP Validation API

modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-invalid.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-is-valid.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/json/totp-user-is-not-found.json, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-invalid.xml, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-is-valid.xml, modules/developer_manual/examples/core/apis/ocs/totp-validation/responses/xml/totp-user-is-not-valid.xml, modules/developer_manual/examples/core/scripts/curl/ocs/validate-totp.sh, modules/developer_manual/nav.adoc, modules/developer_manual/pages/core/apis/ocs-totp-validation-api.adoc
=> [10.0] [PR 1479] Document the new OCS TOTP Validation API

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/user/user_configuration.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/release_notes.adoc, modules/developer_manual/pages/core/apis/ocs-capabilities.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/files/gallery_app.adoc, modules/user_manual/pages/files/webgui/overview.adoc, modules/user_manual/pages/files/webgui/quota.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.2] Backport #1468 

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/user/user_configuration.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/release_notes.adoc, modules/developer_manual/pages/core/apis/ocs-capabilities.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/files/gallery_app.adoc, modules/user_manual/pages/files/webgui/overview.adoc, modules/user_manual/pages/files/webgui/quota.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.1] Backport #1468

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc, modules/admin_manual/pages/configuration/user/user_configuration.adoc, modules/admin_manual/pages/enterprise/firewall/file_firewall.adoc, modules/admin_manual/pages/release_notes.adoc, modules/developer_manual/pages/core/apis/ocs-capabilities.adoc, modules/developer_manual/pages/core/apis/ocs-share-api.adoc, modules/user_manual/pages/files/access_webdav.adoc, modules/user_manual/pages/files/gallery_app.adoc, modules/user_manual/pages/files/webgui/overview.adoc, modules/user_manual/pages/files/webgui/quota.adoc, modules/user_manual/pages/files/webgui/sharing.adoc
=> [10.0] Backport #1468

modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
https://github.com/owncloud/docs/pull/1523
=> [10.2] [PR 1523] Update ocs-recipient-api.adoc

modules/developer_manual/pages/core/apis/ocs-recipient-api.adoc
https://github.com/owncloud/docs/pull/1523
=> [10.1] [PR 1523] Update ocs-recipient-api.adoc

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
=> removed IRC channel reference

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
BP of https://github.com/owncloud/docs/pull/1522
=> [10.2] [PR 1522] removed IRC channel reference

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc
BP of https://github.com/owncloud/docs/pull/1522
=> [10.1] [PR 1522] removed IRC channel reference

modules/admin_manual/pages/maintenance/package_upgrade.adoc
Third party apps in package installation
fixes https://github.com/owncloud/docs/issues/1376
I removed the link in "Disable" because the new link already covers the disabling of the apps.
=> Third party apps in package installation

modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
=> [10.2] [PR 1528] Create migration-guide.adoc

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.0] [PR 1521] Third party apps in package installation

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.1] [PR 1521] Third party apps in package installation

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.2] [PR 1521] Third party apps in package installation

modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
=> [10.1] [PR 1528] Create migration-guide.adoc

modules/admin_manual/pages/installation/system_requirements.adoc
fixes https://github.com/owncloud/docs/issues/237
=> add recommended options

modules/admin_manual/pages/installation/system_requirements.adoc
https://github.com/owncloud/docs/pull/1535
=> [10.1] [PR 1535] add recommended options

modules/admin_manual/pages/installation/system_requirements.adoc
https://github.com/owncloud/docs/pull/1535
=> [10.2] [PR 1535] add recommended options

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> Fix miss newline

modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/maintenance/manual_upgrade.adoc, modules/admin_manual/pages/maintenance/update.adoc, modules/admin_manual/pages/maintenance/upgrade.adoc
Update by #1376 / #1521 like mention by https://github.com/owncloud/docs/pull/1521#issuecomment-513873889
Copied update.adoc text from upgrade.adoc
Fix typo
=> Third party apps clarification

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.2] [PR 1550] Fix miss newline

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.1] [PR 1550] Fix miss newline

modules/admin_manual/pages/maintenance/package_upgrade.adoc
=> [10.0] [PR 1550] Fix miss newline

modules/admin_manual/pages/configuration/user/user_configuration.adoc
=> [10.2] [PR 1543] update and rework the user management page

modules/admin_manual/pages/configuration/user/user_configuration.adoc
=> [10.1] [PR 1543] update and rework the user management page

modules/admin_manual/pages/enterprise/user_management/index.adoc
=> [10.0] [PR 1539] add links to the documents inside

modules/admin_manual/pages/enterprise/user_management/index.adoc
=> [10.2] [PR 1539] add links to the documents inside

modules/admin_manual/pages/enterprise/user_management/index.adoc
=> [10.1] [PR 1539] add links to the documents inside

modules/admin_manual/pages/configuration/user/user_configuration.adoc
=> [10.2] [PR 1548] minor fix

modules/admin_manual/pages/configuration/user/user_configuration.adoc
=> [10.1] [PR 1548] minor fix

modules/admin_manual/pages/configuration/user/index.adoc
containing links to the documents inside
=> create users index page

modules/admin_manual/pages/configuration/user/index.adoc
=> [10.1] [PR 1563] create users index page

modules/admin_manual/pages/configuration/user/index.adoc
=> [10.2] [PR 1563] create users index page

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc, modules/admin_manual/pages/configuration/server/security/index.adoc, modules/admin_manual/pages/configuration/server/security/password_policy.adoc
- removed the "security app" description from password policy document
- added a brute force protection app document
- added links to the index page
=> security docs improvement

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc, modules/admin_manual/pages/configuration/server/security/index.adoc, modules/admin_manual/pages/configuration/server/security/password_policy.adoc
https://github.com/owncloud/docs/pull/1569
=> [10.1] [PR 1569] security docs improvement

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc, modules/admin_manual/pages/configuration/server/security/index.adoc, modules/admin_manual/pages/configuration/server/security/password_policy.adoc
https://github.com/owncloud/docs/pull/1569
=> [10.2] [PR 1569] security docs improvement

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/server/security/index.adoc
in nav.adoc
and in the index page in bullet point form
=> added references

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/server/security/index.adoc
=> [10.1] [PR 1573] added references

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/server/security/index.adoc
=> [10.2] [PR 1573] added references

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc
to demonstrate how users can configure the app in the web UI
=> add picture to bruteforce protection

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc
=> [10.1] [PR 1579] add picture to bruteforce protection

modules/admin_manual/pages/configuration/server/security/brute_force_protection.adoc
=> [10.2] [PR 1579] add picture to bruteforce protection

modules/admin_manual/pages/configuration/server/background_jobs_configuration.adoc
with one error and possible analysis
=> added troubleshooting section

modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
=> [10.1] [PR 1582] added a tag to link

modules/admin_manual/pages/configuration/files/external_storage_configuration_gui.adoc
=> [10.2] [PR 1582] added a tag to link

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.0] [PR 1588] Fix Docker install after repo changes

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.1] [PR 1588] Fix Docker install after repo changes

modules/admin_manual/pages/installation/docker/index.adoc
=> [10.2] [PR 1588] Fix Docker install after repo changes

modules/admin_manual/pages/configuration/files/default_files_configuration.adoc
rephrase the wording to make it more clear
=> improve wording in skeleton doc

modules/admin_manual/pages/configuration/files/default_files_configuration.adoc
https://github.com/owncloud/docs/pull/1587
=> [10.1] [PR 1587] improve wording in skeleton doc

modules/admin_manual/pages/configuration/files/default_files_configuration.adoc
https://github.com/owncloud/docs/pull/1587
=> [10.2] [PR 1587] improve wording in skeleton doc

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.2] [PR 1596] Fix TOC title in admin PDF manual

books/ownCloud_Admin_Manual.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.1] [PR 1596] Fix TOC title in admin PDF manual

books/ownCloud_Admin_Manual.adoc, modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_roles.adoc
=> [10.0] [PR 1596] Fix TOC title in admin PDF manual

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/server/request_tracing.adoc
=> [10.0] [PR 1615] Document the x-request-id functionality in ownCloud server

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/server/request_tracing.adoc
=> [10.1] [PR 1615] Document the x-request-id functionality in ownCloud server

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/server/request_tracing.adoc
=> [10.2] [PR 1615] Document the x-request-id functionality in ownCloud server

package.json, yarn.lock
This change updates cheerio, elasticsearch, and lodash to the latest versions.
=> Update package dependencies

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
This documents the wopi_group configuration key and fixes #1608.
=> Document how to limit access to Microsoft Office Online

docs/best-practices.md
Improving the Best Practices Guide:
- Fixing the missing `+`sign in attributes
- Fixing a bad line break in an example
- Adding complex elements to lists
Backporting required
=> Improving Best Practices

docs/best-practices.md
=> [10.2] [PR 1617] Improving Best Practices

docs/best-practices.md
=> [10.1] [PR 1617] Improving Best Practices

docs/best-practices.md
=> [10.0] [PR 1617] Improving Best Practices

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.2] [PR 1622] Document how to limit access to Microsoft Office Online

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.1] [PR 1622] Document how to limit access to Microsoft Office Online

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.0] [PR 1622] Document how to limit access to Microsoft Office Online

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.2] [PR 1633] Minor fix to limit access to Microsoft Office Online changes

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.1] [PR 1633] Minor fix to limit access to Microsoft Office Online changes

modules/admin_manual/pages/enterprise/collaboration/msoffice-wopi-integration.adoc
=> [10.0] [PR 1633] Minor fix to limit access to Microsoft Office Online changes

modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
fixes https://central.owncloud.org/t/mac-client-not-synching-all-folders-reliably/21258/8
=> wnd added enterprise notion

modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
=> [10.2] [PR 1647] wnd added enterprise notion

modules/admin_manual/pages/appliance/configuration/wnd_setup.adoc
=> [10.1] [PR 1647] wnd added enterprise notion

modules/admin_manual/pages/appliance/configuration/clamav.adoc
=> [10.0] [PR 1637] Create redirect for deprecated server/admin_manual/appliance/Clamav.html

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
fixes https://github.com/owncloud/docs/issues/361
=> added explanation for sharing permissions

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.2] [PR 1646] added explanation for sharing permissions

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.3] [PR 1646] added explanation for sharing permissions

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.0] [PR 1646] added explanation for sharing permissions

modules/admin_manual/pages/configuration/files/file_sharing_configuration.adoc
=> [10.1] [PR 1646] added explanation for sharing permissions

.drone.yml
This should run the drone pipeline for 10.3 and allow PDF generation
=> Run drone pipeline for 10.3

modules/admin_manual/pages/appliance/index.adoc
since we noticed that many request were on the old page, this should fix it.
=> include redirect

modules/admin_manual/pages/appliance/configuration/clamav.adoc
=> [10.1] [PR 1637] Create redirect for deprecated server/admin_manual/appliance/Clamav.html

modules/admin_manual/pages/appliance/configuration/clamav.adoc
=> [10.2] [PR 1637] Create redirect for deprecated server/admin_manual/appliance/Clamav.html

modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh, modules/developer_manual/examples/core/scripts/curl/list-share-details.sh, modules/developer_manual/examples/core/scripts/go/accept-pending-share.go, modules/developer_manual/examples/core/scripts/go/decline-pending-share.go, modules/developer_manual/examples/core/scripts/php/accept-pending-share.php, modules/developer_manual/examples/core/scripts/php/decline-pending-share.php, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml, modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml, modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json, modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb, modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb, modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.2] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs

modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh, modules/developer_manual/examples/core/scripts/curl/list-share-details.sh, modules/developer_manual/examples/core/scripts/go/accept-pending-share.go, modules/developer_manual/examples/core/scripts/go/decline-pending-share.go, modules/developer_manual/examples/core/scripts/php/accept-pending-share.php, modules/developer_manual/examples/core/scripts/php/decline-pending-share.php, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml, modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml, modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json, modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb, modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb, modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.3] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs

modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh, modules/developer_manual/examples/core/scripts/curl/list-share-details.sh, modules/developer_manual/examples/core/scripts/go/accept-pending-share.go, modules/developer_manual/examples/core/scripts/go/decline-pending-share.go, modules/developer_manual/examples/core/scripts/php/accept-pending-share.php, modules/developer_manual/examples/core/scripts/php/decline-pending-share.php, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml, modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml, modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json, modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb, modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb, modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.1] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs

modules/developer_manual/examples/core/scripts/curl/accept-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/decline-pending-share.sh, modules/developer_manual/examples/core/scripts/curl/list-all-shares.sh, modules/developer_manual/examples/core/scripts/curl/list-share-details.sh, modules/developer_manual/examples/core/scripts/go/accept-pending-share.go, modules/developer_manual/examples/core/scripts/go/decline-pending-share.go, modules/developer_manual/examples/core/scripts/php/accept-pending-share.php, modules/developer_manual/examples/core/scripts/php/decline-pending-share.php, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-failure.xml, modules/developer_manual/examples/core/scripts/responses/shares/accept-pending-share-success.xml, modules/developer_manual/examples/core/scripts/responses/shares/get-all-shares-success-with-shares.xml, modules/developer_manual/examples/core/scripts/responses/shares/list-share-details-success.json, modules/developer_manual/examples/core/scripts/ruby/accept-pending-share.rb, modules/developer_manual/examples/core/scripts/ruby/decline-pending-share.rb, modules/developer_manual/pages/core/apis/ocs-share-api.adoc
=> [10.0] [PR 1570] Update the OCS Share API Get Shares From Specific File or Folder docs

modules/admin_manual/pages/appliance/index.adoc
=> [10.1] [PR 1668] include redirect

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.3] [PR 1659] Document the occ encryption:fix-encrypted-version command

modules/developer_manual/pages/testing/ui-testing.adoc
=> [10.3] [PR 1677] Document selenium chrome testing version

modules/developer_manual/pages/testing/ui-testing.adoc
=> [10.0] [PR 1677] Document selenium chrome testing version

modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrade.adoc
=> [10.3] [PR 1657] Unify the wording around skipping major releases when upgrading

modules/admin_manual/pages/maintenance/package_upgrade.adoc, modules/admin_manual/pages/maintenance/upgrade.adoc
=> [10.0] [PR 1657] Unify the wording around skipping major releases when upgrading

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
When customer encounters NT_STATUS_REVISION_MISMATCH we can provide help.
=> info to contact support when certain error appears

modules/admin_manual/pages/configuration/server/occ_command.adoc
If users / customer missed one or several migration steps and are not facing issues, they can manually run those steps with commands documented here.
=> document migration step commands

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.3] [PR 1682] info to contact support when certain error appears

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.2] [PR 1682] info to contact support when certain error appears

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.1] [PR 1682] info to contact support when certain error appears

modules/admin_manual/pages/enterprise/external_storage/windows-network-drive_configuration.adoc
=> [10.0] [PR 1682] info to contact support when certain error appears

docs/best-practices.md
=> [10.2] [PR 1629] Minor text fixes to the best practices update

docs/best-practices.md
=> [10.0] [PR 1629] Minor text fixes to the best practices update

docs/best-practices.md
=> [10.3] [PR 1629] Minor text fixes to the best practices update

docs/best-practices.md
=> [10.1] [PR 1629] Minor text fixes to the best practices update

modules/admin_manual/pages/configuration/server/occ_command.adoc, modules/admin_manual/pages/configuration/user/user_provisioning_api.adoc
=> [10.3] [PR 1650] Document new options for adding users via provisioning API and occ

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.3] [PR 1651] document migration step commands

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.0] [PR 1651] document migration step commands

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.1] [PR 1651] document migration step commands

modules/admin_manual/pages/configuration/server/occ_command.adoc
=> [10.2] [PR 1651] document migration step commands

modules/admin_manual/nav.adoc, modules/admin_manual/pages/appliance/configuration/app_settings.adoc
https://github.com/owncloud/docs/pull/1701
=> [10.2] [PR 1701] Create app_settings.adoc

modules/admin_manual/nav.adoc, modules/admin_manual/pages/appliance/configuration/app_settings.adoc
https://github.com/owncloud/docs/pull/1701
=> [10.1] [PR 1701] Create app_settings.adoc

modules/admin_manual/nav.adoc, modules/admin_manual/pages/appliance/troubleshooting.adoc
=> [10.2] [PR 1704] added troubleshooting section

modules/admin_manual/nav.adoc, modules/admin_manual/pages/appliance/troubleshooting.adoc
=> [10.1] [PR 1704] added troubleshooting section

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
added a command after a session with a customer to replace a string in DB.
also added an important step in updating the data path in oc_jobs.
=> added mysql replace command

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.1] [PR 1711] added mysql replace command

modules/admin_manual/pages/maintenance/manually-moving-data-folders.adoc
=> [10.2] [PR 1711] added mysql replace command

modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
=> [10.2] [PR 1597] Updating Server Prep Ubuntu 18.04

modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
=> [10.3] [PR 1597] Updating Server Prep Ubuntu 18.04

modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc
=> [10.1] [PR 1597] Updating Server Prep Ubuntu 18.04

package.json, yarn.lock
=> Upgrade write-good from version 0.13.1 to 1.0.2

yarn.lock
=> Upgrade @antora/site-generator-default to 2.1.0

yarn.lock
=> Revert "Upgrade @antora/site-generator-default to 2.1.0"

yarn.lock
=> Upgrade @antora to version 2.1.0

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/user/guests_app.adoc
Added documentation here for the guests app as we had not have anything before that except one paragraph in user roles. But since our users / customer use the guests app intensively we should have a better documentation about it. This should be a start, we can add things to it later on as we discover possible use cases and issues.
=> Guests app documentation

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/user/guests_app.adoc
https://github.com/owncloud/docs/pull/1730
=> [10.2] [PR 1730] Guests app documentation

modules/admin_manual/nav.adoc, modules/admin_manual/pages/configuration/user/guests_app.adoc
https://github.com/owncloud/docs/pull/1730
=> [10.1] [PR 1730] Guests app documentation

modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
=> [10.3] [PR 1733] Update migration-guide.adoc

modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
=> [10.2] [PR 1733] Update migration-guide.adoc

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
=> [10.2] [PR 1728] Add missing partial referenced in maintenance upgrade docs

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
=> [10.1] [PR 1728] Add missing partial referenced in maintenance upgrade docs

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
=> [10.3] [PR 1728] Add missing partial referenced in maintenance upgrade docs

modules/admin_manual/pages/configuration/files/encryption/migration-guide.adoc
=> [10.1] [PR 1733] Update migration-guide.adoc

yarn.lock
According to GitHub, the current version of string has a security alert, so this change is aimed at updating it to resolve the alert.
=> Update JavaScript dependencies

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
fixes https://github.com/owncloud/docs/issues/1751
=> add examples

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
=> [10.3] [PR 1753] add examples

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
=> [10.2] [PR 1753] add examples

modules/admin_manual/pages/_partials/maintenance/major_release_note.adoc
=> [10.1] [PR 1753] add examples

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.0] [PR 1752] Update and rework federated sharing page

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.1] [PR 1752] Update and rework federated sharing page

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.3] [PR 1752] Update and rework federated sharing page

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.2] [PR 1752] Update and rework federated sharing page

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.3] [PR 1769] Added info on Systemd apache tempdir config.

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc
=> [10.1] [PR 1769] Added info on Systemd apache tempdir config.

modules/user_manual/pages/_partials/section_page.adoc
=> [10.0] [PR 1774] fix_missing_section_page.adoc_in_user_manual

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.2] [PR 1770] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.3] [PR 1770] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.0] [PR 1770] Update federated_cloud_sharing_configuration.adoc

modules/admin_manual/pages/configuration/files/federated_cloud_sharing_configuration.adoc
=> [10.1] [PR 1770] Update federated_cloud_sharing_configuration.adoc

.drone.yml
=> [10.2] [PR 1801] Remove outdated drone clone plugin

.drone.yml
=> [10.0] [PR 1801] Remove outdated drone clone plugin

.drone.yml
=> [10.1] [PR 1801] Remove outdated drone clone plugin

.drone.yml
=> [10.3] [PR 1801] Remove outdated drone clone plugin

modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.0] [PR 1674] Document recommendations for using NFS storage

modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.1] [PR 1674] Document recommendations for using NFS storage

modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.3] [PR 1674] Document recommendations for using NFS storage

modules/admin_manual/nav.adoc, modules/admin_manual/pages/installation/deployment_recommendations.adoc, modules/admin_manual/pages/installation/deployment_recommendations/nfs.adoc
=> [10.2] [PR 1674] Document recommendations for using NFS storage

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/configuration/server/request_tracing.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/installation/deployment_considerations.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc, modules/developer_manual/pages/testing/test-pilots.adoc, modules/user_manual/pages/files/access_webdav.adoc
Backport of c89fdc6a104d214d7cdc6de2966873ef1a8a8ebf
=> [10.0] Remove extra Nginx reference from docs

modules/admin_manual/pages/configuration/files/big_file_upload_configuration.adoc, modules/admin_manual/pages/configuration/general_topics/general_troubleshooting.adoc, modules/admin_manual/pages/configuration/server/harden_server.adoc, modules/admin_manual/pages/configuration/server/logging/request_tracing.adoc, modules/admin_manual/pages/configuration/server/security_setup_warnings.adoc, modules/admin_manual/pages/installation/deployment_considerations.adoc, modules/admin_manual/pages/installation/letsencrypt/using_letsencrypt.adoc, modules/admin_manual/pages/installation/server_prep_ubuntu_18.04.adoc, modules/developer_manual/pages/bugtracker/triaging.adoc, modules/developer_manual/pages/testing/test-pilots.adoc, modules/user_manual/pages/files/access_webdav.adoc
Backport of c89fdc6a104d214d7cdc6de2966873ef1a8a8ebf
=> [10.1] Remove extra nginx reference from docs

resources/themes/owncloud-theme.yml
=> [10.3] [PR 1819] Left align PDF content

resources/themes/owncloud-theme.yml
=> [10.2] [PR 1819] Left align PDF content

resources/themes/owncloud-theme.yml
=> [10.1] [PR 1819] Left align PDF content

resources/themes/owncloud-theme.yml
=> [10.0] [PR 1819] Left align PDF content

modules/user_manual/pages/files/access_webdav.adoc
`Access Webdav` has `sudo` usage with `curl`. This PR removes sudo usage with curl.
=> Remove sudo usage with curl

modules/user_manual/pages/files/access_webdav.adoc
=> [10.0] [PR 1840] Remove sudo usage with curl

modules/user_manual/pages/files/access_webdav.adoc
=> [10.1] [PR 1840] Remove sudo usage with curl

modules/user_manual/pages/files/access_webdav.adoc
=> [10.2] [PR 1840] Remove sudo usage with curl
